/* ---------- floating assistant (v15.11: motion + interaction upgrade) ---------- */
const asSvg=(d,w=15)=>`<svg viewBox="0 0 24 24" width="${w}" height="${w}" fill="none" stroke="currentColor" stroke-width="2.1" stroke-linecap="round" stroke-linejoin="round">${d}</svg>`;
const ASI={};Object.assign(ASI,{spark:asSvg('<path d="M12 3.5l1.9 5.1 5.1 1.9-5.1 1.9L12 17.5l-1.9-5.1L5 10.5l5.1-1.9z"/><path d="M18.5 15.5l.6 1.6 1.6.6-1.6.6-.6 1.6-.6-1.6-1.6-.6 1.6-.6z"/>',20),pin:asSvg('<path d="M4 5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1z"/><path d="M4 9h16M9 9v11"/>',12),cut:asSvg('<path d="M5 4h14M5 9h10M5 14h14M5 19h8"/>',12),arrow:asSvg('<path d="M15 6l-6 6 6 6"/>',14),link:asSvg('<path d="M10 14a4 4 0 0 0 5.7 0l3-3a4 4 0 0 0-5.7-5.7l-1 1"/><path d="M14 10a4 4 0 0 0-5.7 0l-3 3a4 4 0 0 0 5.7 5.7l1-1"/>',11),doc:asSvg('<path d="M14 3H6a1 1 0 0 0-1 1v16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8z"/><path d="M14 3v5h5"/>',11),ext:asSvg('<path d="M14 4h6v6M20 4l-9 9M18 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h5"/>',11),q:asSvg('<circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.6.3-1 .9-1 1.6v.3M12 17h.01"/>',14),x:asSvg('<path d="M6 6l12 12M18 6L6 18"/>'),max:asSvg('<path d="M15 3h6v6M9 21H3v-6M21 3l-7 7M3 21l7-7"/>'),min:asSvg('<path d="M4 14h6v6M20 10h-6V4M14 10l7-7M3 21l7-7"/>'),reset:asSvg('<path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5"/>'),send:asSvg('<path d="M20 12H5M11 6l-6 6 6 6"/>',17),
 spin:asSvg('<path d="M21 12a9 9 0 1 1-6.2-8.6"/>',17),copy:asSvg('<rect x="9" y="9" width="12" height="12" rx="2"/><path d="M5 15H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v1"/>'),ok:asSvg('<path d="M5 12l5 5L20 7"/>'),again:asSvg('<path d="M21 12a9 9 0 1 1-3-6.7L21 8"/><path d="M21 3v5h-5"/>'),
 web:asSvg('<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a14 14 0 0 1 0 18M12 3a14 14 0 0 0 0 18"/>'),down:asSvg('<path d="M12 5v14M6 13l6 6 6-6"/>'),bolt:asSvg('<path d="M13 3L5 13.5h6L10 21l8-10.5h-6z"/>',15),
 m_auto:asSvg('<path d="M12 3l1.8 4.2L18 9l-4.2 1.8L12 15l-1.8-4.2L6 9l4.2-1.8z"/>'),m_explain:asSvg('<path d="M4 5h16v11H9l-5 4z"/>'),m_search:asSvg('<circle cx="11" cy="11" r="7"/><path d="M20 20l-4-4"/>'),m_calc:asSvg('<rect x="5" y="3" width="14" height="18" rx="2"/><path d="M8 7h8M8 12h2M14 12h2M8 16h2M14 16h2"/>')});
const ASMODE=[['auto','خودکار'],['explain','توضیح صفحه'],['search','جستجوی وب'],['calc','محاسبه']];
const ASUG={map:['مسیر انتخابی را با گزینه‌های دیگر مقایسه کن','ریسک‌های اصلی این مسیر چیست؟'],opt:['چرا این مسیر رتبهٔ اول شد؟','TOPSIS در این بهینه‌ساز چطور کار می‌کند؟'],lq:['منبع و تازگی داده‌های این برآورد را توضیح بده'],cost:['اقلام اصلی هزینه را توضیح بده','با اینکوترمز FOB چه تغییری می‌کند؟'],tar:['حقوق ورودی این کالا چگونه محاسبه شد؟','مجوزهای لازم برای ترخیص چیست؟'],load:['آیا چیدمان را می‌شود بهینه‌تر کرد؟'],dd:['چطور هزینهٔ دموراژ و دیتنشن را کم کنم؟'],ins:['تفاوت ICC A، B و C چیست؟'],sanc:['نتیجهٔ غربالگری را تفسیر کن'],risk:['سه ریسک اول و راه کاهش آن‌ها'],mkt:['روند شاخص‌های بازار را تحلیل کن'],dom:['نرخ رسمی حمل داخلی چطور محاسبه می‌شود؟'],agt:['فرایند تکرارپذیر چیست و چطور بسازم؟'],bkg:['کات‌آف‌های این رزرو را توضیح بده'],cus:['مراحل ترخیص در گمرک ایران'],pnl:['سودآوری این پرونده را تحلیل کن'],rfq:['استعلام حرفه‌ای چه بندهایی باید داشته باشد؟']};
const asCtxSafe=()=>{try{return ctx()}catch(e){return null}};
function asRouteTxt(){const C=asCtxSafe();if(!C||!C.R)return '';const R=C.R,s=R.nodeSeq||[],c=C.cargo||{};
 return `مسیر: ${R.name||''} · ${nname(s[0])} ← ${nname(s[s.length-1])} · کرایهٔ مدل ${usd(R.total||0)} · ${nf(R.avgDays||0,1)} روز · ریسک ${Math.round(R.risk||0)} · بار: ${c.commodity||''}، ${c.weightKg||0} kg، ${c.cbm||0} CBM، ارزش $${c.value||0}، ${c.incoterm||''}، ${c.shipmentType||''} ${c.containerType||''}`}
const asClean=t=>String(t||'').replace(/[ \t]+/g,' ').replace(/\n{3,}/g,'\n\n').trim();
const AS={open:false,mode:'auto',msgs:(()=>{const m=LSG('ifa-as-msgs',[]);return Array.isArray(m)?m.slice(-30).map(x=>({...x,fresh:false})):[]})(),busy:false,wide:false,page:LSG('ifa-as-page',true)!==false,sel:'',unread:0,hist:-1,lastView:''};
const asSv=()=>LSS('ifa-as-msgs',AS.msgs.slice(-30).map(({fresh,...m})=>m));
function asPage(){const out={view:'map',title:'نقشه و مسیرهای پیشنهادی',sub:'',text:'',route:asRouteTxt(),sel:AS.sel||''};
 if(wrap){const T=TABS.find(t=>t.k===view);out.view=view;out.title=T?T.n:view;const B=$('.sx-body',wrap);if(B){out.sub=$$('.sx-seg button.on',B).map(b=>b.textContent.trim()).filter(Boolean).slice(0,4).join(' · ');
   const K=$$('.sx-kpi',B).map(k=>asClean(k.innerText).replace(/\n/g,' ')).slice(0,12).join(' | ');out.text=asClean((K?'شاخص‌ها: '+K+'\n':'')+B.innerText).slice(0,6500)}}
 else{const R=document.getElementById('root')||document.body;out.text=asClean(R.innerText).slice(0,4500)}
 if(!AS.page){out.text='';}return out}
/* markdown → safe HTML (headings, lists, quotes, code, links, [n] citations, tables) */
function asMd(s,res){s=esc(String(s||''));const L=res||[];
 s=s.replace(/```([\s\S]*?)```/g,(m,c)=>'<pre style="white-space:pre-wrap;direction:ltr;font-size:11.5px">'+c.replace(/\n/g,'&#10;')+'</pre>');
 s=s.replace(/\[([^\]\n]{1,200})\]\((https?:\/\/[^\s)]+)\)/g,(m,t,u)=>`<a href="${u}" target="_blank" rel="noopener noreferrer">${t}</a>`);
 s=s.replace(/\[(\d{1,2})\]/g,(m,n)=>{const r=L[+n-1];return r?`<sup><a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer" title="${esc(r.title)}">${fa(n)}</a></sup>`:m});
 s=s.replace(/\*\*([^\n]+?)\*\*/g,'<b>$1</b>').replace(/`([^`\n]+)`/g,'<code>$1</code>');
 const lines=s.split('\n');let h='',lst='',tb=[];const close=()=>{if(lst){h+='</'+lst+'>';lst=''}};
 const flushT=()=>{if(!tb.length)return;const rows=tb.filter(r=>!/^\s*\|?\s*:?-{2,}/.test(r)).map(r=>r.replace(/^\s*\||\|\s*$/g,'').split('|').map(c=>c.trim()));h+='<table>'+rows.map((r,i)=>'<tr>'+r.map(c=>i?'<td>'+c+'</td>':'<th>'+c+'</th>').join('')+'</tr>').join('')+'</table>';tb=[]};
 for(const l of lines){let m;if(/^\s*\|.*\|\s*$/.test(l)){close();tb.push(l);continue}flushT();
  if((m=l.match(/^\s*#{1,4}\s+(.*)/))){close();h+='<h4>'+m[1]+'</h4>'}else if((m=l.match(/^\s*[-•*]\s+(.*)/))){if(lst!=='ul'){close();h+='<ul>';lst='ul'}h+='<li>'+m[1]+'</li>'}
  else if((m=l.match(/^\s*\d+[.)]\s+(.*)/))){if(lst!=='ol'){close();h+='<ol>';lst='ol'}h+='<li>'+m[1]+'</li>'}else if((m=l.match(/^\s*&gt;\s?(.*)/))){close();h+='<blockquote>'+m[1]+'</blockquote>'}else if(!l.trim()){close()}else{close();h+='<div>'+l+'</div>'}}
 flushT();close();return h}
const asHost=u=>{try{return new URL(u).hostname.replace(/^www\./,'')}catch(e){return ''}};
const asHue=s=>{let h=0;for(const c of String(s))h=(h*31+c.charCodeAt(0))%360;return h};
const asTip=(el,html)=>{let tm=0;const hide=()=>{clearTimeout(tm);const x=$('.as-tip');if(x)x.classList.remove('on')};const bad=()=>el.classList.contains('drag')||(el.classList.contains('open')&&el.classList.contains('as-fab'))||(typeof AS!=='undefined'&&AS.open&&el.classList.contains('as-fab'));
 el.addEventListener('mouseenter',()=>{clearTimeout(tm);tm=setTimeout(()=>{if(bad()||!el.matches(':hover')||!el.isConnected)return;const t=$('.as-tip')||document.body.appendChild(Object.assign(document.createElement('div'),{className:'as-tip'}));t.innerHTML=html;const r=el.getBoundingClientRect();t.style.left=Math.max(6,Math.min(innerWidth-t.offsetWidth-6,r.left+r.width/2-t.offsetWidth/2))+'px';t.style.top=Math.max(6,r.top-t.offsetHeight-10)+'px';requestAnimationFrame(()=>t.classList.add('on'))},450)});
 el.addEventListener('mouseleave',hide);el.addEventListener('pointerdown',hide);el.addEventListener('click',hide)};
function asFabSync(){const f=$('.as-fab');if(!f)return;f.classList.toggle('open',AS.open);f.classList.toggle('busy',!!AS.busy);f.classList.toggle('run',!!(typeof AP!=='undefined'&&AP.run));const d=$('.as-dot',f);if(d)d.classList.toggle('on',svOn());
 let b=$('.as-bdg',f);if(AS.unread&&!AS.open){if(!b){b=document.createElement('span');b.className='as-bdg';f.appendChild(b)}b.textContent=fa(AS.unread)}else if(b)b.remove()}
function asFab(){if($('.as-fab'))return;const f=document.createElement('button');f.className='as-fab';f.setAttribute('aria-label','دستیار آسانا');
 f.innerHTML=`<span class="as-orb"></span><span class="i1">${ASI.spark}</span><span class="i2">${ASI.x}</span><span class="as-dot"></span>`;document.body.appendChild(f);asTip(f,'دستیار آسانا — توضیح، جستجو، محاسبه و کنترل خودکار <kbd>Ctrl J</kbd>');
 if(!$('#as-defs')){const d=document.createElementNS('http://www.w3.org/2000/svg','svg');d.id='as-defs';d.setAttribute('width',0);d.setAttribute('height',0);d.style.position='absolute';d.innerHTML='<defs><linearGradient id="apG" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#8FB3AE"/><stop offset="1" stop-color="#9cc7ff"/></linearGradient><linearGradient id="apG2" x1="1" y1="0" x2="0" y2="0"><stop offset="0" stop-color="#5e9fe8"/><stop offset="1" stop-color="#8FB3AE"/></linearGradient></defs>';document.body.appendChild(d)}
 const P=LSG('ifa-as-pos',null);if(P&&P.l!=null){f.style.left=Math.min(innerWidth-56,P.l)+'px';f.style.bottom=Math.min(innerHeight-56,P.b)+'px'}
 let d=null;f.addEventListener('pointerdown',e=>{if(e.button)return;d={x:e.clientX,y:e.clientY,l:f.offsetLeft,b:innerHeight-f.offsetTop-f.offsetHeight,m:false};f.setPointerCapture(e.pointerId)});
 f.addEventListener('pointermove',e=>{if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(!d.m&&Math.hypot(dx,dy)<6)return;if(!d.m){d.m=true;f.classList.add('drag');f.classList.remove('snap')}const l=Math.max(6,Math.min(innerWidth-50,d.l+dx)),b=Math.max(6,Math.min(innerHeight-50,d.b-dy));f.style.left=l+'px';f.style.bottom=b+'px';asPlace()});
 const up=()=>{if(d&&d.m){f.classList.remove('drag');f.classList.add('snap');const l=f.offsetLeft+22<innerWidth/2?20:innerWidth-64;f.style.left=l+'px';const b=innerHeight-f.offsetTop-f.offsetHeight;LSS('ifa-as-pos',{l,b});setTimeout(()=>{asPlace();f.classList.remove('snap')},520);asPlace()}else if(d)asToggle();d=null};
 f.addEventListener('pointerup',up);f.addEventListener('pointercancel',()=>{f.classList.remove('drag');d=null});
 addEventListener('resize',()=>{if(f.offsetLeft>innerWidth-50)f.style.left=(innerWidth-64)+'px';asPlace()});
 document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='j'){e.preventDefault();asToggle()}});
 document.addEventListener('mouseup',e=>{if(e.target.closest&&e.target.closest('.as-panel,.as-ask,.ap-hud,.apx-pre-bg'))return;setTimeout(()=>{const s=String(getSelection()||'').trim();let b=$('.as-ask');if(s.length<3||s.length>1500){if(b)b.remove();return}
  if(!b){b=document.createElement('button');b.className='as-ask';b.innerHTML=ASI.m_auto+'<span>از دستیار بپرس</span>';document.body.appendChild(b)}b.style.left=Math.min(innerWidth-150,e.clientX+8)+'px';b.style.top=Math.max(8,e.clientY-40)+'px';
  b.onmousedown=ev=>ev.preventDefault();b.onclick=()=>{AS.sel=s.slice(0,1500);b.remove();asShow(true);const t=$('.as-ft textarea');if(t){t.value='این بخش انتخاب‌شده را توضیح بده';t.focus();t.select()}asCtxBar()}},10)});
 setInterval(()=>{apPillTick();asFabSync();if(AS.open){const P=asPage();const k=P.view+'|'+P.sub;if(k!==AS.lastView){AS.lastView=k;asCtxBar();if(!AS.msgs.length)asRender()}}},1200);asFabSync()}
function asPlace(){const f=$('.as-fab');if(!f)return;const l=f.offsetLeft,b=innerHeight-f.offsetTop-f.offsetHeight,right=l+22>innerWidth/2;const p=$('.as-panel'),h=$('.ap-hud'),pl=$('.as-pill');
 const put=(e,w)=>{const W=Math.min(w,innerWidth-12);const L=right?Math.max(6,l+44-W):Math.max(6,Math.min(l,innerWidth-W-6));e.style.left=L+'px';const tl=$('.ap-tl:not(.out)');const bb=Math.max(b+56,tl?tl.offsetHeight+30:0);e.style.bottom=bb+'px';e.style.maxHeight=Math.max(260,innerHeight-bb-16)+'px';e.style.transformOrigin=(right?'100%':'0%')+' 100%'};
 if(p)put(p,p.offsetWidth||430);if(h)put(h,h.offsetWidth||410);if(pl){pl.style.bottom=b+'px';pl.style.left=right?Math.max(6,l-(pl.offsetWidth||260)-8)+'px':(l+52)+'px'}}
function asToggle(){asShow(!AS.open)}
function asShow(on){const was=AS.open;AS.open=on;let p=$('.as-panel');if(!on){if(p&&!p.classList.contains('out')){p.classList.add('out');setTimeout(()=>p.remove(),220)}asFabSync();return}
 if(p&&p.classList.contains('out'))p.remove(),p=null;AS.unread=0;if(typeof AP!=='undefined'&&AP.run&&$('.ap-hud'))$('.ap-hud').classList.remove('min');
 $('.as-tip')?.classList.remove('on');const fresh=!p;if(!p){p=document.createElement('div');p.className='as-panel'+(AS.wide?' wide':'');p.style.left='20px';p.setAttribute('role','dialog');p.setAttribute('aria-label','دستیار آسانا');document.body.appendChild(p)}
 p.innerHTML=`<div class="as-hd"><span class="as-lg${AS.busy?' busy':''}">${ASI.spark}</span><div class="tt"><b>دستیار آسانا</b><small><i class="${svOn()?'on':''}"></i>${svOn()?'متصل به سرور تیمی':'حالت آفلاین · محاسبه و توضیح محلی'}</small></div><span class="sp"></span><button class="as-ib as-c" title="گفتگوی تازه">${ASI.reset}</button><button class="as-ib as-w" title="بزرگ/کوچک">${AS.wide?ASI.min:ASI.max}</button><button class="as-ib as-x" title="بستن (Esc)">${ASI.x}</button></div>
  <div class="as-live"></div><div class="as-ctx"></div><div class="as-modes"><span class="ind"></span>${ASMODE.map(([k,n])=>`<button data-m="${k}" class="${AS.mode===k?'on':''}">${ASI['m_'+k]}${n}</button>`).join('')}</div><div class="as-msgs" aria-live="polite"></div><button class="as-down" title="رفتن به پایین">${ASI.down}</button>
  <div class="as-ft"><div class="as-in as-mt"><span class="pf"></span><textarea rows="1" placeholder=""></textarea><button class="go" title="ارسال (Enter)">${ASI.send}</button></div><div class="kb"><span><kbd>Enter</kbd>ارسال</span><span><kbd>Shift Enter</kbd>خط جدید</span><span><kbd>/</kbd>دستورها</span><span><kbd>Ctrl J</kbd>باز/بسته</span></div></div>`;
 $('.as-x',p).onclick=()=>asShow(false);$('.as-w',p).onclick=()=>{AS.wide=!AS.wide;p.classList.toggle('wide',AS.wide);$('.as-w',p).innerHTML=AS.wide?ASI.min:ASI.max;setTimeout(()=>{asPlace();asInd()},460);asPlace()};
 $('.as-c',p).onclick=()=>{const B=$('.as-msgs',p);B.style.transition='opacity .2s';B.style.opacity=0;setTimeout(()=>{AS.msgs=[];AS.sel='';asSv();asRender();asCtxBar();B.style.opacity=1},200)};
 $$('.as-modes button',p).forEach(b=>b.onclick=()=>{asMode(b.dataset.m);$('.as-ft textarea',p).focus()});
 const t=$('.as-ft textarea',p);t.oninput=()=>{t.style.height='auto';t.style.height=Math.min(130,t.scrollHeight)+'px';asSlash(t.value);t.parentElement.classList.toggle('as-mt',!t.value.trim())};
 t.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();asSend()}else if(e.key==='Escape'){asShow(false)}else if(e.key==='ArrowUp'&&!t.value){const U=AS.msgs.filter(m=>m.role==='user');if(U.length){e.preventDefault();t.value=U[U.length-1].content;t.oninput();setTimeout(()=>t.setSelectionRange(t.value.length,t.value.length))}}};
 $('.as-ft .go',p).onclick=()=>asSend();const B=$('.as-msgs',p),dn=$('.as-down',p);B.onscroll=()=>dn.classList.toggle('on',B.scrollHeight-B.scrollTop-B.clientHeight>140);dn.onclick=()=>B.scrollTo({top:B.scrollHeight,behavior:'smooth'});
 asMode(AS.mode,true);asCtxBar();asRender(fresh);asPlace();if(typeof apTl==='function'&&AP.run)apTl();asFabSync();if(!was)setTimeout(()=>t.focus(),60)}
function asInd(){const p=$('.as-panel');if(!p)return;const b=$('.as-modes button.on',p),i=$('.as-modes .ind',p);if(b&&i){i.style.left=b.offsetLeft+'px';i.style.width=b.offsetWidth+'px'}}
function asMode(m,quiet){AS.mode=m;const p=$('.as-panel');if(!p)return;$$('.as-modes button',p).forEach(x=>x.classList.toggle('on',x.dataset.m===m));requestAnimationFrame(asInd);
 const t=$('.as-ft textarea',p);if(t)t.placeholder={auto:'بپرسید؛ نوع پاسخ خودکار تشخیص داده می‌شود…',explain:'دربارهٔ همین صفحه بپرسید…',search:'چه چیزی را در اینترنت جستجو کنم؟',calc:'مثلاً (12000+3500)*1.08 یا 120×100×110 × 24 پالت'}[m];asSlash('')}
const ASSL={calc:'calc','محاسبه':'calc','حساب':'calc',search:'search','جستجو':'search','وب':'search',explain:'explain','توضیح':'explain',auto:'auto'};
function asSlash(v){const k=$('.as-panel .as-in .pf');if(!k)return;const m=String(v).match(/^\/(\S+)/);const md=m&&ASSL[m[1].toLowerCase()];k.textContent=md?(ASMODE.find(x=>x[0]===md)||[])[1]:'';k.classList.toggle('on',!!md);if(!v)k.parentElement.classList.add('as-mt')}
function asCtxBar(){const c=$('.as-panel .as-ctx');if(!c)return;const P=asPage();AS.lastView=P.view+'|'+P.sub;c.innerHTML=`<span class="as-chip" title="${esc(P.title+(P.sub?' · '+P.sub:''))}">${ASI.pin}<span>${esc(P.title)}${P.sub?' · '+esc(P.sub):''}</span></span>${AS.sel?`<span class="as-chip sel" title="${esc(AS.sel)}">${ASI.cut}<span>متن انتخابی</span><b class="as-sx">${ASI.x}</b></span>`:''}<label title="متن و شاخص‌های صفحهٔ فعلی برای پاسخ دقیق‌تر ارسال می‌شود">محتوای صفحه<input type="checkbox" class="as-sw as-pg" ${AS.page?'checked':''}></label>`;
 $('.as-pg',c).onchange=e=>{AS.page=e.target.checked;LSS('ifa-as-page',AS.page)};const x=$('.as-sx',c);if(x)x.onclick=()=>{AS.sel='';asCtxBar()}}
const ASBUSY={search:['در حال جستجو در اینترنت…','خواندن و رتبه‌بندی منابع…','نوشتن پاسخ با ارجاع به منابع…'],calc:['تحلیل مسئله…','محاسبهٔ گام‌به‌گام…'],explain:['خواندن محتوای صفحه…','تحلیل شاخص‌ها و داده‌ها…','نوشتن توضیح…'],auto:['تشخیص نوع پرسش…','جمع‌آوری اطلاعات…','نوشتن پاسخ…']};
function asThinkHtml(){return `<div class="as-m a think"><span class="av">${ASI.spark}</span><div class="as-think"><div class="as-row"><span class="dots"><i></i><i></i><i></i></span><span class="tx">${esc(AS.busyTxt||'در حال فکر کردن…')}</span></div><div class="sk"></div><div class="sk"></div><div class="sk"></div></div></div>`}
function asRender(anim){const B=$('.as-panel .as-msgs');if(!B)return;const P=asPage();
 if(!AS.msgs.length){const S=[...(ASUG[P.view]||[]),'این صفحه را خلاصه و توضیح بده'];const C=asCtxSafe();let i=0;
  const S0=apShip&&apShip();B.innerHTML=`<div class="as-empty"><div class="as-orb2">${ASI.spark}</div><b>چطور می‌توانم کمک کنم؟</b><p>دربارهٔ «${esc(P.title)}» توضیح می‌دهم، در وب جستجو می‌کنم، محاسبه می‌کنم یا فرایند این محموله را خودکار اجرا می‌کنم.</p>
   <div class="as-sug">${C&&C.R&&!AP.run?`<button class="as-apx" data-ap style="--i:${i++}">${ASI.bolt}<span><b>اجرای خودکار این محموله</b><small>${S0?esc(S0.o.nameFa)+' ← '+esc(S0.d.nameFa)+' · ':''}${fa(APS.length)} مرحله با عامل‌های هوشمند</small></span>${ASI.arrow.replace('<svg','<svg class="ar"')}</button>`:''}${!AP.run?`<button class="as-apx" data-pl style="--i:${i++}">${ASI.bolt}<span><b>برنامه‌ریزی محموله با یک جمله</b><small>هدف، محدودیت‌ها و مشخصات بار را بنویسید؛ برنامه را ببینید و اجرا کنید</small></span>${ASI.arrow.replace('<svg','<svg class="ar"')}</button>`:''}<div class="lb">پیشنهادها</div>${S.map(s=>`<button data-q="${esc(s)}" style="--i:${i++}">${ASI.m_explain}<span>${esc(s)}</span>${ASI.arrow.replace('<svg','<svg class="ar"')}</button>`).join('')}<button data-q="120×100×110 × 24 پالت وزن 18000 kg" data-mm="calc" style="--i:${i++}">${ASI.m_calc}<span>حجم و وزن حجمی ۲۴ پالت</span>${ASI.arrow.replace('<svg','<svg class="ar"')}</button><button data-q="آخرین اخبار بندر شهید رجایی" data-mm="search" style="--i:${i++}">${ASI.web}<span>آخرین اخبار بندر شهید رجایی</span>${ASI.arrow.replace('<svg','<svg class="ar"')}</button></div></div>`;
  $$('[data-q]',B).forEach(b=>b.onclick=()=>asSend(b.dataset.q,b.dataset.mm));const a=$('[data-ap]',B);if(a)a.onclick=()=>{asShow(false);apPre()};const pl=$('[data-pl]',B);if(pl)pl.onclick=()=>{asShow(false);plShow()};return}
 const LA=AS.msgs.map(m=>m.role).lastIndexOf('assistant');B.innerHTML=AS.msgs.map((m,i)=>m.role==='user'?`<div class="as-m u${m.fresh?'':' old'}" ${m.fresh?'':'style="animation:none"'}>${esc(m.content)}</div>`:asMsgHtml(m,i,i===LA)).join('')+(AS.busy?asThinkHtml():'');
 $$('.as-m.a .bd',B).forEach(d=>[...d.children].forEach((c,i)=>c.style.setProperty('--i',Math.min(i,24))));
 $$('.as-sc',B).forEach((c,i)=>c.style.setProperty('--i',i%8));
 $$('[data-view]',B).forEach(a=>a.onclick=e=>{e.preventDefault();open(a.dataset.view)});
 $$('.as-m [data-cp]',B).forEach(b=>b.onclick=()=>{const m=AS.msgs[+b.dataset.cp];const txt=String(m&&m.content||'')+(m&&m.res&&m.res.length?'\n\n'+m.res.map((r,i)=>'['+(i+1)+'] '+r.title+' — '+r.url).join('\n'):'');(navigator.clipboard?navigator.clipboard.writeText(txt):Promise.reject()).then(()=>{b.innerHTML=ASI.ok+'کپی شد';setTimeout(()=>{b.innerHTML=ASI.copy+'کپی'},1600)}).catch(()=>toast('کپی ممکن نشد'))});
 $$('.as-m [data-re]',B).forEach(b=>b.onclick=()=>{const i=+b.dataset.re;const u=[...AS.msgs.slice(0,i)].reverse().find(x=>x.role==='user');if(u)asSend(u.content,b.dataset.md||AS.msgs[i].ask||undefined)});
 $$('.as-res b[data-n]',B).forEach(asCount);
 AS.msgs.forEach(m=>m.fresh=false);B.scrollTop=B.scrollHeight}
function asCount(el){const v=+el.dataset.n;if(!isFinite(v))return;const dec=Math.abs(v)<1e3?Math.min(4,(String(v).split('.')[1]||'').length):Math.abs(v)<1e6?2:0;const f=x=>x.toLocaleString('en-US',{maximumFractionDigits:dec,minimumFractionDigits:0});
 if(matchMedia('(prefers-reduced-motion: reduce)').matches||el.dataset.done){el.textContent=f(v);return}el.dataset.done=1;const t0=performance.now(),D=900;const st=n=>{const k=Math.min(1,(n-t0)/D),e=1-Math.pow(1-k,4);el.textContent=f(k<1?v*e:v);if(k<1)requestAnimationFrame(st)};requestAnimationFrame(st)}
const ASMN={explain:'توضیح صفحه',search:'جستجوی وب',calc:'محاسبه',auto:'خودکار',local:'محلی'};
function asMsgHtml(m,i,last){const r=m.res||[];const src=(m.sources||[]).filter(s=>s&&(s.url||s.title));const c=m.calc||{};
 const big=c.value!=null&&isFinite(+c.value)&&c.kind!=='cargo'?`<div class="as-res"><span>نتیجه${c.unit?' ('+esc(c.unit)+')':''}</span><b data-n="${+c.value}">${esc(Number(c.value).toLocaleString('en-US',{maximumFractionDigits:4}))}</b></div>`:'';
 const calc=c.steps?`<table class="as-calc">${c.steps.map((s,j)=>`<tr style="animation-delay:${j*70+200}ms"><td>${esc(s.label)}</td><td>${esc(Number(s.value).toLocaleString('en-US',{maximumFractionDigits:4}))}</td></tr>`).join('')}</table>`:'';
 const links=r.length?`<div class="as-srcs">${r.slice(0,8).map((x,k)=>{const h=asHost(x.url);return `<a class="as-sc" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer" title="${esc(x.snippet||x.title)}"><span class="fv" style="background:hsl(${asHue(h)} 55% 42%)">${fa(k+1)}</span><div><b>${esc(x.title)}</b><small>${esc(h)}</small></div></a>`}).join('')}</div>`
  :src.length?`<div class="as-src">${src.slice(0,6).map(s=>s.url?`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${ASI.link}${esc(s.title||s.url)}</a>`:s.view?`<a href="#" data-view="${esc(s.view)}">${ASI.doc}${esc(s.title)}</a>`:`<span>${ASI.doc}${esc(s.title)}</span>`).join('')}</div>`:'';
 const ext=m.links&&m.links.length?`<div class="as-src">${m.links.map(l=>`<a href="${esc(l[1])}" target="_blank" rel="noopener noreferrer">${ASI.ext}${esc(l[0])}</a>`).join('')}</div>`:'';
 const tl=`<span class="as-tl"><button data-cp="${i}" title="کپی پاسخ">${ASI.copy}کپی</button><button data-re="${i}" title="پرسش دوباره">${ASI.again}دوباره</button>${m.mode!=='search'?`<button data-re="${i}" data-md="search" title="همین پرسش با جستجوی وب">${ASI.web}با وب</button>`:''}</span>`;
 return `<div class="as-m a${m.err?' err':''}${m.fresh?' fresh':' old'}${last?' last':''}" ${m.fresh?'':'style="animation:none"'}><span class="av">${ASI.spark}</span><div class="bd">${asMd(m.content,r)}</div>${big}${calc}${links}${ext}<div class="meta"><span>${esc(ASMN[m.mode]||m.mode||'')}</span>${m.engine?`<span>موتور: ${esc(m.engine)}</span>`:''}${m.model?`<span>${esc(String(m.model).split(':').pop())}</span>`:''}${m.ms?`<span>${fa((m.ms/1000).toFixed(1))} ث</span>`:''}${m.cost?`<span>$${m.cost}</span>`:''}${tl}</div></div>`}
function asLocal(q,mode){const P=asPage();
 if(mode==='calc'||mode==='auto'){const cg=calcCargo(q);if(cg)return {mode:'calc',content:`**ابعاد ${cg.dims.join('×')} cm × ${cg.n}**\n- حجم کل: **${cg.cbm} CBM**\n- وزن حجمی هوایی (۱۶۷ kg/CBM): **${cg.air.toLocaleString('en-US')} kg**${cg.kg?' · قابل پرداخت **'+cg.airChg.toLocaleString('en-US')+' kg**':''}\n- وزن حجمی جاده‌ای (۳۳۳ kg/CBM): **${cg.road.toLocaleString('en-US')} kg**\n- دریایی LCL (W/M): **${cg.seaWM}**`};
  try{const s=q.replace(/^(محاسبه|حساب کن|حساب)\s*[:：]?\s*/,'').replace(/[=?؟]\s*$/,'');const v=calcEval(s);return {mode:'calc',content:'**'+calcNorm(s)+' = '+Number(v).toLocaleString('en-US',{maximumFractionDigits:6})+'**'}}catch(e){if(mode==='calc')return {mode:'calc',err:true,content:'عبارت قابل محاسبه نیست: '+e.message+(svOn()?'':'\n\n> محاسبهٔ مسئله‌های متنی به سرور تیمی و مدل زبانی نیاز دارد.')}}}
 if(mode==='search'||(mode==='auto'&&/(جستجو|اینترنت|خبر|اخبار|آخرین|search|news)/i.test(q)))return {mode:'search',content:'جستجوی زندهٔ اینترنت روی سرور تیمی انجام می‌شود و اکنون به سرور وصل نیستید. می‌توانید همین عبارت را مستقیم باز کنید:',links:[['جستجو در Google','https://www.google.com/search?q='+encodeURIComponent(q)],['جستجو در Bing','https://www.bing.com/search?q='+encodeURIComponent(q)],['اخبار Google','https://news.google.com/search?q='+encodeURIComponent(q)]]};
 const K=wrap?$$('.sx-body .sx-kpi',wrap).map(k=>asClean(k.innerText).replace(/\n/g,' ')).slice(0,8):[];const G=(typeof NAVG!=='undefined'?[]:[]);
 return {mode:'local',content:`**${P.title}**${P.sub?' · '+P.sub:''}\n${P.route?'\n- '+P.route+'\n':''}${K.length?'\n**شاخص‌های این صفحه:**\n'+K.map(k=>'- '+k).join('\n'):'\n'+String(P.text).slice(0,500)}\n\n> توضیح هوشمند و جستجوی وب پس از اتصال به سرور تیمی (و تنظیم مدل زبانی) فعال می‌شود؛ محاسبه همین حالا هم کار می‌کند.`}}
async function asSend(q,mode){const t=$('.as-panel .as-ft textarea');q=String(q??(t?t.value:'')).trim();if(!q||AS.busy)return;if(t){t.value='';t.style.height='auto';asSlash('')}mode=mode||AS.mode;
 const sl=q.match(/^\/(\S+)\s*/);if(sl&&ASSL[sl[1].toLowerCase()]){mode=ASSL[sl[1].toLowerCase()];q=q.slice(sl[0].length).trim();if(!q){asMode(mode);return}}
 if(/^(⚡|کنترل خودکار|اجرای خودکار|autopilot)/i.test(q)){asShow(false);return apPre()}
 AS.msgs.push({role:'user',content:q,fresh:true});AS.busy=true;const BS=ASBUSY[mode]||ASBUSY.auto;let bi=0;AS.busyTxt=BS[0];asRender();asFabSync();const lg=$('.as-panel .as-hd .as-lg');if(lg)lg.classList.add('busy');const go=$('.as-panel .as-ft .go');if(go){go.disabled=true;go.classList.add('busy');go.innerHTML=ASI.spin}
 const tk=setInterval(()=>{bi=Math.min(bi+1,BS.length-1);AS.busyTxt=BS[bi];const x=$('.as-panel .as-think .tx');if(x&&x.textContent!==AS.busyTxt){x.textContent=AS.busyTxt;x.style.animation='none';void x.offsetWidth;x.style.animation=''}},2300);
 const t0=Date.now();let m;
 try{if(!svOn())m=asLocal(q,mode);else{const P=asPage();const H=AS.msgs.slice(0,-1).slice(-6).map(x=>({role:x.role,content:String(x.content||'').slice(0,1500)}));
   const j=await svApi('/api/assist',{method:'POST',body:{q,mode,page:P,history:H}});m={mode:j.mode,content:j.answer||'',res:j.results||[],sources:j.sources||[],calc:j.calc,engine:j.engine,model:j.model,ms:j.ms,cost:j.cost};
   if(j.offline)m.links=[['جستجو در Google','https://www.google.com/search?q='+encodeURIComponent(j.query||q)],['اخبار Google','https://news.google.com/search?q='+encodeURIComponent(j.query||q)]]}}
 catch(e){const L=e.code===404?asLocal(q,mode):null;m=L||{mode,err:true,content:e.message,links:mode==='search'||/جستجو|اینترنت/.test(e.message)?[['جستجو در Google','https://www.google.com/search?q='+encodeURIComponent(q)]]:null}}
 clearInterval(tk);m.role='assistant';m.ask=mode;m.fresh=true;m.ms=m.ms||Date.now()-t0;AS.msgs.push(m);AS.busy=false;AS.sel='';if(!AS.open)AS.unread++;asSv();
 const p=$('.as-panel');if(p){const lg2=$('.as-hd .as-lg',p);if(lg2)lg2.classList.remove('busy');const g=$('.as-ft .go',p);if(g){g.disabled=false;g.classList.remove('busy');g.innerHTML=ASI.send}}asRender();asCtxBar();asFabSync();emit('assistant.answer',{mode:m.mode})}
