function apShip(){const C=asCtxSafe();if(!C||!C.R)return null;const R=C.R,seq=R.nodeSeq||[],G=C.G;const o=G.nodeById[seq[0]],d=G.nodeById[seq[seq.length-1]];const legs=R.legs||[];
 const sea=legs.filter(l=>l.mode==='sea');const ln=l=>({f:l.from&&l.from.id||l.from,t:l.to&&l.to.id||l.to});const lastSea=sea.length?ln(sea[sea.length-1]):null,firstSea=sea.length?ln(sea[0]):null;
 const ir=seq.find(id=>(G.nodeById[id]||{}).country==='IR');const irL=legs.map(ln).filter(l=>(G.nodeById[l.f]||{}).country==='IR');const road=irL.find((l,i)=>(legs.filter(x=>(G.nodeById[ln(x).f]||{}).country==='IR')[i]||{}).mode==='road');
 return {C,R,o,d,legs,sea:!!(lastSea&&(G.nodeById[lastSea.t]||{}).country==='IR'),pol:firstSea&&G.nodeById[firstSea.f],pod:lastSea&&G.nodeById[lastSea.t],entry:ir&&G.nodeById[ir],domFrom:road?G.nodeById[road.f]:null,cargo:C.cargo||{},sel:C.E.selected||0}}
const apDom=n=>{if(!n)return null;const nm=n.nameFa||'';if(/رجایی|بندرعباس/.test(nm))return 'BND';const M={THR:'تهران',BUZ:'بوشهر',BIK:'امام',CHB:'چابهار',ANZ:'انزلی',AMR:'امیرآباد',AST:'آستارا',SRK:'سرخس',BZG:'بازرگان',MRJ:'میرجاوه',INB:'اینچه',LTF:'لطف',JLF:'جلفا',MRN:'مهران',SHL:'شلمچه',ISF:'اصفهان',MHD:'مشهد',TBZ:'تبریز',SYZ:'شیراز',AWZ:'اهواز',QZV:'قزوین',KER:'کرمان',AZD:'یزد',ARK:'اراک',RAS:'رشت',SRY:'ساری',KSH:'کرمانشاه',ZAH:'زاهدان',QOM:'قم',SMN:'سمنان',HMD:'همدان'};for(const [k,v] of Object.entries(M))if(nm.includes(v))return k;return null};
const apDD=n=>{const nm=(n&&n.nameFa)||'';return /رجایی|بندرعباس/.test(nm)?'SHR':/امام/.test(nm)?'BIK':/بوشهر/.test(nm)?'BUZ':/چابهار/.test(nm)?'CHB':/انزلی/.test(nm)?'ANZ':/امیرآباد/.test(nm)?'AMR':/آستارا/.test(nm)?'AST':null};
const apLoc=n=>n?String(n.id||'').replace('_',''):'';
/* stage implementations */
const APF={
 async intake(S){apSay('خواندن مشخصات بار، مبدأ، مقصد و مسیر انتخاب‌شده');const c=S.cargo;apVal('od','مبدأ ← مقصد',(S.o?S.o.nameFa:'?')+' ← '+(S.d?S.d.nameFa:'?'),1);apVal('cg','بار',(APCF[c.commodity]||c.commodity||'')+' · '+apNum(c.weightKg)+' kg · '+fa(c.cbm||0)+' CBM · $'+apNum(c.value));
  apVal('rt','مسیر انتخابی',S.R.name||'—');apVal('fr','کرایهٔ مدل مسیر',usd(S.R.total||0)+' · '+fa(nf(S.R.avgDays||0,1))+' روز');await apW(900)},
 async route(S){await apGo('opt');await apType('[data-k=o]',S.o.id,'تنظیم مبدأ');await apType('[data-k=d]',S.d.id,'تنظیم مقصد');await apBtn('متعادل','پروفایل متعادل');await apClick('.op-run','اجرای بهینه‌سازی');await apW(1100);
  const K=await apFind('.op-kpis');if(K)await apMove(K,'خواندن نتایج');const kp=$$('.op-kpis .sx-kpi',apRoot()).map(k=>asClean(k.innerText).split('\n'));const g=t=>{const x=kp.find(a=>a[0]&&a[0].includes(t));return x?x[1]:null};
  if(g('هزینه'))apVal('p50','هزینهٔ میانه (P50)',g('هزینه'));if(g('زمان'))apVal('d50','زمان میانه',g('زمان'));if(g('احتمال'))apVal('otd','تحویل به‌موقع',g('احتمال'));if(g('TOPSIS'))apVal('tops','امتیاز TOPSIS',g('TOPSIS'));
  const row=apQ('.op-row.on')||apQ('.op-row');if(row){await apMove(row,'گزینهٔ برتر');apVal('best','گزینهٔ برتر بهینه‌ساز',asClean(row.innerText).split('\n')[0].slice(0,60),1)}},
 async live(S){await apGo('lq');await apType('.lq-f',S.o.id,'مبدأ');await apType('.lq-t',S.d.id,'مقصد');await apClick('.lq-go','محاسبه با دادهٔ روز');await apW(1300);
  const Q=IFA.liveQuote({from:S.o.id,to:S.d.id});const b=(Q.routes||[])[0];S.liveQ=b;if(b){apVal('live','کرایه با دادهٔ روز',usd(b.liveUSD)+' · اطمینان '+apPct(b.confidence));apVal('liveR','بهترین گزینهٔ دادهٔ روز',b.name+' · '+fa(b.days)+' روز',1)}const r=apQ('.lq-r,.sx-card');if(r)await apMove(r,'بررسی منبع داده‌ها');
  if(svOn()&&AP.opts.server&&S.pol&&S.pod){try{const C=await cnSched(apLoc(S.pol),apLoc(S.pod));S.sched=C.stats;if(C.stats&&C.stats.n){apSay('برنامهٔ حرکت واقعی خطوط دریافت شد ('+fa(C.stats.n)+' حرکت)','route');apVal('sch','برنامهٔ حرکت خطوط '+apLoc(S.pol)+'→'+apLoc(S.pod),fa(C.stats.n)+' حرکت · نخستین '+new Date(C.stats.earliest).toLocaleDateString('fa-IR')+' · سریع‌ترین '+fa(C.stats.fastest)+' روز · میانه '+fa(C.stats.medianTransit)+' روز',1)}else apVal('sch','برنامهٔ حرکت خطوط','حرکتی در ۴ هفتهٔ آینده از ارائه‌دهندگان متصل یافت نشد',1)}catch(e){if(!/تنظیم نشده/.test(e.message||''))apSay('برنامهٔ حرکت خطوط دریافت نشد: '+String(e.message||e).slice(0,60),'route')}}},
 async landed(S){await apGo('cost');const s=await apFind('.co-src');if(s&&[...s.options].some(o=>o.value==='r'+S.sel))await apType(s,'r'+S.sel,'مسیر');const inc=S.cargo.incoterm||'CFR';await apSeg(inc);await apW(500);
  const L=IFA.landedCost();S.landed=L;apVal('land','هزینهٔ کامل لجستیک',usd(L.totalUSD));apVal('landV','بهای تمام‌شدهٔ کالا در مقصد',usd(L.landedUSD));apVal('buy','سهم خریدار ('+inc+')',usd(L.buyerUSD)+' · فروشنده '+usd(L.sellerUSD),1);
  if(svOn()&&AP.opts.server){const X=acCtx();const C=X?await acCalib(X.lane,X.mode):null;const A=acApply(L,C);if(A){S.cal=A;apSay('برآورد با '+fa(A.nAll)+' ردیف فاکتور واقعی کالیبره شد','cost');apVal('cal','برآورد کالیبره با فاکتورهای واقعی',usd(A.adj)+' ('+(A.pct>0?'+':'')+fa(A.pct)+'٪ نسبت به مدل) · '+fa(A.comps)+' جزء',1)}
   const pc=irDestPort();if(pc){try{const r=await svApi('/api/ports/tariff/calc',{method:'POST',body:{port:pc,eq:S.cargo.containerType||'40HC',qty:1,days:+AP.opts.dwell||10,tons:Math.round((+S.cargo.weightKg||0)/1000),reefer:!!S.cargo.reefer}});S.port=r;apSay('هزینه‌های بندری '+r.name+' با تعرفهٔ ثبت‌شده محاسبه شد','cost');apVal('port','هزینه‌های بندری '+r.name,apRial(r.totalIRR)+' · ۱ کانتینر · '+fa(r.days)+' روز توقف ('+fa(r.free)+' روز آزاد)',1)}catch(e){if(/ثبت نشده/.test(e.message||''))S.portNo=pc}}}},
 async load(S){await apGo('load');const c=S.cargo;const eq=c.shipmentType==='FTL'||c.shipmentType==='ROAD'?'FTL':(c.containerType||'40HC');const b=await apFind('.ld-eq',{txt:eq});if(b)await apClick(b,'انتخاب '+eq);await apW(900);const cv=apQ('canvas');if(cv)await apMove(cv,'بررسی چیدمان سه‌بعدی');
  const P=IFA.pack(null,eq==='FTL'?'40HC':eq);S.eq=eq==='FTL'?'40HC':eq;S.ncont=P.containers;const vu=P.stats.reduce((a,s)=>a+s.volUtil,0)/(P.stats.length||1);S.packU=vu;S.packX=P.unplaced||0;apVal('pack','چیدمان',fa(P.containers)+' × '+eq+' · پرشدگی '+apPct(vu)+(P.unplaced?' · ⚠ '+fa(P.unplaced)+' جانمانده':''))},
 async tariff(S){await apGo('tar');let hs=String(AP.opts.hs||S.cargo.hs||'').replace(/\D/g,''),src='ورودی کاربر';
  if(!hs&&AP.opts.server&&svOn()&&(AP.opts.desc||APCF[S.cargo.commodity])){apSay('درخواست پیشنهاد کد HS از «کارشناس اسناد و گمرک» روی سرور','cus');try{const r=await agApi.hs(AP.opts.desc||APCF[S.cargo.commodity]);const c=(r.candidates||[])[0];if(c&&c.code){hs=c.code.replace(/\D/g,'').padEnd(8,'0');src='عامل اسناد · اطمینان '+apPct(c.confidence)}}catch(e){}}
  if(!hs){hs=APHS[S.cargo.commodity]||'';src='پیش‌فرض گروه کالا'}S.hs=hs;S.hsSrc=src;if(hs)await apType('[data-k=hs]',hs,'درج کد HS');await apType('[data-k=fob]',Math.round(+S.cargo.value||0),'ارزش FOB');await apW(400);
  if(hs&&svOn()&&AP.opts.server){try{await irFxSync();const TB=await irTb(hs);S.tb=TB;S.tbN=(IR.tbMeta||{}).n||0;S.cfx=IR.fx&&IR.fx.rates&&IR.fx.rates.USD?IR.fx:null;if(TB)apSay('نرخ حقوق ورودی از کتاب تعرفهٔ ایران خوانده شد','cus')}catch(e){}}
  const D=IFA.dutyCalc(hs?{hs}:{});S.duty=D;if(S.tb)apVal('tbk','کتاب تعرفهٔ ایران',(S.tb.match==='exact'?'✓ ':'≈ ')+String(S.tb.hs).replace(/^(\d{4})(\d{2})/,'$1.$2.')+' · '+fa(S.tb.duty)+'٪'+(S.tb.range&&S.tb.range[0]!==S.tb.range[1]?' (زیرشاخه‌ها '+fa(S.tb.range[0])+'–'+fa(S.tb.range[1])+'٪)':'')+' · '+String(S.tb.desc||'').slice(0,50),1);if(S.cfx)apVal('cfx','نرخ ارز گمرکی',nf(S.cfx.rates.USD,0)+' ریال/USD · '+(S.cfx.date||''),1);apVal('hs','کد HS',(hs||'—')+' · نرخ '+fa(D.rate)+'٪ · '+src,1);apVal('duty','حقوق ورودی + مالیات‌ها',apRial(D.totalIRR)+' ('+fa(D.effectivePct)+'٪)');if(hs&&svOn()&&AP.opts.server){try{const V=await cnHs(hs);S.hsOk=!!V.valid;S.hsOff=V.desc||'';S.hsHead=V.heading||'';apVal('hsv','کد HS در نامگذاری رسمی',V.valid?'✓ '+hs.slice(0,4)+'.'+hs.slice(4,6)+' · '+(String(V.desc||'').length<14&&V.heading?String(V.heading).slice(0,44)+' › ':'')+String(V.desc||'').slice(0,60):'⚠ زیرعنوان '+hs.slice(0,6)+' در HS 2022 وجود ندارد',1);apSay(V.valid?'کد HS با نامگذاری رسمی HS 2022 تطبیق داده شد':'⚠ کد HS در نامگذاری رسمی یافت نشد','cus')}catch(e){}}
  if(D.permits&&D.permits.length)apVal('perm','مجوزهای لازم',D.permits.map(p=>p.agency).join('، '),1);
  const k=apQ('.sx-kpi');if(k)await apMove(k,'کنترل نتیجه')},
 async ins(S){await apGo('ins');const c=S.cargo;const cls=c.dg?'dg':c.reefer?'rf':{machinery:'mach',auto:'mach',electronics:'elec',steel:'bulk'}[c.commodity]||'gen';await apType('[data-k=cls]',cls,'نوع کالا');await apType('[data-k=cl]','A','شرایط ICC A');
  const I=IFA.cargoLiability();S.ins=I;apVal('ins','حق بیمهٔ ICC A',usd(I.premiumUSD)+' · نرخ '+fa(I.ratePct)+'٪');apVal('insV','ارزش بیمه‌ای (۱۱۰٪ CIF)',usd(I.insuredUSD))},
 async sanc(S){await apGo('sanc');const N=[AP.opts.cust,AP.opts.shp,AP.opts.cne].map(s=>String(s||'').trim()).filter(Boolean);let P=[];try{P=IFA.partners().slice(0,2).map(p=>p.name)}catch(e){}const names=[...new Set([...N,...P])].slice(0,5);
  if(!names.length){apSay('نامی برای غربال وجود ندارد؛ نام مشتری/فرستنده را در شروع وارد کنید');apVal('sanc','غربال تحریم','نامی وارد نشده');return}
  for(const n of names.slice(0,3))await apType('.sn-q',n,'غربال «'+n.slice(0,20)+'»');await apW(700);const H=await IFA.screen(names);const hit=H.filter(h=>(h.hits||[]).some(x=>x.score>=.86));S.sancHits=hit.length;
  apVal('sanc','غربال تحریم ('+fa(names.length)+' نام)',hit.length?'⚠ تطابق احتمالی: '+hit.map(h=>h.query).join('، '):'✓ بدون تطابق',1);if(hit.length)apSay('⚠ تطابق احتمالی تحریم — پیش از هر اقدام، بررسی دستی لازم است','risk')},
 async risk(S){await apGo('risk');const R=IFA.risks().sort((a,b)=>b.score-a.score);const hi=R.filter(r=>r.score>=12);const c=apQ('.rk-c.h')||apQ('.rk-c');if(c)await apMove(c,'ماتریس ریسک');S.risks=R;
  apVal('risk','ریسک‌های بالا',fa(hi.length)+' از '+fa(R.length));if(R[0])apVal('risk1','بالاترین ریسک',R[0].risk+' (امتیاز '+fa(R[0].score)+')',1)},
 async dd(S){if(!S.sea){apSay('مسیر دریایی به بندر ایران ندارد؛ دموراژ بندری لازم نیست');return 'skip'}await apGo('dd');const p=apDD(S.pod);if(p)await apType('[data-k=port]',p,'بندر تخلیه');await apType('[data-k=ct]',String(S.eq||'40').startsWith('20')?'20':'40','نوع کانتینر');await apType('[data-k=n]',S.ncont||1,'تعداد');
  const D=IFA.demurrage();S.dd=D;apVal('dd','دموراژ و دیتنشن برآوردی',usd(D.totalUSD)+' · انبارداری '+apRial(D.storageIRR));apVal('ddf','پایان زمان آزاد',D.freeTimeEnds||'—')},
 async dom(S){const f=apDom(S.domFrom||S.pod||S.entry),t=apDom(S.d);if(!f||!t||f===t){apSay('حمل جاده‌ای داخلی جداگانه‌ای در این مسیر لازم نیست');return 'skip'}await apGo('dom');await apType('[data-k=from]',f,'مبدأ داخلی');await apType('[data-k=to]',t,'مقصد');const tons=Math.max(1,Math.ceil((+S.cargo.weightKg||0)/1000));await apType('[data-k=tons]',tons,'وزن (تن)');
  const T=IFA.truckCost(f,t,'trl',tons);S.domc=T;apVal('dom','حمل داخلی '+f+'→'+t,apRial(T.totalIRR)+' · '+fa(T.trucks)+' دستگاه · '+apNum(T.km)+' km',1)},
 async rfq(S){await apGo('rfq');await apSeg('bi');const cb=$$('input[type=checkbox]',apRoot()).filter(apVis).slice(0,4);for(const c of cb)if(!c.checked)await apType(c,true,'انتخاب فورواردر');const n=$$('input[type=checkbox]',apRoot()).filter(c=>c.checked).length;
  let txt='';try{txt=IFA.rfq('fa')||''}catch(e){}S.rfq=txt;const m=await apFind('.rf-mail');if(m)await apMove(m,'ارسال فقط با تأیید شما');apSay('پیش‌نویس استعلام آماده است؛ ارسال انجام نشد — تصمیم با شماست','buy');apVal('rfq','استعلام از فورواردرها',fa(n)+' گیرنده انتخاب شد · ارسال نشده (منتظر تأیید)',1)},
 async job(S){await apGo('pnl');if(!await apBtn('پروندهٔ جدید','ایجاد پرونده'))throw new Error('دکمهٔ پروندهٔ جدید پیدا نشد');await apW(500);const ref=(apQ('[data-k=ref]')||{}).value||'';S.job=ref;
  if(AP.opts.cust)await apType('[data-k=cust]',AP.opts.cust,'مشتری');await apType('[data-k=mk]',AP.opts.margin||12,'حاشیهٔ سود');await apBtn('ساخت ردیف‌ها از برآورد','ساخت ردیف‌های هزینه/فروش');await apW(700);
  const J=IFA.jobs().find(j=>j.ref===ref)||IFA.jobs().slice(-1)[0];if(J){S.jobv=J;apVal('job','پرونده '+(J.ref||ref),'فروش '+usd(J.salesUSD)+' · هزینه '+usd(J.costUSD)+' · سود '+usd(J.gpUSD)+' ('+fa(J.marginPct)+'٪)',1)}},
 async quote(S){await apGo('sal');await apSeg('quo');await apW(500);const s=await apFind('[data-k=job]');if(s&&S.job){const o=[...s.options].find(o=>o.textContent.includes(S.job));if(o)await apType(s,o.value,'انتخاب پرونده')}const p=await apFind('button',{txt:'PDF'});if(p)await apMove(p,'پیشنهاد قیمت آماده چاپ');apVal('quo','پیشنهاد قیمت چندارزی','آماده (دلار، یورو، درهم، یوان، ریال) · اعتبار '+fa((apQ('[data-k=valid]')||{}).value||7)+' روز')},
 async bkg(S){if(!S.sea){apSay('رزرو کانتینری دریایی برای این مسیر لازم نیست');return 'skip'}await apGo('bkg');await apSeg('bk');if(!await apBtn('رزرو جدید','رزرو جدید'))throw new Error('دکمهٔ رزرو جدید پیدا نشد');await apW(500);
  await apType('[data-k=pol]',apLoc(S.pol),'بندر بارگیری');await apType('[data-k=pod]',apLoc(S.pod),'بندر تخلیه');await apType('[data-k=eq]',S.eq||'40HC','نوع کانتینر');await apType('[data-k=qty]',S.ncont||1,'تعداد');if(S.job)await apType('[data-k=job]',S.job,'پرونده');await apType('[data-k=note]','ثبت خودکار آسانا — منتظر تأیید خط/فورواردر','یادداشت');
  const etd=(apQ('[data-k=etd]')||{}).value||'';await apBtn('بستن','ذخیره');apVal('bkg','درخواست رزرو',apLoc(S.pol)+'→'+apLoc(S.pod)+' · ETD '+etd+' · کات‌آف‌ها در کارتابل مهلت‌ها',1)},
 async docs(S){await apGo('tpl');await apSeg('ci');await apW(400);const j=apQ('.tp-j');if(j&&S.job&&[...j.options].some(o=>o.value===S.job))await apType(j,S.job,'پرونده');
  if(AP.opts.shp)await apType('[data-k=shp]',AP.opts.shp,'فرستنده');if(AP.opts.cne||AP.opts.cust)await apType('[data-k=cne]',AP.opts.cne||AP.opts.cust,'گیرنده');await apType('[data-k=pol]',(S.pol||S.o).nameFa,'بندر/محل بارگیری');await apType('[data-k=pod]',(S.pod||S.d).nameFa,'محل تخلیه');
  await apType('[data-k=org]',S.o.country||'','کشور سازنده');await apType('[data-k=inc]',S.cargo.incoterm||'CFR','اینکوترمز');const p=await apFind('button',{txt:'چاپ'});if(p)await apMove(p,'فاکتور آمادهٔ چاپ');apVal('docs','فاکتور تجاری','پیش‌نویس تکمیل شد'+(S.job?' · '+S.job:''))},
 async cus(S){await apGo('cus');await apSeg('dec');if(!await apBtn('اظهارنامهٔ جدید','اظهارنامهٔ جدید'))throw new Error('دکمهٔ اظهارنامهٔ جدید پیدا نشد');await apW(500);if(S.job)await apType('[data-k=job]',S.job,'پرونده');if(S.hs)await apType('[data-k=hs]',S.hs,'کد تعرفه');
  const cv=Math.round((S.duty&&S.duty.cifUSD)||+S.cargo.value||0);await apType('[data-k=val]',cv,'ارزش گمرکی');if(S.entry)await apType('[data-k=cus]','گمرک '+S.entry.nameFa.replace(/^(مرز|بندر)\s*/,''),'گمرک اجرایی');await apType('[data-k=note]','پیش‌نویس خودکار — کنترل نهایی توسط ترخیص‌کار','یادداشت');await apBtn('بستن','ذخیره');
  apVal('cus','اظهارنامهٔ گمرکی','پیش‌نویس ثبت شد · ارزش '+usd(cv)+(S.hs?' · HS '+S.hs:''),1)},
 async track(S){await apGo('track');await apW(500);const n0=new Set(IFA.shipments.list().map(x=>x.id));const b=apQ('.tr-new');if(b)await apClick(b,'ثبت محموله از مسیر فعلی');let L=IFA.shipments.list();if(!L.some(x=>!n0.has(x.id))){IFA.shipments.create({});L=IFA.shipments.list();open('track');await apW(400)}const s=L.find(x=>!n0.has(x.id))||L[0];S.ship=s;await apW(500);apVal('trk','محموله برای رهگیری',(s&&(s.ref||s.id))+(s&&s.state&&s.state.eta?' · ETA '+new Date(s.state.eta).toLocaleDateString('fa-IR'):''),1)},
 async final(S){apSay('جمع‌بندی نتایج همهٔ عامل‌ها');await apW(500);if(!wrap)open('exec')}};
