/* ===== v15.11: repeatable processes (flows) UI — live run progress, visual step timeline, drag-to-reorder, inline validation ===== */
const flApi={
 list:()=>svApi('/api/flows'),get:id=>svApi('/api/flows/'+id),save:b=>svApi('/api/flows',{method:'POST',body:b}),
 toggle:(id,en)=>svApi('/api/flows/'+id,{method:'PATCH',body:{enabled:!!en}}),del:id=>svApi('/api/flows/'+id,{method:'DELETE'}),
 run:(id,vars)=>svApi('/api/flows/'+id+'/run',{method:'POST',body:vars?{vars}:{}}),cancel:t=>svApi('/api/flows/runs/'+t+'/cancel',{method:'POST',body:{}}),task:t=>svApi('/api/agents/tasks/'+(+t))};
const FLS={edit:null,open:{},poll:{},run:{},meta:null,col:{},dirty:false,added:null};
const FLDOW=['یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه','شنبه'];
const FLEVFA={'shipment.created':'ثبت محمولهٔ جدید','shipment.delayed':'تأخیر محموله','shipment.delivered':'تحویل محموله','milestone.updated':'به‌روزرسانی مرحله','job.status':'تغییر وضعیت پرونده','wb.status':'تغییر وضعیت بارنامه','quote.received':'رسیدن پاسخ استعلام','rates.imported':'ورود نرخ‌های تازه','partner.rates':'نرخ‌های ارسالی شریک','rate.jump':'جهش نرخ','risk.signal':'سیگنال ریسک','surcharge.notice':'اعلام سرشارژ','route.status':'تغییر وضعیت کریدور','domestic.tariff':'نرخ‌نامهٔ حمل داخلی','demurrage.freetime':'پایان زمان آزاد','shipment.overdue':'عقب‌افتادگی محموله','payment.approved':'تأیید پرداخت'};
const FLTY={tool:'ابزار',agent:'کارمند هوشمند',llm:'جمع‌بندی با مدل',notify:'اعلان به تیم',gate:'شرط ادامه'};
const FLTI={tool:'⚙',agent:'🤖',llm:'✦',notify:'📣',gate:'⑂'};const FLTC={tool:'#3d78d8',agent:'#7a5af5',llm:'#2ea58a',notify:'#d9a53a',gate:'#e97366'};
const FLIC={daily_brief:'🌅',rate_watch:'📈',lane_rfq:'🔁',delay_watch:'⏱',risk_scan:'🛰',partner_screen:'🛡',market_weekly:'📊',quote_collect:'📥',delay_event:'⚡'};
const FLSTF={ok:['موفق','ok'],failed:['ناموفق','bad'],stopped:['متوقف (شرط)','warn'],cancelled:['لغو','warn'],partial:['با هشدار','warn'],running:['در حال اجرا','warn'],queued:['در صف','warn']};
function flSchedTxt(s){s=s||{};if(s.mode==='every'){const m=+s.minutes||60;return 'هر '+(m%1440===0?fa(m/1440)+' روز':m%60===0?fa(m/60)+' ساعت':fa(m)+' دقیقه')}
 if(s.mode==='daily')return 'هر روز ساعت '+fa(s.at||'08:00');if(s.mode==='weekly')return 'هر هفته '+(FLDOW[+s.dow]||'')+' ساعت '+fa(s.at||'08:00');if(s.mode==='event')return 'با رویداد «'+(FLEVFA[s.event]||s.event)+'»';return 'اجرای دستی'}
const flSchedIc=s=>({every:'🔄',daily:'🕗',weekly:'📅',event:'⚡'})[(s||{}).mode]||'✋';
const flJ=(v,d)=>{try{const s=String(v||'').trim();return s?JSON.parse(s):d}catch(e){throw new Error('JSON نامعتبر: '+String(v).slice(0,60))}};
const flPJ=o=>o&&Object.keys(o).length?JSON.stringify(o,null,1):'';
const flRel=t=>{const d=(t-Date.now())/6e4,a=Math.abs(d);const s=a<1?'لحظاتی':a<60?fa(Math.round(a))+' دقیقه':a<1440?fa(Math.round(a/60))+' ساعت':fa(Math.round(a/1440))+' روز';return a<1?(d>0?'به‌زودی':'همین حالا'):d>0?s+' دیگر':s+' پیش'};
function flLogHtml(L){if(!L)return '<p class="sx-muted">هنوز اجرا نشده است.</p>';const steps=Array.isArray(L)?L:(L.steps||[]);
 const head=!Array.isArray(L)&&L.status?`<div class="fl-st">${chip((FLSTF[L.status]||['',''])[1]||'warn',(FLSTF[L.status]||[L.status])[0])} ${L.why?'<small>'+esc(L.why)+'</small>':''}</div>`:'';
 const SI={ok:'✓',fail:'×',skip:'↷',stop:'■',warn:'!',approval:'⏳'};
 return head+`<div class="fl-log">${steps.map((s,i)=>{const o=s.out||{};const txt=o.text?String(o.text):'';return `<div class="fl-step ${esc(s.status)}" style="--i:${i}"><span class="dt">${SI[s.status]||'•'}</span><b>${fa(s.n)}. ${esc(s.title)}</b> <small class="sx-muted">${FLTI[s.type]||''} ${esc(FLTY[s.type]||s.type)}${s.ms!=null?' · '+fa((s.ms/1000).toFixed(1))+' ث':''}${s.status==='approval'?' · منتظر تأیید در کارتابل':''}${s.status==='skip'?' · رد شد (شرط when)':''}</small>${s.err?`<div class="fw-al bad">${esc(s.err)}</div>`:''}${txt?`<div class="fl-txt">${esc(txt.slice(0,1500))}</div>`:Object.keys(o).length?`<details><summary>خروجی</summary><pre>${esc(JSON.stringify(o,null,1).slice(0,2500))}</pre></details>`:''}</div>`}).join('')}</div>`}
function flRunHtml(F){const R=FLS.run[F.id];if(!R)return '';const n=R.n||0,T=F.steps.length||1;return `<div class="fl-run"><div class="rw"><span class="sp"></span><span>${R.st==='queued'?'در صف اجرا…':'در حال اجرا · گام '+fa(Math.min(n+1,T))+' از '+fa(T)}${R.cur?' · '+esc(R.cur):''}</span><button class="sx-btn xs" data-cn>لغو</button></div><div class="br"><i style="width:${Math.max(4,Math.round(n/T*100))}%"></i></div></div>`}
async function agFlows(B,re,live){const r=await flApi.list();if(!live())return;FLS.meta=r;const ed=svCan('flows.edit');
 B.oninput=B.onfocusin=B.onkeydown=null;if(FLS.edit&&ed)return flEditor(B,re,live,r);
 const now=Date.now();
 const card=(F,i)=>{const st=FLSTF[F.last_status]||null;const run=FLS.run[F.id];return `<div class="fl-c s-${run?'run':esc(F.last_status||'none')}${F.enabled?'':' off'}${FLS.added===F.id?' fl-added':''}" data-id="${F.id}" style="--i:${i}"><div class="fl-h"><span class="fl-ic">${FLIC[F.tpl]||'🔁'}</span><div style="flex:1;min-width:0"><b>${esc(F.name)}</b><div><span class="fl-sch">${flSchedIc(F.sched)} ${esc(flSchedTxt(F.sched))}</span></div></div>${ed?`<input type="checkbox" class="fl-sw" data-tg ${F.enabled?'checked':''} title="${F.enabled?'زمان‌بندی فعال است':'زمان‌بندی غیرفعال است'}">`:chip(F.enabled?'ok':'warn',F.enabled?'فعال':'غیرفعال')}</div>
  ${F.d?`<p>${esc(F.d)}</p>`:''}<div class="fl-meta"><span>${fa(F.steps.length)} گام</span><span>${fa(F.runs||0)} اجرا</span>${F.last_run?`<span title="${esc(tmDt(F.last_run))}">آخرین: ${flRel(F.last_run)} ${st?chip(st[1],st[0]):''}</span>`:''}${F.enabled&&F.next_due&&F.sched.mode!=='manual'&&F.sched.mode!=='event'?`<span title="${esc(tmDt(F.next_due))}">بعدی: ${F.next_due<now?'به‌زودی':flRel(F.next_due)}</span>`:''}</div>
  <div class="fl-runw">${flRunHtml(F)}</div>
  <div class="fl-act"><button class="sx-btn xs pri" data-run ${run?'disabled':''}>▶ اجرا</button>${ed?`<button class="sx-btn xs" data-ed>✎ ویرایش</button><button class="sx-btn xs" data-dup>⧉ کپی</button>`:''}<button class="sx-btn xs" data-lg>${FLS.open[F.id]?'▾':'▸'} گزارش آخرین اجرا</button>${F.last_task?`<button class="sx-btn xs" data-tr>ردپا</button>`:''}${ed?`<button class="sx-btn xs" data-del>حذف</button>`:''}</div>
  ${FLS.open[F.id]?`<div class="fl-lgb">${flLogHtml(F.last_log)}</div>`:''}</div>`};
 const tvars=t=>Object.entries(t.vars||{}).map(([k,v])=>`<label><small>${esc(k)}</small><input data-v="${esc(k)}" value="${esc(typeof v==='object'?JSON.stringify(v):v)}"></label>`).join('');
 B.innerHTML=`${r.kill?'<div class="fw-al bad">کلید توقف اضطراری فعال است؛ هیچ فرایندی اجرا نمی‌شود.</div>':''}${r.paused?'<div class="fw-al warn">«فرایندگردان» در تنظیمات متوقف شده است.</div>':''}
 <div class="sx-card"><header><b>فرایندهای تکرارپذیر</b><small>زنجیره‌ای از ابزارها و کارمندان هوشمند که دستی، زمان‌بندی‌شده یا با رویداد اجرا می‌شود؛ هر اقدام حساس همچنان از سیاست و کارتابل تأیید عبور می‌کند</small>${ed?'<button class="sx-btn sm pri" data-new>+ فرایند جدید</button>':''}</header>
 ${r.flows.length?`<div class="fl-cards">${r.flows.map(card).join('')}</div>`:'<p class="sx-muted">هنوز فرایندی نساخته‌اید؛ از الگوهای آمادهٔ زیر شروع کنید یا در حالت «⚡ خودکار» مسیر را به‌صورت فرایند ذخیره کنید.</p>'}</div>
 ${ed?`<div class="sx-card"><header><b>الگوهای آماده</b><small>با یک کلیک اضافه و بعد در صورت نیاز ویرایش کنید</small></header><div class="fl-cards">${r.templates.map((t,i)=>`<div class="fl-c tpl" data-k="${esc(t.k)}" style="--i:${i}"><div class="fl-h"><span class="fl-ic">${FLIC[t.k]||'🔁'}</span><div style="flex:1;min-width:0"><b>${esc(t.name)}</b><div><span class="fl-sch">${flSchedIc(t.sched)} ${esc(flSchedTxt(t.sched))} · ${fa(t.steps)} گام</span></div></div></div><p>${esc(t.d)}</p>${Object.keys(t.vars||{}).length?`<div class="fl-vars">${tvars(t)}</div>`:''}<div class="fl-act"><button class="sx-btn xs pri" data-add>+ افزودن</button>${r.flows.some(f=>f.tpl===t.k)?'<small class="sx-muted">✓ قبلاً اضافه شده</small>':''}</div></div>`).join('')}</div></div>`:''}
 <div class="sx-card fl-help"><header><b>راهنمای کوتاه</b></header><p class="sx-muted">در آرگومان‌ها می‌توانید از خروجی گام‌های قبل استفاده کنید: <code>{{vars.pol}}</code>، <code>{{s1.items.length}}</code>، <code>{{s2.items[*].name}}</code>، <code>{{today}}</code>، <code>{{trigger.data.ref}}</code>. شرط‌ها: <code>{{s1.count}} &gt; 0</code>، <code>==</code>، <code>!=</code>، <code>contains</code>. گام «شرط ادامه» اگر برقرار نباشد فرایند را بی‌خطا متوقف می‌کند.</p></div>`;
 FLS.added=null;const F=id=>r.flows.find(x=>x.id===+id);
 $$('.fl-c[data-id]',B).forEach(c=>{const f=F(c.dataset.id);const q=s=>$(s,c);
  q('[data-run]').onclick=tmTry(async()=>{const t=await flApi.run(f.id);toast('فرایند «'+f.name+'» اجرا شد');FLS.run[f.id]={task:t.task.id,n:0,st:'queued'};flRunPaint(B,f);flPoll(f,t.task.id,re,B)});
  if(q('[data-tg]'))q('[data-tg]').onchange=tmTry(async e=>{try{await flApi.toggle(f.id,e.target.checked);f.enabled=e.target.checked;c.classList.toggle('off',!f.enabled);toast(f.enabled?'زمان‌بندی فعال شد':'زمان‌بندی متوقف شد');setTimeout(re,500)}catch(x){e.target.checked=!e.target.checked;throw x}});
  if(q('[data-ed]'))q('[data-ed]').onclick=()=>{FLS.edit=JSON.parse(JSON.stringify(f));FLS.dirty=false;FLS.col={};re()};
  if(q('[data-dup]'))q('[data-dup]').onclick=()=>{const x=JSON.parse(JSON.stringify(f));delete x.id;delete x.last_log;x.name=f.name+' (کپی)';x.tpl=null;FLS.edit=x;FLS.dirty=true;re()};
  q('[data-lg]').onclick=()=>{FLS.open[f.id]=!FLS.open[f.id];re()};
  if(q('[data-tr]'))q('[data-tr]').onclick=()=>{AGS.taskId=f.last_task;AGS.tab='tasks';agSv();re()};
  if(q('[data-del]'))q('[data-del]').onclick=tmTry(async()=>{if(!confirm('فرایند «'+f.name+'» حذف شود؟'))return;c.style.transition='opacity .3s,transform .3s';c.style.opacity=0;c.style.transform='scale(.95)';await flApi.del(f.id);toast('حذف شد');setTimeout(re,280)});
  flRunBind(c,f)});
 $$('.fl-c.tpl',B).forEach(c=>{const b=$('[data-add]',c);b.onclick=tmTry(async()=>{const vars={};$$('[data-v]',c).forEach(i=>{let v=i.value.trim();if(/^-?\d+(\.\d+)?$/.test(v))v=+v;else if(/^[\[{]/.test(v)){try{v=JSON.parse(v)}catch(e){}}vars[i.dataset.v]=v});b.disabled=true;const x=await flApi.save({template:c.dataset.k,vars});b.textContent='✓ اضافه شد';b.classList.add('fl-added');FLS.added=x.flow.id;toast('فرایند «'+x.flow.name+'» اضافه شد');setTimeout(re,450)})});
 for(const f of r.flows){const R=FLS.run[f.id];if(R&&!FLS.poll[f.id])flPoll(f,R.task,re,B)}
 const n=$('[data-new]',B);if(n)n.onclick=()=>{FLS.edit={name:'',d:'',sched:{mode:'manual'},vars:{},enabled:true,steps:[{type:'tool',id:'s1',title:'',tool:'report_daily',args:{}}]};FLS.dirty=false;FLS.col={};re()}}
function flRunBind(c,f){const b=$('[data-cn]',c);if(b)b.onclick=tmTry(async()=>{const R=FLS.run[f.id];if(!R)return;b.disabled=true;await flApi.cancel(R.task);toast('درخواست لغو ثبت شد')})}
function flRunPaint(B,f){const c=$(`.fl-c[data-id="${f.id}"]`,B);if(!c)return;const w=$('.fl-runw',c);w.innerHTML=flRunHtml(f);c.className=c.className.replace(/\bs-\S+/,'s-run');const r=$('[data-run]',c);if(r)r.disabled=!!FLS.run[f.id];flRunBind(c,f)}
function flPoll(f,task,re,B){clearTimeout(FLS.poll[f.id]);let n=0;const tick=async()=>{n++;try{const T=await flApi.task(task);const fs=(T.steps||[]).filter(s=>s.kind==='flow');const R=FLS.run[f.id]||(FLS.run[f.id]={task});R.st=T.status;R.n=fs.length;R.cur=(f.steps[fs.length]||{}).title||'';
  if(!['queued','running'].includes(T.status)){delete FLS.run[f.id];delete FLS.poll[f.id];FLS.open[f.id]=1;toast('فرایند «'+f.name+'»: '+((AGST[T.status]||[T.status])[0]));if(B.isConnected)re();return}if(B.isConnected)flRunPaint(B,f)}catch(e){}
  if(n<150&&B.isConnected)FLS.poll[f.id]=setTimeout(tick,n<15?1000:3000);else delete FLS.poll[f.id]};FLS.poll[f.id]=setTimeout(tick,600)}
function flEditor(B,re,live,r){const E=FLS.edit;const s=E.sched||{mode:'manual'};const TL=r.tools,AG=r.agents;
 const toolHelp=t=>{const T=TL.find(x=>x.name===t);if(!T)return '';const a=Object.entries(T.args||{});return `<small class="sx-muted">${esc(T.d||'')}${a.length?' — آرگومان‌ها: '+a.map(([k,v])=>`<code>${esc(k)}</code>${v.req?'*':''} (${esc(v.type)}${v.d?': '+esc(v.d):''})`).join('، '):''}</small>`};
 const refs=i=>{const R=[...Object.keys(E.vars||{}).map(k=>'{{vars.'+k+'}}'),...E.steps.slice(0,i).map(x=>'{{'+(x.id||'')+'}}'),'{{today}}','{{flow.name}}'];return `<div class="fl-refs">ارجاع‌ها: ${R.map(x=>`<button type="button" data-ref="${esc(x)}">${esc(x)}</button>`).join('')}</div>`};
 const stepHtml=(st,i)=>{const t=st.type;let body='';
  if(t==='tool')body=`<label>ابزار<select data-f="tool">${TL.map(x=>`<option value="${esc(x.name)}" ${x.name===st.tool?'selected':''}>${esc(x.name)}${x.cls==='write'||x.cls==='send'?' ⚠':''}</option>`).join('')}</select></label><label class="w">آرگومان‌ها (JSON)<textarea data-f="args" data-j rows="2" dir="ltr">${esc(flPJ(st.args))}</textarea><span class="er"></span></label><div class="w" style="grid-column:1/-1">${toolHelp(st.tool)}</div>`;
  else if(t==='agent'){const A=AG.find(a=>a.id===st.agent)||AG[0]||{kinds:{}};body=`<label>کارمند<select data-f="agent">${AG.map(a=>`<option value="${esc(a.id)}" ${a.id===A.id?'selected':''}>${esc((a.ic||'')+' '+a.n)}</option>`).join('')}</select></label><label>نوع کار<select data-f="kind">${Object.entries(A.kinds||{}).map(([k,n])=>`<option value="${esc(k)}" ${k===st.kind?'selected':''}>${esc(n)}</option>`).join('')}</select></label><label class="w">ورودی (JSON)<textarea data-f="input" data-j rows="2" dir="ltr">${esc(flPJ(st.input))}</textarea><span class="er"></span></label>`}
  else if(t==='llm')body=`<label class="w">دستور به مدل<textarea data-f="prompt" rows="3">${esc(st.prompt||'')}</textarea></label><label class="w">متن جایگزین بدون مدل<input data-f="fallback" value="${esc(st.fallback||'')}"></label>`;
  else if(t==='notify')body=`<label class="w">متن اعلان<textarea data-f="text" rows="2">${esc(st.text||'')}</textarea></label><label>رویداد<input data-f="event" dir="ltr" value="${esc(st.event||'agent.report')}"></label><label>کلید جلوگیری از تکرار<input data-f="dedupe" dir="ltr" value="${esc(st.dedupe||'')}"></label>`;
  else if(t==='gate')body=`<label class="w">شرط<input data-f="cond" dir="ltr" value="${esc(st.cond||'')}" placeholder="{{s1.count}} > 0"></label><label class="w">پیام توقف<input data-f="stopMsg" value="${esc(st.stopMsg||'')}"></label>`;
  return `<div class="fl-se t-${t}${FLS.col[i]?' col':''}" data-i="${i}" draggable="false" style="--i:${i}"><span class="nd" title="${esc(FLTY[t])}">${FLTI[t]}</span><div class="fl-h"><span class="hdl" title="برای جابه‌جایی بکشید">⋮⋮</span><b>${fa(i+1)}.</b><select data-f="type">${Object.entries(FLTY).map(([k,n])=>`<option value="${k}" ${k===t?'selected':''}>${n}</option>`).join('')}</select><input data-f="title" placeholder="عنوان گام" value="${esc(st.title||'')}"><input data-f="id" size="5" dir="ltr" title="شناسه برای ارجاع {{id.…}}" value="${esc(st.id||('s'+(i+1)))}"><button class="sx-btn xs" data-up ${i?'':'disabled'} title="بالا">↑</button><button class="sx-btn xs" data-dn ${i<E.steps.length-1?'':'disabled'} title="پایین">↓</button><button class="sx-btn xs" data-rm>حذف</button><button class="cl" data-cl title="جمع/باز">▸</button></div>
   <div class="bx"><div><div class="fl-g">${body}<label>فقط اگر (when)<input data-f="when" dir="ltr" value="${esc(st.when||'')}"></label><label class="ck"><input type="checkbox" class="as-sw" data-f="onFail" ${st.onFail==='continue'?'checked':''}> در صورت خطا ادامه بده</label>${refs(i)}</div></div></div></div>`};
 B.innerHTML=`<div class="sx-card"><header><b>${E.id?'ویرایش فرایند':'فرایند جدید'}</b>${FLS.dirty?'<span class="fl-dirty">تغییرات ذخیره نشده</span>':''}<span class="fl-sp"></span><button class="sx-btn sm" data-x>انصراف</button><button class="sx-btn sm pri" data-sv>ذخیره <small style="opacity:.7">Ctrl+S</small></button></header>
  <div class="fl-g"><label>نام<input data-e="name" value="${esc(E.name||'')}"></label><label class="w">توضیح<input data-e="d" value="${esc(E.d||'')}"></label>
  <label>زمان‌بندی<select data-e="mode">${[['manual','دستی'],['every','هر چند دقیقه/ساعت'],['daily','روزانه'],['weekly','هفتگی'],['event','با رویداد']].map(([k,n])=>`<option value="${k}" ${k===s.mode?'selected':''}>${n}</option>`).join('')}</select></label>
  ${s.mode==='every'?`<label>فاصله (دقیقه، حداقل ۱۵)<input data-e="minutes" type="number" min="15" value="${+s.minutes||60}"></label>`:''}
  ${s.mode==='daily'||s.mode==='weekly'?`<label>ساعت (تهران)<input data-e="at" type="time" value="${esc(s.at||'08:00')}"></label>`:''}
  ${s.mode==='weekly'?`<label>روز<select data-e="dow">${FLDOW.map((d,i)=>`<option value="${i}" ${i===(s.dow==null?6:+s.dow)?'selected':''}>${d}</option>`).join('')}</select></label>`:''}
  ${s.mode==='event'?`<label>رویداد<select data-e="event">${r.events.map(k=>`<option value="${esc(k)}" ${k===s.event?'selected':''}>${esc(FLEVFA[k]||k)}</option>`).join('')}</select></label>`:''}
  <label class="ck"><input type="checkbox" class="as-sw" data-e="enabled" ${E.enabled!==false?'checked':''}> فعال</label>
  <label class="w"><span>متغیرها (JSON) — در گام‌ها با <code>{{vars.name}}</code></span><textarea data-e="vars" data-j rows="2" dir="ltr">${esc(flPJ(E.vars))}</textarea><span class="er"></span></label></div></div>
  <div class="sx-card"><header><b>گام‌ها (${fa(E.steps.length)})</b><small>به ترتیب اجرا می‌شوند؛ خروجی هر گام با شناسه‌اش در گام‌های بعد در دسترس است · برای جابه‌جایی، دستگیرهٔ ⋮⋮ را بکشید</small></header>
   <div class="fl-tl">${E.steps.map(stepHtml).join('')}</div><div class="fl-add" style="margin-top:12px">${Object.entries(FLTY).map(([k,n])=>`<button data-addst="${k}"><i style="background:${FLTC[k]}"></i>+ ${n}</button>`).join('')}</div></div>
  ${E.id&&E.last_log?`<div class="sx-card"><header><b>گزارش آخرین اجرا</b></header>${flLogHtml(E.last_log)}</div>`:''}`;
 const collect=(strict)=>{const g=k=>$('[data-e="'+k+'"]',B);E.name=g('name').value.trim();E.d=g('d').value.trim();E.enabled=g('enabled').checked;const m=g('mode').value;
  E.sched=m==='every'?{mode:m,minutes:+(g('minutes')?g('minutes').value:60)||60}:m==='daily'?{mode:m,at:g('at')?g('at').value:'08:00'}:m==='weekly'?{mode:m,at:g('at')?g('at').value:'08:00',dow:g('dow')?+g('dow').value:6}:m==='event'?{mode:m,event:g('event')?g('event').value:r.events[0]}:{mode:'manual'};
  try{E.vars=flJ(g('vars').value,{})}catch(e){if(strict)throw e}
  $$('.fl-se',B).forEach(c=>{const i=+c.dataset.i,st=E.steps[i];const f=k=>$('[data-f="'+k+'"]',c);const v=k=>f(k)?f(k).value:undefined;const nt=v('type');
   const o={type:nt,title:v('title').trim(),id:v('id').trim()};const w=v('when').trim();if(w)o.when=w;if(f('onFail').checked)o.onFail='continue';
   if(nt!==st.type){if(nt==='tool'){o.tool=TL[0]&&TL[0].name;o.args={}}if(nt==='agent'){o.agent=AG[0]&&AG[0].id;o.kind=Object.keys((AG[0]||{}).kinds||{})[0];o.input={}}if(nt==='notify')o.text='📋 {{flow.name}}: ';if(nt==='llm')o.prompt='خروجی گام‌های قبل را در چند خط جمع‌بندی کن.';if(nt==='gate')o.cond='{{s1.count}} > 0';E.steps[i]=o;return}
   const J=(k)=>{try{return flJ(v(k),{})}catch(e){if(strict)throw new Error('گام '+fa(i+1)+': '+e.message);return st[k]||{}}};
   if(nt==='tool'){o.tool=v('tool');o.args=J('args')}else if(nt==='agent'){o.agent=v('agent');const A=AG.find(a=>a.id===o.agent)||{kinds:{}};o.kind=A.kinds[v('kind')]?v('kind'):Object.keys(A.kinds)[0];o.input=J('input')}
   else if(nt==='llm'){o.prompt=v('prompt');const fb=v('fallback').trim();if(fb)o.fallback=fb}else if(nt==='notify'){o.text=v('text');o.event=v('event').trim()||'agent.report';const d=v('dedupe').trim();if(d)o.dedupe=d}else if(nt==='gate'){o.cond=v('cond');const sm=v('stopMsg').trim();if(sm)o.stopMsg=sm}
   E.steps[i]=o})};
 const rr=()=>{collect(false);FLS.dirty=true;flEditor(B,re,live,r)};
 const mv=(a,b)=>{collect(false);const x=E.steps.splice(a,1)[0];E.steps.splice(b,0,x);const c=FLS.col;FLS.col={};FLS.dirty=true;flEditor(B,re,live,r);const el=$(`.fl-se[data-i="${b}"]`,B);if(el&&el.animate)el.animate([{transform:'scale(.97)',boxShadow:'0 0 0 2px var(--accent)'},{transform:'none',boxShadow:'none'}],{duration:500,easing:'cubic-bezier(.34,1.56,.64,1)'})};
 $$('[data-e="mode"],.fl-se [data-f="type"],.fl-se [data-f="agent"],.fl-se [data-f="tool"]',B).forEach(x=>x.onchange=rr);
 B.oninput=e=>{if(!FLS.dirty){FLS.dirty=true;const h=$('.sx-card header b',B);if(h&&!$('.fl-dirty',B))h.insertAdjacentHTML('afterend','<span class="fl-dirty">تغییرات ذخیره نشده</span>')}const t=e.target;if(t.matches&&t.matches('textarea[data-j]')){let ok=true,m='';try{flJ(t.value,{})}catch(x){ok=false;m='JSON نامعتبر — مثلاً {"pol":"Ningbo"}'}t.classList.toggle('bad',!ok);const er=t.parentElement.querySelector('.er');if(er)er.textContent=m}};
 let lastF=null;B.onfocusin=e=>{if(e.target.matches&&e.target.matches('.fl-se input[data-f],.fl-se textarea'))lastF=e.target};
 $$('.fl-se',B).forEach(c=>{const i=+c.dataset.i;$('[data-up]',c).onclick=()=>mv(i,i-1);$('[data-dn]',c).onclick=()=>mv(i,i+1);
  $('[data-rm]',c).onclick=()=>{c.style.transition='opacity .25s,transform .25s';c.style.opacity=0;c.style.transform='translateX(20px)';setTimeout(()=>{collect(false);E.steps.splice(i,1);FLS.col={};FLS.dirty=true;flEditor(B,re,live,r)},230)};
  $('[data-cl]',c).onclick=()=>{FLS.col[i]=!FLS.col[i];c.classList.toggle('col',!!FLS.col[i])};
  $$('[data-ref]',c).forEach(b=>b.onclick=()=>{const t=lastF&&c.contains(lastF)?lastF:$('textarea[data-f],input[data-f="cond"],input[data-f="when"]',c);if(!t)return;const a=t.selectionStart??t.value.length,z=t.selectionEnd??a,ins=b.dataset.ref;const raw=t.matches('textarea[data-j]')&&!t.value.trim()?'{"key":"'+ins+'"}':ins;t.value=t.value.slice(0,a)+raw+t.value.slice(z);t.focus();t.setSelectionRange(a+raw.length,a+raw.length);t.dispatchEvent(new Event('input',{bubbles:true}))});
  const h=$('.hdl',c);h.onmousedown=()=>c.setAttribute('draggable','true');c.ondragend=()=>{c.setAttribute('draggable','false');c.classList.remove('dragging');$$('.fl-se',B).forEach(x=>x.classList.remove('over-t','over-b'))};
  c.ondragstart=e=>{e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(i));c.classList.add('dragging')};
  c.ondragover=e=>{e.preventDefault();const r0=c.getBoundingClientRect();const top=e.clientY<r0.top+r0.height/2;c.classList.toggle('over-t',top);c.classList.toggle('over-b',!top)};c.ondragleave=()=>c.classList.remove('over-t','over-b');
  c.ondrop=e=>{e.preventDefault();const a=+e.dataTransfer.getData('text/plain');const r0=c.getBoundingClientRect();let b=i+(e.clientY<r0.top+r0.height/2?0:1);if(a<b)b--;c.classList.remove('over-t','over-b');if(!isNaN(a)&&a!==b)mv(a,b)}});
 $$('[data-addst]',B).forEach(x=>x.onclick=()=>{collect(false);const t=x.dataset.addst;const ids=new Set(E.steps.map(s=>s.id));let k=E.steps.length+1;while(ids.has('s'+k))k++;const o={type:t,id:'s'+k,title:''};if(t==='tool'){o.tool='report_daily';o.args={}}if(t==='agent'){o.agent=AG[0]&&AG[0].id;o.kind=Object.keys((AG[0]||{}).kinds||{})[0];o.input={}}if(t==='llm')o.prompt='خروجی گام‌های قبل را در چند خط برای مدیر جمع‌بندی کن.';if(t==='notify')o.text='📋 {{flow.name}}: ';if(t==='gate')o.cond='{{s1.count}} > 0';E.steps.push(o);FLS.dirty=true;flEditor(B,re,live,r);const el=$$('.fl-se',B).pop();if(el)el.scrollIntoView({block:'center',behavior:'smooth'})});
 const save=tmTry(async()=>{collect(true);const b={name:E.name,d:E.d,sched:E.sched,vars:E.vars,steps:E.steps,enabled:E.enabled};if(E.id)b.id=E.id;const x=await flApi.save(b);toast('فرایند «'+x.flow.name+'» ذخیره شد');FLS.edit=null;FLS.dirty=false;FLS.added=x.flow.id;re()});
 $('[data-x]',B).onclick=()=>{if(FLS.dirty&&!confirm('تغییرات ذخیره نشده از بین برود؟'))return;FLS.edit=null;FLS.dirty=false;re()};$('[data-sv]',B).onclick=save;
 B.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save()}}}
