/* ---------- autopilot HUD (incremental, animated), takeover badge, pre-flight, run loop ---------- */
const apK=()=>({slow:1.6,normal:1,fast:.45})[AP.opts.speed]||1;
const API_={pause:asSvg('<rect x="6" y="5" width="4" height="14" rx="1"/><rect x="14" y="5" width="4" height="14" rx="1"/>',13),play:asSvg('<path d="M7 5l12 7-12 7z"/>',13),skip:asSvg('<path d="M18 5v14M6 5l9 7-9 7z"/>',13),stop:asSvg('<rect x="6" y="6" width="12" height="12" rx="2"/>',13),chev:asSvg('<path d="M6 9l6 6 6-6"/>',15),
 pdf:asSvg('<path d="M14 3H6a1 1 0 0 0-1 1v16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8z"/><path d="M14 3v5h5"/>',13),job:asSvg('<rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>',13),loop:asSvg('<path d="M17 2l4 4-4 4"/><path d="M3 11V9a3 3 0 0 1 3-3h15M7 22l-4-4 4-4"/><path d="M21 13v2a3 3 0 0 1-3 3H3"/>',13),chat:asSvg('<path d="M4 5h16v11H9l-5 4z"/>',13)};
Object.assign(API_,{play2:asSvg('<path d="M7 5l12 7-12 7z"/>',12),lock:asSvg('<rect x="5" y="11" width="14" height="10" rx="2"/><path d="M8 11V7a4 4 0 0 1 8 0v4"/>',14),min:asSvg('<path d="M6 9l6 6 6-6"/>',15)});
const apFmt=s=>fa(String(Math.floor(s/60)).padStart(2,'0'))+':'+fa(String(Math.floor(s%60)).padStart(2,'0'));
const APDOT={ok:'✓',warn:'!',skip:'↷',stop:'×',fail:'×'};
function apHudBuild(){const h=document.createElement('div');h.className='ap-hud';h.setAttribute('role','region');h.setAttribute('aria-label','کنترل خودکار محموله');
 h.innerHTML=`<div class="ap-hd"><div class="ap-pr"><svg viewBox="0 0 44 44"><circle class="bg" cx="22" cy="22" r="18"/><circle class="fg" cx="22" cy="22" r="18"/></svg><b>۰٪</b></div>
  <div class="tt"><b>اجرای خودکار<span class="stt"><i></i><span></span></span></b><small class="sub"></small></div><div class="tm"><span class="el">۰۰:۰۰</span><small class="eta"></small></div>
  <button class="mn" title="جمع/باز کردن">${API_.chev}</button><button class="cl" title="بستن">${ASI.x}</button></div><div class="ap-bar"><i></i></div>
 <div class="ap-bd"><div class="ap-sumw"></div><div class="ap-now"><span class="ap-av"></span><div class="w"><b></b><span></span></div></div>
  <div class="ap-ctl"><button class="pri ap-pp" title="توقف موقت / ادامه (Space)"></button><button class="ap-sk" title="رد کردن مرحله (Shift+S)">${API_.skip}رد مرحله</button><button class="bad ap-st0" title="پایان (Shift+Esc)">${API_.stop}پایان</button>
   <div class="ap-spd"><span class="ind"></span>${[['slow','کند'],['normal','عادی'],['fast','سریع']].map(([k,n])=>`<button data-sp="${k}">${n}</button>`).join('')}</div><label title="پس از هر مرحله منتظر «ادامه» می‌ماند"><input type="checkbox" class="as-sw ap-sm">گام‌به‌گام — توقف پس از هر مرحله</label></div>
  <div class="ap-tabs"><button data-t="st">مراحل <em></em></button><button data-t="vals">مقادیر <em></em></button><button data-t="log">رویدادها <em></em></button><span class="ind"></span></div>
  <div class="ap-pane" data-p="st"><ul class="ap-st"></ul></div><div class="ap-pane" data-p="vals"><div class="ap-vals"></div></div><div class="ap-pane" data-p="log"><div class="apx-log"></div></div></div>`;
 document.body.appendChild(h);h._vals=new Map();h._logId=0;
 const on=(s,f)=>{const e=$(s,h);if(e)e.onclick=f};
 on('.mn',()=>{h.classList.toggle('min');setTimeout(asPlace,520)});on('.cl',()=>{if(AP.run)return;h.classList.add('out');setTimeout(()=>{h.remove();AP.S=null},260);apFx(false)});
 on('.ap-pp',()=>apPause(!AP.pause));on('.ap-sk',()=>{AP.skip=true;AP.pause=false;apHud()});on('.ap-st0',()=>{AP.stop=true;AP.pause=false});
 $$('.ap-spd button',h).forEach(b=>b.onclick=()=>{AP.opts.speed=b.dataset.sp;AP.k=apK();LSS('ifa-ap-opt',AP.opts);apHud()});
 const sm=$('.ap-sm',h);sm.onchange=()=>{AP.opts.stepMode=sm.checked;LSS('ifa-ap-opt',AP.opts)};
 $$('.ap-tabs button',h).forEach(b=>b.onclick=()=>{AP.hudTab=b.dataset.t;apHud()});
 asPlace();return h}
function apIndTo(box,btn){const i=$('.ind',box);if(i&&btn){i.style.left=btn.offsetLeft+'px';i.style.width=btn.offsetWidth+'px'}}
function apHud(){let h=$('.ap-hud:not(.out)');if(!AP.S&&!h)return;if(!h)h=apHudBuild();
 const L=AP.list||[],N=L.length||1,done=L.filter(s=>['ok','warn','skip'].includes(AP.st[s[0]])).length,pct=AP.done&&!AP.stopped?1:done/N,a=APA[AP.ag]||APA.orc,last=AP.log[AP.log.length-1];
 h.classList.toggle('run',AP.run);h.classList.toggle('paused',AP.run&&AP.pause);h.classList.toggle('done',!!AP.done);
 $('.ap-pr .fg',h).style.strokeDashoffset=(113.1*(1-pct)).toFixed(1);$('.ap-pr b',h).textContent=fa(Math.round(pct*100))+'٪';$('.ap-bar i',h).style.width=(pct*100)+'%';
 $('.stt span',h).textContent=AP.run?(AP.pause?'متوقف موقت':'در حال اجرا'):AP.done?(AP.stopped?'متوقف شد':'پایان یافت'):'آماده';
 const cur=L[AP.cur];$('.sub',h).textContent=AP.run&&cur?`مرحلهٔ ${fa(AP.cur+1)} از ${fa(L.length)} · ${cur[1]}`:AP.done?`${fa(done)} مرحله از ${fa(L.length)} · ${fa(AP.vals.length)} مقدار استخراج شد`:'';
 const sec=((AP.end||Date.now())-AP.t0)/1000;$('.el',h).textContent=apFmt(sec);const eta=$('.eta',h);if(AP.run&&done>0){const rem=(N-done)*(sec/done);eta.textContent='≈ '+apFmt(rem)+' مانده'}else eta.textContent=AP.done?'کل زمان':'';
 const nw=$('.ap-now',h),ct=$('.ap-ctl',h);nw.style.display=ct.style.display=AP.run?'':'none';
 if(AP.run){const av=$('.ap-av',nw);if(h._ag!==AP.ag){h._ag=AP.ag;av.innerHTML=apIc(AP.ag,16);av.classList.remove('chg');void av.offsetWidth;av.classList.add('chg')}$('.w b',nw).textContent=a[1];
  const sp=$('.w span',nw);if(last&&h._lm!==last.id){h._lm=last.id;sp.textContent=last.m;sp.classList.remove('chg');void sp.offsetWidth;sp.classList.add('chg')}
  const pp=$('.ap-pp',ct);const pk=AP.pause?'p':'r';if(pp.dataset.k!==pk){pp.dataset.k=pk;pp.innerHTML=AP.pause?API_.play+'ادامه':API_.pause+'توقف موقت'}
  $$('.ap-spd button',ct).forEach(b=>b.classList.toggle('on',b.dataset.sp===AP.opts.speed));apIndTo($('.ap-spd',ct),$('.ap-spd button.on',ct));$('.ap-sm',ct).checked=!!AP.opts.stepMode}
 const T=AP.hudTab||'st';$$('.ap-tabs button',h).forEach(b=>b.classList.toggle('on',b.dataset.t===T));$$('.ap-pane',h).forEach(p=>p.classList.toggle('on',p.dataset.p===T));apIndTo($('.ap-tabs',h),$('.ap-tabs button.on',h));
 const em=$$('.ap-tabs em',h);em[0].textContent=fa(done)+'/'+fa(L.length);em[1].textContent=fa(AP.vals.length);em[2].textContent=fa(AP.log.length);
 /* stage timeline */
 const ul=$('.ap-st',h),sig=L.map(s=>s[0]).join();if(h._sig!==sig){h._sig=sig;ul.innerHTML=L.map((s,i)=>`<li data-k="${s[0]}"><span class="d">${fa(i+1)}</span><span class="ic">${apIc(s[2],13)}</span><span>${esc(s[1])}</span><small></small></li>`).join('')}
 $$('li',ul).forEach((li,i)=>{const x=AP.st[li.dataset.k]||'';const cls=x==='run'?'run':x;if(li.dataset.s!==cls){li.dataset.s=cls;li.className=cls;$('.d',li).textContent=x in APDOT?APDOT[x]:fa(i+1)}const n=(AP.note||{})[li.dataset.k]||'';const sm=$('small',li);if(sm.textContent!==n)sm.textContent=n});
 if(T==='st'&&AP.run&&h._cur!==AP.cur){h._cur=AP.cur;const li=$('li.run',ul);if(li)li.scrollIntoView({block:'nearest',behavior:apRM()?'auto':'smooth'})}
 /* values */
 const vb=$('.ap-vals',h);for(const v of AP.vals){let e=h._vals.get(v.k);if(!e){e=document.createElement('div');e.className='ap-v new';e.innerHTML='<span><i></i><em>↗ مشاهده</em></span><b></b>';vb.appendChild(e);h._vals.set(v.k,e);e.onclick=()=>{if(AP.run)return toast('پس از پایان یا توقف موقت، با کلیک صفحهٔ منبع باز می‌شود');const x=AP.vals.find(y=>y.k===v.k);if(x&&x.view&&x.view!=='map')open(x.view);else toast('این مقدار از نقشه و مسیرهای پیشنهادی خوانده شد')}}
  if(e.dataset.n!==String(v.n)){if(e.dataset.n){e.classList.remove('new');void e.offsetWidth;e.classList.add('new')}e.dataset.n=v.n;e.classList.toggle('w',v.w);$('span i',e).textContent=v.label;const b=$('b',e);b.textContent=v.value;b.title=v.value}}
 /* event log */
 const lg=$('.apx-log',h);for(const l of AP.log){if(l.id<=h._logId)continue;h._logId=l.id;const d=document.createElement('div');d.innerHTML=`<time>${apFmt((l.t-AP.t0)/1000)}</time><span>${apIc(l.ag,12)}<span>${esc(l.m)}</span></span>`;lg.prepend(d);while(lg.children.length>90)lg.lastChild.remove()}
 /* summary */
 const sw=$('.ap-sumw',h);if(AP.done&&!h._sum){h._sum=1;sw.innerHTML=apSumHtml(done);apSumBind(sw);const bd=$('.ap-bd',h);bd.scrollTo({top:0});if(!AP.stopped)apConfetti($('.ap-sum',sw))}else if(!AP.done&&h._sum){h._sum=0;sw.innerHTML=''}
 $('.cl',h).style.display=AP.run?'none':'';apBadge();const fb=$('.as-fab');if(fb){fb.classList.toggle('run',AP.run);fb.style.setProperty('--ap-p',(pct*360).toFixed(1)+'deg')}if(typeof apTl==='function')apTl()}
setInterval(()=>{if(AP.run)apHud()},1000);
function apSumHtml(done){const L=AP.list||[];const c=k=>L.filter(s=>AP.st[s[0]]===k).length;const S=AP.S||{};const sec=((AP.end||Date.now())-AP.t0)/1000;
 const rec=[S.job&&'پرونده '+S.job,S.ship&&'محموله '+(S.ship.ref||''),AP.st.cus==='ok'&&'اظهارنامه',AP.st.bkg==='ok'&&'رزرو'].filter(Boolean);
 const B=[['ap-rp pri',API_.pdf+'گزارش PDF کامل'],...(S.job?[['ap-oj',API_.job+'باز کردن پرونده']]:[]),['ap-cp',ASI.copy+'کپی همهٔ مقادیر'],['ap-fl',API_.loop+'ذخیره به‌صورت فرایند'],['ap-ag',ASI.again+'اجرای دوباره'],['ap-as',API_.chat+'تحلیل نتایج با دستیار']];
 return `<div class="ap-sum${AP.stopped?' stopped':''}"><div class="ap-cf"></div><div class="hd"><svg class="ck" viewBox="0 0 48 48"><circle cx="24" cy="24" r="22"/><path d="${AP.stopped?'M17 17v14M31 17v14':'M14 25l7 7 13-15'}"/></svg><div><b>${AP.stopped?'اجرا به درخواست شما متوقف شد':'فرایند فورواردینگ این محموله آماده شد'}</b><p>هیچ ایمیل، استعلام یا رزروی به بیرون ارسال نشد؛ موارد بیرونی منتظر تأیید شماست.${rec.length?' ثبت‌شده: '+esc(rec.join('، ')):''}</p></div></div>
  <div class="ap-kp">${[[fa(c('ok')),'موفق'],[fa(c('warn')),'با هشدار'],[fa(AP.vals.length),'مقدار'],[apFmt(sec),'زمان']].map((x,i)=>`<div style="--i:${i}"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div>
  <div class="bt">${B.map((b,i)=>`<button class="${b[0]}" style="--i:${i}">${b[1]}</button>`).join('')}</div></div>`}
function apSumBind(sw){const on=(s,f)=>{const e=$(s,sw);if(e)e.onclick=f};on('.ap-rp',()=>{try{IFA.report()}catch(e){toast(e.message)}});on('.ap-oj',()=>open('pnl'));on('.ap-ag',()=>apPre());on('.ap-fl',()=>apSaveFlow());
 on('.ap-cp',()=>{const S=AP.S;const t='کنترل خودکار · '+(S?S.o.nameFa+' ← '+S.d.nameFa:'')+'\n'+AP.vals.map(v=>v.label+': '+v.value).join('\n');(navigator.clipboard?navigator.clipboard.writeText(t):Promise.reject()).then(()=>toast('مقادیر کپی شد')).catch(()=>toast('کپی ممکن نشد'))});
 on('.ap-as',()=>{asShow(true);asSend('نتایج کنترل خودکار این محموله را تحلیل کن و ۳ پیشنهاد عملی برای کاهش هزینه و ریسک بده:\n'+AP.vals.map(v=>v.label+': '+v.value).join('\n'),'explain')})}
function apConfetti(el){return;const c=$('.ap-cf',el);const C=['#8FB3AE','#5e9fe8','#ffd66b','#5fd39a','#c3a6ff','#ffffff'];let h='';for(let i=0;i<34;i++){const a=Math.random()*Math.PI*2,r=60+Math.random()*130;h+=`<i style="background:${C[i%C.length]};--x:${(Math.cos(a)*r).toFixed(0)}px;--y:${(Math.sin(a)*r*.7+40).toFixed(0)}px;--r:${(Math.random()*720-360).toFixed(0)}deg;animation-delay:${(Math.random()*.15).toFixed(2)}s"></i>`}c.innerHTML=h;setTimeout(()=>c.innerHTML='',1700)}
/* frame + top badge + pause / takeover */
function apFx(on){if(typeof apMode==='function')apMode(!!on);let f=$('.ap-frame');if(on){if(!f){f=document.createElement('div');f.className='ap-frame';document.body.appendChild(f)}return}
 if(f){f.classList.add('out');setTimeout(()=>f.remove(),650)}const b=$('.ap-badge');if(b){b.classList.add('out');setTimeout(()=>b.remove(),400)}const r=$('.ap-ring');if(r)r.remove();const c=$('.ap-cur');if(c){c.animate([{opacity:1},{opacity:0,transform:c.style.transform+' scale(.4)'}],{duration:300,fill:'forwards'});setTimeout(()=>c.remove(),320)}}
function apBadge(){let b=$('.ap-badge:not(.out)');if(!AP.run){return}if(!b){b=document.createElement('div');b.className='ap-badge';document.body.appendChild(b)}
 const cur=(AP.list||[])[AP.cur];const k=(AP.pause?'p':'r')+'|'+(cur?cur[0]:'');if(b.dataset.k===k)return;b.dataset.k=k;b.classList.toggle('paused',AP.pause);const f=$('.ap-frame');if(f)f.classList.toggle('paused',AP.pause);
 b.innerHTML=AP.pause?`<span class="lv"></span><span>کنترل دست شماست</span><small>${cur?esc(cur[1]):''}</small><i class="sep"></i><button class="go" data-b="go">${API_.play}ادامه</button><button data-b="stop">${API_.stop}پایان</button>`:`<span class="lv"></span><span>اجرای خودکار</span><small>${cur?fa(AP.cur+1)+'/'+fa((AP.list||[]).length)+' · '+esc(cur[1]):''}</small><i class="sep"></i><button data-b="pause">${API_.pause}توقف <kbd>Space</kbd></button>`;
 $$('[data-b]',b).forEach(x=>x.onclick=()=>{const v=x.dataset.b;if(v==='go')apPause(false);else if(v==='pause')apPause(true);else{AP.stop=true;AP.pause=false}})}
function apPause(p,why){if(!AP.run)return;AP.pause=p;apSay(p?(why||'توقف موقت — کنترل در دست شماست'):'ادامهٔ اجرای خودکار');apHud()}
function apKey(e){if(!AP.run)return;const t=e.target,ed=t&&t!==AP.focusEl&&!(t.classList&&t.classList.contains('ap-typing'))&&(t.isContentEditable||/^(INPUT|TEXTAREA|SELECT)$/.test(t.tagName));
 if(e.key==='Escape'){e.preventDefault();if(e.shiftKey){AP.stop=true;AP.pause=false}else apPause(true);return}if(ed)return;
 if(e.code==='Space'){e.preventDefault();apPause(!AP.pause)}else if(e.shiftKey&&e.code==='KeyS'){e.preventDefault();AP.skip=true;AP.pause=false}}
/* pill */
function apPillTick(){const S=apShip();let p=$('.as-pill:not(.out)');const sig=S?S.o.id+'>'+S.d.id+'#'+S.sel:'';if(!S||AP.run||AP.dismiss===sig||$('.apx-pre-bg')||$('.ap-tl:not(.out)')){if(p){p.classList.add('out');setTimeout(()=>p.remove(),300)}return}
 if(!p){p=document.createElement('div');p.className='as-pill';p.setAttribute('role','button');p.tabIndex=0;document.body.appendChild(p);asTip(p,'عامل‌های هوش مصنوعی کنترل را به دست می‌گیرند و کل فرایند فورواردینگ این محموله را مرحله‌به‌مرحله اجرا می‌کنند')}
 if(p.dataset.sig!==sig){p.dataset.sig=sig;p.innerHTML=`<span class="bolt">${ASI.bolt}</span><span class="tx"><b>اجرای خودکار</b><small>${esc(S.o.nameFa)} ← ${esc(S.d.nameFa)}</small></span><span class="x" title="پنهان کردن">${ASI.x}</span>`;
  p.onclick=e=>{if(e.target.closest('.x')){AP.dismiss=sig;p.classList.add('out');setTimeout(()=>p.remove(),300);return}apPre()};p.onkeydown=e=>{if(e.key==='Enter')apPre()};asPlace()}}
/* pre-flight */
function apEst(n){const s=n*5.5*apK();return s<60?fa(Math.round(s))+' ثانیه':fa(Math.round(s/60*10)/10)+' دقیقه'}
function apPre(){const S=apShip();if(!S)return toast('ابتدا روی نقشه مبدأ و مقصد بار را انتخاب کنید تا مسیرها ساخته شوند');if(AP.run)return toast('کنترل خودکار در حال اجراست');const o=AP.opts,c=S.cargo;$('.apx-pre-bg')?.remove();
 const bg=document.createElement('div');bg.className='apx-pre-bg';const recs=APS.filter(s=>s[3]).map(s=>s[0]);const G=[...new Set(APS.map(s=>s[2]))];
 const kp=[['مسیر',esc(S.R.name||'')],['کرایه / زمان',usd(S.R.total||0)+' · '+fa(nf(S.R.avgDays||0,1))+' روز'],['بار',esc(APCF[c.commodity]||c.commodity||'')+' · '+apNum(c.weightKg)+' kg'],['نوع حمل',esc((c.shipmentType||'')+' '+(c.containerType||''))+(c.incoterm?' · '+esc(c.incoterm):'')]];
 bg.innerHTML=`<div class="apx-pre" role="dialog" aria-modal="true" aria-label="کنترل خودکار"><header><button class="xx" title="بستن (Esc)">${ASI.x}</button><div class="t"><span>${ASI.bolt}</span><div><b>اجرای خودکار فرایند فورواردینگ</b><small>${esc(S.o.nameFa)} ← ${esc(S.d.nameFa)} · بررسی و تأیید پیش از شروع</small></div></div><p>عامل‌های هوش مصنوعی بین صفحه‌ها و تب‌ها جابه‌جا می‌شوند، مقادیر را استخراج و محاسبه می‌کنند و فرم‌ها را یکی‌یکی برای این محموله پر می‌کنند. هر لحظه می‌توانید متوقف کنید یا با یک کلیک کنترل را پس بگیرید.</p></header><div class="bd">
 <div class="ap-rt" style="--i:0"><div class="n"><i></i><div><b>${esc(S.o.nameFa)}</b><small>مبدأ</small></div></div><div class="ln"><svg preserveAspectRatio="none" viewBox="0 0 100 28"><path d="M0 14 H100"/><path class="f" pathLength="1" stroke-dasharray="1" d="M0 14 H100"/></svg><span>${fa((S.legs||[]).length||1)} بخش حمل · ${fa(nf(S.R.avgDays||0,1))} روز</span></div><div class="n d"><i></i><div><b>${esc(S.d.nameFa)}</b><small>مقصد</small></div></div></div>
 <div class="ap-kpis" style="--i:1">${kp.map((x,i)=>`<div style="--i:${i}"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>
 <h5 style="--i:2">طرف‌ها و کالا<em>اختیاری</em></h5><div class="g" style="--i:3"><label>مشتری<input data-o="cust" value="${esc(o.cust)}" placeholder="نام شرکت مشتری"></label><label>فرستنده (Shipper)<input data-o="shp" value="${esc(o.shp)}" placeholder="نام فروشنده/فرستنده" dir="auto"></label><label>گیرنده (Consignee)<input data-o="cne" value="${esc(o.cne)}" placeholder="خالی = مشتری" dir="auto"></label>
  <label>شرح دقیق کالا (برای HS)<input data-o="desc" value="${esc(o.desc)}" placeholder="مثلاً پمپ سانتریفیوژ صنعتی"></label><label>کد HS (اختیاری)<input data-o="hs" value="${esc(o.hs||c.hs||'')}" dir="ltr" placeholder="خالی = پیشنهاد عامل"></label><label>حاشیهٔ سود ٪<input data-o="margin" type="number" value="${esc(o.margin)}" min="0" max="80"></label></div>
 <h5 style="--i:4">مراحل و عامل‌های مسئول<em class="cnt"></em></h5><div class="ap-grp" style="--i:5">${G.map((g,i)=>`<div class="ap-gc" style="--i:${i}"><header><span>${apIc(g,12)}</span>${esc(APA[g][1])}</header>${APS.filter(s=>s[2]===g).map(s=>{const lk=s[0]==='intake'||s[0]==='final';const off=o.off.includes(s[0])&&!lk;return `<label class="ap-chip${off?' off':''}${lk?' lock':''}"><input type="checkbox" data-s="${s[0]}" ${off?'':'checked'} ${lk?'disabled':''}><i>✓</i>${esc(s[1])}${s[3]?' <small style="opacity:.6">(ثبت)</small>':''}</label>`}).join('')}</div>`).join('')}</div>
 <div class="nt" style="--i:6">${API_.lock}<span>هیچ ایمیل، استعلام، رزرو یا پرداختی به بیرون ارسال نمی‌شود؛ موارد بیرونی فقط پیش‌نویس می‌شوند و تصمیم با شماست. ${svOn()?'عامل‌های سرور برای پیشنهاد کد HS کمک می‌کنند.':'بدون اتصال سرور، همهٔ محاسبه‌ها محلی انجام می‌شود.'} رکوردها (پرونده، رزرو، اظهارنامه، محموله) فقط در همین برنامه ثبت می‌شوند.</span></div></div>
 <footer><button class="go">${API_.play2}شروع اجرا<kbd>Enter</kbd></button><button class="apx-cn">انصراف</button><span class="est"></span><div class="opt"><label><input type="checkbox" class="as-sw" data-o="records" ${o.records?'checked':''}>ثبت رکوردها</label><label><input type="checkbox" class="as-sw" data-o="stepMode" ${o.stepMode?'checked':''}>گام‌به‌گام</label><label>سرعت <select data-o="speed">${[['slow','کند (نمایشی)'],['normal','عادی'],['fast','سریع']].map(([k,n])=>`<option value="${k}" ${o.speed===k?'selected':''}>${n}</option>`).join('')}</select></label></div></footer></div>`;
 document.body.appendChild(bg);
 const rd=()=>{$$('[data-o]',bg).forEach(e=>{o[e.dataset.o]=e.type==='checkbox'?e.checked:e.type==='number'?+e.value:e.value.trim()});o.off=$$('[data-s]',bg).filter(e=>!e.checked).map(e=>e.dataset.s);LSS('ifa-ap-opt',o)};
 const upd=()=>{const n=$$('[data-s]',bg).filter(e=>e.checked&&(o.records||!recs.includes(e.dataset.s))).length;$('.cnt',bg).textContent=fa(n)+' مرحله انتخاب شده';const sp=$('[data-o=speed]',bg).value;const k0=AP.opts.speed;AP.opts.speed=sp;$('.est',bg).textContent='زمان تقریبی: '+apEst(n);AP.opts.speed=k0};
 const shut=()=>{document.removeEventListener('keydown',kd,true);bg.classList.add('out');setTimeout(()=>bg.remove(),260)};
 const kd=e=>{if(!bg.isConnected)return document.removeEventListener('keydown',kd,true);if(e.key==='Escape'){e.preventDefault();e.stopPropagation();shut()}else if(e.key==='Enter'&&e.target.tagName!=='SELECT'&&e.target.tagName!=='BUTTON'){e.preventDefault();go()}};document.addEventListener('keydown',kd,true);
 const go=()=>{rd();shut();setTimeout(()=>apStart(),180)};
 $$('[data-s]',bg).forEach(e=>e.onchange=()=>{e.parentElement.classList.toggle('off',!e.checked);upd()});bg.addEventListener('mousedown',e=>{if(e.target===bg)shut()});$('.apx-cn',bg).onclick=shut;$('.xx',bg).onclick=shut;$('.go',bg).onclick=go;
 const r=$('[data-o=records]',bg);r.onchange=()=>{o.records=r.checked;$$('[data-s]',bg).forEach(e=>{if(recs.includes(e.dataset.s)){e.checked=r.checked;e.parentElement.classList.toggle('off',!r.checked)}});upd()};$('[data-o=speed]',bg).onchange=upd;upd();setTimeout(()=>$('[data-o=cust]',bg).focus(),80)}
function apIntro(S){if(apRM())return Promise.resolve();const d=document.createElement('div');d.className='ap-intro';d.innerHTML=`<div class="c"><div class="o">${ASI.bolt}</div><div><b>عامل‌ها کنترل را به دست گرفتند</b><small>${esc(S.o.nameFa)} ← ${esc(S.d.nameFa)} · ${fa(AP.list.length)} مرحله</small></div><span class="pb"></span></div>`;document.body.appendChild(d);setTimeout(()=>d.remove(),1550);return apSleep(1150*Math.min(1,AP.k))}
async function apStart(over){const S=apShip();if(!S)return toast('مسیری انتخاب نشده است');if(AP.run)return;if(over)Object.assign(AP.opts,over);
 $('.ap-hud')?.remove();$('.ap-tl')?.remove();Object.assign(AP,{ts:{},run:true,pause:false,stop:false,skip:false,done:false,stopped:false,k:apK(),st:{},note:{},vals:[],log:[],logN:0,cur:-1,t0:Date.now(),end:0,S,hudTab:'st',ag:'orc',cx:innerWidth/2,cy:innerHeight/2,lastRect:null});AP.list=APS.filter(s=>!AP.opts.off.includes(s[0])&&(AP.opts.records||!s[3]));
 asShow(false);$('.as-pill')?.remove();apFx(true);apHud();emit('autopilot.start',{from:S.o.id,to:S.d.id});await apIntro(S);
 const take=e=>{if(!AP.run||!e.isTrusted||AP.pause)return;if(e.target.closest&&e.target.closest('.ap-hud,.as-fab,.as-panel,.apx-pre-bg,.ap-badge'))return;apPause(true,'کنترل دست شماست — هر وقت خواستید «ادامه» را بزنید');toast('کنترل خودکار متوقف شد؛ کنترل دست شماست')};
 document.addEventListener('pointerdown',take,true);document.addEventListener('keydown',apKey,true);
 try{for(let i=0;i<AP.list.length;i++){const [k,n,ag]=AP.list[i];AP.cur=i;AP.ag=ag;AP.st[k]='run';AP.ts[k]={s:Date.now()};apSay('شروع: '+n,ag);
   try{const r=await APF[k](S);AP.st[k]=r==='skip'?'skip':'ok';if(r==='skip')AP.note[k]='لازم نبود'}catch(e){if(e===APSTOP)throw e;if(e===APSKIP){AP.st[k]='skip';AP.note[k]='رد شد';apSay('مرحله رد شد');continue}AP.st[k]='warn';AP.note[k]=String(e.message||e).slice(0,40);apSay('⚠ '+n+': '+(e.message||e)+' — ادامه با مرحلهٔ بعد',ag)}
   AP.ts[k].e=Date.now();apHud();if(AP.opts.stepMode&&i<AP.list.length-1)apPause(true,'گام‌به‌گام: برای مرحلهٔ بعد «ادامه» را بزنید');await apW(250)}}
 catch(e){if(e===APSTOP){AP.stopped=true;AP.list.forEach(s=>{if(!AP.st[s[0]]||AP.st[s[0]]==='run')AP.st[s[0]]='stop'});apSay('اجرا به درخواست شما پایان یافت')}else apSay('خطا: '+(e.message||e))}
 finally{document.removeEventListener('pointerdown',take,true);document.removeEventListener('keydown',apKey,true);AP.run=false;AP.done=true;AP.end=Date.now();AP.ag='orc';AP.hudTab='vals';apFx(false);apHud();emit('autopilot.done',{from:S.o.id,to:S.d.id,stopped:AP.stopped});if(!AP.stopped)toast('کنترل خودکار پایان یافت · '+fa(AP.vals.length)+' مقدار استخراج شد')}}
