/* ---------- autopilot brain: findings engine, approval gates, self-healing, run history, executive brief ---------- */
const APSEV={hi:['بحرانی',3],md:['هشدار',2],lo:['نکته',1],ok:['مثبت',0]};
function apFind_(k,id,sev,t,d,v,fix){AP.finds=AP.finds||[];if(AP.finds.some(f=>f.id===id))return null;const f={k,id,sev,t,d:d||'',v:v||'',fix:fix||'',n:Date.now()};AP.finds.push(f);
 apSay((sev==='hi'?'⛔ ':sev==='md'?'⚠ ':'• ')+'یافته: '+t,'orc');return f}
const apPctN=x=>Math.round((+x||0)*100);
/* rule-based analysis after each stage — deterministic, explainable, no external calls */
const APTH={
 route(S){const C=S.sched,sd=(S.legs||[]).filter(l=>l.mode==='sea').reduce((a,l)=>a+(+l.days||0),0);if(C&&C.n&&C.medianTransit&&sd>0&&C.medianTransit>sd*1.25)apFind_('route','sched','md','زمان ترانزیت واقعی خطوط بیشتر از مدل است','میانهٔ برنامهٔ حرکت خطوط '+fa(C.medianTransit)+' روز در برابر '+fa(Math.round(sd))+' روز مدل دریایی؛ ETA و دموراژ را با برنامهٔ واقعی تنظیم کنید.','opt');if(C&&C.n===0)apFind_('route','nosch','md','حرکتی در ۴ هفتهٔ آینده از خطوط متصل یافت نشد','ظرفیت را با فورواردر یا خط جایگزین بررسی کنید.','bkg');const v=(AP.vals.find(x=>x.k==='otd')||{}).value||'';const p=parseFloat(String(v).replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[^\d.]/g,''));
  if(p&&p<70)apFind_('route','otd','md','احتمال تحویل به‌موقع پایین است ('+fa(Math.round(p))+'٪)','عدم‌قطعیت زمان در این مسیر بالاست؛ بافر زمانی در قرارداد یا مسیر جایگزین با ترانزیت کمتر را بررسی کنید.','opt','پروفایل «سریع» یا مسیر جایگزین');
  if((S.R.avgDays||0)>35)apFind_('route','long','lo','زمان ترانزیت طولانی ('+fa(nf(S.R.avgDays,1))+' روز)','هزینهٔ سرمایهٔ در گردش و ریسک تأخیر بیشتر است.','opt')},
 live(S){const b=S.liveQ;if(!b)return;const m=+S.R.total||0;if(m>0&&b.liveUSD){const dv=(b.liveUSD-m)/m;if(Math.abs(dv)>=.15)apFind_('live','dev',dv>.3?'hi':'md','نرخ بازار '+fa(Math.abs(Math.round(dv*100)))+'٪ '+(dv>0?'بالاتر':'پایین‌تر')+' از مدل مسیر','کرایهٔ روز '+usd(b.liveUSD)+' در برابر مدل '+usd(m)+'. '+(dv>0?'پیش از قیمت‌دهی به مشتری، نرخ را با استعلام واقعی تأیید کنید.':'فرصت خرید ارزان‌تر از برآورد وجود دارد.'),'lq',dv>0?'استعلام فوری از فورواردرها':'')}
  if(b.confidence!=null&&b.confidence<.6)apFind_('live','conf','lo','اطمینان دادهٔ روز پایین است ('+apPct(b.confidence)+')','منابع نرخ کم یا قدیمی‌اند؛ نتیجه را تقریبی در نظر بگیرید.','lq')},
 landed(S){const L=S.landed,val=+S.cargo.value||0;if(S.portNo)apFind_('landed','ptn','lo','تعرفهٔ بندری مقصد ثبت نشده است','هزینه‌های تخلیه، بارگیری و انبارداری بندر از نرخ‌های پیش‌فرض آمده‌اند؛ تعرفهٔ سازمان بنادر را وارد کنید.','ir:pt','ورود تعرفهٔ بندری');else if(S.port&&S.port.days>S.port.free)apFind_('landed','ptd','md','توقف '+fa(S.port.days)+' روزه بیش از '+fa(S.port.free)+' روز انبارداری رایگان است','هزینهٔ بندری برآوردی هر کانتینر '+apRial(S.port.totalIRR)+'؛ ترخیص سریع‌تر یا انتقال به بندر خشک را بسنجید.','ir:pt','محاسبهٔ تعرفهٔ بندری');if(S.cal&&Math.abs(S.cal.pct)>=8)apFind_('landed','cal',Math.abs(S.cal.pct)>=20?'hi':'md','فاکتورهای واقعی '+fa(Math.abs(S.cal.pct))+'٪ '+(S.cal.pct>0?'بیشتر':'کمتر')+' از برآورد مدل‌اند','برآورد کالیبره '+usd(S.cal.adj)+' در برابر مدل '+usd(S.cal.base)+'؛ برای قیمت‌دهی به مشتری از رقم کالیبره استفاده کنید.','cost','قیمت‌دهی با رقم کالیبره');if(!L||!val)return;const r=L.totalUSD/val;if(r>=.25)apFind_('landed','ratio',r>=.4?'hi':'md','هزینهٔ لجستیک '+fa(Math.round(r*100))+'٪ ارزش کالاست','برای این ارزش کالا سهم حمل بالاست؛ تجمیع بار، اینکوترم دیگر یا مسیر ارزان‌تر را بررسی کنید.','cost','مقایسهٔ اینکوترم‌ها');
  else if(r<.08)apFind_('landed','ratio','ok','سهم لجستیک از ارزش کالا مناسب است ('+fa(Math.round(r*100))+'٪)','','cost')},
 load(S){if(S.packX>0)apFind_('load','unpl','hi',fa(S.packX)+' قلم بار در چیدمان جا نماند','تجهیزات بزرگ‌تر یا کانتینر اضافه لازم است؛ بدون اصلاح، رزرو ناقص خواهد بود.','load','تغییر نوع کانتینر');
  else if(S.packU!=null&&S.packU<.55&&S.cargo.shipmentType!=='LCL')apFind_('load','util','md','پرشدگی کانتینر کم است ('+apPct(S.packU)+')','بخش زیادی از ظرفیت خالی است؛ حمل LCL/تجمیعی یا کانتینر کوچک‌تر را بسنجید.','load','بررسی LCL')},
 tariff(S){const D=S.duty;if(!D)return;if(S.tb){if(S.tb.match==='exact')apFind_('tariff','tbk','ok','نرخ حقوق ورودی از کتاب تعرفهٔ ایران: '+fa(S.tb.duty)+'٪','ردیف '+S.tb.hs+' · '+String(S.tb.desc||'').slice(0,90),'tar');else apFind_('tariff','tbk','md','ردیف ۸ رقمی دقیق این کد در کتاب تعرفه نیست','نزدیک‌ترین ردیف '+S.tb.hs+' با '+fa(S.tb.duty)+'٪'+(S.tb.range&&S.tb.range[0]!==S.tb.range[1]?'؛ زیرشاخه‌ها بین '+fa(S.tb.range[0])+' تا '+fa(S.tb.range[1])+'٪':'')+' — کد دقیق را پیش از اظهار تعیین کنید.','ir:tb','بررسی در کتاب تعرفه')}else if(S.tbN===0&&svOn())apFind_('tariff','tbn','lo','کتاب تعرفهٔ ایران روی سرور وارد نشده است','نرخ حقوق ورودی از جدول تقریبی فصل‌ها آمده است؛ فایل Excel کتاب تعرفه را یک بار وارد کنید.','ir:tb','ورود کتاب تعرفه');if(svOn()&&AP.opts.server&&!S.cfx)apFind_('tariff','cfx','md','نرخ ارز گمرکی روی سرور ثبت نشده است','حقوق ورودی با نرخ پیش‌فرض برنامه محاسبه شد و ممکن است با اظهارنامه فرق کند.','ir:tb','ثبت نرخ ارز گمرکی');if(S.hsOk===false)apFind_('tariff','hsx','hi','کد HS در نامگذاری رسمی HS 2022 وجود ندارد','پیش از اظهار، کد را اصلاح کنید؛ کد نادرست باعث توقف ترخیص و جریمه می‌شود.','tar','اصلاح کد HS');else if(S.hsOk===true&&S.hsOff)apFind_('tariff','hsok','ok','کد HS در نامگذاری رسمی تأیید شد','عنوان رسمی: '+(S.hsHead&&S.hsOff.length<14?S.hsHead+' › ':'')+S.hsOff,'tar');if((S.hsSrc||'').includes('پیش‌فرض'))apFind_('tariff','hs','md','کد HS از پیش‌فرض گروه کالا انتخاب شد','نرخ حقوق ورودی ممکن است دقیق نباشد؛ شرح دقیق کالا یا کد HS را تأیید کنید.','tar','وارد کردن شرح دقیق کالا');
  if((D.effectivePct||0)>=30)apFind_('tariff','duty','md','بار مالیاتی ورود بالاست ('+fa(D.effectivePct)+'٪)','بررسی معافیت‌ها، مناطق آزاد یا ترجیحات تعرفه‌ای توصیه می‌شود.','tar');
  if(D.permits&&D.permits.length>=2)apFind_('tariff','perm','lo',fa(D.permits.length)+' مجوز پیش از ترخیص لازم است','زمان اخذ مجوزها را در برنامهٔ زمانی لحاظ کنید: '+D.permits.map(p=>p.agency).join('، '),'tar')},
 ins(S){const I=S.ins;if(I&&(I.ratePct||0)>.6)apFind_('ins','rate','lo','نرخ بیمه بالاتر از معمول است ('+fa(I.ratePct)+'٪)','استعلام از بیمه‌گر دوم یا تغییر شرایط پوشش می‌تواند هزینه را کم کند.','ins')},
 sanc(S){if(S.sancHits>0)apFind_('sanc','hit','hi','تطابق احتمالی در غربال تحریم','پیش از هر قیمت‌دهی، رزرو یا ارسال سند، بررسی دستی انطباق الزامی است.','sanc','بررسی دستی تطابق‌ها');
  else if(!(AP.opts.cust||AP.opts.shp||AP.opts.cne))apFind_('sanc','none','md','غربال تحریم بدون نام طرف‌ها انجام شد','نام مشتری، فرستنده و گیرنده را وارد کنید تا غربال معتبر باشد.','sanc')},
 risk(S){const R=S.risks||[];const hi=R.filter(r=>r.score>=12);if(R[0]&&R[0].score>=16)apFind_('risk','top','hi','ریسک بحرانی: '+R[0].risk,'امتیاز '+fa(R[0].score)+' — پیش از تعهد به مشتری برنامهٔ کاهش ریسک لازم است.','risk','برنامهٔ کاهش ریسک');
  else if(hi.length)apFind_('risk','hi','md',fa(hi.length)+' ریسک با امتیاز بالا','بالاترین: '+(R[0]?R[0].risk:''),'risk')},
 dd(S){const D=S.dd;if(D&&(D.totalUSD||0)>0)apFind_('dd','dd',D.totalUSD>1500?'md':'lo','هزینهٔ دموراژ/دیتنشن پیش‌بینی می‌شود ('+usd(D.totalUSD)+')','زمان آزاد بیشتر از خط کشتیرانی بگیرید یا ترخیص را پیش از رسیدن آماده کنید.','dd','مذاکرهٔ زمان آزاد')},
 job(S){const J=S.jobv;if(!J)return;const m=+J.marginPct||0;if(m<0)apFind_('job','gp','hi','پرونده زیان‌ده است ('+fa(m)+'٪)','قیمت فروش کمتر از هزینه است؛ قیمت‌گذاری را اصلاح کنید.','pnl','بازبینی قیمت فروش');else if(m<8)apFind_('job','gp','md','حاشیهٔ سود کم است ('+fa(m)+'٪)','حاشیهٔ زیر ۸٪ ریسک نوسان نرخ را پوشش نمی‌دهد.','pnl');else apFind_('job','gp','ok','حاشیهٔ سود سالم ('+fa(m)+'٪)','','pnl')}};
function apThink(k,S){AP.finds=AP.finds||[];const n0=AP.finds.length;try{APTH[k]&&APTH[k](S)}catch(e){}const nw=AP.finds.slice(n0);
 if(nw.length){AP.fk=AP.fk||{};const w=nw.reduce((a,f)=>Math.max(a,APSEV[f.sev][1]),0);AP.fk[k]=w>=3?'hi':w===2?'md':w===1?'lo':'ok'}
 const hi=nw.find(f=>f.sev==='hi');if(hi&&AP.opts.gate!==false&&AP.run&&!AP.stop){AP.hudTab='fx';AP.gate=hi.id;apPause(true,'دروازهٔ تأیید: «'+hi.t+'» — پس از بررسی، «ادامه» را بزنید');toast('یافتهٔ بحرانی؛ اجرا برای تأیید شما متوقف شد')}
 return nw}
/* self-healing: one automatic retry after resetting the UI state */
async function apExec(k,S,n,ag){try{return await APF[k](S)}catch(e){if(e===APSTOP||e===APSKIP||AP.opts.heal===false)throw e;
  apSay('🔁 خطا در «'+n+'»؛ بازیابی خودکار و تلاش دوباره','orc');AP.heal=(AP.heal||0)+1;try{if(wrap&&typeof close==='function')close()}catch(x){}
  await apW(700);const r=await APF[k](S);AP.note[k]='بازیابی شد';AP.healed=AP.healed||{};AP.healed[k]=1;apSay('✓ «'+n+'» پس از بازیابی انجام شد',ag);return r}}
function apScore(){const F=AP.finds||[];let s=100;for(const f of F)s-=f.sev==='hi'?15:f.sev==='md'?6:f.sev==='lo'?2:0;const L=AP.list||[];s-=L.filter(x=>AP.st[x[0]]==='warn').length*5;return Math.max(0,Math.min(100,Math.round(s)))}
/* run history (local, last 12) */
function apHistAll(){return LSG('ifa-ap-hist',[])||[]}
function apHistSave(){const S=AP.S;if(!S||AP.stopped)return;const H=apHistAll();const lane=S.o.id+'>'+S.d.id;AP.prev=H.filter(h=>h.lane===lane).slice(-1)[0]||null;
 const F=AP.finds||[];H.push({t:Date.now(),lane,name:S.o.nameFa+' ← '+S.d.nameFa,route:S.R.name||'',sec:Math.round((AP.end-AP.t0)/1000),score:apScore(),fr:Math.round(+S.R.total||0),land:Math.round(S.landed?S.landed.totalUSD:0),duty:Math.round(S.duty?S.duty.totalIRR:0),hi:F.filter(f=>f.sev==='hi').length,md:F.filter(f=>f.sev==='md').length,ok:(AP.list||[]).filter(x=>AP.st[x[0]]==='ok').length,n:(AP.list||[]).length});
 LSS('ifa-ap-hist',H.slice(-12))}
/* executive brief — local, deterministic */
function apBrief(){const S=AP.S||{},F=(AP.finds||[]).slice().sort((a,b)=>APSEV[b.sev][1]-APSEV[a.sev][1]),sc=apScore();const hi=F.filter(f=>f.sev==='hi'),md=F.filter(f=>f.sev==='md');
 const verdict=hi.length?'نیازمند اقدام پیش از تعهد':md.length>2?'قابل اجرا با اصلاحات':'آمادهٔ پیشنهاد به مشتری';
 const L=[];if(S.R)L.push('مسیر «'+(S.R.name||'')+'» با کرایهٔ مدل '+usd(S.R.total||0)+' و '+fa(nf(S.R.avgDays||0,1))+' روز ترانزیت');if(S.landed)L.push('هزینهٔ کامل لجستیک '+usd(S.landed.totalUSD)+' و بهای تمام‌شده در مقصد '+usd(S.landed.landedUSD));if(S.jobv)L.push('سود پرونده '+usd(S.jobv.gpUSD)+' ('+fa(S.jobv.marginPct)+'٪)');
 const P=AP.prev;let cmp='';if(P){const d=(a,b)=>b?Math.round((a-b)/b*100):0;const dl=S.landed?d(S.landed.totalUSD,P.land):0;cmp='نسبت به اجرای '+new Date(P.t).toLocaleDateString('fa-IR')+': امتیاز آمادگی '+fa(P.score)+' → '+fa(sc)+(P.land&&S.landed?' · هزینهٔ کامل '+(dl>0?'+':'')+fa(dl)+'٪':'')}
 return {score:sc,verdict,lines:L,acts:F.filter(f=>f.sev!=='ok').slice(0,3),cmp}}
function apBriefHtml(){const B=apBrief();const c=B.score>=80?'ok':B.score>=55?'md':'hi';
 return `<div class="ap-brief" data-c="${c}"><div class="sc"><svg viewBox="0 0 40 40"><circle class="bg" cx="20" cy="20" r="16"/><circle class="fg" cx="20" cy="20" r="16" style="stroke-dashoffset:${(100.5*(1-B.score/100)).toFixed(1)}"/></svg><b>${fa(B.score)}</b></div>
 <div class="tx"><small>جمع‌بندی هماهنگ‌کننده · امتیاز آمادگی</small><b>${esc(B.verdict)}</b>${B.lines.length?`<p>${esc(B.lines.join('؛ '))}.</p>`:''}${B.cmp?`<p class="cmp">${esc(B.cmp)}</p>`:''}</div>
 ${B.acts.length?`<ol>${B.acts.map(f=>`<li data-s="${f.sev}"><b>${esc(f.fix||f.t)}</b><span>${esc(f.fix?f.t:f.d)}</span></li>`).join('')}</ol>`:''}</div>`}
/* findings pane */
function apFxRender(h){const box=$('.ap-fx',h);if(!box)return;const F=(AP.finds||[]).slice().sort((a,b)=>APSEV[b.sev][1]-APSEV[a.sev][1]||a.n-b.n);const sig=F.map(f=>f.id+f.sev).join()+'|'+(AP.gate||'');if(box._sig===sig)return;box._sig=sig;
 if(!F.length){box.innerHTML='<div class="ap-fx0">'+(AP.run?'عامل‌ها پس از هر مرحله نتایج را تحلیل می‌کنند؛ یافته‌ها اینجا ظاهر می‌شوند.':'یافتهٔ قابل توجهی نبود.')+'</div>';return}
 const nm=k=>((AP.list||[]).find(s=>s[0]===k)||APS.find(s=>s[0]===k)||[0,''])[1];
 box.innerHTML=F.map(f=>`<div class="ap-f" data-s="${f.sev}" data-id="${f.id}"><i></i><div><span><em>${APSEV[f.sev][0]}</em>${esc(nm(f.k))}</span><b>${esc(f.t)}</b>${f.d?`<p>${esc(f.d)}</p>`:''}${f.v?`<button data-v="${f.v}">${f.fix?esc(f.fix):'مشاهده'} ←</button>`:''}</div></div>`).join('');
 $$('.ap-f button',box).forEach(b=>b.onclick=e=>{e.stopPropagation();if(AP.run&&!AP.pause)return toast('ابتدا اجرا را موقتاً متوقف کنید');const v=b.dataset.v;if(v.startsWith('ir:'))irShow({tab:v.slice(3)});else open(v)})}
/* timeline markers */
function apFxMark(){const t=$('.ap-tl');if(!t)return;const L=AP.list||[];$$('.nd',t).forEach((nd,i)=>{const f=(AP.fk||{})[(L[i]||[])[0]]||'';if((nd.dataset.f||'')!==f){if(f)nd.dataset.f=f;else delete nd.dataset.f}})}
