/* ---------- v15.15 data connectors (client): official HS check, carrier schedules, connector registry ---------- */
const CN={st:null,t:0};
async function cnStatus(force){if(!svOn())return null;if(!force&&CN.st&&Date.now()-CN.t<60e3)return CN.st;try{CN.st=await svApi('/api/live/connectors');CN.t=Date.now()}catch(e){CN.st=null}return CN.st}
async function cnHs(code){if(!svOn())throw new Error('اتصال سرور لازم است');return svApi('/api/live/hs/verify?code='+encodeURIComponent(code))}
async function cnHsSearch(q){if(!svOn())throw new Error('اتصال سرور لازم است');return svApi('/api/live/hs/search?q='+encodeURIComponent(q))}
async function cnSched(from,to,o={}){if(!svOn())throw new Error('اتصال سرور لازم است');return svApi('/api/live/schedules?from='+encodeURIComponent(from)+'&to='+encodeURIComponent(to)+(o.start?'&start='+o.start:'')+(o.weeks?'&weeks='+o.weeks:''))}
async function cnGeo(q,city){if(!svOn())throw new Error('اتصال سرور لازم است');return svApi('/api/live/geocode?q='+encodeURIComponent(q)+(city?'&city='+encodeURIComponent(city):''))}
const CNM={rates:'نرخ',port:'بندر',fx:'ارز',sea:'دریایی',road:'جاده‌ای',air:'هوایی',multi:'چندوجهی',customs:'گمرک',compliance:'انطباق'};
async function cnShow(){$('.cn-bg')?.remove();const bg=document.createElement('div');bg.className='cn-bg';bg.innerHTML='<div class="cn-dlg" role="dialog" aria-modal="true" aria-label="منابع داده"><header><div><b>منابع و اتصال‌های داده</b><small>هر رقم برنامه با منبع و تاریخ خود نمایش داده می‌شود</small></div><button class="x" aria-label="بستن">'+ASI.x+'</button></header><div class="bd"><div class="ld">در حال بررسی…</div></div></div>';document.body.appendChild(bg);
 const shut=()=>{bg.classList.add('out');setTimeout(()=>bg.remove(),200)};bg.addEventListener('mousedown',e=>{if(e.target===bg)shut()});$('.x',bg).onclick=shut;
 const bd=$('.bd',bg);if(!svOn()){bd.innerHTML='<p class="nt">برای اتصال‌های زنده (HS رسمی، برنامهٔ حرکت خطوط، فاصلهٔ واقعی نشان) برنامه باید به سرور تیمی وصل باشد. بدون سرور، محاسبه‌ها با داده‌های داخلی و نرخ ارز عمومی انجام می‌شود.</p>';return}
 const S=await cnStatus(true);if(!S){bd.innerHTML='<p class="nt">وضعیت اتصال‌ها از سرور دریافت نشد (نسخهٔ سرور ۱.۱۰ به بعد لازم است).</p>';return}
 bd.innerHTML='<div class="sm"><b>'+fa(S.on)+'</b> از '+fa(S.total)+' منبع فعال</div>'+S.connectors.map(c=>{const s=c.status;const cls=!c.on?'off':s&&s.ok===false?'err':s&&s.ok?'ok':'on';const tm=s&&s.at?new Date(s.at).toLocaleString('fa-IR',{dateStyle:'short',timeStyle:'short'}):'';
  return '<div class="cn-r" data-s="'+cls+'"><i></i><div><b>'+esc(c.name)+'</b><small>'+esc(CNM[c.mode]||c.mode)+' · '+(!c.on?'غیرفعال — '+esc(c.env||''):s&&s.ok===false?'خطا: '+esc(s.err||''):s&&s.ok?'آخرین دریافت موفق '+esc(tm):'فعال، هنوز فراخوانی نشده')+'</small></div>'+(c.docs?'<a href="'+esc(c.docs)+'" target="_blank" rel="noopener">مستندات ↗</a>':'')+'</div>'}).join('')+'<button class="cn-ac cn-ir">داده‌های ایران: کانال‌های نرخ، کتاب تعرفه، ارز گمرکی، تعرفهٔ بندری ←</button><button class="cn-ac">ثبت فاکتور واقعی و دقت برآوردها ←</button><p class="nt">کلیدها فقط روی سرور (فایل ‎.env یا config.json) نگه داشته می‌شوند و هرگز به مرورگر نمی‌آیند. API قیمت خطوط و ایرلاین‌ها معمولاً قرارداد مشتری لازم دارند و شرایط استفادهٔ بسیاری از آن‌ها کار مرتبط با ایران را محدود می‌کند.</p>';const ab=$('.cn-ac:not(.cn-ir)',bd);if(ab)ab.onclick=()=>acShow({tab:'in'});const ib=$('.cn-ir',bd);if(ib)ib.onclick=()=>irShow({})}
