/* ---------- v15.16 actual costs (invoices) → estimate accuracy → calibrated estimates ---------- */
const ACN={origin:'جمع‌آوری مبدأ',exp:'ترخیص صادراتی',psi:'بازرسی PSI',thc:'THC و ترمینال',freight:'کرایهٔ حمل اصلی',fuel:'سوخت / BAF',peak:'سورشارژ فصلی/پیک',special:'سورشارژ کالای ویژه',transfer:'ترانشیپ/فیدر',ins:'بیمه',border:'عوارض مرزی/ترانزیت',docs:'اسناد و بارنامه',dem:'دموراژ/انبارداری',imp:'ترخیص وارداتی',broker:'حق‌العمل‌کاری',duty:'حقوق ورودی',vat:'مالیات ارزش افزوده',bank:'کارمزد بانکی',fx:'اسپرد ارز',inv:'هزینهٔ سرمایه',last:'حمل داخلی تا انبار',other:'سایر'};
const ACUR=['USD','EUR','AED','CNY','TRY','IRR'];
function acCtx(){const S=apShip();if(!S)return null;const L=S.legs||[];const m=L.some(l=>l.mode==='sea')?'sea':L.some(l=>l.mode==='air')?'air':L.some(l=>l.mode==='rail')?'rail':'road';return {lane:S.o.id+'>'+S.d.id,name:S.o.nameFa+' ← '+S.d.nameFa,mode:m,eq:S.cargo&&S.cargo.containerType||''}}
function acEst(){try{const L=IFA.landedCost();const E={};for(const x of L.lines||[])E[x.key]=(E[x.key]||0)+(+x.usd||0);return E}catch(e){return {}}}
async function acCalib(lane,mode){if(!svOn())return null;try{return await svApi('/api/actuals/calib?lane='+encodeURIComponent(lane)+'&mode='+encodeURIComponent(mode||''))}catch(e){return null}}
function acApply(L,C){if(!L||!C||!C.components)return null;let adj=0,base=0,n=0;for(const x of L.lines||[]){const c=C.components[x.key];base+=x.usd;adj+=x.usd*(c?c.factor:1);if(c)n+=c.n.lane}const used=Object.keys(C.components).length;if(!used)return null;return {base:Math.round(base),adj:Math.round(adj),pct:base?Math.round((adj-base)/base*100):0,n,nAll:C.n,comps:used}}
function acRow(l,E){const o=Object.entries(ACN).map(([k,n])=>`<option value="${k}"${k===l.comp?' selected':''}>${n}</option>`).join('');const c=ACUR.map(k=>`<option${k===l.cur?' selected':''}>${k}</option>`).join('');const est=l.est!=null?l.est:(E[l.comp]?Math.round(E[l.comp]):'');
 return `<tr${l.conf!=null&&l.conf<.5?' class="lo"':''}><td><select data-f="comp">${o}</select></td><td><input data-f="label" value="${esc(l.label||'')}" dir="auto"></td><td><input data-f="amt" type="number" step="any" min="0" value="${l.amt||''}" dir="ltr"></td><td><select data-f="cur">${c}</select></td><td><input data-f="est" type="number" step="any" min="0" value="${est}" dir="ltr" placeholder="—"></td><td><button class="rm" title="حذف ردیف">${ASI.x}</button></td></tr>`}
async function acShow(o={}){$('.cn-bg')?.remove();const X=acCtx()||{lane:'',name:'مسیری انتخاب نشده',mode:'',eq:''};const E=acEst();let jobs=[];try{jobs=IFA.jobs().slice(-40).reverse()}catch(e){}
 const bg=document.createElement('div');bg.className='cn-bg';bg.innerHTML=`<div class="cn-dlg ac-dlg" role="dialog" aria-modal="true" aria-label="هزینهٔ واقعی"><header><div><b>هزینهٔ واقعی و دقت برآوردها</b><small>${esc(X.name)}${X.mode?' · '+esc(({sea:'دریایی',air:'هوایی',rail:'ریلی',road:'جاده‌ای'})[X.mode]||X.mode):''} — فاکتورها برآوردهای بعدی همین مسیر را کالیبره می‌کنند</small></div><button class="x" aria-label="بستن">${ASI.x}</button></header>
 <div class="ac-tabs"><button data-t="in" class="on">ثبت فاکتور</button><button data-t="acc">دقت و ضرایب</button></div>
 <div class="bd" data-p="in"><div class="ac-g"><label>پرونده<select data-k="ref"><option value="">—</option>${jobs.map(j=>`<option${j.ref===o.ref?' selected':''}>${esc(j.ref||'')}</option>`).join('')}</select></label><label>تاریخ فاکتور<input data-k="date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>صادرکننده<input data-k="vendor" placeholder="خط، فورواردر، ترخیص‌کار…" dir="auto"></label></div>
  <textarea class="ac-tx" placeholder="متن فاکتور، صورت‌حساب (Debit Note) یا پیام نرخ را اینجا بچسبانید — یا PDF/متن را انتخاب کنید" dir="auto"></textarea>
  <div class="ac-bt"><label class="ac-file">${API_.pdf}انتخاب فایل<input type="file" accept=".pdf,.txt,.csv,text/plain,application/pdf" hidden></label><button class="go ac-parse">استخراج ردیف‌ها</button><span class="ac-st"></span></div>
  <div class="ac-tw"><table class="ac-t"><thead><tr><th>جزء هزینه</th><th>شرح</th><th>مبلغ</th><th>ارز</th><th>برآورد $</th><th></th></tr></thead><tbody></tbody></table><button class="ac-add">+ ردیف</button></div>
  <footer><button class="go ac-save" disabled>ثبت هزینهٔ واقعی</button><span class="ac-sum"></span></footer></div>
 <div class="bd" data-p="acc" hidden><div class="ld">در حال بارگیری…</div></div></div>`;document.body.appendChild(bg);
 const shut=()=>{bg.classList.add('out');setTimeout(()=>bg.remove(),200)};bg.addEventListener('mousedown',e=>{if(e.target===bg)shut()});$('.x',bg).onclick=shut;
 const tb=$('.ac-t tbody',bg),st=$('.ac-st',bg),sv=$('.ac-save',bg);
 const sync=()=>{const R=$$('tr',tb);sv.disabled=!R.length;const t={};R.forEach(r=>{const a=+$('[data-f=amt]',r).value||0,c=$('[data-f=cur]',r).value;t[c]=(t[c]||0)+a});$('.ac-sum',bg).textContent=R.length?fa(R.length)+' ردیف · '+Object.entries(t).map(([c,v])=>nf(v,0)+' '+c).join(' + '):'';};
 const bindRows=()=>{$$('tr',tb).forEach(r=>{$('.rm',r).onclick=()=>{r.remove();sync()};$$('input,select',r).forEach(i=>i.oninput=i.onchange=()=>{if(i.dataset.f==='comp'){const e=$('[data-f=est]',r);if(!e.dataset.t&&E[i.value])e.value=Math.round(E[i.value])}else if(i.dataset.f==='est')e0(i);sync()})});sync()};const e0=i=>i.dataset.t=1;
 const fill=L=>{tb.innerHTML=L.map(l=>acRow(l,E)).join('');bindRows()};
 $('.ac-add',bg).onclick=()=>{tb.insertAdjacentHTML('beforeend',acRow({comp:'other',cur:'USD'},E));bindRows()};
 let pdf=null;$('.ac-file input',bg).onchange=async e=>{const f=e.target.files[0];if(!f)return;if(/pdf$/i.test(f.name)||f.type==='application/pdf'){const b=new Uint8Array(await f.arrayBuffer());let s='';for(let i=0;i<b.length;i+=32768)s+=String.fromCharCode.apply(null,b.subarray(i,i+32768));pdf=btoa(s);st.textContent='PDF: '+f.name}else{$('.ac-tx',bg).value=await f.text();pdf=null;st.textContent=f.name}};
 $('.ac-parse',bg).onclick=async()=>{const t=$('.ac-tx',bg).value;st.textContent='در حال استخراج…';try{let r;if(svOn())r=await svApi('/api/actuals/parse',{method:'POST',body:pdf?{pdf,llm:true}:{text:t,llm:true}});else{if(pdf)throw new Error('خواندن PDF به اتصال سرور نیاز دارد؛ متن را بچسبانید');r=invParse(t)}
   if(!r.lines.length){st.textContent='ردیف قابل‌تشخیصی پیدا نشد؛ ردیف‌ها را دستی اضافه کنید';return}fill(r.lines);st.textContent=fa(r.lines.length)+' ردیف استخراج شد'+(r.llm?' (با مدل زبانی)':'')+' — بررسی و اصلاح کنید'}catch(e){st.textContent=e.message||String(e)}};
 sv.onclick=async()=>{if(!svOn())return toast('ثبت هزینهٔ واقعی به اتصال سرور تیمی نیاز دارد');if(!X.lane)return toast('ابتدا مسیر را روی نقشه انتخاب کنید');const g=k=>$('[data-k='+k+']',bg).value;
  const lines=$$('tr',tb).map(r=>{const v=f=>$('[data-f='+f+']',r).value;return {comp:v('comp'),label:v('label'),amt:+v('amt'),cur:v('cur'),est:+v('est')||null}}).filter(l=>l.amt>0);if(!lines.length)return toast('مبلغی وارد نشده است');
  sv.disabled=true;try{const r=await svApi('/api/actuals',{method:'POST',body:{ref:g('ref'),date:g('date'),vendor:g('vendor'),lane:X.lane,mode:X.mode,eq:X.eq,src:pdf?'invoice-pdf':'invoice',lines}});toast('هزینهٔ واقعی ثبت شد · '+fa(r.n)+' ردیف · '+usd(r.usd));tb.innerHTML='';$('.ac-tx',bg).value='';pdf=null;sync();tab('acc')}catch(e){toast(e.message||String(e));sv.disabled=false}};
 const tab=t=>{$$('.ac-tabs button',bg).forEach(b=>b.classList.toggle('on',b.dataset.t===t));$$('.bd',bg).forEach(p=>p.hidden=p.dataset.p!==t);if(t==='acc')acAcc($('[data-p=acc]',bg),X)};$$('.ac-tabs button',bg).forEach(b=>b.onclick=()=>tab(b.dataset.t));
 if(o.tab)tab(o.tab);setTimeout(()=>$('.ac-tx',bg).focus(),80)}
async function acAcc(box,X){if(!svOn()){box.innerHTML='<p class="nt">دقت برآوردها از فاکتورهای ثبت‌شده روی سرور تیمی محاسبه می‌شود.</p>';return}
 try{const [A,C]=await Promise.all([svApi('/api/actuals/accuracy'),X.lane?acCalib(X.lane,X.mode):null]);if(!A.n){box.innerHTML='<p class="nt">هنوز فاکتوری با برآورد مرجع ثبت نشده است. با هر فاکتور، اختلاف هر جزء با برآورد اندازه‌گیری و برای مسیرهای مشابه ضریب تصحیح ساخته می‌شود.</p>';return}
  let L=null;try{L=IFA.landedCost()}catch(e){}const ap=C&&L?acApply(L,C):null;const pc=v=>v==null?'—':fa(Math.round(v*100))+'٪';
  box.innerHTML=`<div class="ac-k"><div><b>${fa(A.n)}</b><span>ردیف فاکتور</span></div><div><b>${pc(A.overall.mape)}</b><span>خطای میانگین (MAPE)</span></div><div><b>${A.bias==null?'—':(A.bias>0?'+':'')+fa(Math.round(A.bias*100))+'٪'}</b><span>سوگیری برآوردها</span></div>${ap?`<div><b>${usd(ap.adj)}</b><span>برآورد کالیبرهٔ این مسیر (${ap.pct>0?'+':''}${fa(ap.pct)}٪)</span></div>`:''}</div>
  <table class="ac-t ro"><thead><tr><th>جزء</th><th>تعداد</th><th>MAPE</th><th>ضریب این مسیر</th><th>سطح</th></tr></thead><tbody>${Object.entries(A.byComp).sort((a,b)=>b[1].n-a[1].n).map(([k,s])=>{const c=C&&C.components[k];return `<tr><td>${esc(ACN[k]||k)}</td><td>${fa(s.n)}</td><td>${pc(s.mape)}</td><td>${c?'× '+fa(c.factor):'—'}</td><td>${c?({lane:'همین مسیر',mode:'همین شیوه',all:'کل'})[c.level]:'—'}</td></tr>`}).join('')}</tbody></table>
  <p class="nt">روش: میانهٔ نسبت «واقعی ÷ برآورد» برای هر جزء، با انقباض سلسله‌مراتبی (مسیر ← شیوهٔ حمل ← کل) تا چند فاکتور محدود ضریب افراطی نسازند. پنجره: ۱۸ ماه اخیر.</p>`}catch(e){box.innerHTML='<p class="nt">'+esc(e.message||String(e))+'</p>'}}
