/* ===== v15.17 Iran data: rate channels (Telegram/Bale), Iran customs tariff book + customs FX, PMO port tariffs ===== */
const IR={tb:{},tbMeta:null,fx:null,fxAt:0};
const IRP={IR_BND:'SHR',IR_BAH:'BAH',IR_BIK:'BIK',IR_BUZ:'BUZ',IR_CHB:'CHB',IR_KHO:'KHO',IR_ASS:'ASS',IR_LEN:'LEN',IR_QSH:'QSH',IR_JSK:'JSK',IR_ANZ:'ANZ',IR_ASP:'AST',IR_AMI:'AMR',IR_NOW:'NOW',IR_KSP:'KSP'};
const irNum=v=>{const n=+String(v??'').replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[,٬\s]/g,'');return isFinite(n)?n:NaN};
async function irTb(hs){const d=String(hs||'').replace(/\D/g,'');if(d.length<4||!svOn())return null;if(d in IR.tb)return IR.tb[d];try{const j=await svApi('/api/tariff/ir?hs='+d);IR.tbMeta=j.meta||IR.tbMeta;IR.tb[d]=j.result||null}catch(e){return null}return IR.tb[d]}
async function irFxSync(force){if(!svOn())return null;if(!force&&IR.fx&&Date.now()-IR.fxAt<30*60e3)return IR.fx;try{const F=await svApi('/api/tariff/fx');IR.fx=F;IR.fxAt=Date.now();
 if(F&&F.rates&&+F.rates.USD>0&&typeof FIN!=='undefined'&&FIN.rx&&FIN.rx.cus!==+F.rates.USD){FIN.rx.cus=+F.rates.USD;try{finSave()}catch(e){}}return F}catch(e){return null}}
/* book-first HS lookup: cached server tariff-book rows take precedence over local tables */
(()=>{if(typeof hsLookup!=='function')return;const o=hsLookup;hsLookup=function(code){const d=String(code||'').replace(/\D/g,'');const t=IR.tb[d];
 if(t&&t.duty!=null&&(t.match==='exact'||t.match==='parent'||t.match==='child'))return {code:t.hs,rate:t.duty,n:t.desc,src:'کتاب تعرفهٔ ایران'+(IR.tbMeta&&IR.tbMeta.label?' · '+IR.tbMeta.label:'')};
 if(d.length>=6&&!(d in IR.tb)&&svOn())irTb(d);return o(code)}})();
function irDestPort(){try{const C=asCtxSafe();const seq=(C&&C.R&&C.R.nodeSeq)||[];for(let i=seq.length-1;i>=0;i--)if(IRP[seq[i]])return IRP[seq[i]]}catch(e){}return null}
const irB64=f=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]||'');r.onerror=()=>rej(r.error);r.readAsDataURL(f)});
const irWhen=t=>t?new Date(t).toLocaleString('fa-IR',{dateStyle:'short',timeStyle:'short'}):'—';
async function irShow(o={}){$('.cn-bg')?.remove();const bg=document.createElement('div');bg.className='cn-bg';
 bg.innerHTML=`<div class="cn-dlg ac-dlg ir-dlg" role="dialog" aria-modal="true" aria-label="داده‌های ایران"><header><div><b>داده‌های ایران</b><small>کانال‌های نرخ، کتاب تعرفهٔ گمرک و نرخ ارز گمرکی، تعرفه‌های بندری — روی سرور تیمی و مشترک برای همهٔ اعضا</small></div><button class="x" aria-label="بستن">${ASI.x}</button></header>
 <div class="ac-tabs"><button data-t="rc" class="on">کانال‌های نرخ</button><button data-t="tb">تعرفهٔ گمرک و ارز</button><button data-t="pt">تعرفهٔ بندری</button></div>
 <div class="bd" data-p="rc"><div class="ld">در حال بارگیری…</div></div><div class="bd" data-p="tb" hidden><div class="ld">در حال بارگیری…</div></div><div class="bd" data-p="pt" hidden><div class="ld">در حال بارگیری…</div></div></div>`;
 document.body.appendChild(bg);const shut=()=>{bg.classList.add('out');setTimeout(()=>bg.remove(),200)};bg.addEventListener('mousedown',e=>{if(e.target===bg)shut()});$('.x',bg).onclick=shut;
 const R={rc:irRc,tb:irTbTab,pt:irPt};const done={};const tab=t=>{$$('.ac-tabs button',bg).forEach(b=>b.classList.toggle('on',b.dataset.t===t));$$('.bd',bg).forEach(p=>p.hidden=p.dataset.p!==t);if(!done[t]){done[t]=1;const box=$('[data-p='+t+']',bg);if(!svOn()){box.innerHTML='<p class="nt">این بخش روی سرور تیمی نگه داشته می‌شود تا همهٔ اعضا از یک کتاب تعرفه، نرخ ارز گمرکی، تعرفهٔ بندری و صف نرخ‌های کانال استفاده کنند. ابتدا برنامه را به سرور وصل کنید.</p>';return}R[t](box)}};
 $$('.ac-tabs button',bg).forEach(b=>b.onclick=()=>tab(b.dataset.t));tab(o.tab&&R[o.tab]?o.tab:'rc')}
/* ---- tab 1: rate channels ---- */
const IRST={auto:['افزوده شد','ok'],approved:['تأیید شد','ok'],pending:['در انتظار بازبینی','md'],rejected:['رد شد','off']};
async function irRc(box){let D;try{D=await svApi('/api/ratech')}catch(e){box.innerHTML='<p class="nt">'+esc(e.message)+'</p>';return}const C=D.cfg,S=D.status,L=S.last||{};
 const src=s=>`<tr data-id="${esc(s.id)}"><td><select data-f="kind"><option value="tg"${s.kind==='tg'?' selected':''}>کانال عمومی تلگرام</option><option value="bot"${s.kind==='bot'?' selected':''}>ربات بله/تلگرام</option></select></td><td><input data-f="handle" value="${esc(s.handle||'')}" placeholder="@channel" dir="ltr"></td><td><input data-f="name" value="${esc(s.name||'')}" placeholder="نام نمایشی" dir="auto"></td><td class="c"><input type="checkbox" data-f="trust"${s.trust?' checked':''} title="منبع مورد اعتماد"></td><td class="c"><input type="checkbox" data-f="auto"${s.auto?' checked':''} title="افزودن خودکار به بانک نرخ"></td><td class="ir-ss">${s.err?'<i data-s="err" title="'+esc(s.err)+'"></i>':s.last?'<i data-s="ok" title="'+esc(irWhen(s.last))+'"></i>':'<i></i>'}</td><td><button class="rm" title="حذف">${ASI.x}</button></td></tr>`;
 const it=r=>{const s=IRST[r.status]||[r.status,''];return `<tr data-i="${r.id}" data-s="${s[1]}"><td>${esc(irWhen(r.ts))}<small>${esc(r.srcname||'')}</small></td><td dir="auto">${esc(r.pol||'؟')} ← ${esc(r.pod||'؟')}<small>${esc(r.eq||'')}</small></td><td dir="ltr" class="n">${nf(r.amt,0)} ${esc(r.cur||'')}${r.dev!=null?`<small class="${Math.abs(r.dev)>.3?'w':''}">${r.dev>0?'+':''}${Math.round(r.dev*100)}٪ بازار</small>`:''}</td><td><span class="ir-st" data-s="${s[1]}">${s[0]}</span>${r.why?`<small>${esc(r.why)}</small>`:''}</td><td>${r.status==='pending'?`<button class="go sm" data-a="approve">تأیید</button><button class="ir-lk" data-a="reject">رد</button>`:''}</td></tr>`};
 box.innerHTML=`<div class="ac-k"><div><b>${fa(D.counts.auto||0)}</b><span>افزوده‌شدهٔ خودکار</span></div><div><b>${fa(D.counts.pending||0)}</b><span>در انتظار بازبینی</span></div><div><b>${fa(D.counts.approved||0)}</b><span>تأییدشدهٔ دستی</span></div><div><b>${esc(irWhen(S.at))}</b><span>آخرین دریافت${L.errors&&L.errors.length?' · ⚠ '+esc(L.errors[0]):''}</span></div></div>
 <h4 class="ir-h">منابع</h4><div class="ac-tw"><table class="ac-t ir-src"><thead><tr><th>نوع</th><th>شناسه</th><th>نام</th><th title="منبع مورد اعتماد">معتبر</th><th title="افزودن خودکار">خودکار</th><th></th><th></th></tr></thead><tbody>${C.sources.map(src).join('')}</tbody></table></div>
 <div class="ac-bt"><button class="ac-add ir-add">+ منبع</button><label class="ir-in">هر<input data-c="every" type="number" min="5" value="${C.every}" dir="ltr">دقیقه</label><label class="ir-in">حداقل اطمینان<input data-c="autoMin" type="number" step=".05" min=".3" max="1" value="${C.autoMin}" dir="ltr"></label><label class="ir-in">حداکثر انحراف از بازار<input data-c="maxDev" type="number" step=".05" min=".05" value="${C.maxDev}" dir="ltr"></label><label class="ir-in"><input type="checkbox" data-c="on"${C.on?' checked':''}>دریافت خودکار</label></div>
 <div class="ac-bt"><button class="go ir-save">ذخیرهٔ منابع</button><button class="ac-file ir-poll">دریافت اکنون</button><span class="ac-st ir-pst">ربات‌ها: ${S.bots.bale?'بله ✓':'بله —'} · ${S.bots.telegram?'تلگرام ✓':'تلگرام —'}${S.net?'':' · دریافت شبکه‌ای خاموش است'}</span></div>
 <details class="ir-tst"><summary>آزمون با متن پیام (یا افزودن دستی پیام فورواردشده)</summary><textarea class="ac-tx ir-tx" placeholder="مثلاً: شانگهای به بندرعباس 40HC 2450 دلار، اعتبار تا پایان ماه" dir="auto"></textarea><div class="ac-bt"><select class="ir-tsrc"><option value="">ورودی دستی (نیاز به بازبینی)</option>${C.sources.map(s=>`<option value="${esc(s.id)}">${esc(s.name||s.handle)}</option>`).join('')}</select><button class="go ir-ing">استخراج و ثبت</button></div></details>
 <h4 class="ir-h">نرخ‌های دریافتی</h4>${D.items.length?`<div class="ac-tw"><table class="ac-t ro ir-it"><thead><tr><th>زمان · منبع</th><th>مسیر</th><th>مبلغ</th><th>وضعیت</th><th></th></tr></thead><tbody>${D.items.map(it).join('')}</tbody></table></div>`:'<p class="nt">هنوز نرخی دریافت نشده است.</p>'}
 <p class="nt">«معتبر + خودکار»: نرخ‌هایی که مبدأ، مقصد و مبلغشان روشن است، اطمینان استخراج کافی دارند، اعتبارشان نگذشته و بیش از حد مجاز از میانهٔ بازار فاصله ندارند مستقیم به بانک نرخ می‌روند؛ بقیه در صف بازبینی می‌مانند. کانال عمومی تلگرام از صفحهٔ پیش‌نمایش وب (t.me/s/…) خوانده می‌شود؛ برای کانال خصوصی یا بله، ربات را مدیر کانال کنید. اگر سرور به تلگرام دسترسی ندارد، IFA_TG_WEB و IFA_TG_API را به یک واسط مجاز تنظیم کنید.</p>`;
 const tb=$('.ir-src tbody',box);const bindRm=()=>$$('.rm',tb).forEach(b=>b.onclick=()=>b.closest('tr').remove());bindRm();
 $('.ir-add',box).onclick=()=>{tb.insertAdjacentHTML('beforeend',src({id:'',kind:'tg',handle:'',name:'',trust:false,auto:false}));bindRm();$('tr:last-child [data-f=handle]',tb).focus()};
 $('.ir-save',box).onclick=async()=>{const sources=$$('tr',tb).map(r=>{const g=k=>$('[data-f='+k+']',r);return {id:r.dataset.id||undefined,kind:g('kind').value,handle:g('handle').value.trim(),name:g('name').value.trim(),trust:g('trust').checked,auto:g('auto').checked}}).filter(s=>s.handle||s.kind==='bot');const c=k=>$('[data-c='+k+']',box);
  try{await svApi('/api/ratech/cfg',{method:'PUT',body:{sources,every:+c('every').value,autoMin:+c('autoMin').value,maxDev:+c('maxDev').value,on:c('on').checked}});toast('منابع نرخ ذخیره شد');irRc(box)}catch(e){toast(e.message)}};
 $('.ir-poll',box).onclick=async e=>{e.target.disabled=true;$('.ir-pst',box).textContent='در حال دریافت…';try{const r=await svApi('/api/ratech/poll',{method:'POST',body:{}});toast(fa(r.msgs||0)+' پیام · '+fa(r.auto||0)+' نرخ افزوده · '+fa(r.pending||0)+' در صف'+(r.errors&&r.errors.length?' · '+r.errors[0]:''));irRc(box)}catch(x){toast(x.message);e.target.disabled=false}};
 $('.ir-ing',box).onclick=async()=>{const t=$('.ir-tx',box).value.trim();if(t.length<8)return toast('متن پیام را وارد کنید');try{const r=await svApi('/api/ratech/ingest',{method:'POST',body:{text:t,source:$('.ir-tsrc',box).value}});toast(r.n?fa(r.n)+' نرخ استخراج شد · '+fa(r.auto)+' افزوده · '+fa(r.pending)+' در صف':'نرخی در متن شناسایی نشد');irRc(box)}catch(e){toast(e.message)}};
 $$('.ir-it [data-a]',box).forEach(b=>b.onclick=async()=>{const id=b.closest('tr').dataset.i;try{await svApi('/api/ratech/items/'+id,{method:'POST',body:{action:b.dataset.a}});toast(b.dataset.a==='approve'?'نرخ به بانک نرخ افزوده شد':'رد شد');irRc(box)}catch(e){toast(e.message)}})}
/* ---- tab 2: customs tariff book + customs FX ---- */
async function irTbTab(box){let M,F;try{[M,F]=await Promise.all([svApi('/api/tariff/ir'),svApi('/api/tariff/fx')])}catch(e){box.innerHTML='<p class="nt">'+esc(e.message)+'</p>';return}const m=M.meta||{};IR.tbMeta=m;IR.fx=F;IR.fxAt=Date.now();const R=F.rates||{};const C=(()=>{try{return asCtxSafe()}catch(e){return null}})();const hs0=(C&&C.cargo&&C.cargo.hs)||'';
 box.innerHTML=`<div class="ac-k"><div><b>${fa(m.n||0)}</b><span>ردیف در کتاب تعرفه${m.label?' · '+esc(m.label):''}</span></div><div><b>${esc(irWhen(m.at))}</b><span>آخرین ورود${m.by?' · '+esc(m.by):''}</span></div><div><b dir="ltr">${R.USD?nf(R.USD,0):'—'}</b><span>نرخ ارز گمرکی USD (ریال)${F.date?' · '+esc(F.date):''}</span></div></div>
 <h4 class="ir-h">ورود کتاب تعرفه (Excel یا CSV)</h4><div class="ac-bt"><label class="ac-file">${API_.pdf}انتخاب فایل<input type="file" class="ir-tf" accept=".xlsx,.csv,.tsv,.txt" hidden></label><input class="ir-lbl" placeholder="عنوان، مثلاً کتاب تعرفهٔ ۱۴۰۵" dir="auto"><select class="ir-md"><option value="replace">جایگزینی کامل</option><option value="merge">ادغام</option></select><button class="go ir-imp" disabled>ورود</button><span class="ac-st ir-ist"></span></div>
 <p class="nt">ستون‌های لازم: «کد/ردیف تعرفه» (۸ رقمی، با یا بدون نقطه) و «حقوق ورودی» (درصد). «شرح کالا»، «SUQ/واحد» و «اولویت» اختیاری‌اند. همهٔ برگه‌های فایل Excel خوانده می‌شوند.</p>
 <h4 class="ir-h">جستجو در کتاب تعرفه</h4><div class="ac-bt"><input class="ir-q" placeholder="کد HS یا شرح کالا" value="${esc(hs0)}" dir="auto"><button class="ac-file ir-qb">جستجو</button></div><div class="ir-qr"></div>
 <h4 class="ir-h">نرخ ارز گمرکی و پارامترها</h4><div class="ac-g ir-fx">${['USD','EUR','CNY','AED'].map(k=>`<label>${k} (ریال)<input data-r="${k}" type="number" min="0" value="${R[k]||''}" dir="ltr"></label>`).join('')}<label>تاریخ<input data-x="date" type="date" value="${esc(F.date||new Date().toISOString().slice(0,10))}"></label><label>ارزش افزوده ٪<input data-x="vat" type="number" step=".5" value="${F.vat}" dir="ltr"></label><label>هلال احمر (٪ حقوق ورودی)<input data-x="hl" type="number" step=".1" value="${F.hl}" dir="ltr"></label></div>
 <div class="ac-bt"><button class="go ir-fxs">ذخیرهٔ نرخ ارز گمرکی</button>${F.auto?'<button class="ac-file ir-fxr">دریافت از منبع خودکار</button>':''}<span class="ac-st">${esc(F.src||'ثبت نشده')}</span></div>
 <p class="nt">با ذخیره، نرخ مبنای گمرکی همهٔ اعضا (محاسبه‌گر حقوق ورودی و اتوپایلوت) به این مقدار تنظیم می‌شود. مرجع رسمی نرخ را از اطلاعیهٔ گمرک/بانک مرکزی بردارید؛ برای دریافت خودکار، IFA_CUSTOMS_FX_URL را به یک منبع JSON مجاز تنظیم کنید.</p>`;
 let file=null;$('.ir-tf',box).onchange=e=>{file=e.target.files[0]||null;$('.ir-imp',box).disabled=!file;$('.ir-ist',box).textContent=file?file.name+' · '+fa(Math.round(file.size/1024))+' KB':''};
 $('.ir-imp',box).onclick=async e=>{if(!file)return;e.target.disabled=true;$('.ir-ist',box).textContent='در حال ورود…';try{const x=/\.xlsx$/i.test(file.name);const b={label:$('.ir-lbl',box).value.trim(),mode:$('.ir-md',box).value,name:file.name};if(x)b.xlsx=await irB64(file);else b.text=await file.text();const r=await svApi('/api/tariff/ir/import',{method:'POST',body:b});IR.tb={};toast(fa(r.imported)+' ردیف تعرفه وارد شد'+(r.skipped?' · '+fa(r.skipped)+' ردیف نادیده':''));irTbTab(box)}catch(x){toast(x.message);$('.ir-ist',box).textContent=x.message;e.target.disabled=false}};
 const qr=$('.ir-qr',box);const row=r=>`<tr><td dir="ltr">${esc(String(r.hs).replace(/^(\d{4})(\d{2})(\d*)$/,'$1.$2$3'))}</td><td dir="auto">${esc(r.desc||'')}</td><td class="n">${fa(r.duty)}٪</td><td>${esc(r.suq||'')}</td></tr>`;
 const search=async()=>{const v=$('.ir-q',box).value.trim();if(v.length<2){qr.innerHTML='';return}qr.innerHTML='<p class="nt">…</p>';try{const d=v.replace(/\D/g,'');let L,h='';if(d.length>=6&&d.length===v.replace(/[\s.]/g,'').length){const j=await svApi('/api/tariff/ir?hs='+d);const t=j.result;IR.tb[d]=t||null;L=t?(t.children||[t]):[];h=t?({exact:'تطبیق دقیق',parent:'نزدیک‌ترین ردیف بالادستی',child:'تنها زیرشاخه',children:'زیرشاخه‌ها',sibling:'کد ۸ رقمی یافت نشد — هم‌خانواده‌های ۶ رقمی'})[t.match]+(t.range&&t.range[0]!==t.range[1]?' · بازهٔ نرخ '+fa(t.range[0])+'–'+fa(t.range[1])+'٪':''):'در کتاب تعرفه یافت نشد'}else{const j=await svApi('/api/tariff/ir?q='+encodeURIComponent(v));L=j.results||[];h=fa(L.length)+' نتیجه'}
  qr.innerHTML=`<p class="nt">${esc(h)}</p>`+(L.length?`<div class="ac-tw"><table class="ac-t ro"><thead><tr><th>کد</th><th>شرح</th><th>حقوق ورودی</th><th>واحد</th></tr></thead><tbody>${L.map(row).join('')}</tbody></table></div>`:'')}catch(e){qr.innerHTML='<p class="nt">'+esc(e.message)+'</p>'}};
 $('.ir-qb',box).onclick=search;$('.ir-q',box).onkeydown=e=>{if(e.key==='Enter')search()};if(hs0&&m.n)search();
 $('.ir-fxs',box).onclick=async()=>{const rates={};$$('[data-r]',box).forEach(i=>{const v=irNum(i.value);if(v>0)rates[i.dataset.r]=v});const g=k=>$('[data-x='+k+']',box).value;try{await svApi('/api/tariff/fx',{method:'PUT',body:{rates,date:g('date'),vat:+g('vat'),hl:+g('hl')}});await irFxSync(true);toast('نرخ ارز گمرکی ذخیره و در محاسبه‌ها اعمال شد');irTbTab(box)}catch(e){toast(e.message)}};
 const fr=$('.ir-fxr',box);if(fr)fr.onclick=async()=>{try{await svApi('/api/tariff/fx/refresh',{method:'POST',body:{}});await irFxSync(true);toast('نرخ ارز گمرکی به‌روز شد');irTbTab(box)}catch(e){toast(e.message)}}}
/* ---- tab 3: PMO port tariffs ---- */
async function irPt(box,sel){let D;try{D=await svApi('/api/ports/tariff')}catch(e){box.innerHTML='<p class="nt">'+esc(e.message)+'</p>';return}const P=D.ports||[];const dp=sel||irDestPort()||(P.find(p=>p.n)||{}).id||'SHR';let C=null;try{C=asCtxSafe()}catch(e){}const ct=String((C&&C.cargo&&C.cargo.containerType)||'40HC');
 box.innerHTML=`<div class="ac-g"><label>بندر<select class="ir-pp">${P.map(p=>`<option value="${p.id}"${p.id===dp?' selected':''}>${esc(p.name)}${p.n?' · '+fa(p.n)+' ردیف':''}</option>`).join('')}</select></label><label>کانتینر<select class="ir-pe"><option value="20"${/20/.test(ct)?' selected':''}>۲۰ فوت</option><option value="40"${/20/.test(ct)?'':' selected'}>۴۰ فوت / HC</option></select></label><label>تعداد<input class="ir-pq" type="number" min="1" value="1" dir="ltr"></label><label>روز توقف در بندر<input class="ir-pd" type="number" min="0" value="10" dir="ltr"></label><label>وزن (تن)<input class="ir-pw" type="number" min="0" value="${Math.round(((C&&C.cargo&&C.cargo.weightKg)||0)/1000)}" dir="ltr"></label><label class="ir-in"><input type="checkbox" class="ir-pr"${C&&C.cargo&&C.cargo.reefer?' checked':''}>یخچالی</label></div>
 <div class="ac-bt"><button class="go ir-pc">محاسبه</button><span class="ac-st ir-pst2"></span></div><div class="ir-pres"></div><h4 class="ir-h">ردیف‌های تعرفه</h4><div class="ir-prow"></div>
 <h4 class="ir-h">ورود تعرفهٔ بندری (Excel یا CSV)</h4><div class="ac-bt"><label class="ac-file">${API_.pdf}انتخاب فایل<input type="file" class="ir-ptf" accept=".xlsx,.csv,.tsv,.txt" hidden></label><input class="ir-plbl" placeholder="عنوان، مثلاً تعرفهٔ ۱۴۰۵ سازمان بنادر" dir="auto"><button class="go ir-pimp" disabled>ورود</button><span class="ac-st ir-pist"></span></div>
 <p class="nt">ستون‌ها: «بندر» (یا بندر انتخاب‌شده در بالا)، «خدمت» (تخلیه و بارگیری، انبارداری، برق یخچالی، عوارض بندری، اسکن…)، «کانتینر» (20/40/*)، «واحد» (کانتینر، روز، تن، بارنامه)، «مبلغ»، «ارز» (پیش‌فرض ریال)، «از روز» و «تا روز» برای پله‌های انبارداری (روز شمار از تخلیه)، «روز آزاد». با ورود، پله‌های انبارداری در محاسبه‌گر دموراژ و انبارداری هم برای همهٔ اعضا به‌روز می‌شود. مبالغ را از ابلاغیهٔ رسمی تعرفه‌های سازمان بنادر و دریانوردی یا صورت‌حساب ترمینال بردارید.</p>`;
 const g=c=>$(c,box);const rows=async()=>{const p=g('.ir-pp').value;try{const j=await svApi('/api/ports/tariff?port='+p);g('.ir-prow').innerHTML=j.rows.length?`<p class="nt">${esc(j.meta?j.meta.label+' · '+irWhen(j.meta.at):'')}</p><div class="ac-tw"><table class="ac-t ro"><thead><tr><th>خدمت</th><th>کانتینر</th><th>واحد</th><th>مبلغ</th><th>روزها</th></tr></thead><tbody>${j.rows.map(r=>`<tr><td>${esc(r.name||r.item)}</td><td>${r.eq==='*'?'همه':esc(r.eq)}</td><td>${({box:'کانتینر',day:'روز',ton:'تن',bl:'بارنامه'})[r.unit]||esc(r.unit)}</td><td dir="ltr" class="n">${nf(r.amt,0)} ${esc(r.cur)}</td><td>${r.d_from!=null||r.d_to!=null?fa(r.d_from||1)+'–'+(r.d_to?fa(r.d_to):'∞'):''}${r.free!=null?' · آزاد '+fa(r.free):''}</td></tr>`).join('')}</tbody></table></div>`:'<p class="nt">برای این بندر تعرفه‌ای ثبت نشده است.</p>'}catch(e){g('.ir-prow').innerHTML='<p class="nt">'+esc(e.message)+'</p>'}};
 const calc=async()=>{try{const r=await svApi('/api/ports/tariff/calc',{method:'POST',body:{port:g('.ir-pp').value,eq:g('.ir-pe').value,qty:+g('.ir-pq').value,days:+g('.ir-pd').value,tons:+g('.ir-pw').value,reefer:g('.ir-pr').checked}});
  g('.ir-pres').innerHTML=`<div class="ac-k"><div><b>${apRial(r.totalIRR)}</b><span>جمع هزینه‌های بندری · ${fa(r.qty)} کانتینر</span></div><div><b>${fa(r.free)}</b><span>روز انبارداری رایگان</span></div></div><div class="ac-tw"><table class="ac-t ro"><tbody>${r.lines.map(l=>`<tr><td>${esc(l.name)}</td><td class="n" dir="ltr">${nf(l.amt,0)} ${esc(l.cur)}</td><td><small>${esc(l.detail)}</small></td></tr>`).join('')}</tbody></table></div>`;g('.ir-pst2').textContent=''}catch(e){g('.ir-pres').innerHTML='';g('.ir-pst2').textContent=e.message}};
 g('.ir-pc').onclick=calc;g('.ir-pp').onchange=()=>{rows();calc()};rows();if((P.find(p=>p.id===dp)||{}).n)calc();
 let file=null;g('.ir-ptf').onchange=e=>{file=e.target.files[0]||null;g('.ir-pimp').disabled=!file;g('.ir-pist').textContent=file?file.name:''};
 g('.ir-pimp').onclick=async e=>{if(!file)return;e.target.disabled=true;g('.ir-pist').textContent='در حال ورود…';try{const b={label:g('.ir-plbl').value.trim(),port:g('.ir-pp').value,name:file.name};if(/\.xlsx$/i.test(file.name))b.xlsx=await irB64(file);else b.text=await file.text();const r=await svApi('/api/ports/tariff/import',{method:'POST',body:b});toast(fa(r.imported)+' ردیف تعرفهٔ بندری وارد شد · '+r.ports.length+' بندر');irPt(box,r.ports[0])}catch(x){toast(x.message);g('.ir-pist').textContent=x.message;e.target.disabled=false}}}
setTimeout(()=>{irFxSync()},4000);setInterval(()=>{irFxSync()},30*60e3);
