
/* ---------- corridors China → Iran: statuses (kv «ifa-routes»), cost/time/risk comparison & scenarios ---------- */
const DTKT5=[[75,387810],[100,476650],[150,654300],[200,766050],[250,877800],[300,989550],[350,1081300],[400,1173050],[450,1264800],[500,1344050],[550,1423300],[600,1502550],[650,1581800],[700,1661050],[750,1740300],[800,1806200],[850,1872100],[900,1938000],[950,2003900],[1000,2069800],[1100,2191550],[1200,2303250],[1300,2414950],[1400,2526650],[1500,2638350],[1600,2731750],[1700,2825150],[1800,2918550],[1900,3011950],[2000,3100350]];
function domPerTon(km){const T=DTKT5;let v;if(km<=T[0][0])v=T[0][1];else{v=null;for(let i=1;i<T.length;i++)if(km<=T[i][0]){const [a,x]=T[i-1],[b,y]=T[i];v=x+(y-x)*(km-a)/(b-a);break}if(v==null){const n=T.length;v=T[n-1][1]+(T[n-1][1]-T[n-2][1])/(T[n-1][0]-T[n-2][0])*(km-T[n-1][0])}}const V=dtCurrent();return {rial:v*V.tkm/1668,tkm:V.tkm,from:V.from,src:V.src}}
const DOMKM={IRBND:{IRTHR:1330,IRMHD:1480,IRIFN:1000,IRTBZ:1950,IRSYZ:600,IRBND:0},IRZBR:{IRTHR:1850,IRMHD:1500,IRIFN:1500,IRTBZ:2450,IRSYZ:1200,IRZBR:0},IRSRK:{IRTHR:1080,IRMHD:185,IRIFN:1500,IRTBZ:1700,IRSYZ:1450,IRSRK:0},IRBZR:{IRTHR:330,IRMHD:1200,IRIFN:750,IRTBZ:330,IRSYZ:1200,IRBZR:0}};
const RTS=[
 {id:'sea-bnd',n:'دریایی مستقیم به بندرعباس + جاده',modes:['sea','road'],via:'IRBND',podRx:/bandar|abbas|BND|رجایی|عباس/i,days:[20,28],port:5,base:{'20':1700,'40':2600,'40R':4200},kw:/hormuz|bandar\s*abbas|shahid\s*rajaee|persian\s*gulf|strait|هرمز|بندرعباس|بندر عباس|شهید رجایی|خلیج فارس|تنگه/i},
 {id:'sea-jea',n:'دریایی با ترانشیپ جبل‌علی → بندرعباس',modes:['sea','sea','road'],via:'IRBND',podRx:/jebel|dubai|جبل/i,days:[24,33],port:7,base:{'20':1900,'40':2900,'40R':4600},kw:/jebel\s*ali|dubai|uae|emirates|feeder|hormuz|جبل\s*علی|دبی|امارات|هرمز/i},
 {id:'sea-chb',n:'دریایی به چابهار + جاده',modes:['sea','road'],via:'IRZBR',podRx:/chabahar|چابهار/i,days:[22,30],port:6,base:{'20':1800,'40':2800,'40R':4500},kw:/chabahar|oman\s*sea|gulf\s*of\s*oman|arabian\s*sea|چابهار|دریای عمان/i},
 {id:'rail-kz',n:'ریلی چین–قزاقستان–ترکمنستان → سرخس/اینچه‌برون',modes:['rail','road'],via:'IRSRK',podRx:/sarakhs|incheh|سرخس|اینچه/i,mode:'rail',days:[14,22],port:3,base:{'20':3600,'40':4600},kw:/khorgos|altynkol|dostyk|alashankou|kazakhstan|turkmenistan|sarakhs|incheh|china.?iran\s*(rail|train)|قزاقستان|ترکمنستان|سرخس|اینچه|قطار\s*(چین|باری)/i},
 {id:'road-tir',n:'جاده‌ای TIR از کاشغر (قرقیزستان–ازبکستان–ترکمنستان)',modes:['road'],via:'IRSRK',podRx:/sarakhs|bajgiran|tehran|سرخس|باجگیران|تهران/i,mode:'road',days:[16,25],port:2,base:{'20':6800,'40':6800},kw:/irkeshtam|torugart|kyrgyz|uzbekistan|turkmenistan|tir\b|bajgiran|قرقیزستان|ازبکستان|ترکمنستان|تیر|باجگیران/i},
 {id:'casp',n:'ریلی تا آکتائو + کشتی خزر → انزلی/امیرآباد',modes:['rail','sea','road'],via:'IRBZR',podRx:/anzali|amirabad|انزلی|امیرآباد/i,mode:'rail',days:[22,32],port:5,base:{'20':4200,'40':5200},kw:/aktau|kuryk|caspian|anzali|amirabad|خزر|انزلی|امیرآباد|آکتائو/i}];
const RSTFA={open:'باز',caution:'احتیاط',closed:'بسته'};
function routesState(){const k=kvGet('ifa-routes')||{};return {st:k.st||{},hist:Array.isArray(k.hist)?k.hist:[],base:k.base||{}}}
function routesList(){const S=routesState();return RTS.map(r=>{const s=S.st[r.id]||{status:'open'};return {id:r.id,name:r.n,modes:r.modes,via:r.via,days:r.days,status:s.status||'open',statusFa:RSTFA[s.status||'open'],reason:s.reason||'',source:s.source||'',since:s.ts||null,by:s.by||''}})}
function routeSet(id,status,reason,source,by){if(!RTS.some(r=>r.id===id))throw E(400,'مسیر ناشناخته: '+id);if(!RSTFA[status])throw E(400,'وضعیت نامعتبر (open/caution/closed)');const k=kvGet('ifa-routes')||{};k.st=k.st||{};const prev=k.st[id]||{status:'open'};
 k.st[id]={status,reason:String(reason||'').slice(0,400),source:String(source||'').slice(0,500),ts:Date.now(),by};k.hist=[{id,from:prev.status||'open',to:status,reason:k.st[id].reason,source:k.st[id].source,ts:Date.now(),by},...(k.hist||[])].slice(0,300);kvPut('ifa-routes',k,by);
 fire('route.status',{ref:id,route:(RTS.find(r=>r.id===id)||{}).n,from:RSTFA[prev.status||'open'],to:RSTFA[status],reason:k.st[id].reason,source:k.st[id].source},'rst|'+id+'|'+status+'|'+Date.now());dispatch().catch(()=>{});return {prev}}
function compareRoutes(o={}){const C=agCfg();const S=routesState();const eq=o.eq||'40HC',cls=eqCls(eq),qty=Math.max(1,+o.qty||1),value=+o.value||0,dl=+o.deadlineDays||0;const sc=o.scenario||{};
 const pol=portOf(o.pol||'Ningbo')||portOf('Ningbo');const dest=portOf(o.dest||o.pod||'Tehran')||portOf('Tehran');const wt=+o.weightT||(cls==='20'?18:22);const F=fxNow();const A=ratesAll();const src=[];
 const R=RTS.map(r=>{const st=(sc.closed||[]).includes(r.id)?'closed':(sc.status||{})[r.id]||(S.st[r.id]||{}).status||'open';const notes=[];
  /* main leg: real rates first (rate bank, partner panel, online RFQ), else configurable model default */
  const L=A.filter(x=>x.usd>0&&eqCls(x.eq)===cls&&Date.parse(x.date||0)>Date.now()-120*864e5&&(x.polC===pol[0]||(!!r.mode&&/^CN/.test(x.polC)))&&(r.mode?x.mode===r.mode:(!x.mode||x.mode==='sea'))&&r.podRx.test(x.pod+' '+(x.note||'')));
  let main,msrc,conf;if(L.length){main=median(L.map(x=>x.usd));msrc='میانهٔ '+L.length+' نرخ واقعی ۱۲۰ روز اخیر';conf=Math.min(0.9,0.5+L.length*0.08);L.slice(0,4).forEach(x=>src.push(rSrc(x)))}
  else{const b={...r.base,...((C.routeBase||{})[r.id]||{}),...((S.base||{})[r.id]||{})};main=b[cls]||b['40'];msrc='پیش‌فرض قابل‌تنظیم مدل (نه نرخ بازار) — با نرخ واقعی جایگزین کنید';conf=0.25;notes.push('کرایهٔ بخش اصلی از پیش‌فرض مدل است')}
  const fp=+((sc.freightPct||{})[r.mode||'sea'])||+sc.freightPct_all||0;if(fp)main*=1+fp/100;
  /* domestic leg: official tonne-km tariff (floor) */
  const km=(DOMKM[r.via]||{})[dest[0]]??(dest[4]==='IR'?null:0);let dom=0,domR=0,dsrc='';if(km==null){notes.push('فاصلهٔ داخلی تا '+dest[2]+' در جدول نیست')}else if(km>0){const d=domPerTon(km);domR=d.rial*wt;const fxp=+sc.fxPct||0;const free=F.free?F.free*(1+fxp/100):null;dom=free?domR/free:0;dsrc='تعرفهٔ رسمی تن-کیلومتر '+d.tkm+' ریال از '+d.from+' × '+wt+' تن × '+km+' km';if(!free)notes.push('نرخ دلار آزاد در دسترس نیست؛ هزینهٔ داخلی فقط به ریال')}
  const dly=+((sc.delay||{})[r.id])||0;const dd=km?Math.ceil(km/550):0;const dmin=r.days[0]+r.port+dd+dly,dmax=r.days[1]+r.port+dd+2+dly,dmid=Math.round((dmin+dmax)/2);
  const carry=value*(C.carry/100)*dmid/365;const rp=(C.riskPct[st]??1)/100*value;const total=(main+dom)*qty+carry+rp;
  const feas=st!=='closed'&&(!dl||dmax<=dl);const tight=st!=='closed'&&dl&&dmax>dl&&dmid<=dl;
  return {id:r.id,name:r.n,modes:r.modes,status:st,statusFa:RSTFA[st],mainUSD:Math.round(main),mainSource:msrc,domUSD:Math.round(dom),domIRR:Math.round(domR),domSource:dsrc,km,daysMin:dmin,daysMax:dmax,days:dmid,carryUSD:Math.round(carry),riskUSD:Math.round(rp),totalUSD:Math.round(total),perUnitUSD:Math.round(main+dom),confidence:+conf.toFixed(2),feasible:feas,tight:!!tight,notes}});
 R.sort((a,b)=>(b.feasible-a.feasible)||(a.totalUSD-b.totalUSD));const best=R.find(r=>r.feasible)||null;
 src.push({kind:'tariff',ref:'dtar',title:'شاخص رسمی تن-کیلومتر حمل جاده‌ای ('+dtCurrent().tkm+' ریال از '+dtCurrent().from+')',view:'dom'});if(F.free)src.push({kind:'fx',ref:'fx',title:'دلار آزاد '+Math.round(F.free)+' ریال',view:'mkt'});
 return {input:{pol:pol[1],dest:dest[1],eq,qty,value,deadlineDays:dl||null,weightT:wt,scenario:sc},routes:R,best:best&&best.id,assumptions:['هزینهٔ نگهداری موجودی: '+C.carry+'٪ سالانهٔ ارزش کالا','حق بیمهٔ ریسک: باز '+C.riskPct.open+'٪، احتیاط '+C.riskPct.caution+'٪ ارزش','کرایهٔ داخلی = کف تعرفهٔ رسمی؛ بازار معمولاً بالاتر است','زمان‌ها تقریبی و بدون صف‌های استثنایی'],
  caveat:'این مقایسه مشاورهٔ تحریمی یا حقوقی نیست؛ پیش از رزرو، مالکیت/پرچم کشتی، خط کشتیرانی و طرف‌ها را غربال کنید.',sources:src}}

/* ---------- shipping-document consistency check ---------- */
function iso6346(c){c=String(c).toUpperCase().replace(/[^A-Z0-9]/g,'');if(!/^[A-Z]{3}[UJZ]\d{7}$/.test(c))return null;const V='0123456789A?BCDEFGHIJK?LMNOPQRSTU?VWXYZ';let s=0;for(let i=0;i<10;i++){const v=i<4?V.indexOf(c[i]):+c[i];s+=v*2**i}return (s%11)%10===+c[10]}
function docFields(t){t=enDig(String(t||''));const g=(re,i=1)=>{const m=t.match(re);return m?String(m[i]).trim():null};const num=s=>s==null?null:numP(s);
 const ctr=[...new Set([...t.toUpperCase().matchAll(/\b([A-Z]{3}[UJZ])\s?-?(\d{6})\s?-?(\d)\b/g)].map(m=>m[1]+m[2]+m[3]))];
 return {containers:ctr,seals:[...new Set([...t.matchAll(/seal\s*(?:no\.?|number|#)?\s*[:\-]?\s*([A-Z0-9]{5,15})/gi)].map(m=>m[1].toUpperCase()))],
  gross:num(g(/(?:gross\s*weight|g\.\s?w\.?|gw|وزن\s*ناخالص)\s*[:\-]?\s*([\d.,]+)\s*(?:kgs?|kilo)/i)),net:num(g(/(?:net\s*weight|n\.\s?w\.?|nw|وزن\s*خالص)\s*[:\-]?\s*([\d.,]+)\s*(?:kgs?|kilo)/i)),
  packages:num(g(/(?:total\s*)?(?:packages|pkgs|no\.?\s*of\s*packages|cartons|ctns|pallets|bags|cases|بسته|کارتن)\s*[:\-]?\s*([\d.,]+)/i))??num(g(/([\d,]+)\s*(?:packages|pkgs|cartons|ctns|pallets|bags|cases)\b/i)),
  cbm:num(g(/([\d.,]+)\s*(?:cbm|m3|m³)/i)),value:num(g(/(?:total\s*(?:amount|value|invoice\s*value)?|grand\s*total|مبلغ\s*کل)\s*[:\-]?\s*(?:USD|US\$|EUR|CNY|AED|\$)?\s*([\d.,]+)/i)),currency:g(/\b(USD|EUR|CNY|RMB|AED)\b/i),
  incoterm:g(/\b(EXW|FCA|FAS|FOB|CFR|CNF|CIF|CPT|CIP|DAP|DPU|DDP)\b/),hs:[...new Set([...t.matchAll(/(?:H\.?S\.?\s*(?:code|no\.?)?|tariff\s*code|کد\s*تعرفه)\s*[:\-]?\s*(\d{4}[.\s]?\d{2}(?:[.\s]?\d{2,4})?)/gi)].map(m=>m[1].replace(/\D/g,'')))],
  shipper:g(/shipper\s*(?:\/\s*exporter)?\s*[:\-]?\s*\n?\s*([^\n]{3,80})/i),consignee:g(/consignee\s*[:\-]?\s*\n?\s*([^\n]{3,80})/i),notify:g(/notify\s*(?:party)?\s*[:\-]?\s*\n?\s*([^\n]{3,80})/i),
  pol:(portOf(g(/(?:port\s*of\s*loading|pol|loading\s*port)\s*[:\-]?\s*([^\n]{3,40})/i)||'')||[])[1]||null,pod:(portOf(g(/(?:port\s*of\s*discharge|pod|discharge\s*port|destination)\s*[:\-]?\s*([^\n]{3,40})/i)||'')||[])[1]||null,
  invoiceNo:g(/invoice\s*(?:no\.?|number|#)\s*[:\-]?\s*([A-Z0-9\-/]{3,30})/i),blNo:g(/b\/?l\s*(?:no\.?|number|#)\s*[:\-]?\s*([A-Z0-9\-]{5,30})/i),origin:g(/(?:country\s*of\s*origin|made\s*in|origin)\s*[:\-]?\s*([A-Za-z ]{3,30})/i)}}
const DOCFA={invoice:'فاکتور تجاری',packing:'لیست عدل‌بندی',bl:'بارنامه',co:'گواهی مبدأ',decl:'اظهارنامه',other:'سند'};
function docsCheck(docs){const D=(Array.isArray(docs)?docs:[]).slice(0,10).map((d,i)=>({type:d.type||'other',name:d.name||(DOCFA[d.type]||'سند')+' '+(i+1),f:{...docFields(d.text||''),...(d.fields||{})}}));const I=[];const add=(sev,msg,docsx)=>I.push({sev,msg,docs:docsx||[]});
 for(const d of D)for(const c of d.f.containers){const v=iso6346(c);if(v===false)add('high','رقم کنترل شمارهٔ کانتینر '+c+' نادرست است (ISO 6346)',[d.name])}
 const cmpNum=(k,lab,tol)=>{const H=D.filter(d=>d.f[k]!=null&&d.f[k]>0);if(H.length<2)return;const base=H[0].f[k];for(const d of H.slice(1))if(Math.abs(d.f[k]-base)/base>tol)add('high',lab+' ناهمخوان: '+H[0].name+' = '+base+' ، '+d.name+' = '+d.f[k],[H[0].name,d.name])};
 cmpNum('gross','وزن ناخالص',0.005);cmpNum('net','وزن خالص',0.005);cmpNum('packages','تعداد بسته',0);cmpNum('cbm','حجم (CBM)',0.03);
 const cmpSet=(k,lab)=>{const H=D.filter(d=>d.f[k]&&d.f[k].length);if(H.length<2)return;const a=new Set(H[0].f[k]);for(const d of H.slice(1)){const b=new Set(d.f[k]);const miss=[...a].filter(x=>!b.has(x)),extra=[...b].filter(x=>!a.has(x));if(miss.length||extra.length)add(k==='hs'?'med':'high',lab+' ناهمخوان بین '+H[0].name+' و '+d.name+(miss.length?' · فقط در اولی: '+miss.join('، '):'')+(extra.length?' · فقط در دومی: '+extra.join('، '):''),[H[0].name,d.name])}};
 cmpSet('containers','شمارهٔ کانتینر');cmpSet('seals','شمارهٔ پلمب');cmpSet('hs','کد HS');
 const cmpTxt=(k,lab)=>{const H=D.filter(d=>d.f[k]);if(H.length<2)return;const n=s=>nk(s).replace(/(co|ltd|limited|company|inc|llc|trading|شرکت)/g,'');const a=n(H[0].f[k]);for(const d of H.slice(1)){const b=n(d.f[k]);if(a&&b&&!(a.includes(b)||b.includes(a)))add('med',lab+' متفاوت: «'+H[0].f[k]+'» در برابر «'+d.f[k]+'»',[H[0].name,d.name])}};
 cmpTxt('consignee','گیرنده (Consignee)');cmpTxt('shipper','فرستنده (Shipper)');cmpTxt('incoterm','اینکوترمز');cmpTxt('pol','بندر بارگیری');cmpTxt('pod','بندر تخلیه');cmpTxt('currency','ارز');
 for(const d of D){if(d.f.net&&d.f.gross&&d.f.net>d.f.gross)add('high','وزن خالص از ناخالص بیشتر است',[d.name]);if(d.type==='invoice'&&!d.f.hs.length)add('low','کد HS در فاکتور درج نشده',[d.name]);if(d.type==='bl'&&!d.f.containers.length)add('med','شمارهٔ کانتینر در بارنامه پیدا نشد',[d.name]);if(d.type==='invoice'&&!d.f.incoterm)add('low','اینکوترمز در فاکتور پیدا نشد',[d.name])}
 const parties=[...new Set(D.flatMap(d=>[d.f.shipper,d.f.consignee,d.f.notify]).filter(Boolean))];const sc=parties.map(p=>({name:p,hits:sanctScreen(p).hits})).filter(x=>x.hits.length);for(const s of sc)add('high','نام «'+s.name+'» با فهرست تحریم مشابهت دارد: '+s.hits.slice(0,2).map(h=>h.name+' ('+h.list+')').join('، ')+' — بررسی انسانی لازم است',[]);
 return {docs:D.map(d=>({name:d.name,type:d.type,fields:d.f})),issues:I.sort((a,b)=>'highmedlow'.indexOf(a.sev)-'highmedlow'.indexOf(b.sev)),ok:!I.some(i=>i.sev==='high'),sanctions:sc,caveat:'کنترل خودکار جایگزین بازبینی کارشناس اسناد و ترخیص نیست؛ استخراج از متن ممکن است خطا داشته باشد.'}}

/* ---------- HS code suggestion (built-in heading dictionary; confirm in the official Iranian tariff book) ---------- */
const HSD=[['8517.13','گوشی هوشمند','smartphone|mobile phone|cell phone|گوشی|موبایل|تلفن همراه'],['8471.30','لپ‌تاپ','laptop|notebook computer|لپ ?تاپ'],['8471.50','واحد پردازش رایانه','server|computer unit|کیس|سرور'],['8528.72','تلویزیون','television|tv set|تلویزیون'],['8418.10','یخچال‌فریزر','refrigerator|fridge|یخچال'],['8450.11','ماشین لباسشویی','washing machine|لباسشویی'],['8415.10','کولر گازی','air conditioner|split ac|کولر گازی|اسپلیت'],
 ['8541.43','ماژول/پنل خورشیدی','solar panel|photovoltaic|pv module|پنل خورشیدی|خورشیدی'],['8504.40','اینورتر و مبدل','inverter|converter|power supply|اینورتر|منبع تغذیه'],['8507.60','باتری لیتیومی','lithium battery|li-ion|باتری لیتیوم'],['9405.42','چراغ LED','led lamp|led light|لامپ ال ای دی|چراغ led|ال‌ای‌دی'],['8544.49','کابل برق','electric cable|wire|cable|کابل|سیم'],['8536.50','کلید و سوئیچ','switch|کلید برق'],
 ['8708.99','قطعات خودرو','auto parts|car parts|vehicle parts|قطعات خودرو|لوازم یدکی'],['8708.30','لنت و ترمز','brake pad|brake|لنت|ترمز'],['4011.10','لاستیک سواری','car tyre|car tire|passenger tire|لاستیک سواری|تایر'],['4011.20','لاستیک کامیون','truck tyre|truck tire|bus tire|لاستیک کامیون'],['8703.80','خودروی برقی','electric vehicle|ev car|خودرو برقی'],['8711.60','موتورسیکلت برقی','electric motorcycle|e-bike|موتور برقی'],
 ['8481.80','شیر صنعتی','valve|شیر صنعتی|ولو'],['8413.70','پمپ گریز از مرکز','centrifugal pump|pump|پمپ'],['8414.80','کمپرسور','compressor|کمپرسور'],['8482.10','بلبرینگ','ball bearing|bearing|بلبرینگ|یاتاقان'],['8483.40','گیربکس','gearbox|gear|گیربکس'],['8501.52','الکتروموتور','electric motor|motor|الکتروموتور'],['8429.52','بیل مکانیکی','excavator|بیل مکانیکی'],['8474.20','سنگ‌شکن','crusher|سنگ شکن'],['8477.10','دستگاه تزریق پلاستیک','injection moulding|injection molding|تزریق پلاستیک'],
 ['8445.19','ماشین‌آلات نساجی','textile machine|spinning|ماشین نساجی'],['8428.10','آسانسور','elevator|lift|آسانسور'],['8443.32','چاپگر','printer|پرینتر|چاپگر'],['9018.90','تجهیزات پزشکی','medical device|medical equipment|تجهیزات پزشکی'],['3004.90','دارو','medicine|pharmaceutical|دارو'],
 ['6907.21','کاشی و سرامیک','ceramic tile|porcelain tile|tile|کاشی|سرامیک'],['7306.30','لوله فولادی','steel pipe|steel tube|لوله فولادی|لوله آهنی'],['7208.51','ورق فولادی','steel plate|steel sheet|hot rolled|ورق فولادی|ورق آهن'],['7318.15','پیچ و مهره','bolt|screw|nut|پیچ|مهره'],['7604.29','پروفیل آلومینیوم','aluminium profile|aluminum profile|پروفیل آلومینیوم'],['7019.39','الیاف شیشه','fiberglass|glass fiber|فایبرگلاس'],
 ['3901.10','پلی‌اتیلن','polyethylene|pe granule|hdpe|ldpe|پلی اتیلن|گرانول'],['3902.10','پلی‌پروپیلن','polypropylene|pp granule|پلی پروپیلن'],['3904.10','PVC','pvc resin|polyvinyl|پی وی سی'],['3923.21','کیسهٔ پلاستیکی','plastic bag|کیسه پلاستیک'],['3917.23','لوله PVC','pvc pipe|لوله پلاستیکی'],['4002.19','کائوچوی مصنوعی','synthetic rubber|sbr|کائوچو'],
 ['2804.61','سیلیکون','silicon metal|سیلیسیم'],['2836.20','کربنات سدیم','soda ash|sodium carbonate|سودا اش'],['3824.99','افزودنی شیمیایی','chemical additive|additive|افزودنی'],['3208.90','رنگ و لاک','paint|varnish|coating|رنگ صنعتی'],['3402.42','شوینده','detergent|surfactant|شوینده'],
 ['5407.61','پارچهٔ پلی‌استر','polyester fabric|پارچه پلی استر'],['5208.52','پارچهٔ نخی','cotton fabric|پارچه نخی'],['6109.10','تی‌شرت','t-shirt|tshirt|تی شرت'],['6203.42','شلوار مردانه','trousers|jeans|شلوار'],['6402.99','کفش','shoes|footwear|sneakers|کفش'],['4202.92','کیف و چمدان','bag|luggage|suitcase|کیف|چمدان'],
 ['9403.60','مبلمان چوبی','wooden furniture|furniture|مبلمان|مبل'],['9401.71','صندلی','chair|seat|صندلی'],['9503.00','اسباب‌بازی','toy|toys|اسباب بازی'],['9506.91','لوازم ورزشی','fitness equipment|sports equipment|لوازم ورزشی'],['8516.60','لوازم آشپزخانهٔ برقی','electric oven|cooker|microwave|اجاق|مایکروویو'],['7323.93','ظروف استیل','stainless kitchenware|cookware|ظروف'],['6911.10','ظروف چینی','porcelain tableware|ظروف چینی'],
 ['0902.30','چای سیاه','black tea|tea|چای'],['1006.30','برنج','rice|برنج'],['0805.10','پرتقال','orange|پرتقال'],['0802.51','پسته','pistachio|پسته'],['0806.20','کشمش','raisin|کشمش'],['0910.20','زعفران','saffron|زعفران'],['1701.99','شکر','sugar|شکر'],['1507.90','روغن سویا','soybean oil|روغن سویا'],['2309.90','خوراک دام','animal feed|feed|خوراک دام'],
 ['8486.20','تجهیزات تولید نیمه‌هادی','semiconductor equipment|wafer'],['8803.30','قطعات هواپیما','aircraft parts|قطعات هواپیما'],['9306.30','مهمات','ammunition|cartridge|مهمات']];
const HSDUAL=/^(8486|8803|9306|8471\.50|8517)/;
function hsSuggest(desc){const t=String(desc||'').toLowerCase();if(!t.trim())return {query:desc,candidates:[]};const C=[];
 for(const [code,n,kw] of HSD){let sc=0;const hits=[];for(const k of kw.split('|')){const re=new RegExp('(^|[^\\p{L}])'+k.replace(/[.*+?^${}()[\]\\]/g,'\\$&').replace(/ \?/g,' ?')+'($|[^\\p{L}])','iu');if(re.test(t)){sc+=k.length>5?2:1;hits.push(k)}}if(sc)C.push({code,heading:code.slice(0,4),name:n,score:sc,hits})}
 C.sort((a,b)=>b.score-a.score);const top=C[0]?C[0].score:0;
 return {query:desc,candidates:C.slice(0,5).map(c=>({code:c.code,heading:c.heading,name:c.name,matched:c.hits,confidence:+Math.min(0.85,0.35+0.12*c.score-(c.score<top?0.15:0)).toFixed(2),dualUse:HSDUAL.test(c.code)})),
  caveat:'کد پیشنهادی فقط تا ۶ رقم (HS جهانی) است. کد ۸ رقمی، حقوق ورودی، اولویت کالایی و مجوزها را با کتاب مقررات صادرات و واردات سال جاری و سامانهٔ جامع گمرکی تطبیق دهید.'+(C.slice(0,5).some(c=>HSDUAL.test(c.code))?' ⚠ برخی گزینه‌ها ممکن است کالای دومنظوره یا مشمول محدودیت صادراتی/تحریمی باشند.':'')}}

/* ---------- invoice vs quote reconciliation ---------- */
function reconcile(o){const C=agCfg();const inv=o.invoice||{};const qt=o.quote||{};const wrsCap=o.wrsCap!=null?+o.wrsCap:C.wrsCap;
 const lines=Array.isArray(inv.lines)&&inv.lines.length?inv.lines.map(l=>({desc:String(l.desc||l.n||''),amt:+l.amt||+l.v||0,cur:curNorm(l.cur||inv.cur||'USD'),qty:+l.qty||1})):enDig(inv.text||'').split('\n').map(l=>{const m=[...l.matchAll(AMTRX)].pop();const qm=l.match(/(\d+)\s*[x×]\s*(?:20|40)|(?:20|40)\S*\s*[x×]\s*(\d+)/i);return m?{desc:l.replace(m[0],'').trim().slice(0,120),amt:numP(m[2]||m[3]),cur:curNorm(m[1]||m[4]),qty:qm?+(qm[1]||qm[2]):1}:null}).filter(Boolean);
 let Q=qt;if(qt.id){const r=ratesAll().find(x=>x.id===qt.id);if(r)Q={...r,...qt,amt:qt.amt||r.amt,cur:qt.cur||r.cur,incl:qt.incl||r.incl}}
 const qty=+o.qty||+Q.qty||1;const qUSD=usdOf(Q.amt,Q.cur||'USD')||0;const declared=new Set([...(Q.surcharges||[]).map(s=>surKey(s.code||s)),...String(Q.incl||'').toUpperCase().split(/[\s,;/+]+/).filter(Boolean).map(surKey)]);
 const I=[];let base=null,extra=0;const R=lines.map(l=>{const usd=usdOf(l.amt,l.cur);const sm=l.desc.match(SURRX);const code=sm?surKey(sm[1]):null;const isBase=!code&&/(ocean|sea|freight|كرايه|کرایه|حمل|O\/F|basic)/i.test(l.desc);const row={...l,usd:usd!=null?Math.round(usd):null,code,kind:isBase?'base':code?'surcharge':'other'};
  if(isBase&&!base)base=row;else if(code){if(code==='WRS'&&wrsCap>=0&&usd!=null&&usd/Math.max(1,l.qty)>wrsCap&&wrsCap>0){I.push({sev:'high',msg:'سرشارژ ریسک جنگ (WRS) '+Math.round(usd)+'$ بیش از سقف توافقی '+wrsCap+'$ برای هر واحد'});extra+=usd-wrsCap*l.qty}
   else if(!declared.has(code)&&!(Q.allin&&!['WRS','DTHC'].includes(code))){I.push({sev:'high',msg:'سرشارژ اعلام‌نشده در پیشنهاد: '+code+' = '+l.amt+' '+l.cur});if(usd)extra+=usd}}return row});
 if(base&&qUSD){const per=(base.usd||0)/Math.max(1,base.qty||qty);const d=per-qUSD;if(Math.abs(d)/qUSD>0.01){I.push({sev:d>0?'high':'low',msg:'کرایهٔ پایه '+Math.round(per)+'$ در برابر پیشنهاد '+Math.round(qUSD)+'$ ('+(d>0?'+':'')+Math.round(d)+'$ هر واحد)'});if(d>0)extra+=d*Math.max(1,base.qty||qty)}}else if(!base)I.push({sev:'med',msg:'ردیف کرایهٔ پایه در صورتحساب شناسایی نشد'});
 if(base&&base.qty&&qty&&base.qty!==qty)I.push({sev:'high',msg:'تعداد کانتینر صورتحساب ('+base.qty+') با پیشنهاد ('+qty+') یکی نیست'});
 const curs=[...new Set(lines.map(l=>l.cur))];if(Q.cur&&curs.length&&!curs.includes(curNorm(Q.cur)))I.push({sev:'med',msg:'ارز صورتحساب ('+curs.join('، ')+') با ارز پیشنهاد ('+Q.cur+') متفاوت است؛ نرخ تبدیل را کنترل کنید'});
 if(Q.valid&&inv.date&&inv.date>Q.valid)I.push({sev:'med',msg:'تاریخ صورتحساب ('+inv.date+') پس از اعتبار پیشنهاد ('+Q.valid+') است'});
 const totalUSD=Math.round(R.reduce((s,r)=>s+(r.usd||0),0));
 return {lines:R,quote:{id:Q.id||null,vendor:Q.vendor||'',usd:Math.round(qUSD)||null,qty,declared:[...declared],allin:!!Q.allin},totalUSD,disputeUSD:Math.round(Math.max(0,extra)),issues:I,ok:!I.some(i=>i.sev==='high'),
  draft:I.length?`Dear ${Q.vendor||'Partner'},\n\nRegarding invoice ${inv.no||''}, we found the following differences against your quotation${Q.id?' ('+Q.id+')':''}:\n${I.map(i=>'- '+i.msg).join('\n')}\n\nPlease issue a corrected invoice or provide supporting documents. Disputed amount: USD ${Math.round(Math.max(0,extra))}.\n\nBest regards`:''}}

/* ---------- sanctions screening (local copy of OFAC/UN/EU lists) ---------- */
let SANC=null;function sanctLoad(){try{const st=fs.statSync(SFILE());if(SANC&&SANC.m===st.mtimeMs)return SANC;const J=JSON.parse(fs.readFileSync(SFILE(),'utf8'));const nz2=s=>String(s||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9\u0600-\u06ff ]/g,' ').replace(/\b(co|ltd|limited|company|inc|llc|corp|corporation|trading|group|the|of|and|shipping|logistics|international|intl|plc|gmbh|sa|fze|fzco|jsc|pjsc)\b/g,' ').replace(/\s+/g,' ').trim();
 SANC={m:st.mtimeMs,date:J.m&&J.m.date,nz:nz2,E:J.d.map(e=>({list:e[0],type:e[1],name:e[2],prog:e[3],keys:[e[2],...(e[4]||[])].map(nz2).filter(k=>k.length>3)}))};return SANC}catch(e){return null}}
function sanctScreen(name){const S=sanctLoad();if(!S)return {name,hits:[],list:null,note:'فهرست تحریم روی سرور ساخته نشده است'};const n=S.nz(name);if(n.length<4)return {name,hits:[],list:S.date};const nt=new Set(n.split(' '));
 const H=[];for(const e of S.E){for(const k of e.keys){let sc=0;if(k===n)sc=1;else{const kt=k.split(' ');if(kt.length>=2&&kt.every(t=>nt.has(t)))sc=0.9;else if(nt.size>=2&&[...nt].every(t=>kt.includes(t)))sc=0.85}if(sc){H.push({name:e.name,list:{O:'OFAC SDN',C:'OFAC Non-SDN',U:'UN',E:'EU'}[e.list]||e.list,program:e.prog,score:sc});break}}if(H.length>=10)break}
 return {name,hits:H,list:S.date,note:'شباهت نام به معنای تحریم بودن نیست و تطابق قطعی نیاز به بررسی شناسه، نشانی و ملیت دارد.'}}

/* ---------- route-risk news monitoring (allow-listed feeds; content is data, never instructions) ---------- */
const SEV=[[/\b(closed|closure|shut(?:\s*down)?|suspend\w*|halt\w*|blocked|attack\w*|missile|drone\s*strike|seiz\w*|war\b|explosion|mined?)\b|بسته\s*شد|تعطیل|توقف|مسدود|حمله|موشک|توقیف|جنگ|انفجار/i,2],[/\b(strike|congest\w*|delay\w*|storm|cyclone|backlog|queue|diverts?|rerout\w*|disrupt\w*)\b|اعتصاب|ازدحام|تأخیر|تاخیر|طوفان|صف\s|اختلال/i,1],[/\b(reopen\w*|resum\w*|restor\w*|lifted)\b|بازگشایی|ازسرگیری|رفع\s*محدودیت/i,-2]];
const CLOSE=/\b(closed|closure|shut|blocked|suspended)\b|بسته\s*شد|مسدود|تعطیل/i;
const SURN=/\b(surcharge|GRI|PSS|EBS|war\s*risk|WRS|peak\s*season|emergency\s*bunker|rate\s*increase|rate\s*restoration)\b|سرشارژ|افزایش\s*نرخ\s*(کرایه|حمل)|نرخ\s*جدید\s*کرایه/i;
async function newsScan(ctx,{feeds,maxItems=40}={}){const C=agCfg();const F=(feeds&&feeds.length?feeds:C.feeds).slice(0,15);const items=[],errs=[];
 for(const url of F){let h='';try{h=new URL(url).hostname}catch(e){continue}if(!agAllowed(h)){errs.push(h+': خارج از فهرست مجاز');continue}
  try{const x=await getT(url,{timeout:20000});for(const it of rssItems(x).slice(0,maxItems))items.push({...it,feed:h})}catch(e){errs.push(h+': '+e.message.slice(0,80))}}
 const S=routesState();const sig=[],sur=[];let fresh=0;
 for(const it of items){const txt=(it.title+' . '+it.desc).slice(0,1500);const seen=q1("SELECT rowid FROM ag_mem WHERE kind='news' AND ref=?",it.link);it.fresh=!seen;if(!seen){fresh++;memAdd('news',it.link,it.title,it.desc,it.feed+(it.pub?' · '+it.pub:''))}
  const inj=agInj(txt);if(inj.length)(ctx.inj=ctx.inj||[]).push(...inj);
  let sev=0;for(const [re,w] of SEV)if(re.test(txt))sev+=w;
  for(const r of RTS)if(r.kw.test(txt)&&sev!==0)sig.push({route:r.id,name:r.n,sev,close:CLOSE.test(txt),reopen:sev<0,title:it.title.slice(0,240),url:it.link,feed:it.feed,pub:it.pub||'',fresh:!seen});
  if(SURN.test(txt))sur.push({title:it.title.slice(0,240),url:it.link,feed:it.feed,pub:it.pub||'',carrier:(txt.match(CARRIERS)||[])[1]||'',fresh:!seen})}
 const props=[];for(const r of RTS){const L=sig.filter(s=>s.route===r.id);if(!L.length)continue;const cur=(S.st[r.id]||{}).status||'open';const neg=L.filter(s=>s.sev>=2),pos=L.filter(s=>s.reopen);const feedsN=new Set(neg.map(s=>s.feed)).size;
  let to=null;if(neg.length){to=neg.filter(s=>s.close).length>=2&&feedsN>=2?'closed':'caution'}else if(pos.length&&cur!=='open')to='open';
  if(to&&to!==cur&&!(cur==='closed'&&to==='caution'))props.push({route:r.id,name:r.n,from:cur,to,evidence:(neg.length?neg:pos).slice(0,4)})}
 return {feeds:F.length,items:items.length,list:items.slice(0,80).map(it=>({title:String(it.title||'').slice(0,240),desc:String(it.desc||'').replace(/<[^>]+>/g,' ').slice(0,300),url:it.link,feed:it.feed,pub:it.pub||'',fresh:!!it.fresh})),fresh,errors:errs,signals:sig.slice(0,60),surcharges:sur.slice(0,30),proposals:props,sources:[...sig,...sur].slice(0,20).map(s=>({kind:'news',ref:s.url,title:s.title,url:s.url,ts:s.pub,feed:s.feed}))}}
