
/* ---------- tool definitions (the same registry serves agents, the approval queue and the MCP server) ---------- */
const RTEN={'sea-bnd':'Direct sea to Bandar Abbas (Shahid Rajaee) + road','sea-jea':'Sea via Jebel Ali transshipment → Bandar Abbas + road','sea-chb':'Sea to Chabahar + road','rail-kz':'Rail China–Kazakhstan–Turkmenistan → Sarakhs/Incheh Borun','road-tir':'Road (TIR) Kashgar–Kyrgyzstan–Uzbekistan–Turkmenistan → Sarakhs','casp':'Rail to Aktau + Caspian vessel → Anzali/Amirabad'};
const pubBase0=()=>(CFG.publicUrl||('http://'+(CFG.host==='0.0.0.0'?'localhost':CFG.host)+':'+CFG.port)).replace(/\/$/,'');
function rfqCore(b,uname){const id='RFQ-'+Date.now().toString(36).toUpperCase()+crypto.randomBytes(2).toString('hex').toUpperCase();const days=Math.min(60,Math.max(1,+b.validDays||CFG.live.rfq.days));
 run('INSERT INTO rfq(id,title,text,route,model,days,created,expires,by) VALUES(?,?,?,?,?,?,?,?,?)',id,String(b.title||'RFQ').slice(0,200),String(b.text).slice(0,20000),String(b.route||'').slice(0,200),+b.model||null,+b.days||null,Date.now(),Date.now()+days*864e5,uname);
 const base=pubBase0();const mk=(vendor,email)=>{const t=crypto.randomBytes(16).toString('base64url');run('INSERT INTO rfq_inv(token,rfq,vendor,email) VALUES(?,?,?,?)',t,id,vendor,email);return {name:vendor,email,url:base+'/q/'+t,token:t}};
 const open=mk(null,null);const inv=(Array.isArray(b.recipients)?b.recipients:[]).slice(0,50).filter(r=>r&&r.email&&/@/.test(r.email)).map(r=>mk(String(r.name||r.email).slice(0,120),String(r.email).slice(0,160)));let emailed=0;
 if(CHANNELS.email()){for(const i of inv){enqueue('rfq.sent','email',i.email,`${b.title||'Request for Quotation'}\nDear ${i.name},\n\n${b.text}\n\n————————\nثبت آنلاین پیشنهاد قیمت / Submit your quotation online:\n${i.url}\n`);run('UPDATE rfq_inv SET sent=? WHERE token=?',Date.now(),i.token);emailed++}dispatch().catch(()=>{})}
 audit(uname,'','rfq.create','rfq',id,{recipients:inv.length,emailed,via:'agent'});return {id,open:open.url,invites:inv.map(({token,...x})=>x),emailed,smtp:CHANNELS.email()}}
const shipsAll=()=>{const S=kvGet('ifa-ship');return Array.isArray(S)?S:[]};
function shipBrief(s){const ms=s.ms||[];const done=ms.filter(m=>m.act!=null);const nx=ms.find(m=>m.act==null);return {id:s.id,ref:s.ref,name:s.name||'',ctr:s.ctr||'',customer:s.cust||s.customer||'',last:done.length?{n:done[done.length-1].n,at:done[done.length-1].act}:null,next:nx?{n:nx.n,planned:nx.pl||null,overdueH:nx.pl&&Date.now()>nx.pl?Math.round((Date.now()-nx.pl)/3600e3):0}:null,progress:ms.length?Math.round(done.length/ms.length*100):null}}
function overdueAll(){const now=Date.now(),O=[];for(const s of shipsAll()){const b=shipBrief(s);if(b.next&&b.next.overdueH>=(CFG.scheduler.overdueHours||24))O.push({kind:'overdue',ref:s.ref,msg:'مرحلهٔ «'+b.next.n+'» محمولهٔ '+s.ref+' '+b.next.overdueH+' ساعت عقب است',sev:'high',ship:b})}
 for(const a of (kvGet('ifa-dd-alerts')||[])){const d=Math.round((Date.parse(a.freeEnd)-Date.parse(agToday()))/864e5);if(d>=0&&d<=3)O.push({kind:'freetime',ref:a.ref||a.ctr,msg:'پایان زمان آزاد کانتینر '+(a.ctr||'')+' ('+(a.ref||'')+') تا '+d+' روز دیگر'+(a.perDay?' · '+a.perDay+' در روز پس از آن':''),sev:d<=1?'high':'med'})}
 for(const b of (kvGet('ifa-bkg')||[])){if(['ship','canc'].includes(b.st))continue;for(const [f,n] of [['si','SI'],['vgm','VGM'],['cy','CY'],['doc','اسناد']]){const t=Date.parse(b[f]);if(t&&t>now&&t-now<36*3600e3)O.push({kind:'cutoff',ref:b.no||b.id,msg:'کات‌آف '+n+' رزرو '+(b.no||b.id)+' در '+Math.round((t-now)/3600e3)+' ساعت آینده',sev:'high'})}}return O}
const toolSum=(n,a)=>({rfq_send:()=>'ارسال '+((a.items||[]).length||1)+' استعلام (RFQ) به '+(a.items||[a]).reduce((s,i)=>s+((i.recipients||[]).length),0)+' گیرنده: '+(a.items||[a]).map(i=>i.title).join(' | ')}[n]||(()=>''))();
tool('rates_search',{d:'جستجوی بانک نرخ (نرخ دستی، پنل شرکا، پاسخ‌های RFQ) برای یک مسیر',keys:['ifa-rates'],args:{pol:['string','بندر/شهر مبدأ'],pod:['string','مقصد'],eq:['string','نوع کانتینر مثل 40HC'],mode:['string','sea/rail/road'],days:['number','بازهٔ روز (پیش‌فرض ۱۸۰)']},
 run:a=>{const L=ratesAll().filter(r=>laneMatch(r,{pol:a.pol,pod:a.pod,eq:a.eq,mode:a.mode,days:a.days||180})).sort((x,y)=>String(y.date).localeCompare(x.date)).slice(0,40);return {n:L.length,median:median(L.map(r=>r.usd).filter(Boolean)),rates:L.map(({polC,podC,usdK,...r})=>r),sources:L.slice(0,10).map(rSrc)}}});
tool('rates_benchmark',{d:'سنجش یک مبلغ با میانهٔ نرخ‌های واقعی همان مسیر',cls:'compute',keys:['ifa-rates'],args:{amount:['number','مبلغ',1],cur:['string','ارز'],pol:['string','مبدأ'],pod:['string','مقصد'],eq:['string','کانتینر']},run:a=>{const u=usdOf(a.amount,a.cur||'USD');return {usd:u&&Math.round(u),...benchOne(u||0,a)}}});
tool('rates_anomalies',{d:'ناهنجاری‌های بانک نرخ (MAD z>3.5) و نرخ‌های منقضی‌شده',cls:'compute',keys:['ifa-rates'],run:()=>{const r=anomalies();return {...r,sources:r.outliers.slice(0,10).map(o=>o.source)}}});
tool('market_indices',{d:'آخرین مقادیر شاخص‌های بازار (CCFI، SCFI، WCI، FBX، سوخت) با تغییر هفتگی/ماهانه',run:()=>{const R=weeklyReport();return {rows:R.rows,alerts:R.alerts,sources:R.rows.slice(0,12).map(r=>({kind:'index',ref:r.series+'|'+r.line,title:r.name+' = '+r.value+' ('+r.date+')',view:'mkt',ts:r.date}))}}});
tool('market_forecast',{d:'پیش‌بینی کوتاه‌مدت یک شاخص با بازهٔ ۸۰٪',cls:'compute',args:{series:['string','ccfi/scfi/wci/fbx/bunker'],line:['string','خط شاخص، مثل PERSIAN_GULF_RED_SEA'],weeks:['number','افق (هفته، ≤۸)']},run:a=>idxForecast(a.series||'ccfi',a.line||'PERSIAN_GULF_RED_SEA',Math.min(8,+a.weeks||4))});
tool('fx_get',{d:'نرخ ارز رسمی و دلار آزاد (کش سرور)',run:()=>{const F=fxNow();return {freeUSD:F.free,rates:{EUR:F.R.EUR,AED:F.R.AED,CNY:F.R.CNY,IRR:F.R.IRR},date:F.date,sources:[{kind:'fx',ref:'fx',title:'نرخ ارز سرور'+(F.free?' · دلار آزاد '+Math.round(F.free)+' ریال':''),view:'mkt'}]}}});
tool('domestic_tariff',{d:'شاخص رسمی تن-کیلومتر حمل جاده‌ای داخلی و کرایهٔ کف یک مسیر',args:{km:['number','فاصلهٔ جاده‌ای'],tons:['number','تناژ']},run:a=>{const V=dtCurrent();const o={tkm:V.tkm,from:V.from,source:V.src,url:V.url||null,history:dtVersions().map(v=>({from:v.from,tkm:v.tkm}))};if(+a.km>0){const d=domPerTon(+a.km);o.perTonIRR=Math.round(d.rial);o.totalIRR=Math.round(d.rial*(+a.tons||24))}return {...o,sources:[{kind:'tariff',ref:V.from,title:'شاخص '+V.tkm+' ریال/تن-km از '+V.from+' — '+V.src,url:V.url||undefined,view:'dom'}]}}});
tool('routes_list',{d:'فهرست کریدورهای چین→ایران با وضعیت فعلی (باز/احتیاط/بسته)، دلیل و منبع',run:()=>{const L=routesList();return {routes:L,sources:L.filter(r=>r.source).map(r=>({kind:'route',ref:r.id,title:r.name+': '+r.statusFa+' — '+r.reason,url:/^https?:/.test(r.source)?r.source:undefined}))}}});
tool('routes_compare',{d:'مقایسهٔ مسیرها: کرایه (نرخ واقعی یا پیش‌فرض)، حمل داخلی رسمی، زمان، هزینهٔ نگهداری موجودی، ریسک و مهلت؛ پشتیبانی از سناریو',cls:'compute',args:{pol:['string','مبدأ (مثل Ningbo)'],dest:['string','مقصد نهایی در ایران'],eq:['string','40HC/20GP'],qty:['number','تعداد'],value:['number','ارزش کالا (دلار)'],deadlineDays:['number','مهلت تحویل (روز)'],weightT:['number','وزن هر کانتینر (تن)'],scenario:['object','سناریو: {closed:[ids], freightPct:{sea:10}, fxPct:20, delay:{id:5}}']},run:a=>compareRoutes(a)});
tool('routes_set_status',{d:'تغییر وضعیت یک مسیر (با دلیل و منبع)',cls:'write',keys:['ifa-routes'],approvers:['admin','manager','ops'],args:{id:['string','شناسهٔ مسیر',1],status:['string','open/caution/closed',1],reason:['string','دلیل',1],source:['string','پیوند منبع',1]},
 sum:a=>'تغییر وضعیت مسیر «'+((RTS.find(r=>r.id===a.id)||{}).n||a.id)+'» به «'+(RSTFA[a.status]||a.status)+'» — '+(a.reason||''),dedupe:a=>'route|'+a.id+'|'+a.status,
 run:(a,ctx)=>{if(!a.source)throw E(400,'منبع تغییر وضعیت لازم است');const r=routeSet(a.id,a.status,a.reason,a.source,ctx.approver||ctx.actor.username);return {ok:true,id:a.id,status:a.status,undo:{id:a.id,prev:r.prev}}},
 undo:(u,who)=>routeSet(u.id,u.prev.status||'open',(u.prev.reason||'')+' (بازگردانی)',u.prev.source||'revert',who)});
tool('memory_search',{d:'جستجو در حافظهٔ سازمانی (تصمیم‌ها، خبرها، ایمیل‌ها، نتیجهٔ کارها، اسناد)',args:{q:['string','عبارت جستجو',1],kind:['string','نوع (news/task/decision/mail/quote/doc/report)']},run:a=>{const R=memSearch(a.q,{kind:a.kind});return {hits:R,sources:R.map(m=>({kind:m.kind,ref:m.ref,title:m.title,url:/^https?:/.test(m.ref)?m.ref:undefined,ts:m.ts}))}}});
tool('team_notify',{d:'هشدار داخلی به تیم از راه قواعد اعلان (بله/تلگرام/پیامک/وب‌هوک تیم)',cls:'notify',args:{event:['string','نوع رویداد (agent.alert/agent.report/risk.signal/surcharge.notice)'],text:['string','متن',1],ref:['string','مرجع'],dedupe:['string','کلید جلوگیری از تکرار']},
 run:(a,ctx)=>{const ev=/^(agent\.alert|agent\.report|risk\.signal|surcharge\.notice|quote\.benchmarked)$/.test(a.event)?a.event:'agent.alert';const n=_fire0(ev,{ref:a.ref||'',agent:ctx.ag.n,text:String(a.text||'').replace(/<[^>]+>/g,'').slice(0,1500)},a.dedupe?String(a.dedupe):null);dispatch().catch(()=>{});return {queued:n,event:ev}}});
tool('report_daily',{d:'گزارش روزانهٔ مدیر: شاخص‌ها، ارز، نرخ‌های تازه، ناهنجاری، تأییدهای معطل، محموله‌های عقب‌افتاده، وضعیت مسیرها',cls:'compute',run:()=>dailyReport()});
tool('report_weekly',{d:'گزارش هفتگی بازار',cls:'compute',run:()=>{const R=weeklyReport();return {week:R.week,text:R.text,rows:R.rows,lanes:R.lanes,sources:R.rows.slice(0,10).map(r=>({kind:'index',ref:r.series+'|'+r.line,title:r.name+' '+r.date,view:'mkt'}))}}});
tool('discover_forwarders',{d:'کشف فورواردرهای جدید از فرستندگان ایمیل نرخ، پاسخ‌دهندگان RFQ و بانک نرخ که هنوز شریک ثبت‌شده نیستند',run:()=>{const P=q('SELECT name,email FROM partners WHERE revoked=0');const known=new Set(P.flatMap(p=>[nk(p.name),String(p.email||'').toLowerCase().split('@')[1]||'']).filter(Boolean));const C=new Map();const add=(name,email,why)=>{const d=String(email||'').toLowerCase().split('@')[1]||'';const k=nk(name)||d;if(!k||known.has(nk(name))||(d&&known.has(d)))return;const o=C.get(k)||{name,email:email||'',why:[]};o.why.push(why);C.set(k,o)};
 for(const m of q('SELECT sender,subject FROM inbox ORDER BY id DESC LIMIT 300')){const e=(String(m.sender).match(/[\w.+-]+@[\w-]+\.[\w.]+/)||[''])[0];add(String(m.sender).replace(/<.*>/,'').replace(/"/g,'').trim()||e,e,'ایمیل نرخ: '+String(m.subject).slice(0,60))}
 for(const r of q('SELECT DISTINCT vendor,contact FROM rfq_resp'))add(r.vendor,(String(r.contact||'').match(/[\w.+-]+@[\w-]+\.[\w.]+/)||[''])[0],'پاسخ به RFQ');for(const r of ratesAll().slice(0,500))if(r.vendor)add(r.vendor,'','بانک نرخ');
 const L=[...C.values()].slice(0,40);return {candidates:L,note:'جستجوی وب عمومی برای فورواردر جدید به API جستجو نیاز دارد که پیکربندی نشده است؛ این فهرست از دادهٔ خود شماست.',sources:[{kind:'data',ref:'inbox+rfq+rates',title:'صندوق ایمیل نرخ، پاسخ‌های RFQ و بانک نرخ'}]}}});
tool('rfq_list',{d:'فهرست استعلام‌ها با دعوت‌ها و پاسخ‌ها',perm:'rfq.send',run:a=>{const L=q('SELECT * FROM rfq ORDER BY created DESC LIMIT 30').map(r=>({id:r.id,title:r.title,route:r.route,created:r.created,expires:r.expires,invites:q('SELECT vendor,sent,opened,responded FROM rfq_inv WHERE rfq=? AND vendor IS NOT NULL',r.id),responses:q('SELECT vendor,price,cur,usd,days,free,valid FROM rfq_resp WHERE rfq=? ORDER BY usd',r.id)}));return {rfqs:L,sources:L.slice(0,10).map(r=>({kind:'rfq',ref:r.id,title:r.title,view:'rfq'}))}}});
tool('rfq_responses',{d:'پاسخ‌های دریافتی یک یا چند RFQ',perm:'rfq.send',args:{rfqs:['array','شناسه‌های RFQ',1,{type:'string'}]},run:a=>{const ids=(a.rfqs||[]).slice(0,20);const R=ids.flatMap(id=>q('SELECT r.*,f.route,f.title FROM rfq_resp r JOIN rfq f ON f.id=r.rfq WHERE r.rfq=?',id));return {responses:R.map(({ip,token,...r})=>r),sources:R.map(r=>({kind:'rfq',ref:r.rfq+'/'+r.id,title:r.vendor+' · '+Math.round(r.usd)+'$ · '+r.rfq,view:'rfq'}))}}});
tool('approvals_list',{d:'تأییدهای در انتظار',run:()=>{const L=q("SELECT id,agent,tool,summary,created FROM ag_appr WHERE status='pending' ORDER BY id DESC LIMIT 50");return {pending:L,sources:L.map(a=>({kind:'approval',ref:'#'+a.id,title:a.summary,view:'agt'}))}}});
tool('shipments_list',{d:'محموله‌ها و آخرین/بعدی مرحله (یا یک محموله با مرجع)',keys:['ifa-ship'],args:{ref:['string','مرجع پرونده/محموله/کانتینر']},run:a=>{let S=shipsAll();if(a.ref){const k=nk(a.ref);S=S.filter(s=>[s.ref,s.name,s.ctr,s.bl,s.job].some(x=>x&&nk(x).includes(k)))}const L=S.slice(0,50).map(shipBrief);return {n:L.length,shipments:L,sources:L.slice(0,10).map(s=>({kind:'shipment',ref:s.ref,title:'محمولهٔ '+s.ref+(s.next?' · بعدی: '+s.next.n:''),view:'track'}))}}});
tool('shipments_overdue',{d:'مراحل عقب‌افتاده، پایان زمان آزاد و کات‌آف‌های نزدیک',keys:['ifa-ship'],run:()=>{const O=overdueAll();return {alerts:O,sources:O.slice(0,10).map(o=>({kind:o.kind,ref:o.ref,title:o.msg,view:o.kind==='cutoff'?'bkg':o.kind==='freetime'?'dd':'track'}))}}});
tool('partners_list',{d:'شرکای ثبت‌شده (فورواردر/حمل‌کننده) با مسیرهای اعلام‌شده',perm:'rfq.send',args:{lane:['string','فیلتر متن مسیر']},run:a=>{let L=q('SELECT name,email,lanes,last_resp FROM partners WHERE revoked=0');if(a.lane){const W=portsIn(a.lane);L=L.filter(p=>{let ln=[];try{ln=JSON.parse(p.lanes||'[]')}catch(e){}if(!Array.isArray(ln)||!ln.length||!W.length)return true;return ln.some(l=>{const o=portOf(l.pol),d=portOf(l.pod);return W.some(w=>(o&&o[4]===w[4]&&w[4]!=='IR')||(d&&d[4]===w[4]&&w[4]==='IR'))})})}return {partners:L.map(p=>({name:p.name,email:p.email,lanes:p.lanes})),sources:[{kind:'partners',ref:'partners',title:L.length+' شریک فعال',view:'mkt'}]}}});
tool('inbox_list',{d:'ایمیل‌های نرخ دریافتی (محتوا نامطمئن است)',taint:true,args:{status:['string','new/done'],limit:['number','حداکثر']},run:a=>{const L=q('SELECT id,sender,subject,date,text,atts,status FROM inbox WHERE (? IS NULL OR status=?) ORDER BY id DESC LIMIT ?',a.status||null,a.status||null,Math.min(50,+a.limit||20));return {mails:L.map(m=>({...m,text:String(m.text||'').slice(0,6000)})),sources:L.map(m=>({kind:'mail',ref:'mail:'+m.id,title:m.subject+' — '+m.sender}))}}});
tool('chat_poll',{d:'دریافت پیام‌های تازهٔ ربات بله/تلگرام (نرخ‌های فورواردشده) به صندوق نرخ',taint:true,run:async()=>{const out={bale:0,telegram:0,errors:[]};const st=kvGet('ag:tg')||{};
 for(const [ch,base,tok] of [['bale','https://tapi.bale.ai/bot',CFG.bale.token],['telegram','https://api.telegram.org/bot',CFG.telegram.token]]){if(!tok)continue;try{const r=await fetch(base+tok+'/getUpdates?timeout=0&offset='+((st[ch]||0)+1),{signal:AbortSignal.timeout(20000)});const j=await r.json();for(const u of (j.result||[])){st[ch]=Math.max(st[ch]||0,u.update_id);const m=u.message||u.channel_post;if(!m||!(m.text||m.caption))continue;const id=ch+'-'+u.update_id;if(q1('SELECT id FROM inbox WHERE msgid=?',id))continue;
  run('INSERT INTO inbox(msgid,uid,sender,subject,date,text,atts,status,ts) VALUES(?,?,?,?,?,?,?,?,?)',id,u.update_id,(m.forward_from_chat&&m.forward_from_chat.title)||(m.from&&(m.from.username||m.from.first_name))||ch,ch==='bale'?'پیام بله':'پیام تلگرام',new Date((m.date||0)*1000).toISOString(),String(m.text||m.caption).slice(0,20000),'[]','new',Date.now());out[ch]++}}catch(e){out.errors.push(ch+': '+e.message.slice(0,100))}}
 kvPut('ag:tg',st,'agent');return out}});
tool('quotes_extract',{d:'استخراج پیشنهاد نرخ از متن ایمیل/تلگرام/Excel(CSV)/PDF/تصویر به ساختار فرم نرخ',cls:'compute',taint:true,args:{text:['string','متن'],vendor:['string','فرستنده'],ref:['string','مرجع منبع'],file:['object','{name,mime,data(base64)} برای PDF یا تصویر'],llm:['boolean','استفاده از مدل زبانی برای بهبود']},run:(a,ctx)=>quotesExtract(a,ctx)});
tool('quotes_check',{d:'کنترل پیشنهادها: اعتبار، سقف WRS، نسبت ۴۰/۲۰، انحراف از بازار، زمان در برابر مهلت، روز آزاد، غربال تحریم',cls:'compute',args:{quotes:['array','پیشنهادها',1,{type:'object'}],deadlineDays:['number','مهلت'],pol:['string','مبدأ'],pod:['string','مقصد'],eq:['string','کانتینر']},run:a=>quotesCheck(a.quotes||[],a)});
tool('rates_add',{d:'افزودن نرخ‌های استخراج‌شده به بانک نرخ (با منبع)',cls:'write',keys:['ifa-rates'],approvers:['admin','manager','sales','finance','ops'],args:{quotes:['array','نرخ‌ها',1,{type:'object'}],source:['string','منبع',1],ref:['string','مرجع']},
 sum:a=>'افزودن '+(a.quotes||[]).length+' نرخ به بانک نرخ از «'+String(a.source||'').slice(0,80)+'»: '+(a.quotes||[]).slice(0,3).map(x=>x.pol+'→'+x.pod+' '+x.eq+' '+x.amt+' '+x.cur).join('، '),dedupe:a=>a.ref?'radd|'+a.ref:null,
 run:(a,ctx)=>{const A0=kvGet('ifa-rates');const A=Array.isArray(A0)?A0:[];const ids=[];for(const x of (a.quotes||[]).slice(0,50)){if(!(+x.amt>0))continue;const id='AG-'+Date.now().toString(36)+Math.random().toString(36).slice(2,6);ids.push(id);A.unshift({id,mode:x.mode||'sea',vendor:String(x.vendor||x.carrier||'').slice(0,80),pol:x.pol||'',pod:x.pod||'',eq:x.eq||'',amt:+x.amt,cur:x.cur||'USD',from:agToday(),to:x.valid||'',src:'agent',incl:(x.surcharges||[]).map(s=>s.code+(s.amt?' '+s.amt:'')).join(', '),note:[String(a.source||'').slice(0,120),x.days?'T/T '+x.days+'d':'',x.free?'free '+x.free+'d':''].filter(Boolean).join(' · '),t:Date.now()})}
  kvPut('ifa-rates',A,ctx.approver||ctx.actor.username);if(a.ref&&/^mail:\d+$/.test(a.ref))run("UPDATE inbox SET status='done' WHERE id=?",+a.ref.slice(5));_fire0('rates.imported',{n:ids.length,src:'agent'});return {added:ids.length,ids,undo:{ids}}},
 undo:u=>{const A0=kvGet('ifa-rates');const A=(Array.isArray(A0)?A0:[]).filter(r=>!u.ids.includes(r.id));kvPut('ifa-rates',A,'revert');return {removed:u.ids.length}}});
tool('rfq_draft',{d:'پیش‌نویس دوزبانهٔ استعلام برای یک مسیر',cls:'compute',args:{route:['string','شناسهٔ مسیر'],pol:['string','مبدأ'],dest:['string','مقصد'],eq:['string','کانتینر'],qty:['number','تعداد'],commodity:['string','کالا'],incoterm:['string','اینکوترمز'],ready:['string','آمادگی بار'],deadlineDays:['number','مهلت تحویل']},run:a=>rfqDraft(a)});
tool('rfq_send',{d:'ارسال استعلام(ها) به فورواردرها با پیوند ثبت آنلاین پیشنهاد',cls:'external',perm:'rfq.send',approvers:['admin','manager','ops','sales'],args:{items:['array','[{title,text,route,model,days,recipients:[{name,email}]}]',1,{type:'object'}],plan:['number','شناسهٔ کار برنامه']},sum:a=>toolSum('rfq_send',a),dedupe:a=>a.plan?'rfq|'+a.plan:null,
 run:(a,ctx)=>{const R=(a.items||[]).slice(0,6).map(i=>({route:i.routeId||i.route,...rfqCore(i,ctx.approver||ctx.actor.username)}));if(a.plan)agEnqueue('procurement','collect',{plan:a.plan,rfqs:R.map(r=>r.id)},{by:ctx.approver,trig:'rfq.sent',due:Date.now()+24*3600e3});return {rfqs:R,undo:{rfqs:R.map(r=>r.id)}}},
 undo:u=>{for(const id of u.rfqs)run('UPDATE rfq SET expires=? WHERE id=?',Date.now(),id);return {expired:u.rfqs.length,note:'پیوندهای ثبت پیشنهاد بسته شد؛ ایمیل‌های ارسال‌شده قابل برگشت نیستند'}}});
tool('negotiate_draft',{d:'پیش‌نویس مذاکره با هدف قیمتی مستند به میانهٔ بازار و بهترین پیشنهاد رقیب',cls:'compute',args:{vendor:['string','فورواردر',1],usd:['number','پیشنهاد فعلی',1],target:['number','هدف'],median:['number','میانهٔ بازار'],best:['number','بهترین پیشنهاد رقیب'],rfq:['string','RFQ'],issues:['array','مشکلات',0,{type:'string'}]},run:a=>negDraft(a)});
tool('negotiate_send',{d:'ارسال ایمیل مذاکره به فورواردر',cls:'external',perm:'rfq.send',approvers:['admin','manager','sales'],args:{to:['string','ایمیل',1],subject:['string','موضوع',1],text:['string','متن',1],vendor:['string','فورواردر']},sum:a=>'ارسال ایمیل مذاکره به '+(a.vendor||'')+' <'+a.to+'>: '+a.subject,dedupe:a=>'neg|'+a.to+'|'+a.subject,
 run:a=>{if(!CHANNELS.email())throw E(501,'SMTP پیکربندی نشده است');if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(a.to||''))throw E(400,'ایمیل نامعتبر');enqueue('agent.negotiate','email',a.to,(a.subject||'')+'\n'+a.text);dispatch().catch(()=>{});return {queued:1}}});
tool('booking_create',{d:'ثبت درخواست رزرو (تعهد) نزد فورواردر برنده',cls:'commit',approvers:['admin','manager','ops'],args:{vendor:['string','فورواردر',1],route:['string','مسیر',1],pol:['string','مبدأ'],pod:['string','مقصد'],eq:['string','کانتینر'],qty:['number','تعداد'],usd:['number','مبلغ هر واحد'],rfq:['string','RFQ'],etd:['string','ETD']},
 sum:a=>'ثبت درخواست رزرو '+(a.qty||1)+'×'+(a.eq||'')+' نزد '+a.vendor+' روی مسیر «'+((RTS.find(r=>r.id===a.route)||{}).n||a.route)+'» به مبلغ '+a.usd+'$ هر واحد',dedupe:a=>'bkg|'+a.rfq+'|'+a.vendor,
 run:(a,ctx)=>{const B0=kvGet('ifa-bkg');const B=Array.isArray(B0)?B0:[];const id='BK'+Date.now().toString(36);B.unshift({id,no:'',carrier:a.vendor,vessel:'',voy:'',pol:a.pol||'',pod:a.pod||'BND',eq:a.eq||'40HC',qty:+a.qty||1,etd:a.etd||'',cy:'',si:'',vgm:'',doc:'',job:'',st:'req',note:'درخواست رزرو پس از تأیید '+(ctx.approver||'')+' · '+(a.rfq||'')+' · '+a.usd+'$/واحد · مسیر '+a.route});kvPut('ifa-bkg',B,ctx.approver||ctx.actor.username);
  agEnqueue('tracker','check',{booking:id},{by:ctx.approver,trig:'booking'});agEnqueue('docs','check',{booking:id,docs:[]},{by:ctx.approver,trig:'booking'});return {booking:id,undo:{id}}},
 undo:u=>{const B0=kvGet('ifa-bkg');const B=(Array.isArray(B0)?B0:[]).map(b=>b.id===u.id?{...b,st:'canc',note:(b.note||'')+' · لغو (بازگردانی)'}:b);kvPut('ifa-bkg',B,'revert');return {cancelled:u.id}}});
tool('customer_reply',{d:'ارسال پاسخ/به‌روزرسانی به مشتری (ایمیل، بله، تلگرام یا پیامک)',cls:'external',perm:'notify.send',approvers:['admin','manager','ops','sales'],args:{to:['string','گیرنده',1],channel:['string','email/bale/telegram/sms',1],text:['string','متن',1],ref:['string','مرجع']},sum:a=>'ارسال پیام به مشتری ('+a.channel+' → '+a.to+'): '+String(a.text||'').slice(0,120),dedupe:a=>'cr|'+a.to+'|'+sha(String(a.text)).slice(0,10),
 run:a=>{const ch=['email','bale','telegram','sms'].includes(a.channel)?a.channel:'email';if(!CHANNELS[ch]||!CHANNELS[ch]())throw E(501,'کانال «'+ch+'» پیکربندی نشده است');enqueue('agent.customer',ch,a.to,a.text);dispatch().catch(()=>{});return {queued:1,channel:ch}}});
tool('payment_request',{d:'ثبت درخواست پرداخت برای تأیید مالی (عامل هرگز پرداخت انجام نمی‌دهد)',cls:'money',keys:['ifa-payq'],approvers:['admin','finance'],fourEyes:true,args:{vendor:['string','ذی‌نفع',1],amount:['number','مبلغ',1],cur:['string','ارز',1],ref:['string','صورتحساب/پرونده',1],reason:['string','شرح']},
 sum:a=>'درخواست پرداخت '+a.amount+' '+a.cur+' به '+a.vendor+' بابت '+a.ref,dedupe:a=>'pay|'+a.vendor+'|'+a.ref,
 run:(a,ctx)=>{const P0=kvGet('ifa-payq');const P=Array.isArray(P0)?P0:[];const id='PQ'+Date.now().toString(36);P.unshift({id,vendor:a.vendor,amount:+a.amount,cur:a.cur,ref:a.ref,reason:a.reason||'',st:'approved',approvedBy:ctx.approver,ts:Date.now(),note:'پرداخت باید توسط کاربر مالی در بانک انجام و ثبت شود'});kvPut('ifa-payq',P,ctx.approver);_fire0('payment.approved',{ref:a.ref,vendor:a.vendor,amount:a.amount,cur:a.cur,by:ctx.approver});return {payq:id,undo:{id}}},
 undo:u=>{const P0=kvGet('ifa-payq');kvPut('ifa-payq',(Array.isArray(P0)?P0:[]).map(p=>p.id===u.id?{...p,st:'void'}:p),'revert');return {voided:u.id}}});
tool('sanctions_screen',{d:'غربال نام شرکت/شخص/کشتی با فهرست‌های OFAC، UN و EU (نسخهٔ محلی)',cls:'compute',args:{names:['array','نام‌ها',1,{type:'string'}]},run:a=>{const R=(a.names||[]).slice(0,30).map(sanctScreen);return {results:R,sources:[{kind:'sanctions',ref:'lists',title:'فهرست‌های تحریم'+(R[0]&&R[0].list?' (به‌روزرسانی '+R[0].list+')':'')}]}}});
tool('docs_check',{d:'کنترل سازگاری اسناد حمل (فاکتور، پکینگ، بارنامه، گواهی مبدأ)',cls:'compute',args:{docs:['array','[{type:invoice|packing|bl|co|decl, name, text, fields}]',1,{type:'object'}]},run:a=>{const r=docsCheck(a.docs);return {...r,sources:r.docs.map(d=>({kind:'doc',ref:d.name,title:d.name}))}}});
tool('hs_suggest',{d:'پیشنهاد کد HS (۶ رقم) با درجهٔ اطمینان',cls:'compute',args:{desc:['string','شرح کالا',1]},run:a=>({...hsSuggest(a.desc),sources:[{kind:'hs',ref:'dict',title:'واژه‌نامهٔ داخلی سرفصل‌های HS (نسخهٔ ۲۰۲۲ سامانهٔ هماهنگ)'}]})});
tool('pdf_text',{d:'استخراج متن از PDF (بهترین تلاش؛ PDFهای اسکن‌شده متن ندارند)',cls:'compute',taint:true,args:{data:['string','PDF به base64',1]},run:a=>{const t=pdfText(Buffer.from(String(a.data||''),'base64'));return {chars:t.length,text:t.slice(0,30000),note:t.length<20?'متنی استخراج نشد (احتمالاً اسکن یا فونت کدگذاری‌شده)؛ از مدل دارای بینایی یا OCR استفاده کنید':''}}});
tool('invoice_reconcile',{d:'تطبیق صورتحساب حمل با پیشنهاد قیمت: کرایهٔ پایه، سرشارژ اعلام‌نشده، سقف WRS، تعداد، ارز، اعتبار',cls:'compute',args:{invoice:['object','{no,date,cur,text|lines:[{desc,amt,cur,qty}]}',1],quote:['object','{id}|{vendor,amt,cur,incl,surcharges,allin,valid}',1],qty:['number','تعداد'],wrsCap:['number','سقف WRS هر واحد']},run:a=>{const r=reconcile(a);return {...r,sources:[{kind:'invoice',ref:(a.invoice||{}).no||'invoice',title:'صورتحساب '+((a.invoice||{}).no||'')},...(r.quote.id?[{kind:'rate',ref:r.quote.id,title:'پیشنهاد '+r.quote.id,view:'rate'}]:[])]}}});
tool('tasks_review',{d:'بازبینی کیفیت کار عامل‌ها در یک بازهٔ زمانی',args:{hours:['number','بازه (ساعت)']},run:a=>qaReview(+a.hours||24)});
tool('news_scan',{d:'خواندن خبرهای منابع مجاز و استخراج سیگنال ریسک مسیر و اطلاعیهٔ سرشارژ',cls:'web',args:{feeds:['array','فیدهای RSS (باید در فهرست مجاز باشند)',0,{type:'string'}]},run:(a,ctx)=>newsScan(ctx,a)});
tool('web_fetch',{d:'خواندن متن یک صفحهٔ وب از دامنه‌های مجاز (محتوا نامطمئن است)',cls:'web',args:{url:['string','نشانی',1]},run:async(a,ctx)=>{const h=await getT(a.url,{timeout:20000});const t=htmlTxt(h).slice(0,12000);const inj=agInj(t);if(inj.length)(ctx.inj=ctx.inj||[]).push(...inj);return {url:a.url,text:t,injection:inj,sources:[{kind:'web',ref:a.url,title:a.url,url:a.url}]}}});
