
/* ---------- orchestrator: queue, runner, scheduler, event triggers ---------- */
const HUMAN={id:'human',n:'کاربر',level:0,role:'viewer',budget:{calls:1e6,tokens:400000,usd:5,steps:1e6,ext:0},tools:[]};
function agEnqueue(agent,kind,input,o={}){const a=AGENTS[agent];if(!a)throw E(400,'عامل ناشناخته');if(!a.kinds[kind])throw E(400,'نوع کار نامعتبر برای «'+a.n+'»');
 if(o.dedupe&&q1("SELECT id FROM ag_task WHERE agent=? AND kind=? AND status IN ('queued','running') AND trig=?",agent,kind,o.trig||''))return null;
 const title=a.kinds[kind]+(input&&input.title?' · '+String(input.title).slice(0,80):'');return Number(run('INSERT INTO ag_task(due,agent,kind,title,status,input,trig,parent,by,created) VALUES(?,?,?,?,?,?,?,?,?,?)',o.due||null,agent,kind,title,'queued',JSON.stringify(input||{}),o.trig||'manual',o.parent||null,o.by||'system',Date.now()).lastInsertRowid)}
const srcKey=s=>(s.kind||'')+'|'+(s.ref||s.url||s.title||'');
async function agRun(id){if(run("UPDATE ag_task SET status='running',started=? WHERE id=? AND status='queued'",Date.now(),id).changes!==1)return q1('SELECT * FROM ag_task WHERE id=?',id);
 const T=q1('SELECT * FROM ag_task WHERE id=?',id);const ag=AGENTS[T.agent];const C=agCfg();const fin=(st,o)=>{run('UPDATE ag_task SET status=?,output=?,sources=?,flags=?,cost=?,tokens=?,calls=?,model=?,finished=?,err=?,tainted=? WHERE id=?',st,o.out?clip(o.out,60000):null,JSON.stringify(o.src||[]),JSON.stringify(o.flags||{}),o.cost||0,o.tokens||0,o.calls||0,o.model||null,Date.now(),o.err||null,o.tainted?1:0,id);return q1('SELECT * FROM ag_task WHERE id=?',id)};
 if(C.kill)return fin('blocked',{err:'کلید توقف اضطراری فعال است'});if(C.paused[ag.id])return fin('blocked',{err:'عامل متوقف است'});
 agUse(ag.id,{tasks:1});const ctx={task:id,ag,actor:agActor(ag),sources:[],steps:0,tokens:0,cost:0,inj:[],by:T.by,approvals:[]};let input={};try{input=JSON.parse(T.input||'{}')}catch(e){}
 try{const pb=(PB[ag.id]||{})[T.kind];let out;if(pb)out=await pb(ctx,input);else if(T.kind==='ask')out=await agAsk(ctx,String(input.q||input.question||''));else throw new Error('برای این نوع کار دستورالعملی تعریف نشده است');
  const seen=new Set();const src=[...(out.sources||[]),...ctx.sources].filter(s=>s&&!seen.has(srcKey(s))&&seen.add(srcKey(s))).slice(0,40);delete out.sources;
  const summ=String(out.summary||out.answer||'');const flags={tainted:!!ctx.tainted,inj:[...new Set(ctx.inj)].slice(0,10),denied:ctx.denied||0,approvals:ctx.approvals};
  if(/\d{2,}/.test(enDig(summ).replace(/\d{4}-\d\d-\d\d/g,''))&&!src.length)return fin('rejected',{out,flags,err:'خروجی شامل عدد است ولی منبعی ندارد؛ طبق سیاست رد شد',cost:ctx.cost,tokens:ctx.tokens,calls:ctx.steps,model:ctx.model,tainted:ctx.tainted});
  memAdd('task',String(id),ag.n+' · '+(ag.kinds[T.kind]||T.kind),summ,ag.id);
  const R=fin('done',{out,src,flags,cost:ctx.cost,tokens:ctx.tokens,calls:ctx.steps,model:ctx.model,tainted:ctx.tainted});_fire0('agent.done',{ref:'#'+id,agent:ag.n,kind:ag.kinds[T.kind]||T.kind,summary:summ.slice(0,400)},'agd|'+id);return R}
 catch(e){return fin('failed',{err:String(e.message||e).slice(0,500),flags:{denied:ctx.denied||0,policy:!!e.policy},cost:ctx.cost,tokens:ctx.tokens,calls:ctx.steps,model:ctx.model,tainted:ctx.tainted})}}
let AGBUSY=false;async function agWorker(){if(AGBUSY)return;AGBUSY=true;try{for(let n=0;n<5;n++){const t=q1("SELECT id FROM ag_task WHERE status='queued' AND (due IS NULL OR due<=?) ORDER BY id LIMIT 1",Date.now());if(!t)break;await agRun(t.id)}}catch(e){console.error('agents',e.message)}finally{AGBUSY=false}}
function agTick(){const C=agCfg();run("UPDATE ag_appr SET status='expired' WHERE status='pending' AND expires<?",Date.now());if(C.kill||!C.sched)return;const N=agNow();const L=kvGet('ag:sched')||{};let ch=false;
 for(const a of Object.values(AGENTS))for(const [kind,s] of a.sched||[]){const k=a.id+'.'+kind;if(C.paused[a.id])continue;const last=L[k]||0;let due=false;
  if(s.every){if(!last){L[k]=Date.now();ch=true;continue}due=Date.now()-last>=s.every*60e3}else if(s.at){due=N.hm>=s.at&&(s.dow==null||s.dow===N.dow)&&agDay(last)!==N.day}
  if(due){L[k]=Date.now();ch=true;agEnqueue(a.id,kind,{},{trig:'schedule',dedupe:true})}}if(ch)kvPut('ag:sched',L,'scheduler')}
const AGEV={'rates.imported':['analyst','scan'],'partner.rates':['analyst','scan'],'rate.jump':['analyst','scan'],'quote.received':['procurement','collect'],'rates.inbox':['procurement','inbox'],'shipment.overdue':['tracker','check'],'demurrage.freetime':['tracker','check']};
const AGEVT=new Map();
function agOnEvent(type,data){const m=AGEV[type];if(!m)return;const C=agCfg();if(C.kill||C.paused[m[0]])return;if(data&&String(data.src||'')==='agent'&&m[0]==='analyst'&&type==='rates.imported'){}
 let input={},trig='event:'+type;if(type==='quote.received'&&data&&data.ref){const a=q1("SELECT args FROM ag_appr WHERE tool='rfq_send' AND status='executed' AND result LIKE ? ORDER BY id DESC",'%'+data.ref+'%');let plan=null;try{plan=a&&JSON.parse(a.args).plan}catch(e){}input=plan?{plan}:{rfq:data.ref};trig+=':'+(plan||data.ref)}
 const k=m.join('.')+'|'+trig;const last=AGEVT.get(k)||0;if(Date.now()-last<60e3)return;AGEVT.set(k,Date.now());agEnqueue(m[0],m[1],input,{trig,dedupe:true});setTimeout(()=>agWorker().catch(()=>{}),50)}
fire=function(type,data,dedupe){const n=_fire0(type,data,dedupe);try{agOnEvent(type,data)}catch(e){}return n};
if(require.main===module){setInterval(()=>agWorker().catch(()=>{}),2000).unref?.();setInterval(()=>{try{agTick()}catch(e){console.error('agents tick',e.message)}},60e3).unref?.();setTimeout(()=>{try{agTick()}catch(e){}},8000).unref?.()}

/* ---------- approvals: decide · execute · revert ---------- */
const apPub=a=>({...a,args:(()=>{try{return JSON.parse(a.args)}catch(e){return a.args}})(),sources:(()=>{try{return JSON.parse(a.sources||'[]')}catch(e){return []}})(),flags:(()=>{try{return JSON.parse(a.flags||'[]')}catch(e){return []}})(),result:(()=>{try{return JSON.parse(a.result)}catch(e){return a.result}})(),undo:undefined,reversible:!!(a.undo&&TOOLS[a.tool]&&TOOLS[a.tool].undo&&['executed','auto'].includes(a.status)),clsFa:CLSFA[a.cls]||a.cls,agentName:(AGENTS[a.agent]||{n:a.agent==='mcp'?'کلاینت MCP':a.agent}).n,hard:HARD.includes(a.cls)});
async function apDecide(id,u,ip,b){const a=q1('SELECT * FROM ag_appr WHERE id=?',id);if(!a)throw E(404,'مورد تأیید یافت نشد');if(a.status!=='pending')throw E(409,'این مورد قبلاً «'+a.status+'» شده است');const t=TOOLS[a.tool];
 if(t.approvers&&!t.approvers.includes(u.role))throw E(403,'تأیید «'+t.name+'» فقط با نقش‌های '+t.approvers.join('، ')+' ممکن است');
 const task=a.task?q1('SELECT by FROM ag_task WHERE id=?',a.task):null;if(t.fourEyes&&task&&task.by===u.username)throw E(403,'اصل چهار چشم: درخواست‌دهندهٔ کار نمی‌تواند پرداخت را خودش تأیید کند');
 if(b.decision==='reject'){run("UPDATE ag_appr SET status='rejected',decided_by=?,decided_at=?,note=? WHERE id=?",u.username,Date.now(),String(b.note||'').slice(0,500),id);audit(u.username,ip,'agent.reject','approval',String(id),{tool:a.tool,note:b.note||''});memAdd('decision','ap'+id,'رد: '+a.summary,b.note||'',u.username);return apPub(q1('SELECT * FROM ag_appr WHERE id=?',id))}
 if(b.decision!=='approve')throw E(400,'decision باید approve یا reject باشد');if(agCfg().kill)throw E(423,'کلید توقف اضطراری فعال است');
 let args=JSON.parse(a.args);if(b.args&&typeof b.args==='object'){args={...args,...b.args};}
 const ag=AGENTS[a.agent]||{id:a.agent,n:a.agent,role:u.role,tools:Object.keys(TOOLS),level:1,budget:{calls:1e6,steps:1e6,ext:1e6}};const ctx={ag,actor:{...agActor(ag),role:u.role},approved:true,approver:u.username,task:a.task,sources:[]};
 run("UPDATE ag_appr SET status='executing',decided_by=?,decided_at=?,note=?,args=? WHERE id=?",u.username,Date.now(),String(b.note||'').slice(0,500),JSON.stringify(args),id);
 try{const r=await t.run(args,ctx);run("UPDATE ag_appr SET status='executed',result=?,undo=? WHERE id=?",clip(r,8000),r&&r.undo?JSON.stringify(r.undo):null,id);agUse(a.agent,{ext:HARD.includes(t.cls)?1:0});
  audit(u.username,ip,'agent.approve','approval',String(id),{tool:a.tool,cls:a.cls,agent:a.agent,task:a.task,edited:!!b.args});memAdd('decision','ap'+id,'تأیید: '+a.summary,(b.note||'')+'\n'+clip(r,1500),u.username);if(a.task)agStep({task:a.task},'approved',a.tool,{by:u.username,approval:id},r,0,1)}
 catch(e){run("UPDATE ag_appr SET status='failed',result=? WHERE id=?",JSON.stringify({error:e.message}),id);audit(u.username,ip,'agent.approve.fail','approval',String(id),{tool:a.tool,error:e.message});throw E(e.code&&e.code<500?e.code:500,'اجرا ناموفق: '+e.message)}
 return apPub(q1('SELECT * FROM ag_appr WHERE id=?',id))}
function apRevert(id,u,ip){const a=q1('SELECT * FROM ag_appr WHERE id=?',id);if(!a)throw E(404,'یافت نشد');const t=TOOLS[a.tool];if(!['executed','auto'].includes(a.status)||!a.undo||!t.undo)throw E(409,'این اقدام برگشت‌پذیر نیست');if(t.approvers&&!t.approvers.includes(u.role))throw E(403,'دسترسی کافی ندارید');
 const r=t.undo(JSON.parse(a.undo),u.username);run("UPDATE ag_appr SET status='reverted',reverted_by=?,reverted_at=? WHERE id=?",u.username,Date.now(),id);audit(u.username,ip,'agent.revert','approval',String(id),{tool:a.tool});memAdd('decision','rv'+id,'بازگردانی: '+a.summary,'',u.username);return {...apPub(q1('SELECT * FROM ag_appr WHERE id=?',id)),undoResult:r}}

/* ---------- HTTP API ---------- */
const taskPub=t=>t&&({...t,input:(()=>{try{return JSON.parse(t.input)}catch(e){return t.input}})(),output:(()=>{try{return JSON.parse(t.output)}catch(e){return t.output}})(),sources:(()=>{try{return JSON.parse(t.sources||'[]')}catch(e){return []}})(),flags:(()=>{try{return JSON.parse(t.flags||'{}')}catch(e){return {}}})(),agentName:(AGENTS[t.agent]||{}).n});
function agOverview(u){const C=agCfg();const P=agProviders();const pick=agPick();return {version:VERSION,kill:!!C.kill,sched:!!C.sched,mask:!!C.mask,fts:AGFTS,
 agents:Object.values(AGENTS).map(a=>{const U=agUseGet(a.id),B=agBudget(a);const last=q1('SELECT id,kind,status,finished,created FROM ag_task WHERE agent=? ORDER BY id DESC LIMIT 1',a.id);return {id:a.id,name:a.n,icon:a.ic,desc:a.d,instr:a.instr,role:a.role,level:agLevel(a),defaultLevel:a.level,maxLevel:a.maxLevel??3,web:!!a.web,paused:!!C.paused[a.id],kinds:a.kinds,sched:a.sched||[],tools:a.tools.map(n=>({name:n,cls:(TOOLS[n]||{}).cls,clsFa:CLSFA[(TOOLS[n]||{}).cls]})),usage:U,budget:B,last,pending:q1("SELECT COUNT(*) n FROM ag_appr WHERE agent=? AND status='pending'",a.id).n}}),
 llm:{active:pick?{id:pick.id,kind:pick.kind,model:pick.model,local:!!pick.local,label:pick.label||'',vision:!!pick.vision,url:pick.url?String(pick.url).replace(/^(https?:\/\/[^/]+).*/,'$1'):''}:null,use:C.llm.use,sensitive:C.llm.sensitive,providers:P.map(p=>({id:p.id,kind:p.kind,url:p.url,model:p.model,label:p.label||'',local:!!p.local,vision:!!p.vision,priceIn:p.priceIn||0,priceOut:p.priceOut||0,hasKey:!!p.key,env:p.id==='env'})),maxTokens:C.llm.maxTokens},
 cfg:can(u,'agents.admin')?{allow:C.allow,feeds:C.feeds,wrsCap:C.wrsCap,carry:C.carry,riskPct:C.riskPct,devHi:C.devHi,devLo:C.devLo,ratio:C.ratio,tg:C.tg,approvalHours:C.approvalHours,level:C.level,budget:C.budget,routeBase:C.routeBase}:null,
 pending:q1("SELECT COUNT(*) n FROM ag_appr WHERE status='pending'").n,today:q1('SELECT COALESCE(SUM(tasks),0) tasks,COALESCE(SUM(calls),0) calls,COALESCE(SUM(tokens),0) tokens,COALESCE(SUM(cost),0) cost FROM ag_use WHERE day=?',agDay()),tools:Object.values(TOOLS).map(t=>({name:t.name,cls:t.cls,d:t.d})),routes:routesList()}}
route('GET','/api/agents',(req,u)=>agOverview(u),'agents.use');
route('POST','/api/agents/cfg',async(req,u)=>{const b=await body(req);const C=agCfg();const p={};
 for(const k of ['allow','feeds'])if(Array.isArray(b[k]))p[k]=b[k].map(s=>String(s).trim()).filter(Boolean).slice(0,40);for(const k of ['wrsCap','carry','devHi','devLo','approvalHours'])if(b[k]!=null&&isFinite(+b[k]))p[k]=+b[k];for(const k of ['mask','tg','sched'])if(b[k]!=null)p[k]=!!b[k];if(Array.isArray(b.ratio)&&b.ratio.length===2)p.ratio=b.ratio.map(Number);if(b.riskPct)p.riskPct={...C.riskPct,...b.riskPct};
 if(b.level)p.level={...C.level,...Object.fromEntries(Object.entries(b.level).filter(([k])=>AGENTS[k]).map(([k,v])=>[k,Math.max(0,Math.min(AGENTS[k].maxLevel??3,+v))]))};if(b.budget)p.budget={...C.budget,...b.budget};if(b.paused)p.paused={...C.paused,...b.paused};if(b.routeBase)p.routeBase={...C.routeBase,...b.routeBase};
 if(b.llm){const L={...b.llm};if(Array.isArray(L.providers)){const old=new Map((C.llm.providers||[]).map(x=>[x.id,x]));L.providers=L.providers.filter(x=>x&&x.id&&x.id!=='env'&&['openai','anthropic','ollama'].includes(x.kind)).slice(0,8).map(x=>({id:String(x.id).slice(0,30),kind:x.kind,url:String(x.url||'').slice(0,300),model:String(x.model||'').slice(0,100),key:x.key==null||x.key==='***'?((old.get(x.id)||{}).key||''):String(x.key),local:!!x.local,vision:!!x.vision,jsonMode:x.jsonMode!==false,priceIn:+x.priceIn||0,priceOut:+x.priceOut||0}))}for(const k of Object.keys(L))if(!['providers','use','sensitive','maxTokens','temperature','timeoutSec'].includes(k))delete L[k];p.llm=L}
 agCfgSet(p,u.username);audit(u.username,ipOf(req),'agents.config','agents','cfg',{keys:Object.keys(p),llm:p.llm?{use:p.llm.use,providers:(p.llm.providers||[]).map(x=>x.id+':'+x.kind)}:undefined});return agOverview(u)},'agents.admin');
route('POST','/api/agents/kill',async(req,u)=>{const b=await body(req);const on=!!b.on;agCfgSet({kill:on},u.username);if(on)run("UPDATE ag_task SET status='blocked',err='توقف اضطراری',finished=? WHERE status='queued'",Date.now());audit(u.username,ipOf(req),on?'agents.kill':'agents.resume','agents','kill',{reason:b.reason||''});_fire0('agent.alert',{ref:'kill',agent:'سیستم',text:on?'⛔ همهٔ عامل‌ها با کلید توقف اضطراری متوقف شدند ('+u.username+')':'▶️ عامل‌ها دوباره فعال شدند ('+u.username+')'});dispatch().catch(()=>{});return {kill:on}},'agents.kill');
route('POST','/api/agents/llm/test',async(req,u)=>{const b=await body(req);const P=agProviders();const p=P.find(x=>x.id===(b.id||agCfg().llm.use))||P[0];if(!p)throw E(400,'هیچ مدلی تعریف نشده است');const t0=Date.now();
 try{const r=await agLLMRaw(p,{system:'Reply with JSON only.',messages:[{role:'user',content:'Return {"ok":true,"lang":"fa","echo":"سلام"}'}],json:true,maxTokens:400});const jj=agPJ(r.text);const oh=r.tin>1500?r.tin:0;audit(u.username,ipOf(req),'agents.llm.test','agents',p.id,{ok:true,tin:r.tin});return {ok:true,provider:p.id,model:p.model,served:r.model||p.model,ms:Date.now()-t0,reply:String(r.text).slice(0,200),json:!!(jj&&jj.ok===true),fa:!!(jj&&/سلام/.test(jj.echo||'')),tokens:r.tin+r.tout,tin:r.tin,tout:r.tout,thinking:!!r.thinking,overhead:oh,costUSD:+((r.tin*(+p.priceIn||0)+r.tout*(+p.priceOut||0))/1e6).toFixed(5),note:oh?'این واسط حدود '+oh+' توکن ورودی پنهان (دستور سیستمی خودِ واسط) به هر درخواست می‌افزاید؛ هزینه و سهمیهٔ توکن را بر همین مبنا تنظیم کنید.':''}}catch(e){return {ok:false,provider:p.id,error:e.message.slice(0,300),ms:Date.now()-t0}}},'agents.admin');
route('GET','/api/agents/tasks',req=>{const s=new URL(req.url,'http://x').searchParams;const L=q(`SELECT id,agent,kind,title,status,trig,by,created,started,finished,cost,tokens,calls,model,err,tainted,flags FROM ag_task WHERE (? IS NULL OR agent=?) AND (? IS NULL OR status=?) ORDER BY id DESC LIMIT ?`,s.get('agent'),s.get('agent'),s.get('status'),s.get('status'),Math.min(300,+s.get('limit')||80));return L.map(t=>({...t,flags:(()=>{try{return JSON.parse(t.flags||'{}')}catch(e){return {}}})(),agentName:(AGENTS[t.agent]||{}).n}))},'agents.use');
route('GET','/api/agents/tasks/:id',(req,u,P)=>{const t=q1('SELECT * FROM ag_task WHERE id=?',+P.id);if(!t)throw E(404,'کار یافت نشد');return {...taskPub(t),steps:q('SELECT * FROM ag_step WHERE task=? ORDER BY id',t.id),approvals:q('SELECT * FROM ag_appr WHERE task=? ORDER BY id',t.id).map(apPub)}},'agents.use');
route('POST','/api/agents/tasks',async(req,u)=>{const b=await body(req);const id=agEnqueue(String(b.agent||''),String(b.kind||''),b.input||{},{by:u.username,trig:'manual:'+u.username});audit(u.username,ipOf(req),'agent.task','agent',String(id),{agent:b.agent,kind:b.kind});
 if(b.wait){const t=await agRun(id);return taskPub(q1('SELECT * FROM ag_task WHERE id=?',t.id))}setTimeout(()=>agWorker().catch(()=>{}),20);return {id,status:'queued'}},'agents.use');
route('POST','/api/agents/tasks/:id/cancel',(req,u,P)=>{const r=run("UPDATE ag_task SET status='cancelled',finished=?,err=? WHERE id=? AND status='queued'",Date.now(),'لغو توسط '+u.username,+P.id);return {cancelled:r.changes}},'agents.use');
route('GET','/api/agents/approvals',req=>{const s=new URL(req.url,'http://x').searchParams;const st=s.get('status')||'pending';return q(`SELECT * FROM ag_appr WHERE ${st==='all'?'1=1':st==='done'?"status NOT IN ('pending')":'status=?'} ORDER BY id DESC LIMIT ?`,...(st==='all'||st==='done'?[]:[st]),Math.min(300,+s.get('limit')||100)).map(apPub)},'agents.use');
route('POST','/api/agents/approvals/:id',async(req,u,P)=>apDecide(+P.id,u,ipOf(req),await body(req)),'agents.approve');
route('POST','/api/agents/approvals/:id/revert',(req,u,P)=>apRevert(+P.id,u,ipOf(req)),'agents.approve');
route('POST','/api/agents/ask',async(req,u)=>{const b=await body(req);const qs=String(b.q||'').trim().slice(0,2000);if(!qs)throw E(400,'پرسش خالی است');const id=agEnqueue('analyst','ask',{q:qs,title:qs.slice(0,60)},{by:u.username,trig:'ask:'+u.username});const t=await agRun(id);const o=taskPub(t);return {task:t.id,status:t.status,...(o.output||{}),sources:o.sources,err:t.err}},'agents.use');
route('POST','/api/agents/tool/:name',async(req,u,P)=>{const t=TOOLS[P.name];if(!t)throw E(404,'ابزار ناشناخته');if(!['read','compute'].includes(t.cls))throw E(403,'ابزارهای تغییردهنده یا بیرونی فقط از راه عامل و کارتابل تأیید اجرا می‌شوند');if(t.perm&&!can(u,t.perm))throw E(403,'دسترسی کافی ندارید');for(const k of t.keys||[])if(!canKey(u,k))throw E(403,'دسترسی به «'+k+'» ندارید');
 const b=await body(req);const ctx={ag:HUMAN,actor:u,sources:[]};const r=await t.run(b.args||{},ctx);audit(u.username,ipOf(req),'agent.tool','tool',t.name,{cls:t.cls});return r},'agents.use');
route('GET','/api/agents/routes',()=>({routes:routesList(),hist:routesState().hist.slice(0,50)}),'');
route('POST','/api/agents/routes/:id',async(req,u,P)=>{if(!canKey(u,'ifa-routes'))throw E(403,'دسترسی کافی ندارید');const b=await body(req);routeSet(P.id,b.status,b.reason,b.source||'manual',u.username);audit(u.username,ipOf(req),'route.status','route',P.id,{status:b.status,reason:b.reason});return {routes:routesList()}},'');
route('POST','/api/agents/compare',async(req,u)=>compareRoutes(await body(req)),'agents.use');
route('GET','/api/agents/memory',req=>{const s=new URL(req.url,'http://x').searchParams;return memSearch(s.get('q')||'',{kind:s.get('kind')||undefined,limit:Math.min(50,+s.get('limit')||20)})},'agents.use');
route('GET','/api/agents/keys',()=>q('SELECT id,name,role,level,tools,created,by,revoked,last_used FROM ag_key ORDER BY id DESC'),'agents.admin');
route('POST','/api/agents/keys',async(req,u)=>{const b=await body(req);if(!ROLES[b.role||'viewer'])throw E(400,'نقش نامعتبر');const k='ifa_mcp_'+crypto.randomBytes(24).toString('base64url');const tools=Array.isArray(b.tools)&&b.tools.length?b.tools.filter(n=>TOOLS[n]):null;
 run('INSERT INTO ag_key(name,hash,role,level,tools,created,by) VALUES(?,?,?,?,?,?,?)',String(b.name||'MCP').slice(0,60),sha(k),b.role||'viewer',Math.max(0,Math.min(2,+b.level||1)),tools?JSON.stringify(tools):null,Date.now(),u.username);audit(u.username,ipOf(req),'mcp.key.create','mcp',String(b.name||''),{role:b.role,level:b.level});return {key:k,note:'این کلید فقط یک بار نمایش داده می‌شود'}},'agents.admin');
route('DELETE','/api/agents/keys/:id',(req,u,P)=>{run('UPDATE ag_key SET revoked=1 WHERE id=?',+P.id);audit(u.username,ipOf(req),'mcp.key.revoke','mcp',P.id,null);return {ok:true}},'agents.admin');

/* ---------- MCP server (JSON-RPC 2.0 over Streamable HTTP · POST /mcp) ---------- */
function mcpIdentity(req){const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!t)return null;if(t.startsWith('ifa_mcp_')){const k=q1('SELECT * FROM ag_key WHERE hash=? AND revoked=0',sha(t));if(!k)return null;run('UPDATE ag_key SET last_used=? WHERE id=?',Date.now(),k.id);
  return {who:'mcp:'+k.name,role:k.role,level:k.level,tools:k.tools?JSON.parse(k.tools):null}}const u=readToken(t);if(!u||!can(u,'agents.use'))return null;return {who:u.username,role:u.role,level:1,tools:null,user:u}}
const mcpAgent=id=>({id:'mcp',n:'کلاینت MCP ('+id.who+')',level:id.level,maxLevel:2,role:id.role,web:false,tools:(id.tools||Object.keys(TOOLS)).filter(n=>TOOLS[n]),budget:{calls:3000,tokens:200000,usd:2,steps:1e9,ext:50},instr:''});
async function mcpHandle(req,res){const id=mcpIdentity(req);const out=(code,o)=>send(res,code,o);if(!id)return send(res,401,{jsonrpc:'2.0',error:{code:-32001,message:'Unauthorized: Bearer token (IFA user token or ifa_mcp_ key) required'},id:null},{'WWW-Authenticate':'Bearer'});
 let b;try{b=await body(req)}catch(e){return out(400,{jsonrpc:'2.0',error:{code:-32700,message:'Parse error'},id:null})}
 const one=async m=>{if(!m||m.jsonrpc!=='2.0'||!m.method)return {jsonrpc:'2.0',error:{code:-32600,message:'Invalid Request'},id:m&&m.id!=null?m.id:null};if(m.id==null)return null;const ok=r=>({jsonrpc:'2.0',id:m.id,result:r});const er=(c,msg)=>({jsonrpc:'2.0',id:m.id,error:{code:c,message:msg}});const ag=mcpAgent(id);
  if(m.method==='initialize'){const v=(m.params||{}).protocolVersion;return ok({protocolVersion:['2024-11-05','2025-03-26','2025-06-18'].includes(v)?v:'2025-03-26',capabilities:{tools:{listChanged:false}},serverInfo:{name:'ifa-asana-agents',title:'سامانه لجستیک آسانا (Asana Logistics) — ابزارهای عامل‌ها',version:VERSION},instructions:'ابزارهای دادهٔ حمل‌ونقل IFA. ابزارهای external/commit/money و write (در سطح ۱) به‌جای اجرا، درخواست تأیید انسانی می‌سازند.'})}
  if(m.method==='ping')return ok({});
  if(m.method==='tools/list')return ok({tools:ag.tools.map(n=>{const t=TOOLS[n];return {name:t.name,description:t.d+' · نوع: '+(CLSFA[t.cls]||t.cls)+(HARD.includes(t.cls)?' (نیازمند تأیید انسانی)':''),inputSchema:agSchema(t),annotations:{readOnlyHint:['read','compute','web'].includes(t.cls),destructiveHint:false,openWorldHint:['web','external'].includes(t.cls)}}})});
  if(m.method==='tools/call'){const p=m.params||{};const t=TOOLS[p.name];if(!t||!ag.tools.includes(p.name))return er(-32602,'Unknown tool: '+p.name);const ctx={ag,actor:{id:0,username:id.who,role:id.role,name:id.who},sources:[]};
   try{const r=await agCall(ctx,p.name,p.arguments||{});audit(id.who,ipOf(req),'mcp.call','tool',p.name,{cls:t.cls,pending:!!(r&&r.pending)});const txt=r&&r.pending?'درخواست تأیید انسانی ثبت شد: #'+r.approval+' (کارتابل تأیید در IFA)':clip(r,20000);return ok({content:[{type:'text',text:txt}],structuredContent:r&&typeof r==='object'&&!Array.isArray(r)?r:{result:r},isError:false})}
   catch(e){audit(id.who,ipOf(req),'mcp.denied','tool',p.name,{error:e.message});return ok({content:[{type:'text',text:'خطا: '+e.message}],isError:true})}}
  if(m.method==='resources/list')return ok({resources:[]});if(m.method==='prompts/list')return ok({prompts:[]});return er(-32601,'Method not found: '+m.method)};
 if(Array.isArray(b)){const R=(await Promise.all(b.map(one))).filter(Boolean);if(!R.length){res.writeHead(202,cors());return res.end()}return out(200,R)}const r=await one(b);if(!r){res.writeHead(202,cors());return res.end()}return out(200,r)}
route('POST','/api/mcp',async(req,u,P,res)=>{await mcpHandle(req,res);return null});
route('GET','/api/mcp',()=>({__code:405,error:'MCP: use POST (JSON-RPC 2.0). SSE stream is not offered by this server.'}));
const P5={qxText,qxVerify,pdfText,iso6346,docFields,docsCheck,hsSuggest,reconcile,compareRoutes,agGround,piiMask,piiUnmask,agInj,agPolicy,AGENTS,TOOLS,idxForecast,qaRule,newsScan,dateOf,eqNorm,portOf};
