/* ===== v15.9: AI employees (agents) · approvals inbox · tasks/audit · Persian Q&A · smart RFQ · tools · corridors · model/MCP settings ===== */
const agApi={
 overview:()=>svApi('/api/agents'),
 ask:q=>svApi('/api/agents/ask',{method:'POST',body:{q}}),
 run:(agent,kind,input={},wait=false)=>svApi('/api/agents/tasks',{method:'POST',body:{agent,kind,input,wait}}),
 tasks:(o={})=>svApi('/api/agents/tasks?'+new URLSearchParams(Object.entries(o).filter(([,v])=>v!=null&&v!==''))),
 task:id=>svApi('/api/agents/tasks/'+(+id)),
 cancel:id=>svApi('/api/agents/tasks/'+(+id)+'/cancel',{method:'POST',body:{}}),
 approvals:(status='pending')=>svApi('/api/agents/approvals?status='+encodeURIComponent(status)),
 approve:(id,note='',args)=>svApi('/api/agents/approvals/'+(+id),{method:'POST',body:{decision:'approve',note,...(args?{args}:{})}}),
 reject:(id,note='')=>svApi('/api/agents/approvals/'+(+id),{method:'POST',body:{decision:'reject',note}}),
 revert:id=>svApi('/api/agents/approvals/'+(+id)+'/revert',{method:'POST',body:{}}),
 tool:(name,args={})=>svApi('/api/agents/tool/'+encodeURIComponent(name),{method:'POST',body:{args}}),
 extract:(text,o={})=>agApi.tool('quotes_extract',{text,...o}),
 docsCheck:docs=>agApi.tool('docs_check',{docs}),
 hs:desc=>agApi.tool('hs_suggest',{desc}),
 reconcile:(invoice,quote,o={})=>agApi.tool('invoice_reconcile',{invoice,quote,...o}),
 compareRoutes:(o={})=>svApi('/api/agents/compare',{method:'POST',body:o}),
 routes:()=>svApi('/api/agents/routes'),
 setRouteStatus:(id,status,reason='')=>svApi('/api/agents/routes/'+encodeURIComponent(id),{method:'POST',body:{status,reason,source:'manual'}}),
 memory:q=>svApi('/api/agents/memory?q='+encodeURIComponent(q||'')),
 kill:(on=true,reason='')=>svApi('/api/agents/kill',{method:'POST',body:{on,reason}}),
 config:p=>svApi('/api/agents/cfg',{method:'POST',body:p}),
 testModel:id=>svApi('/api/agents/llm/test',{method:'POST',body:{id}}),
 keys:()=>svApi('/api/agents/keys'),
 createKey:(name,role='viewer',level=1)=>svApi('/api/agents/keys',{method:'POST',body:{name,role,level}}),
 revokeKey:id=>svApi('/api/agents/keys/'+(+id),{method:'DELETE'})
};
const AGS=Object.assign({tab:'dash',apSt:'pending',tool:'qx',taskId:null,agF:'',wf:{pol:'Ningbo',dest:'Tehran',eq:'40HC',qty:1,value:50000,deadlineDays:45,weightT:22,commodity:''},sc:{fxPct:0,seaPct:0,closed:[]}},(()=>{const o=LSG('ifa-ag-ui',{});return o&&typeof o==='object'?o:{}})());
AGS.ask=[];AGS.ov=null;AGS.res={};AGS.seq=0;
const agSv=()=>LSS('ifa-ag-ui',{tab:AGS.tab,apSt:AGS.apSt,tool:AGS.tool,wf:AGS.wf,sc:AGS.sc,agF:AGS.agF});
const AGLV=['۰ · فقط مشاهده و گزارش','۱ · پیشنهاد + تأیید انسانی','۲ · خودکار با ثبت و امکان بازگشت','۳ · خودکار کامل (فقط کم‌ریسک)'];
const AGST={queued:['در صف','warn'],running:['در حال اجرا','warn'],done:['انجام شد','ok'],failed:['ناموفق','bad'],rejected:['رد شد (سیاست)','bad'],blocked:['مسدود','bad'],cancelled:['لغو','warn'],waiting:['منتظر تأیید','warn'],pending:['در انتظار تأیید','warn'],executed:['اجرا شد','ok'],executing:['در حال اجرا','warn'],auto:['خودکار (ثبت‌شده)','ok'],reverted:['بازگردانده شد','warn'],expired:['منقضی','bad']};
const agSt=s=>{const x=AGST[s]||[s||'—',''];return chip(x[1],x[0])};
const agUsd=v=>v==null||v===''||isNaN(+v)?'—':nf(Math.round(+v))+'$';
const agJ=v=>esc(JSON.stringify(v,null,1)||'').slice(0,20000);
const agTxt=s=>esc(String(s==null?'':s)).replace(/\n/g,'<br>');
const agSrc=S=>Array.isArray(S)&&S.length?`<div class="ag-src"><small>منابع:</small>${S.slice(0,14).map((s,i)=>`<span class="ag-s" ${s.view?`data-view="${esc(s.view)}"`:''} title="${esc((s.kind||'')+' · '+(s.ref||''))}">[S${i+1}] ${esc(String(s.title||s.ref||s.kind||'').slice(0,110))}${s.url?` <a href="${esc(s.url)}" target="_blank" rel="noopener">↗</a>`:''}</span>`).join('')}</div>`:'';
const agBindSrc=root=>$$('.ag-s[data-view]',root).forEach(x=>x.onclick=e=>{if(e.target.tagName==='A')return;IFA.open(x.dataset.view)});
async function agOv(force){if(!AGS.ov||force)AGS.ov=await agApi.overview();return AGS.ov}
function rAgt(b,C){
 if(!svOn()){b.innerHTML=tmOff('کارکنان هوشمند (عامل‌ها)');tmGo(b);return}
 if(!svCan('agents.use')){b.innerHTML=`<div class="sx-card"><header><b>دسترسی به عامل‌ها ندارید</b></header><p class="sx-muted">نقش شما مجوز «agents.use» ندارد؛ از مدیر سیستم بخواهید نقش فروش، عملیات، مالی یا مدیر به شما بدهد.</p></div>`;return}
 const adm=svCan('agents.admin');if(AGS.tab==='cfg'&&!adm)AGS.tab='dash';const pend=AGS.ov?AGS.ov.pending:0;
 b.innerHTML=`<div class="ag-w">${tmSeg([['dash','داشبورد عامل‌ها'],['ap','کارتابل تأیید'+(pend?' ('+fa(pend)+')':'')],['tasks','کارها و ردپا'],['ask','پرسش و پاسخ'],['rfq','استعلام هوشمند'],['tools','ابزارها'],['routes','کریدورها'],adm?['cfg','تنظیمات، مدل و MCP']:null],AGS.tab,'mk-sub ag-sub')}<div class="ag-b"><div class="sx-muted ag-ld">در حال بارگذاری…</div></div></div>`;
 $$('.ag-sub button',b).forEach(x=>x.onclick=()=>{AGS.tab=x.dataset.v;agSv();rAgt(b,C)});
 const B=$('.ag-b',b);const my=++AGS.seq;const live=()=>my===AGS.seq&&B.isConnected;
 const P={dash:agDash,ap:agAp,tasks:agTasks,ask:agAsk,rfq:agRfq,tools:agTools,routes:agRoutes,cfg:agCfgUI}[AGS.tab]||agDash;
 (async()=>{try{await agOv(AGS.tab==='dash'||!AGS.ov);if(!live())return;const s=$('.ag-sub button[data-v="ap"]',b);if(s)s.textContent='کارتابل تأیید'+(AGS.ov.pending?' ('+fa(AGS.ov.pending)+')':'');await P(B,()=>rAgt(b,C),live)}catch(e){if(live())B.innerHTML=`<div class="fw-al bad">خطا در دریافت اطلاعات عامل‌ها: ${esc(e.message)}${e.code===404?' — نسخهٔ سرور قدیمی است؛ server.js نسخهٔ 1.8.0 یا جدیدتر را نصب کنید.':''}</div>`}})()}
/* ---------- dashboard ---------- */
async function agDash(B,re){const O=AGS.ov,adm=svCan('agents.admin'),kc=svCan('agents.kill');const T=O.today||{};
 const NOIN={analyst:['scan','forecast','daily','weekly','discover'],risk:['scan'],tracker:['check'],qa:['review'],procurement:['inbox']};
 B.innerHTML=`${O.kill?`<div class="fw-al bad ag-kill"><b>⛔ توقف اضطراری فعال است</b> — هیچ عاملی اجرا نمی‌شود، کارتابل تأیید قفل است و MCP پاسخ نمی‌دهد. ${kc?'<button class="sx-btn sm pri" data-kill="0">فعال‌سازی دوبارهٔ عامل‌ها</button>':''}</div>`:''}
 <div class="ex-kpis"><div class="sx-kpi"><small>مدل زبانی فعال</small><b title="${O.llm.active?esc(O.llm.active.url||''):''}">${O.llm.active?esc(O.llm.active.model||O.llm.active.id):'قاعده‌محور'}</b><small>${O.llm.active?(O.llm.active.local?'محلی (داده بیرون نمی‌رود)':'ابری · پوشش اطلاعات شخصی '+(O.mask?'روشن':'خاموش')):'بدون مدل؛ پاسخ‌ها از قواعد و داده‌ها'}</small></div>
 <div class="sx-kpi"><small>در انتظار تأیید شما</small><b>${fa(O.pending)}</b><small>اقدام‌های بیرونی/تعهدی/مالی</small></div><div class="sx-kpi"><small>کارهای امروز</small><b>${fa(T.tasks||0)}</b><small>${fa(T.calls||0)} فراخوانی ابزار</small></div><div class="sx-kpi"><small>توکن امروز</small><b>${nf(T.tokens||0)}</b><small>هزینهٔ مدل: ${(+T.cost||0).toFixed(3)}$</small></div><div class="sx-kpi"><small>زمان‌بندی خودکار</small><b>${O.sched?'روشن':'خاموش'}</b><small>جست‌وجوی حافظه: ${O.fts?'FTS5':'ساده'}</small></div></div>
 ${!O.kill&&kc?`<div class="ag-killbar"><button class="sx-btn sm ag-stop" data-kill="1">⛔ توقف اضطراری همهٔ عامل‌ها</button><span class="sx-muted">کارهای در صف مسدود، تأییدها و MCP قفل می‌شوند. ثبت در ردپای ممیزی.</span></div>`:''}
 <div class="ag-grid">${O.agents.map(a=>{const U=a.usage||{},Bu=a.budget||{};const pct=Bu.calls?Math.min(100,Math.round(100*(U.calls||0)/Bu.calls)):0;
  return `<div class="sx-card ag-card ${a.paused?'ag-paused':''}"><header><b>${esc(a.icon||'🤖')} ${esc(a.name)}</b><small>${chip(a.level>=2?'ok':a.level===1?'warn':'',AGLV[a.level]||a.level)} ${a.paused?chip('bad','متوقف'):''} ${a.web?chip('warn','خوانندهٔ وب · بدون ارسال'):''} ${a.pending?chip('warn',fa(a.pending)+' تأیید'):''}</small></header>
  <p class="ag-d">${esc(a.desc)}</p><div class="ag-use"><span>بودجهٔ روزانه: ${fa(U.calls||0)}/${fa(Bu.calls||0)} فراخوانی · ${nf(U.tokens||0)} توکن · ${(+U.usd||+U.cost||0).toFixed(2)}/${Bu.usd||0}$</span><i style="width:${pct}%"></i></div>
  <div class="sx-muted ag-last">آخرین کار: ${a.last?`${esc(a.kinds[a.last.kind]||a.last.kind)} · ${agSt(a.last.status)} · ${tmDt(a.last.finished||a.last.created)} <a href="#" data-task="${a.last.id}">جزئیات</a>`:'هنوز کاری انجام نداده'}</div>
  <div class="ag-kinds">${(NOIN[a.id]||[]).filter(k=>a.kinds[k]).map(k=>`<button class="sx-btn xs" data-run="${a.id}" data-kind="${k}" ${O.kill||a.paused?'disabled':''}>▶ ${esc(a.kinds[k])}</button>`).join('')}</div>
  <details class="ag-more"><summary>ابزارها و دستورالعمل</summary><p class="sx-muted">${esc(a.instr||'')}</p><div>${a.tools.map(t=>chip(['external','commit','money'].includes(t.cls)?'warn':'',esc(t.name)+' · '+esc(t.clsFa||t.cls||''))).join(' ')}</div>${a.sched&&a.sched.length?`<p class="sx-muted">زمان‌بندی: ${a.sched.map(s=>esc(a.kinds[s[0]]||s[0])+' '+(s[1].at?'هر روز '+s[1].at:'هر '+fa(s[1].every)+' دقیقه')).join(' · ')}</p>`:''}</details>
  ${adm?`<div class="ag-adm"><label>سطح اختیار <select data-lv="${a.id}">${AGLV.slice(0,(a.maxLevel??3)+1).map((n,i)=>`<option value="${i}" ${i===a.level?'selected':''}>${n}</option>`).join('')}</select></label><label><input type="checkbox" data-pause="${a.id}" ${a.paused?'checked':''}> توقف این عامل</label></div>`:''}</div>`}).join('')}</div>
 <p class="sx-note">اقدام‌های بیرونی (ارسال ایمیل/پیام)، تعهدی (رزرو) و مالی همیشه به کارتابل تأیید می‌روند، صرف‌نظر از سطح اختیار. پرداخت هرگز اجرا نمی‌شود؛ فقط درخواستِ تأییدشده در صف پرداخت ثبت می‌شود.</p>`;
 $$('[data-kill]',B).forEach(x=>x.onclick=tmTry(async()=>{const on=x.dataset.kill==='1';let reason='';if(on){reason=prompt('دلیل توقف اضطراری؟','')||'';if(!confirm('همهٔ عامل‌ها متوقف شوند؟'))return}await agApi.kill(on,reason);toast(on?'همهٔ عامل‌ها متوقف شدند':'عامل‌ها فعال شدند');AGS.ov=null;re()}));
 $$('[data-run]',B).forEach(x=>x.onclick=tmTry(async()=>{x.disabled=true;x.textContent='در حال اجرا…';const t=await agApi.run(x.dataset.run,x.dataset.kind,{},true);toast((t.output&&t.output.summary||'').slice(0,140)||('کار #'+t.id+' · '+((AGST[t.status]||[t.status])[0])));AGS.taskId=t.id;AGS.tab='tasks';agSv();AGS.ov=null;re()}));
 $$('[data-task]',B).forEach(x=>x.onclick=e=>{e.preventDefault();AGS.taskId=+x.dataset.task;AGS.tab='tasks';agSv();re()});
 $$('[data-lv]',B).forEach(x=>x.onchange=tmTry(async()=>{AGS.ov=await agApi.config({level:{[x.dataset.lv]:+x.value}});toast('سطح اختیار به‌روز شد');re()}));
 $$('[data-pause]',B).forEach(x=>x.onchange=tmTry(async()=>{AGS.ov=await agApi.config({paused:{[x.dataset.pause]:x.checked}});re()}))}
/* ---------- approvals inbox ---------- */
function agArgsView(a){const A=a.args||{};let h='';
 if(Array.isArray(A.items))h+=A.items.map(it=>`<div class="ag-draft"><b>${esc(it.title||'')}</b>${it.recipients?`<small> → ${esc(it.recipients.map(r=>r.name||r.email).join('، ')||'بدون گیرنده (فقط پیوند عمومی)')}</small>`:''}<pre>${esc(String(it.text||'').slice(0,4000))}</pre></div>`).join('');
 else if(A.text||A.body)h+=`<div class="ag-draft">${A.to?`<small>به: ${esc(A.to)}</small>`:''}${A.subject?`<b>${esc(A.subject)}</b>`:''}<pre>${esc(String(A.text||A.body).slice(0,4000))}</pre></div>`;
 const kv=Object.entries(A).filter(([k,v])=>!['items','text','body'].includes(k)&&(typeof v!=='object'||v===null));if(kv.length)h+=`<div class="ag-kv">${kv.map(([k,v])=>`<span><small>${esc(k)}</small> ${esc(String(v)).slice(0,120)}</span>`).join('')}</div>`;return h}
async function agAp(B,re,live){const L=await agApi.approvals(AGS.apSt);if(!live())return;const ap=svCan('agents.approve');
 B.innerHTML=`<div class="ag-row">${tmSeg([['pending','در انتظار'],['done','تصمیم‌گرفته'],['all','همه']],AGS.apSt,'ag-aps')}<button class="sx-btn sm" data-rf>تازه‌سازی</button></div>
 ${L.length?L.map(a=>`<div class="sx-card ag-ap ${a.hard?'ag-hard':''}" data-id="${a.id}"><header><b>#${fa(a.id)} · ${esc(a.summary||a.tool)}</b><small>${agSt(a.status)} ${chip(a.hard?'warn':'',esc(a.clsFa||a.cls))} ${esc(a.agentName||a.agent)} · ${esc(a.tool)} · ${tmDt(a.created)}${a.status==='pending'&&a.expires?' · مهلت '+tmDt(a.expires):''}</small></header>
  ${a.why?`<p class="sx-muted">چرا: ${esc(a.why)}</p>`:''}${(a.flags||[]).length?`<div class="fw-al warn">${a.flags.map(esc).join('<br>')}</div>`:''}${agArgsView(a)}${agSrc(a.sources)}
  ${a.task?`<a href="#" class="ag-tl" data-task="${a.task}">کار مبدأ #${fa(a.task)}</a>`:''}
  ${a.status==='pending'?(ap?`<details class="ag-edit"><summary>ویرایش ورودی‌ها پیش از تأیید (JSON)</summary><textarea class="ag-args" rows="8">${agJ(a.args)}</textarea></details><div class="ag-act"><input class="ag-note" placeholder="یادداشت تصمیم (اختیاری، در ردپای ممیزی ثبت می‌شود)"><button class="sx-btn sm pri" data-ok>تأیید و اجرا</button><button class="sx-btn sm" data-no>رد</button></div>`:'<p class="sx-muted">برای تصمیم‌گیری مجوز «agents.approve» لازم است.</p>'):`<p class="sx-muted">${a.decided_by?'تصمیم: '+esc(a.decided_by)+' · '+tmDt(a.decided_at):''}${a.note?' · «'+esc(a.note)+'»':''}${a.reverted_by?' · بازگردانی: '+esc(a.reverted_by)+' '+tmDt(a.reverted_at):''}</p>${a.result?`<details><summary>نتیجهٔ اجرا</summary><pre>${agJ(a.result)}</pre></details>`:''}${a.reversible&&ap?'<button class="sx-btn sm" data-rv>↩ بازگردانی (Undo)</button>':''}`}</div>`).join(''):`<div class="sx-card"><p class="sx-muted">${AGS.apSt==='pending'?'موردی در انتظار تأیید نیست.':'موردی ثبت نشده است.'}</p></div>`}`;
 $$('.ag-aps button',B).forEach(x=>x.onclick=()=>{AGS.apSt=x.dataset.v;agSv();re()});$('[data-rf]',B).onclick=()=>{AGS.ov=null;re()};agBindSrc(B);
 $$('[data-task]',B).forEach(x=>x.onclick=e=>{e.preventDefault();AGS.taskId=+x.dataset.task;AGS.tab='tasks';agSv();re()});
 $$('.ag-ap',B).forEach(c=>{const id=+c.dataset.id,note=()=>($('.ag-note',c)||{}).value||'';
  const ok=$('[data-ok]',c);if(ok)ok.onclick=tmTry(async()=>{let args;const ta=$('.ag-args',c),d=$('.ag-edit',c);if(d&&d.open){try{args=JSON.parse(ta.value)}catch(e){return toast('JSON ورودی‌ها نامعتبر است')}}ok.disabled=true;await agApi.approve(id,note(),args);toast('تأیید و اجرا شد');AGS.ov=null;re()});
  const no=$('[data-no]',c);if(no)no.onclick=tmTry(async()=>{await agApi.reject(id,note());toast('رد شد');AGS.ov=null;re()});
  const rv=$('[data-rv]',c);if(rv)rv.onclick=tmTry(async()=>{if(!confirm('این اقدام بازگردانده شود؟'))return;await agApi.revert(id);toast('بازگردانده شد');re()})})}
/* ---------- tasks & audit trail ---------- */
async function agTasks(B,re,live){const O=AGS.ov;const L=await agApi.tasks({agent:AGS.agF,limit:120});if(!live())return;let D=null;if(AGS.taskId){try{D=await agApi.task(AGS.taskId)}catch(e){AGS.taskId=null}}if(!live())return;
 B.innerHTML=`<div class="ag-row"><label class="sx-f"><span>عامل</span><select class="ag-af"><option value="">همه</option>${O.agents.map(a=>`<option value="${a.id}" ${a.id===AGS.agF?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label><button class="sx-btn sm" data-rf>تازه‌سازی</button></div>
 <div class="ag-split"><div class="sx-card ag-tl-l"><table class="sx-tbl"><thead><tr><th>#</th><th>عامل / کار</th><th>وضعیت</th><th>آغازگر</th><th>زمان</th><th>ابزار</th></tr></thead><tbody>${L.map(t=>`<tr data-id="${t.id}" class="${t.id===AGS.taskId?'on':''}"><td>${fa(t.id)}</td><td><b>${esc(t.agentName||t.agent)}</b><br><small>${esc(String(t.title||t.kind).slice(0,70))}</small></td><td>${agSt(t.status)}${t.flags&&t.flags.inj&&t.flags.inj.length?' '+chip('bad','تزریق'):''}${t.tainted?' '+chip('warn','دادهٔ بیرونی'):''}</td><td><small>${esc(String(t.trig||'').slice(0,24))}</small></td><td><small>${tmDt(t.created)}</small></td><td>${fa(t.calls||0)}${t.cost?' · '+(+t.cost).toFixed(3)+'$':''}</td></tr>`).join('')||'<tr><td colspan="6" class="sx-muted">هنوز کاری ثبت نشده است.</td></tr>'}</tbody></table></div>
 <div class="ag-det">${D?agTaskView(D):'<div class="sx-card"><p class="sx-muted">یک کار را برای دیدن مراحل، ورودی/خروجی هر ابزار، تأییدها و منابع انتخاب کنید.</p></div>'}</div></div>`;
 $('.ag-af',B).onchange=e=>{AGS.agF=e.target.value;agSv();re()};$('[data-rf]',B).onclick=re;
 $$('tr[data-id]',B).forEach(r=>r.onclick=()=>{AGS.taskId=+r.dataset.id;re()});agBindSrc(B);
 const cx=$('[data-cancel]',B);if(cx)cx.onclick=tmTry(async()=>{await agApi.cancel(D.id);re()});
 $$('[data-goap]',B).forEach(x=>x.onclick=()=>{AGS.tab='ap';AGS.apSt='all';agSv();re()})}
function agOutView(o){if(o==null)return '';if(typeof o!=='object')return `<p>${agTxt(o)}</p>`;let h='';
 if(o.summary)h+=`<div class="fw-al ok">${agTxt(o.summary)}</div>`;if(o.answer)h+=`<div class="ag-ans">${agTxt(o.answer)}</div>`;
 if(o.report&&o.report.text&&o.report.text!==o.summary)h+=`<pre class="ag-pre">${esc(o.report.text)}</pre>`;
 if(o.comparison)h+=agCmpTbl(o.comparison);if(Array.isArray(o.rows)&&o.rows.length)h+=agRowsTbl(o.rows);
 if(Array.isArray(o.notes)&&o.notes.length)h+=`<div class="fw-al warn">${o.notes.map(esc).join('<br>')}</div>`;if(o.next)h+=`<p class="sx-muted">${esc(o.next)}</p>`;
 return h+`<details><summary>خروجی کامل (JSON)</summary><pre>${agJ(o)}</pre></details>`}
function agTaskView(D){const F=D.flags||{};return `<div class="sx-card"><header><b>#${fa(D.id)} · ${esc(D.agentName||D.agent)} · ${esc(D.title||D.kind)}</b><small>${agSt(D.status)} · ${esc(D.trig||'')} · ${tmDt(D.created)}${D.model?' · مدل '+esc(D.model):''} · ${fa(D.calls||0)} فراخوانی · ${nf(D.tokens||0)} توکن · ${(+D.cost||0).toFixed(4)}$</small></header>
 ${D.err?`<div class="fw-al bad">${esc(D.err)}</div>`:''}${(F.inj||[]).length?`<div class="fw-al bad">نشانهٔ تزریق دستور در دادهٔ ورودی: ${F.inj.map(esc).join(' | ')} — اقدام‌های تغییردهنده برای این کار مسدود شد.</div>`:''}${F.denied?`<div class="fw-al warn">${fa(F.denied)} فراخوانی توسط سیاست رد شد.</div>`:''}
 ${D.status==='queued'?'<button class="sx-btn sm" data-cancel>لغو کار</button>':''}
 ${agOutView(D.output)}${agSrc(D.sources)}
 ${(D.approvals||[]).length?`<p>تأییدهای این کار: ${D.approvals.map(a=>`#${fa(a.id)} ${esc(a.tool)} ${agSt(a.status)}`).join(' · ')} <button class="sx-btn xs" data-goap>کارتابل</button></p>`:''}
 <details ${D.steps&&D.steps.length<14?'open':''}><summary>مراحل و ردپا (${fa((D.steps||[]).length)})</summary><table class="sx-tbl ag-steps"><thead><tr><th>#</th><th>نوع</th><th>نام</th><th>ورودی</th><th>خروجی</th><th>ms</th></tr></thead><tbody>${(D.steps||[]).map((s,i)=>`<tr class="${s.ok===0?'bad':''}"><td>${fa(i+1)}</td><td>${esc(s.kind)}</td><td>${esc(s.name||'')}</td><td><code>${esc(String(s.input||'').slice(0,260))}</code></td><td><code>${esc(String(s.output||'').slice(0,320))}</code></td><td>${s.ms!=null?fa(s.ms):''}</td></tr>`).join('')}</tbody></table></details>
 <details><summary>ورودی کار</summary><pre>${agJ(D.input)}</pre></details></div>`}
/* ---------- Persian Q&A ---------- */
async function agAsk(B,re){const SUG=['میانهٔ نرخ ۴۰ فوت نینگبو به بندرعباس چقدر است؟','وضعیت مسیرها و تأییدهای در انتظار','کدام محموله‌ها تأخیر دارند؟','پیش‌بینی شاخص CCFI هفتهٔ آینده','کرایهٔ رسمی جاده‌ای بندرعباس به تهران'];
 const draw=()=>{const H=$('.ag-hist',B);H.innerHTML=AGS.ask.length?AGS.ask.map(x=>`<div class="sx-card ag-qa"><header><b>❓ ${esc(x.q)}</b><small>${x.pending?'در حال پاسخ…':`${chip(x.mode==='llm'?'ok':'',x.mode==='llm'?'مدل زبانی + داده':'قاعده‌محور')} ${x.grounded?chip('ok','مستند'):''} ${agSt(x.status)} ${x.task?'<a href="#" data-task="'+x.task+'">کار #'+fa(x.task)+'</a>':''}`}</small></header>${x.pending?'<div class="sx-muted">…</div>':`<div class="ag-ans">${agTxt(x.answer||x.err||'پاسخی تولید نشد')}</div>${x.note?`<p class="sx-muted">${esc(x.note)}</p>`:''}${agSrc(x.sources)}${(x.links||[]).length?`<div class="ag-links">${x.links.map(v=>`<button class="sx-btn xs" data-open="${esc(v)}">باز کردن «${esc((TABS.find(s=>s.k===v)||{}).n||v)}»</button>`).join('')}</div>`:''}`}</div>`).join(''):'<p class="sx-muted">هر پرسشی دربارهٔ نرخ‌ها، شاخص‌ها، مسیرها، محموله‌ها، استعلام‌ها یا قواعد داخلی بپرسید. هر عدد پاسخ به منبعش ارجاع داده می‌شود؛ عدد بی‌منبع رد می‌شود.</p>';
  agBindSrc(H);$$('[data-open]',H).forEach(x=>x.onclick=()=>IFA.open(x.dataset.open));$$('[data-task]',H).forEach(x=>x.onclick=e=>{e.preventDefault();AGS.taskId=+x.dataset.task;AGS.tab='tasks';agSv();re()})};
 B.innerHTML=`<div class="sx-card"><header><b>پرسش و پاسخ فارسی روی داده‌های شرکت</b><small>تحلیل‌گر بازار با ابزارهای فقط‌خواندنی پاسخ می‌دهد</small></header><div class="ag-askf"><textarea class="ag-q" rows="2" placeholder="مثلاً: ارزان‌ترین پیشنهاد ۲۰ فوت شانگهای به بندرعباس در ماه گذشته؟"></textarea><button class="sx-btn pri" data-ask>بپرس</button></div><div class="ag-sug">${SUG.map(s=>`<button class="sx-btn xs">${esc(s)}</button>`).join('')}</div></div><div class="ag-hist"></div>`;
 const ta=$('.ag-q',B);const go=async()=>{const q=ta.value.trim();if(!q)return;ta.value='';const x={q,pending:1};AGS.ask.unshift(x);AGS.ask=AGS.ask.slice(0,20);draw();try{Object.assign(x,await agApi.ask(q))}catch(e){x.err=e.message;x.status='failed'}x.pending=0;if(B.isConnected)draw()};
 $('[data-ask]',B).onclick=go;ta.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();go()}};$$('.ag-sug button',B).forEach(x=>x.onclick=()=>{ta.value=x.textContent;go()});draw()}
/* ---------- route comparison table ---------- */
function agCmpTbl(c){if(!c||!Array.isArray(c.routes))return '';const best=c.best;return `<table class="sx-tbl ag-cmp"><thead><tr><th>مسیر</th><th>وضعیت</th><th>کرایهٔ اصلی/واحد</th><th>حمل داخلی</th><th>روز</th><th>نگهداری موجودی</th><th>ریسک</th><th>کل برآوردی</th><th>اطمینان</th></tr></thead><tbody>${c.routes.map(r=>`<tr class="${r.id===best?'ag-best':''} ${r.status==='closed'?'ag-closed':''}"><td><b>${esc(r.name)}</b>${r.id===best?' '+chip('ok','پیشنهادی'):''}${!r.feasible&&r.status!=='closed'?' '+chip('bad','خارج از مهلت'):''}${r.tight?' '+chip('warn','مهلت تنگ'):''}<br><small class="sx-muted">${esc(r.mainSource||'')}</small>${(r.notes||[]).length?`<br><small class="sx-muted">${r.notes.map(esc).join(' · ')}</small>`:''}</td><td>${chip(r.status==='open'?'ok':r.status==='closed'?'bad':'warn',esc(r.statusFa||r.status))}</td><td>${agUsd(r.perUnitUSD??r.mainUSD)}</td><td>${r.domUSD?agUsd(r.domUSD):r.domIRR?nf(Math.round(r.domIRR/1e4))+' هزار تومان':'—'}<br><small class="sx-muted" title="${esc(r.domSource||'')}">${r.km?fa(r.km)+' km':''}</small></td><td>${fa(r.days)}<small class="sx-muted"> (${fa(r.daysMin)}–${fa(r.daysMax)})</small></td><td>${agUsd(r.carryUSD)}</td><td>${agUsd(r.riskUSD)}</td><td><b>${agUsd(r.totalUSD)}</b></td><td>${fa(Math.round((r.confidence||0)*100))}٪</td></tr>`).join('')}</tbody></table>${c.caveat?`<p class="sx-note">${esc(c.caveat)}</p>`:''}`}
function agRowsTbl(R){const K=[['vendor','فورواردر'],['route','مسیر'],['eq','کانتینر'],['usd','هر واحد $'],['totalUSD','کل با نگهداری $'],['valid','اعتبار'],['days','روز'],['issues','ایرادها']];return `<table class="sx-tbl"><thead><tr>${K.map(k=>`<th>${k[1]}</th>`).join('')}<th>وضعیت</th></tr></thead><tbody>${R.map(r=>`<tr>${K.map(([k])=>`<td>${Array.isArray(r[k])?r[k].map(x=>esc(typeof x==='object'?x.msg||JSON.stringify(x):x)).join('<br>'):esc(r[k]==null?'—':typeof r[k]==='number'?nf(r[k]):r[k])}</td>`).join('')}<td>${r.ok?chip('ok','قابل قبول'):chip('warn','نیاز به بررسی')}</td></tr>`).join('')}</tbody></table>`}
/* ---------- smart RFQ workflow ---------- */
async function agRfq(B,re,live){const W=AGS.wf;const EQ=[['20GP','۲۰ فوت'],['40GP','۴۰ فوت'],['40HC','۴۰ فوت HC'],['40RF','۴۰ فوت یخچالی']];
 B.innerHTML=`<div class="sx-card"><header><b>استعلام هوشمند محموله</b><small>کارشناس خرید: مقایسهٔ مسیرها ← غربال تحریم ← پیش‌نویس دوزبانهٔ RFQ ← کارتابل تأیید ← ارسال ← جمع‌بندی خودکار پاسخ‌ها ← مذاکره/رزرو با تأیید</small></header>
 <div class="ag-form">${fwI('مبدأ (بندر/شهر چین)','pol',W.pol)}${fwI('مقصد نهایی در ایران','dest',W.dest)}${fwI('کانتینر','eq',W.eq,{opts:EQ})}${fwI('تعداد','qty',W.qty,{t:'number',step:1})}${fwI('وزن هر کانتینر (تن)','weightT',W.weightT,{t:'number',step:1})}${fwI('ارزش کالا (دلار)','value',W.value,{t:'number',step:1000})}${fwI('مهلت تحویل (روز)','deadlineDays',W.deadlineDays,{t:'number',step:1})}${fwI('شرح کالا','commodity',W.commodity)}</div>
 <div class="ag-act"><button class="sx-btn pri" data-plan>ساخت برنامهٔ استعلام</button><button class="sx-btn" data-cmp>فقط مقایسهٔ مسیرها</button>${AGS.res.plan&&AGS.res.plan.id?'<button class="sx-btn" data-col>جمع‌بندی پاسخ‌های رسیده</button>':''}</div></div><div class="ag-out"></div>`;
 fwBind(B,W,()=>agSv());const O=$('.ag-out',B);
 const show=()=>{const p=AGS.res.plan,c=AGS.res.col;let h='';if(p){const o=p.output||{};h+=`<div class="sx-card"><header><b>برنامهٔ استعلام · کار #${fa(p.id)}</b><small>${agSt(p.status)}</small></header>${p.err?`<div class="fw-al bad">${esc(p.err)}</div>`:''}${o.summary?`<div class="fw-al ok">${agTxt(o.summary)}</div>`:''}${agCmpTbl(o.comparison)}${(o.notes||[]).length?`<div class="fw-al warn">${o.notes.map(esc).join('<br>')}</div>`:''}
  ${(o.drafts||[]).map(d=>`<details class="ag-draft"><summary>پیش‌نویس: ${esc(d.title||'')} · ${fa((d.recipients||[]).length)} گیرنده</summary><pre>${esc(d.text||'')}</pre></details>`).join('')}${o.approval?`<div class="ag-act"><button class="sx-btn sm pri" data-goap>بررسی و تأیید ارسال در کارتابل (#${fa(o.approval)})</button></div>`:''}${o.next?`<p class="sx-muted">${esc(o.next)}</p>`:''}</div>`}
  if(c)h+=`<div class="sx-card"><header><b>جمع‌بندی پاسخ‌ها · کار #${fa(c.id)}</b><small>${agSt(c.status)}</small></header>${agOutView(c.output)}${(c.output&&(c.output.negotiation||c.output.booking))?'<button class="sx-btn sm pri" data-goap>کارتابل تأیید</button>':''}</div>`;
  if(AGS.res.cmp)h+=`<div class="sx-card"><header><b>مقایسهٔ مسیرها</b></header>${agCmpTbl(AGS.res.cmp)}</div>`;O.innerHTML=h;$$('[data-goap]',O).forEach(x=>x.onclick=()=>{AGS.tab='ap';AGS.apSt='pending';agSv();re()})};
 const inp=()=>({...W,qty:+W.qty||1,value:+W.value||0,deadlineDays:+W.deadlineDays||0,weightT:+W.weightT||22});
 $('[data-plan]',B).onclick=tmTry(async e=>{e.target.disabled=true;O.innerHTML='<div class="sx-muted">کارشناس خرید در حال مقایسهٔ مسیرها و نوشتن پیش‌نویس‌ها…</div>';try{AGS.res.plan=await agApi.run('procurement','plan',inp(),true);AGS.res.col=null;AGS.res.cmp=null;AGS.ov=null}finally{if(live())re()}});
 $('[data-cmp]',B).onclick=tmTry(async()=>{AGS.res.cmp=await agApi.compareRoutes(inp());show()});
 const cl=$('[data-col]',B);if(cl)cl.onclick=tmTry(async()=>{cl.disabled=true;AGS.res.col=await agApi.run('procurement','collect',{plan:AGS.res.plan.id},true);AGS.ov=null;show();cl.disabled=false});show()}
/* ---------- tools ---------- */
const agB64=f=>new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]||'');r.onerror=()=>no(new Error('خواندن فایل ناموفق بود'));r.readAsDataURL(f)});
async function agFileText(f){const n=f.name.toLowerCase();if(/\.xlsx?$/.test(n)){const R=await readXlsx(await f.arrayBuffer());return {text:R.map(r=>r.map(c=>String(c??'').replace(/[,\n]/g,' ')).join(',')).join('\n')}}
 if(/\.(csv|txt|tsv|eml)$/.test(n)||/^text\//.test(f.type))return {text:await f.text()};if(f.size>12e6)throw new Error('فایل بزرگ‌تر از ۱۲ مگابایت است');return {file:{name:f.name,mime:f.type||(/\.pdf$/.test(n)?'application/pdf':'application/octet-stream'),data:await agB64(f)}}}
async function agTools(B,re){const T=AGS.tool;
 B.innerHTML=`${tmSeg([['qx','استخراج نرخ از ایمیل/فایل'],['doc','کنترل اسناد'],['hs','پیشنهاد کد HS'],['rec','تطبیق صورتحساب'],['cmp','مقایسه و سناریو']],T,'ag-ts')}<div class="ag-tb"></div><div class="ag-tout"></div>`;
 $$('.ag-ts button',B).forEach(x=>x.onclick=()=>{AGS.tool=x.dataset.v;agSv();re()});const tb=$('.ag-tb',B),O=$('.ag-tout',B);
 if(T==='qx'){tb.innerHTML=`<div class="sx-card"><header><b>استخراج پیشنهاد نرخ</b><small>متن ایمیل/تلگرام، جدول Excel/CSV، PDF یا عکس اعلام نرخ</small></header><textarea class="ag-t" rows="7" placeholder="متن پیشنهاد را اینجا بچسبانید…"></textarea><div class="ag-row"><input class="ag-v" placeholder="فرستنده/فورواردر"><input type="file" class="ag-f" accept=".xlsx,.xls,.csv,.txt,.pdf,image/*"><label><input type="checkbox" class="ag-llm" checked> بهبود با مدل زبانی (اگر تنظیم شده)</label><button class="sx-btn pri" data-go>استخراج</button></div><p class="sx-note">عددهایی که مدل برمی‌گرداند باید در متن منبع وجود داشته باشند؛ وگرنه حذف می‌شوند. PDF اسکن‌شده و عکس فقط با مدل دارای بینایی خوانده می‌شود. ثبت در بانک نرخ از راه کارشناس خرید و کارتابل تأیید انجام می‌شود.</p></div>`;
  $('[data-go]',tb).onclick=tmTry(async e=>{const f=$('.ag-f',tb).files[0];let a={text:$('.ag-t',tb).value,vendor:$('.ag-v',tb).value,llm:$('.ag-llm',tb).checked};if(f)Object.assign(a,await agFileText(f),f&&a.text&&!/\.(xlsx?|csv|txt)$/i.test(f.name)?{}:{});if(!a.text&&!a.file)return toast('متن یا فایل لازم است');e.target.disabled=true;O.innerHTML='<div class="sx-muted">در حال استخراج…</div>';try{const r=await agApi.extract(a.text,a);AGS.res.qx=r;O.innerHTML=agQxView(r);agBindSrc(O);const d=$('[data-csv]',O);if(d)d.onclick=()=>dl('quotes.csv','\ufeffvendor,pol,pod,eq,amt,cur,usd,valid,free,days,surcharges\n'+r.quotes.map(q=>[q.vendor,q.pol,q.pod,q.eq,q.amt,q.cur,q.usd,q.valid,q.free,q.days,(q.surcharges||[]).map(s=>s.code+' '+s.amt).join(' ')].map(v=>String(v??'').replace(/,/g,' ')).join(',')).join('\n'),'text/csv')}finally{e.target.disabled=false}})}
 if(T==='doc'){const TY=[['invoice','فاکتور تجاری'],['packing','لیست عدل‌بندی'],['bl','بارنامه'],['co','گواهی مبدأ'],['decl','اظهارنامه']];tb.innerHTML=`<div class="sx-card"><header><b>کنترل سازگاری اسناد حمل</b><small>وزن، تعداد بسته، شمارهٔ کانتینر و پلمپ (با رقم کنترل ISO 6346)، ارزش، اینکوترمز، HS و طرفین</small></header><div class="ag-docs">${[0,1,2,3].map(i=>`<div class="ag-doc"><select>${TY.map(([k,n],j)=>`<option value="${k}" ${j===i?'selected':''}>${n}</option>`).join('')}</select><textarea rows="5" placeholder="متن سند (یا فایل PDF/متنی)"></textarea><input type="file" accept=".pdf,.txt,.csv,.xlsx"></div>`).join('')}</div><button class="sx-btn pri" data-go>بررسی اسناد</button></div>`;
  $('[data-go]',tb).onclick=tmTry(async()=>{const D=[];for(const d of $$('.ag-doc',tb)){let text=$('textarea',d).value;const f=$('input',d).files[0];if(f){const x=await agFileText(f);if(x.file){if(!/pdf/.test(x.file.mime))throw new Error('برای سند تصویری از مدل دارای بینایی در «استخراج» استفاده کنید');const p=await agApi.tool('pdf_text',{data:x.file.data});if(p.note)toast(p.note);text=(text+'\n'+p.text).trim()}else text=(text+'\n'+x.text).trim()}if(text.trim())D.push({type:$('select',d).value,name:f?f.name:undefined,text})}if(D.length<2)return toast('حداقل دو سند لازم است');const r=await agApi.docsCheck(D);
   O.innerHTML=`<div class="sx-card"><header><b>${r.ok?'✅ ناسازگاری جدی پیدا نشد':'⚠️ '+fa(r.issues.length)+' مورد برای بررسی'}</b></header>${r.issues.map(i=>`<div class="fw-al ${i.sev==='high'?'bad':i.sev==='med'?'warn':''}">${chip(i.sev==='high'?'bad':i.sev==='med'?'warn':'',i.sev==='high'?'جدی':i.sev==='med'?'متوسط':'جزئی')} ${esc(i.msg)}</div>`).join('')}<table class="sx-tbl"><thead><tr><th>فیلد</th>${r.docs.map(d=>`<th>${esc(d.name)}</th>`).join('')}</tr></thead><tbody>${Object.keys(r.docs[0].fields).map(k=>`<tr><td>${esc(k)}</td>${r.docs.map(d=>{const v=d.fields[k];return `<td>${esc(Array.isArray(v)?v.join('، '):v==null?'—':String(v))}</td>`}).join('')}</tr>`).join('')}</tbody></table></div>`})}
 if(T==='hs'){tb.innerHTML=`<div class="sx-card"><header><b>پیشنهاد کد HS</b><small>۶ رقم جهانی با درجهٔ اطمینان؛ کد ۸ رقمی را با کتاب مقررات تطبیق دهید</small></header><div class="ag-row"><input class="ag-h" placeholder="شرح کالا به فارسی یا انگلیسی، مثلاً پنل خورشیدی ۵۵۰ وات"><button class="sx-btn pri" data-go>پیشنهاد</button></div></div>`;
  const go=tmTry(async()=>{const v=$('.ag-h',tb).value.trim();if(!v)return;const r=await agApi.hs(v);O.innerHTML=`<div class="sx-card">${r.candidates.length?`<table class="sx-tbl"><thead><tr><th>کد</th><th>عنوان</th><th>اطمینان</th><th>واژه‌های منطبق</th></tr></thead><tbody>${r.candidates.map(c=>`<tr><td><b>${esc(c.code)}</b>${c.dualUse?' '+chip('bad','کالای دوکاربردی؟'):''}</td><td>${esc(c.name)}</td><td>${fa(Math.round(c.confidence*100))}٪</td><td>${esc((c.matched||[]).join('، '))}</td></tr>`).join('')}</tbody></table>`:'<p class="sx-muted">پیشنهادی پیدا نشد؛ شرح دقیق‌تر بنویسید.</p>'}<p class="sx-note">${esc(r.caveat||'')}</p></div>`});$('[data-go]',tb).onclick=go;$('.ag-h',tb).onkeydown=e=>{if(e.key==='Enter')go()}}
 if(T==='rec'){tb.innerHTML=`<div class="sx-card"><header><b>تطبیق صورتحساب حمل با پیشنهاد قیمت</b><small>کرایهٔ پایه، سرشارژ اعلام‌نشده، سقف WRS، تعداد و ارز</small></header><div class="ag-form">${['شمارهٔ صورتحساب|no','فورواردر|vendor','نرخ پیشنهادی هر واحد|amt','ارز|cur','تعداد کانتینر|qty','سرشارژهای مشمول (مثل BAF,THC)|incl','سقف WRS هر واحد|cap'].map(s=>{const [l,k]=s.split('|');return `<label class="sx-f"><span>${l}</span><input data-r="${k}" value="${k==='cur'?'USD':k==='qty'?'1':''}"></label>`}).join('')}</div><textarea class="ag-il" rows="6" placeholder="ردیف‌های صورتحساب: هر خط «شرح, مبلغ, ارز, تعداد» — یا متن کامل صورتحساب"></textarea><button class="sx-btn pri" data-go>تطبیق</button></div>`;
  $('[data-go]',tb).onclick=tmTry(async()=>{const g=k=>($(`[data-r="${k}"]`,tb).value||'').trim();const raw=$('.ag-il',tb).value.trim();if(!raw)return toast('ردیف‌های صورتحساب لازم است');const rows=raw.split('\n').map(l=>l.split(/[,;\t]/).map(x=>x.trim()));const lines=rows.every(r=>r.length>=2&&!isNaN(parseFloat(r[1])))?rows.map(r=>({desc:r[0],amt:parseFloat(r[1]),cur:r[2]||g('cur')||'USD',qty:+r[3]||1})):null;
   const r=await agApi.reconcile({no:g('no'),...(lines?{lines}:{text:raw})},{vendor:g('vendor'),amt:+g('amt')||0,cur:g('cur')||'USD',qty:+g('qty')||1,incl:g('incl')},{qty:+g('qty')||1,...(g('cap')?{wrsCap:+g('cap')}:{})});
   O.innerHTML=`<div class="sx-card"><header><b>${r.ok?'✅ صورتحساب با پیشنهاد می‌خواند':'⚠️ مبلغ مورد اختلاف: '+agUsd(r.disputeUSD)}</b><small>جمع صورتحساب ${agUsd(r.totalUSD)}</small></header>${r.issues.map(i=>`<div class="fw-al ${i.sev==='high'?'bad':'warn'}">${esc(i.msg)}</div>`).join('')}<table class="sx-tbl"><thead><tr><th>شرح</th><th>نوع</th><th>کد</th><th>مبلغ</th><th>تعداد</th><th>دلار</th></tr></thead><tbody>${r.lines.map(l=>`<tr><td>${esc(l.desc)}</td><td>${l.kind==='base'?'کرایهٔ پایه':l.kind==='surcharge'?'سرشارژ':esc(l.kind||'')}</td><td>${esc(l.code||'')}</td><td>${nf(l.amt)} ${esc(l.cur)}</td><td>${fa(l.qty||1)}</td><td>${agUsd(l.usd)}</td></tr>`).join('')}</tbody></table>${r.draft?`<label class="sx-f"><span>پیش‌نویس اعتراض به فورواردر (ارسال فقط از راه عامل مالی و تأیید)</span><textarea rows="8">${esc(r.draft)}</textarea></label>`:''}</div>`})}
 if(T==='cmp'){const W=AGS.wf,S=AGS.sc;const R=(AGS.ov.routes||[]);tb.innerHTML=`<div class="sx-card"><header><b>مقایسهٔ مسیرها و سناریوی «اگر…»</b><small>هزینهٔ کل = کرایهٔ اصلی + حمل داخلی رسمی + هزینهٔ نگهداری موجودی در راه + ریسک</small></header><div class="ag-form">${fwI('مبدأ','pol',W.pol)}${fwI('مقصد','dest',W.dest)}${fwI('کانتینر','eq',W.eq,{opts:[['20GP','۲۰ فوت'],['40GP','۴۰ فوت'],['40HC','۴۰ HC']]})}${fwI('تعداد','qty',W.qty,{t:'number'})}${fwI('ارزش کالا $','value',W.value,{t:'number'})}${fwI('مهلت (روز)','deadlineDays',W.deadlineDays,{t:'number'})}</div>
  <div class="ag-scn"><b>سناریو:</b> ${R.map(r=>`<label><input type="checkbox" data-cl="${r.id}" ${(S.closed||[]).includes(r.id)?'checked':''}> بسته شدن ${esc(r.name)}</label>`).join('')}<label class="sx-f"><span>تغییر کرایهٔ دریایی ٪</span><input type="number" data-s="seaPct" value="${+S.seaPct||0}"></label><label class="sx-f"><span>تغییر نرخ ارز ٪</span><input type="number" data-s="fxPct" value="${+S.fxPct||0}"></label></div><button class="sx-btn pri" data-go>مقایسه</button></div>`;
  fwBind($('.ag-form',tb),W,()=>agSv());$('[data-go]',tb).onclick=tmTry(async()=>{S.closed=$$('[data-cl]',tb).filter(x=>x.checked).map(x=>x.dataset.cl);S.seaPct=+$('[data-s="seaPct"]',tb).value||0;S.fxPct=+$('[data-s="fxPct"]',tb).value||0;agSv();
   const sc={...(S.closed.length?{closed:S.closed}:{}),...(S.seaPct?{freightPct:{sea:S.seaPct}}:{}),...(S.fxPct?{fxPct:S.fxPct}:{})};const base={...W,qty:+W.qty||1,value:+W.value||0,deadlineDays:+W.deadlineDays||0};
   const [a,c]=await Promise.all([agApi.compareRoutes(base),Object.keys(sc).length?agApi.compareRoutes({...base,scenario:sc}):null]);const bn=x=>(x.routes.find(r=>r.id===x.best)||{});
   O.innerHTML=`<div class="sx-card"><header><b>وضع فعلی</b><small>پیشنهادی: ${esc(bn(a).name||'—')} · ${agUsd(bn(a).totalUSD)}</small></header>${agCmpTbl(a)}</div>${c?`<div class="sx-card"><header><b>با سناریو</b><small>پیشنهادی: ${esc(bn(c).name||'—')} · ${agUsd(bn(c).totalUSD)} (${(bn(c).totalUSD||0)>=(bn(a).totalUSD||0)?'+':''}${agUsd((bn(c).totalUSD||0)-(bn(a).totalUSD||0))})</small></header>${agCmpTbl(c)}</div>`:''}`})}}
function agQxView(r){return `<div class="sx-card"><header><b>${fa(r.quotes.length)} پیشنهاد استخراج شد</b><small>روش: ${esc(r.how||'rules')}${r.lane&&r.lane.pol?' · مسیر: '+esc(r.lane.pol)+' → '+esc(r.lane.pod||'?'):''}</small></header>${(r.injection||[]).length?`<div class="fw-al bad">نشانهٔ تزریق دستور در متن: ${r.injection.map(esc).join(' | ')} — این متن فقط به‌عنوان داده خوانده شد.</div>`:''}${(r.flags||[]).length?`<div class="fw-al warn">${r.flags.map(esc).join('<br>')}</div>`:''}
 ${r.quotes.length?`<table class="sx-tbl"><thead><tr><th>مبدأ</th><th>مقصد</th><th>کانتینر</th><th>مبلغ</th><th>دلار</th><th>اعتبار</th><th>روز آزاد</th><th>ترانزیت</th><th>سرشارژها</th><th>اطمینان</th></tr></thead><tbody>${r.quotes.map(q=>`<tr><td>${esc(q.pol||'?')}</td><td>${esc(q.pod||'?')}</td><td>${esc(q.eq)}${q.eqGuess?' '+chip('warn','حدس'):''}</td><td>${nf(q.amt)} ${esc(q.cur)}</td><td>${agUsd(q.usd)}</td><td>${esc(q.valid||'—')}</td><td>${q.free!=null?fa(q.free):'—'}</td><td>${q.days?fa(q.days):'—'}</td><td>${(q.surcharges||[]).map(s=>esc(s.code)+(s.incl?' (شامل)':' '+nf(s.amt))).join('، ')||'—'}${q.allin?' '+chip('ok','All-in'):''}</td><td>${fa(Math.round((q.conf||0)*100))}٪</td></tr>`).join('')}</tbody></table><button class="sx-btn sm" data-csv>دریافت CSV</button>`:''}
 ${(r.surcharges||[]).length&&!r.quotes.length?`<p>سرشارژها: ${r.surcharges.map(s=>esc(s.code)+' '+nf(s.amt)+' '+esc(s.cur||'')).join('، ')}</p>`:''}${(r.notes||[]).length?`<p class="sx-muted">${r.notes.map(esc).join('<br>')}</p>`:''}${agSrc(r.sources)}</div>`}
/* ---------- corridors ---------- */
async function agRoutes(B,re,live){const r=await agApi.routes();if(!live())return;const STS=[['open','باز'],['caution','احتیاط'],['closed','بسته']];const RST=Object.fromEntries(STS);
 B.innerHTML=`<div class="sx-card"><header><b>وضعیت کریدورهای چین → ایران</b><small>عامل ریسک از خبرهای منابع مجاز پیشنهاد تغییر می‌دهد (با تأیید)؛ تغییر دستی هم ثبت و اعلان می‌شود</small></header><table class="sx-tbl"><thead><tr><th>کریدور</th><th>وضعیت</th><th>دلیل / منبع</th><th>از</th><th>تغییر</th></tr></thead><tbody>${r.routes.map(x=>`<tr data-id="${esc(x.id)}"><td><b>${esc(x.name)}</b><br><small class="sx-muted">${esc((x.modes||[]).map(m=>({sea:'دریا',rail:'ریل',road:'جاده',air:'هوا'})[m]||m).join(' + '))} · ${fa(x.days&&x.days[0]||'')}${x.days&&x.days[1]?'–'+fa(x.days[1]):''} روز</small></td><td>${chip(x.status==='open'?'ok':x.status==='closed'?'bad':'warn',esc(x.statusFa))}</td><td><small>${esc(x.reason||'—')}${x.source?' · '+esc(x.source):''}${x.by?' · '+esc(x.by):''}</small></td><td><small>${x.since?tmDt(x.since):'—'}</small></td><td><select>${STS.map(([k,n])=>`<option value="${k}" ${k===x.status?'selected':''}>${n}</option>`).join('')}</select><input placeholder="دلیل" class="ag-rr"><button class="sx-btn xs" data-set>ثبت</button></td></tr>`).join('')}</tbody></table></div>
 <div class="sx-card"><header><b>تاریخچهٔ تغییرات</b></header>${(r.hist||[]).length?`<table class="sx-tbl"><tbody>${r.hist.map(h=>`<tr><td><small>${tmDt(h.ts)}</small></td><td>${esc((r.routes.find(x=>x.id===h.id)||{}).name||h.id)}</td><td>${esc(RST[h.from]||h.from||'')} → <b>${esc(RST[h.to]||h.to||'')}</b></td><td><small>${esc(h.reason||'')}${h.source&&h.source!=='manual'?' · '+esc(String(h.source).slice(0,90)):''}</small></td><td><small>${esc(h.by||'')}</small></td></tr>`).join('')}</tbody></table>`:'<p class="sx-muted">تغییری ثبت نشده است.</p>'}</div>`;
 $$('tr[data-id] [data-set]',B).forEach(x=>x.onclick=tmTry(async()=>{const tr=x.closest('tr');const st=$('select',tr).value,rs=$('.ag-rr',tr).value.trim();if(st!=='open'&&!rs)return toast('دلیل تغییر را بنویسید');await agApi.setRouteStatus(tr.dataset.id,st,rs);toast('وضعیت مسیر ثبت شد');AGS.ov=null;re()}))}
/* ---------- settings: model, policy, MCP ---------- */
async function agCfgUI(B,re,live){const O=AGS.ov,C=O.cfg||{};let K=[];try{K=await agApi.keys()}catch(e){}if(!live())return;const L=O.llm;const PV=L.providers.filter(p=>!p.env).map(p=>({...p,key:p.hasKey?'***':''}));const envP=L.providers.find(p=>p.env);
 const prow=(p,i)=>`<tr data-i="${i}"><td><input data-p="id" value="${esc(p.id)}" size="8"></td><td><select data-p="kind">${[['openai','OpenAI-سازگار (OpenAI، OpenRouter، vLLM، LM Studio، DeepSeek…)'],['anthropic','Anthropic'],['ollama','Ollama (محلی)']].map(([k,n])=>`<option value="${k}" ${k===p.kind?'selected':''}>${n}</option>`).join('')}</select></td><td><input data-p="url" value="${esc(p.url||'')}" placeholder="https://api.openai.com/v1"></td><td><input data-p="model" value="${esc(p.model||'')}" size="12"></td><td><input data-p="key" type="password" value="${esc(p.key||'')}" placeholder="کلید API" autocomplete="off"></td><td><input type="checkbox" data-p="local" ${p.local?'checked':''}></td><td><input type="checkbox" data-p="vision" ${p.vision?'checked':''}></td><td><input data-p="priceIn" type="number" step="0.01" value="${p.priceIn||0}" size="4"> / <input data-p="priceOut" type="number" step="0.01" value="${p.priceOut||0}" size="4"></td><td><button class="sx-btn xs" data-test="${esc(p.id)}">آزمون</button><button class="sx-btn xs" data-del>✕</button></td></tr>`;
 const ids=[...(envP?[['env','env · '+envP.model]]:[]),...PV.map(p=>[p.id,p.id+' · '+p.model])];
 const mcpUrl=svUrl()+'/mcp';
 B.innerHTML=`<div class="sx-card"><header><b>مدل زبانی</b><small>بدون مدل هم همه‌چیز کار می‌کند (قاعده‌محور)؛ مدل فقط فهم متن آزاد و نگارش را بهتر می‌کند. هر عدد خروجی مدل باید منبع داشته باشد.</small></header>
 ${envP?`<div class="fw-al">مدل تعریف‌شده روی سرور (فایل <code>.env</code> یا متغیرهای محیطی): <b>${esc(envP.label||envP.kind)} · ${esc(envP.model)}</b> · <span dir="ltr">${esc(String(envP.url||'').replace(/^(https?:\/\/[^/]+).*/,'$1'))}</span> ${envP.local?'(محلی)':'(ابری)'} ${envP.vision?chip('ok','بینایی'):''} ${envP.hasKey?chip('ok','کلید روی سرور'):chip('bad','بدون کلید')} <button class="sx-btn xs" data-test="env">آزمون اتصال</button><div class="ag-tres"></div> — کلید هرگز به مرورگر فرستاده نمی‌شود.</div>`:''}
 <table class="sx-tbl ag-prov"><thead><tr><th>شناسه</th><th>نوع</th><th>نشانی API</th><th>مدل</th><th>کلید</th><th>محلی</th><th>بینایی</th><th>قیمت ورودی/خروجی ($/1M)</th><th></th></tr></thead><tbody>${PV.map(prow).join('')}</tbody></table><button class="sx-btn xs" data-add>+ افزودن مدل</button>
 <div class="ag-form">${fwI('مدل پیش‌فرض','use',L.use||'',{opts:[['','نخستین مدل'],['none','هیچ (قاعده‌محور)'],...ids]})}${fwI('مدل دادهٔ حساس (ترجیحاً محلی)','sensitive',L.sensitive||'',{opts:[['','همان پیش‌فرض'],...ids]})}${fwI('سقف توکن پاسخ','maxTokens',L.maxTokens||1400,{t:'number'})}</div>
 <label><input type="checkbox" data-c="mask" ${O.mask?'checked':''}> پوشاندن اطلاعات شخصی (ایمیل، تلفن، شناسه‌ها) پیش از ارسال به مدل ابری</label></div>
 <div class="sx-card"><header><b>سیاست و بودجه</b></header><div class="ag-form">
 <label class="sx-f"><span>دامنه‌های مجاز برای خواندن وب/خبر (هر خط یکی)</span><textarea data-c="allow" rows="4" dir="ltr">${esc((C.allow||[]).join('\n'))}</textarea></label><label class="sx-f"><span>خوراک‌های خبری RSS (هر خط یکی)</span><textarea data-c="feeds" rows="4" dir="ltr">${esc((C.feeds||[]).join('\n'))}</textarea></label>
 <label class="sx-f"><span>سقف توافقی WRS هر واحد ($؛ ۰ = بدون سقف)</span><input type="number" data-c="wrsCap" value="${C.wrsCap??''}"></label><label class="sx-f"><span>هزینهٔ نگهداری موجودی (٪ سالانه)</span><input type="number" data-c="carry" value="${C.carry??''}"></label><label class="sx-f"><span>آستانهٔ گرانی نسبت به میانه (کسر؛ 0.15 = ۱۵٪)</span><input type="number" data-c="devHi" value="${C.devHi??''}"></label><label class="sx-f"><span>آستانهٔ ارزانی مشکوک (کسر منفی؛ 0.2- = ۲۰٪)</span><input type="number" data-c="devLo" value="${C.devLo??''}"></label><label class="sx-f"><span>مهلت کارتابل تأیید (ساعت)</span><input type="number" data-c="approvalHours" value="${C.approvalHours??''}"></label></div>
 <label><input type="checkbox" data-c="sched" ${O.sched?'checked':''}> اجرای زمان‌بندی‌شدهٔ خودکار عامل‌ها</label> <label><input type="checkbox" data-c="tg" ${C.tg?'checked':''}> خواندن پیام‌های ربات بله/تلگرام در صندوق نرخ</label>
 <details><summary>پیشرفته: بودجهٔ عامل‌ها، درصد ریسک و هزینهٔ پایهٔ کریدورها (JSON)</summary><label class="sx-f"><span>budget</span><textarea data-j="budget" rows="4">${agJ(C.budget||{})}</textarea></label><label class="sx-f"><span>riskPct</span><textarea data-j="riskPct" rows="3">${agJ(C.riskPct||{})}</textarea></label><label class="sx-f"><span>routeBase (کرایهٔ پیش‌فرض هر کریدور — فرض قابل‌تنظیم، نه نرخ بازار)</span><textarea data-j="routeBase" rows="4">${agJ(C.routeBase||{})}</textarea></label></details>
 <div class="ag-act"><button class="sx-btn pri" data-save>ذخیرهٔ تنظیمات</button></div></div>
 <div class="sx-card"><header><b>اتصال MCP</b><small>Claude Desktop، Cursor یا هر کلاینت MCP می‌تواند ابزارهای سامانهٔ آسانا را با همین سیاست‌ها و کارتابل تأیید صدا بزند</small></header>
 <p>نشانی: <code>${esc(mcpUrl)}</code> · هدر: <code>Authorization: Bearer ifa_mcp_…</code></p><pre class="ag-pre" dir="ltr">${esc(JSON.stringify({mcpServers:{'asana-logistics':{command:'npx',args:['-y','mcp-remote',mcpUrl,'--header','Authorization:${IFA_KEY}'],env:{IFA_KEY:'Bearer ifa_mcp_…'}}}},null,2))}</pre>
 <div class="ag-row"><input class="ag-kn" placeholder="نام کلید (مثلاً Claude مدیر فروش)"><select class="ag-kr">${Object.entries(ROLEF).map(([k,n])=>`<option value="${k}" ${k==='viewer'?'selected':''}>${n}</option>`).join('')}</select><select class="ag-kl">${AGLV.slice(0,3).map((n,i)=>`<option value="${i}" ${i===1?'selected':''}>${n}</option>`).join('')}</select><button class="sx-btn sm pri" data-key>ساخت کلید</button></div><div class="ag-newkey"></div>
 <table class="sx-tbl"><thead><tr><th>نام</th><th>نقش</th><th>سطح</th><th>ساخته</th><th>آخرین استفاده</th><th></th></tr></thead><tbody>${K.map(k=>`<tr class="${k.revoked?'ag-closed':''}"><td>${esc(k.name)}</td><td>${esc(ROLEF[k.role]||k.role)}</td><td>${fa(k.level)}</td><td><small>${tmDt(k.created)} · ${esc(k.by||'')}</small></td><td><small>${k.last_used?tmDt(k.last_used):'—'}</small></td><td>${k.revoked?chip('bad','باطل'):`<button class="sx-btn xs" data-rk="${k.id}">ابطال</button>`}</td></tr>`).join('')||'<tr><td colspan="6" class="sx-muted">کلیدی ساخته نشده است.</td></tr>'}</tbody></table></div>`;
 const LS={use:L.use||'',sensitive:L.sensitive||'',maxTokens:L.maxTokens||1400};fwBind($('.ag-form',B),LS,()=>{});
 const tb=$('.ag-prov tbody',B);const readP=()=>$$('tr',tb).map(tr=>{const o={};$$('[data-p]',tr).forEach(x=>{o[x.dataset.p]=x.type==='checkbox'?x.checked:x.type==='number'?+x.value||0:x.value.trim()});return o}).filter(p=>p.id);
 $('[data-add]',B).onclick=()=>{tb.insertAdjacentHTML('beforeend',prow({id:'m'+(tb.children.length+1),kind:'openai',url:'',model:'',key:''},tb.children.length));bindRow()};
 const bindRow=()=>{$$('[data-del]',tb).forEach(x=>x.onclick=()=>x.closest('tr').remove())};bindRow();
 $$('[data-test]',B).forEach(x=>x.onclick=tmTry(async()=>{x.disabled=true;const r=await agApi.testModel(x.dataset.test).finally(()=>x.disabled=false);toast(r.ok?'✅ '+r.model+' پاسخ داد ('+fa(r.ms)+' ms)':'❌ '+r.error);const o=$('.ag-tres',B);if(o)o.innerHTML=r.ok?`<div class="fw-al ${r.overhead?'warn':'ok'}">✅ ${esc(r.served||r.model)} · ${fa(r.ms)} ms · JSON ${r.json?'درست':'نادرست'} · فارسی ${r.fa?'درست':'نادرست'} · ورودی ${nf(r.tin)} / خروجی ${nf(r.tout)} توکن · هزینهٔ تقریبی ${r.costUSD}$${r.note?'<br>'+esc(r.note):''}</div>`:`<div class="fw-al bad">❌ ${esc(r.error||'')}</div>`}));
 $('[data-save]',B).onclick=tmTry(async()=>{const c=k=>$(`[data-c="${k}"]`,B);const p={llm:{providers:readP(),use:LS.use,sensitive:LS.sensitive,maxTokens:+LS.maxTokens||1400},mask:c('mask').checked,sched:c('sched').checked,tg:c('tg').checked,allow:c('allow').value.split('\n'),feeds:c('feeds').value.split('\n')};
  for(const k of ['wrsCap','carry','devHi','devLo','approvalHours'])if(c(k).value!=='')p[k]=+c(k).value;for(const x of $$('[data-j]',B)){try{p[x.dataset.j]=JSON.parse(x.value||'{}')}catch(e){return toast('JSON «'+x.dataset.j+'» نامعتبر است')}}
  AGS.ov=await agApi.config(p);toast('تنظیمات عامل‌ها ذخیره شد');re()});
 $('[data-key]',B).onclick=tmTry(async()=>{const r=await agApi.createKey($('.ag-kn',B).value.trim()||'MCP',$('.ag-kr',B).value,+$('.ag-kl',B).value);$('.ag-newkey',B).innerHTML=`<div class="fw-al ok">کلید ساخته شد — فقط همین یک بار نمایش داده می‌شود:<br><code dir="ltr" class="ag-k">${esc(r.key)}</code> <button class="sx-btn xs" data-cp>کپی</button></div>`;$('[data-cp]',B).onclick=()=>{navigator.clipboard&&navigator.clipboard.writeText(r.key);toast('کپی شد')}});
 $$('[data-rk]',B).forEach(x=>x.onclick=tmTry(async()=>{if(!confirm('این کلید باطل شود؟'))return;await agApi.revokeKey(x.dataset.rk);re()}))}
(()=>{const st=document.createElement('style');st.textContent=`.ag-w{display:flex;flex-direction:column;gap:10px}.ag-sub{flex-wrap:wrap}.ag-b{display:flex;flex-direction:column;gap:10px}.ag-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(290px,1fr));gap:10px}.ag-card .ag-d{font-size:12px;line-height:1.8;color:var(--muted);margin:6px 0}.ag-card header small{display:flex;flex-wrap:wrap;gap:4px;margin-top:4px}.ag-paused{opacity:.65}.ag-use{position:relative;font-size:11px;color:var(--faint);padding-bottom:6px}.ag-use i{position:absolute;bottom:0;right:0;height:3px;border-radius:3px;background:var(--accent,#3b82f6)}.ag-last{font-size:11.5px;margin:6px 0}.ag-kinds{display:flex;flex-wrap:wrap;gap:4px;margin:6px 0}.ag-adm{display:flex;flex-wrap:wrap;gap:10px;align-items:center;font-size:12px;border-top:1px dashed var(--line);padding-top:6px}.ag-adm select{font:inherit;font-size:11.5px}.ag-more{font-size:12px}.ag-killbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.ag-stop{border-color:var(--bad,#dc2626)!important;color:var(--bad,#dc2626)!important}
.ag-row{display:flex;flex-wrap:wrap;gap:8px;align-items:center;margin:6px 0}.ag-row input:not([type=checkbox]),.ag-act input{flex:1;min-width:160px}.ag-act{display:flex;flex-wrap:wrap;gap:6px;align-items:center;margin-top:8px}.ag-draft pre,.ag-pre,.ag-ap pre,.ag-det pre{white-space:pre-wrap;font-size:11.5px;background:var(--panel2);border:1px solid var(--line);border-radius:8px;padding:8px;max-height:260px;overflow:auto;unicode-bidi:plaintext;text-align:start}.ag-kv{display:flex;flex-wrap:wrap;gap:6px;font-size:11.5px;margin:6px 0}.ag-kv span{background:var(--hover);border-radius:6px;padding:2px 6px}.ag-hard{border-inline-start:3px solid var(--warn,#d97706)}.ag-args{width:100%;font:11px monospace;direction:ltr}
.ag-src{display:flex;flex-wrap:wrap;gap:4px;align-items:center;margin-top:8px;font-size:11px}.ag-s{background:var(--hover);border-radius:6px;padding:2px 7px;color:var(--muted)}.ag-s[data-view]{cursor:pointer}.ag-s[data-view]:hover{color:var(--ink,inherit)}.ag-ans{line-height:2;font-size:13.5px;margin:6px 0}.ag-askf{display:flex;gap:8px;align-items:stretch}.ag-askf textarea{flex:1;font:inherit;resize:vertical}.ag-sug,.ag-links{display:flex;flex-wrap:wrap;gap:4px;margin-top:8px}
.ag-split{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.25fr);gap:10px;align-items:start}.ag-tl-l{max-height:72vh;overflow:auto}.ag-tl-l tr[data-id]{cursor:pointer}.ag-tl-l tr.on{background:var(--hover)}.ag-steps code{font-size:10.5px;word-break:break-all;direction:ltr;display:block;text-align:left}.ag-steps tr.bad{background:color-mix(in srgb,var(--bad,#dc2626) 8%,transparent)}
.ag-form{display:grid;grid-template-columns:repeat(auto-fill,minmax(170px,1fr));gap:8px;margin:8px 0}.ag-form textarea{width:100%;font:inherit}.ag-cmp td,.ag-cmp th{font-size:11.5px;vertical-align:top}.ag-best{background:color-mix(in srgb,var(--good,#16a34a) 9%,transparent)}.ag-closed{opacity:.55}.ag-scn{display:flex;flex-wrap:wrap;gap:10px;align-items:center;font-size:12px;margin:6px 0}.ag-docs{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:8px;margin:8px 0}.ag-doc{display:flex;flex-direction:column;gap:4px}.ag-doc textarea,.ag-tb textarea{width:100%;font:inherit;font-size:12px}.ag-ts{flex-wrap:wrap;margin-bottom:8px}
.ag-prov input:not([type=checkbox]),.ag-prov select{font:inherit;font-size:11.5px;max-width:100%}.ag-prov td{vertical-align:middle}.ag-k{word-break:break-all;user-select:all}@media(max-width:900px){.ag-split{grid-template-columns:1fr}.ag-askf{flex-direction:column}}`;document.head.appendChild(st)})();
