/* ===== v15.8: official domestic road tariff (tonne-km) engine · market check · tariff watch · waybill import ===== */
const DTKT=[[75,387810],[100,476650],[150,654300],[200,766050],[250,877800],[300,989550],[350,1081300],[400,1173050],[450,1264800],[500,1344050],[550,1423300],[600,1502550],[650,1581800],[700,1661050],[750,1740300],[800,1806200],[850,1872100],[900,1938000],[950,2003900],[1000,2069800],[1050,2135700],[1100,2191550],[1150,2247400],[1200,2303250],[1250,2359100],[1300,2414950],[1350,2470800],[1400,2526650],[1450,2582500],[1500,2638350],[1550,2685050],[1600,2731750],[1650,2778450],[1700,2825150],[1750,2871850],[1800,2918550],[1850,2965250],[1900,3011950],[1950,3058650],[2000,3100350]];/* net driver rate, toman per tonne, at the 1,668-toman index (1405 table) */
const DTKI=1668;
const DT0=[{id:'1402-02-31',from:'2023-05-21',tkm:5500,src:'سازمان راهداری (تین‌نیوز، ۳۱ اردیبهشت ۱۴۰۲)'},{id:'1403-03',from:'2024-06-01',tkm:7150,ap:1,src:'جدول نرخ خالص بر مبنای شاخص ۷۱۵ تومان (تین‌نیوز، ۲۶ خرداد ۱۴۰۳) — تاریخ اجرا تقریبی'},{id:'1404-03-24',from:'2025-06-14',tkm:11040,src:'سامانهٔ سازمان راهداری از ۲۴ خرداد ۱۴۰۴'},{id:'1404-10-18',from:'2026-01-08',tkm:13190,src:'مصوبهٔ ۲۳۴ شورای عالی هماهنگی ترابری (۱۷ دی ۱۴۰۴)'},{id:'1405-03-15',from:'2026-06-05',tkm:16680,src:'سازمان راهداری — مصوبهٔ شورای عالی هماهنگی ترابری (خبرگزاری مهر، ۱۳ خرداد ۱۴۰۵)',url:'https://www.mehrnews.com/news/6848782'}];
const DTSTOP0={sgl:71081000,dbl:84033000,from:'2026-08-01',src:'گزارش صنفی مرداد ۱۴۰۵ — پیش از استناد با بخشنامهٔ رسمی تطبیق دهید',ver:0};
const DTF0={trl:{c:1,st:'dbl',mt:0},ctn:{c:1,st:'dbl',mt:0},rf:{c:1,st:'dbl',mt:0},ten:{c:1,st:'dbl',mt:0},sgl:{c:1,st:'sgl',mt:0},van:{c:1,st:'sgl',mt:0}};
const DTOFF=['trl','ctn','rf'];/* official table is published for 12/18-wheel tractor-trailers */
const DTKIND={tkm:'شاخص تن-کیلومتر',stop:'حق توقف',rail:'تعرفهٔ ریلی',port:'تعرفهٔ بندری',toll:'عوارض آزادراه',fuel:'سوخت ناوگان',comm:'کمیسیون/عوارض بارنامه',freight:'کرایهٔ حمل'};
function dtK(km){km=Math.max(0,+km||0);const T=DTKT;if(km<=T[0][0])return T[0][1]/DTKI;for(let i=1;i<T.length;i++)if(km<=T[i][0]){const [a,x]=T[i-1],[b,y]=T[i];return (x+(y-x)*(km-a)/(b-a))/DTKI}const n=T.length,s=(T[n-1][1]-T[n-2][1])/(T[n-1][0]-T[n-2][0]);return (T[n-1][1]+s*(km-T[n-1][0]))/DTKI}
const dtStore=()=>{const o=LSG('ifa-dtar',null);return o&&typeof o==='object'?o:{}};
function dtVers(){const M=new Map();for(const x of [...DT0,...(Array.isArray(dtStore().v)?dtStore().v:[])])if(x&&x.from&&+x.tkm>0)M.set(x.from,x);return [...M.values()].sort((a,b)=>a.from<b.from?-1:1)}
function dtIdx(d){const s=String(d||fwToday()).slice(0,10);const V=dtVers();let r=V[0];for(const v of V)if(v.from<=s)r=v;return r}
const dtCur=()=>dtIdx(fwToday());
const dtAdjF=d=>{const a=dtIdx(d).tkm,b=dtCur().tkm;return a>0?b/a:1};
const dtStop=()=>Object.assign({},DTSTOP0,dtStore().stop||{});
const dtFleet=()=>{const o=LSG('ifa-dom-f',{})||{};const r={};for(const k of new Set([...Object.keys(DTF0),...Object.keys(o)]))r[k]=Object.assign({c:1,st:'dbl',mt:0},DTF0[k]||{},o[k]||{});return r};
const dtOn=S=>{const o=S&&S.off!=null?S.off:LSG('ifa-dom',{}).off;return o==null||+o!==0};
function dtStopCost(days,cls){days=+days||0;if(days<=0)return 0;const b=+dtStop()[cls==='sgl'?'sgl':'dbl']||0;let c=0;const P=Math.ceil(days/2);for(let p=1;p<=P;p++){const d=p*2;c+=b*(p===1?1:d>30?1.7:d>10?1.4:1.3)}return c}
const DTDEF={off:1,com:8,levy:0,ins:.05,val:0,load:15000000,toll:3000000,wgh:0,stop:0,mtn:0,prt:0,dg:0,ret:0,ssn:0,qs:100,fq:3000,ffp:6000,fx:20,rr:4500,rh:2500000,offer:0};
function dtCalc(S0,T=dmTypes()){const S=Object.assign({},DTDEF,S0||{});const t=T.find(x=>x[0]===S.ty)||T[0];const F=dtFleet()[t[0]]||{c:1,st:'dbl',mt:0};
 const km=+S.km||dmKm(S.from,S.to);const tons=Math.max(.1,+S.tons||t[2]);const n=Math.max(1,Math.ceil(tons/t[2]));const tt=tons/n;const ch=Math.max(tt,+F.mt||0);
 const V=dtIdx(S.date);const K=dtK(km);const adj=(+S.mtn||0)+(+S.prt||0)+(+S.dg||0)+(+S.ret||0)+(+S.ssn||0);
 const floor=K*V.tkm*ch*(+F.c||1);const net=floor*(1+adj/100);const com=net*(+S.com||0)/100;const levy=net*(+S.levy||0)/100;const insr=(+S.val||0)*(+S.ins||0)/100/n;
 const extra=(+S.load||0)+(+S.toll||0)+(+S.wgh||0);const stop=dtStopCost(S.stop,F.st);const per=net+com+levy+insr+extra+stop;const tot=per*n;
 const L=km*t[4]/100,qs=Math.min(100,Math.max(0,S.qs==null?100:+S.qs))/100;const fuel=L*(qs*(+S.fq||0)+(1-qs)*(+S.ffp||0));const fuelFree=L*(+S.ffp||0);
 const rail=DMC.find(x=>x[0]===S.from)?.[4]&&DMC.find(x=>x[0]===S.to)?.[4]?km*.95*tons*(+S.rr||0)+tons*(+S.rh||0)*2:null;
 const W=[];if(!DTOFF.includes(t[0]))W.push('جدول رسمی برای کشنده‌های ۱۲ و ۱۸ چرخ منتشر شده است؛ برای «'+t[1]+'» ضریب ناوگان را با نرخ‌نامهٔ استانی یا شرکت حمل تطبیق دهید.');
 if(tt<t[2]*.5&&!(+F.mt))W.push('بار هر دستگاه کمتر از نیمی از ظرفیت است؛ در عمل اغلب «دربستی» حساب می‌شود. حداقل تناژ محاسبه را در جدول ناوگان تنظیم کنید.');
 if((+S.com||0)>10)W.push('کمیسیون بیش از سقف رایج ۱۰٪ است.');if(V.ap)W.push('تاریخ اجرای شاخص این دوره تقریبی است.');
 if((Date.now()-Date.parse(dtCur().from))/864e5>240)W.push('بیش از ۸ ماه از آخرین ابلاغ ثبت‌شده گذشته است؛ «پایش ابلاغ‌ها» را بررسی کنید.');
 const o={V,K,km,ch,tt,adj,floor,net,com,levy,insr,extra,stop,per,tot,n,F,W,fuelL:L,fuel,fuelFree};
 return {t,km,tons,n,base:net,fuel,fs:net?fuel/net:0,trip:net+extra+stop,com:com+levy,insr,per,tot,pt:tot/tons,ptk:km?tot/tons/km:0,rail,fsens:(+S.fx||0)/100*fuel*n,off:o}}
function dmCalc(S,T=dmTypes()){return dtOn(S)?dtCalc(S,T):dmCalc0(S,T)}
/* market observations: domestic waybills + IRR domestic rows of the rate bank, normalised to the official floor at their own date */
function dtObs(){const T=dmTypes(),F=dtFleet();const O=[];const fl=(km,d,ty,ch)=>dtK(km)*dtIdx(d).tkm*ch*((F[ty]||{}).c||1);
 LSG('ifa-wb',[]).filter(w=>w.st!=='cancel'&&+w.freight>0&&w.from&&w.to&&w.from!==w.to).forEach(w=>{const t=T.find(x=>x[0]===w.ty)||T[0];const km=dmKm(w.from,w.to);if(km<30)return;const tons=(+w.kg||t[2]*1000)/1000;const n=Math.max(1,Math.ceil(tons/t[2]));const ch=Math.max(tons/n,+((F[t[0]]||{}).mt)||0);const d=w.date||fwToday();const f=fl(km,d,t[0],ch);if(f>0)O.push({src:'wb',id:w.id,from:w.from,to:w.to,ty:t[0],km,date:d,per:+w.freight/n,fl:f,m:+w.freight/n/f,ref:w.off||w.no,co:w.co||''})});
 LSG('ifa-rates',[]).filter(r=>r&&r.mode==='dom'&&r.cur==='IRR'&&+r.amt>0).forEach(r=>{const a=DMC.find(c=>nkey(r.pol).includes(nkey(c[1]))||nkey(r.pol)===nkey(c[0])),b=DMC.find(c=>nkey(r.pod).includes(nkey(c[1]))||nkey(r.pod)===nkey(c[0]));if(!a||!b||a[0]===b[0])return;const km=dmKm(a[0],b[0]);const d=r.from||fwToday();const f=fl(km,d,'trl',24);if(f>0)O.push({src:'rate',id:r.id,from:a[0],to:b[0],ty:'trl',km,date:d,per:+r.amt,fl:f,m:+r.amt/f,ref:r.vendor||r.id,co:r.vendor||''})});
 return O}
function dtClean(A){if(A.length<4)return {keep:A,out:[]};const md=mkMed(A.map(x=>x.m));const mad=(mkMed(A.map(x=>Math.abs(x.m-md)))||md*.08)*1.4826;const keep=A.filter(x=>Math.abs(x.m-md)<=3*mad);return {keep,out:A.filter(x=>!keep.includes(x))}}
function dtMarket(from,to,O=dtObs()){const lane=O.filter(x=>x.from===from&&x.to===to);const A0=lane.length>=2?lane:O;const {keep,out}=dtClean(A0);if(!keep.length)return null;const cf=dtCur().from;
 return {scope:lane.length>=2?'lane':'all',n:keep.length,laneN:lane.length,out:out.length,m:mkMed(keep.map(x=>x.m)),last:keep.map(x=>x.date).sort().pop(),pre:keep.filter(x=>x.date<cf).length,obs:keep}}
function dtScore(mk,V){const P=[];const age=(Date.now()-Date.parse(V.from))/864e5;let a=V.ap?20:35;if(age>270)a-=15;P.push(['شاخص رسمی',a,35]);
 let b=0,c=0;if(mk){b=Math.round(Math.min(35,mk.n*7)*(mk.scope==='lane'?1:.55)*(mk.m<.95?.5:1));const ra=(Date.now()-Date.parse(mk.last))/864e5;c=ra<=45?20:ra<=120?10:3}P.push(['دادهٔ بازار',b,35]);P.push(['تازگی بازار',c,20]);P.push(['مستندبودن منبع',V.url||V.id?10:5,10]);
 return {s:Math.max(0,Math.min(100,P.reduce((x,p)=>x+p[1],0))),P}}
function dtVerdict(offer,R,mkPer,S){if(!(offer>0))return null;const o=R.off;const net=(offer-o.extra-o.stop-o.insr)/(1+((+S.com||0)+(+S.levy||0))/100);const F=[];
 if(net<o.floor*.995)F.push(['bad','زیر کف قانونی: سهم خالص راننده حدود '+tmn(net)+' در برابر کف '+tmn(o.floor)+' — ریسک تخلف و عدم بارگیری']);
 if(mkPer&&offer>mkPer*1.5)F.push(['bad','بیش از ۱٫۵ برابر بازار ('+fa(nf(offer/mkPer,2))+'×)']);else if(mkPer&&offer<mkPer*.8)F.push(['warn','حدود '+fa(nf((1-offer/mkPer)*100,0))+'٪ ارزان‌تر از بازار — احتمال نبود ناوگان یا هزینهٔ پنهان']);
 if(!F.length)F.push(['ok','در محدودهٔ قانونی'+(mkPer?' و بازار':'')]);return {net,F,dOff:offer/R.per-1,dMk:mkPer?offer/mkPer-1:null}}
const dtBar=(v,mx,cls)=>`<i class="dt-bar ${cls||''}"><i style="width:${Math.max(2,Math.min(100,v/mx*100))}%"></i></i>`;
let DTV='calc';
function rDom(b,C){const T=dmTypes();const wt=+(C&&C.cargo&&C.cargo.weightKg)||0;const val=(+(C&&C.cargo&&C.cargo.value)||0)*fwFx().free;
 const S=Object.assign({from:'BND',to:'THR',km:null,ty:'trl',tons:wt?Math.round(wt/100)/10:24,val:Math.round(val),date:''},DTDEF,LSG('ifa-dom',{}));const sv=()=>LSS('ifa-dom',S);
 if(!dtOn(S)&&DTV==='calc')DTV='old';
 b.innerHTML=`<div class="dt">${tmSeg([['calc','برآورد رسمی و بازار'],['tar','تعرفه و پایش ابلاغ‌ها'],['imp','ورود بارنامه‌ها'],['old','مدل قدیمی (نرخ هر کیلومتر)']],DTV,'mk-sub dt-sub')}<div class="dt-b"></div></div>`;
 $$('.dt-sub button',b).forEach(x=>x.onclick=()=>{DTV=x.dataset.v;if(DTV==='calc'&&!dtOn(S)){S.off=1;sv()}rDom(b,C)});
 const B=$('.dt-b',b);const re=()=>rDom(b,C);
 if(DTV==='old'){B.innerHTML=`<div class="fw-al ${dtOn(S)?'':'bad'}">${dtOn(S)?'این مدل قدیمی فقط برای مقایسه است؛ محاسبهٔ همهٔ بخش‌ها (بارنامه، سود و زیان، هزینهٔ حمل با دادهٔ روز) با «برآورد رسمی» انجام می‌شود.':'محاسبهٔ رسمی خاموش است و همهٔ بخش‌ها از این مدل (نرخ هر کیلومتر) استفاده می‌کنند.'} <button class="sx-btn sm" data-tg>${dtOn(S)?'استفاده از مدل قدیمی در همهٔ بخش‌ها':'بازگشت به محاسبهٔ رسمی'}</button></div><div class="dt-old"></div>`;
  $('[data-tg]',B).onclick=()=>{S.off=dtOn(S)?0:1;sv();DTV=S.off?'calc':'old';re()};rDomOld($('.dt-old',B),C);return}
 if(DTV==='tar')return dtTar(B,S,sv,re);if(DTV==='imp')return dtImp(B,re);
 const opts=DMC.map(c=>[c[0],c[1]]);const FL=dtFleet();
 B.innerHTML=`<div class="dt-fresh"></div><div class="fw"><div class="sx-card fw-form"><header><b>کرایهٔ حمل جاده‌ای داخلی بر مبنای شاخص رسمی تن-کیلومتر</b><small>${window.__ifaKm&&window.__ifaKm()?'فاصلهٔ جاده‌ای از مسیریاب ('+esc(window.__ifaKm())+')':'فاصلهٔ جاده‌ای تقریبی (خط مستقیم × ۱٫۲۵)؛ اگر فاصلهٔ دقیق را دارید وارد کنید'}</small></header><div class="fw-g">
  ${fwI('مبدأ','from',S.from,{opts})}${fwI('مقصد','to',S.to,{opts})}${fwI('فاصلهٔ دقیق (km، اختیاری)','km',S.km)}${fwI('نوع ناوگان','ty',S.ty,{opts:T.map(t=>[t[0],t[1]+' · '+fa(t[2])+' تن'+(DTOFF.includes(t[0])?'':' (غیرکشنده)')])})}${fwI('وزن بار (تن)','tons',S.tons,{step:.1})}${fwI('تاریخ حمل (خالی = امروز)','date',S.date,{t:'date'})}
  ${fwI('کمیسیون شرکت حمل ٪ (سقف رایج ۱۰)','com',S.com,{step:.5})}${fwI('عوارض بارنامه ٪ (تأییدشده وارد کنید)','levy',S.levy,{step:.5})}${fwI('بیمهٔ بار (٪ ارزش)','ins',S.ins,{step:.01})}${fwI('ارزش بار (ریال)','val',S.val)}
  ${fwI('بارگیری و تخلیه (ریال/سفر)','load',S.load)}${fwI('عوارض آزادراه (ریال/سفر)','toll',S.toll)}${fwI('باسکول و سایر (ریال/سفر)','wgh',S.wgh)}${fwI('روز توقف/معطلی','stop',S.stop)}${fwI('نرخ پیشنهادی دریافتی (ریال/دستگاه)','offer',S.offer)}</div>
  <details ${(+S.mtn||+S.prt||+S.dg||+S.ret||+S.ssn)?'open':''}><summary>ضرایب مسیر و کالا (قابل مذاکره؛ خارج از جدول رسمی)</summary><div class="fw-g">${fwI('مسیر کوهستانی/صعب‌العبور ٪','mtn',S.mtn)}${fwI('بندر یا مرز (معطلی، تشریفات) ٪','prt',S.prt)}${fwI('کالای خطرناک/حساس ٪','dg',S.dg)}${fwI('برگشت خالی ٪','ret',S.ret)}${fwI('فصل اوج/کمبود ناوگان ٪','ssn',S.ssn)}</div></details>
  <details><summary>سوخت، ریل و ضرایب ناوگان</summary><div class="fw-g">${fwI('سهم سوخت داخل سهمیه ٪','qs',S.qs)}${fwI('گازوئیل سهمیه‌ای (ریال/لیتر)','fq',S.fq)}${fwI('گازوئیل خارج سهمیه (ریال/لیتر)','ffp',S.ffp)}${fwI('آزمون افزایش قیمت سوخت ٪','fx',S.fx)}${fwI('نرخ ریلی (ریال/تن-کیلومتر)','rr',S.rr)}${fwI('تخلیه و بارگیری ریلی هر سر (ریال/تن)','rh',S.rh)}</div>
  <table class="sx-tbl dm-tt"><thead><tr><th>ناوگان</th><th>ضریب نسبت به جدول رسمی</th><th>طبقهٔ حق توقف</th><th>حداقل تناژ محاسبه</th></tr></thead><tbody>${T.map(t=>{const f=FL[t[0]]||{};return `<tr><td>${esc(t[1])}${DTOFF.includes(t[0])?'':' <small class="sx-muted">(فرض)</small>'}</td><td><input type="number" step=".05" data-ff="${t[0]}|c" value="${f.c??1}"></td><td><select data-ff="${t[0]}|st"><option value="sgl" ${f.st==='sgl'?'selected':''}>کامیون تک</option><option value="dbl" ${f.st!=='sgl'?'selected':''}>جفت/تریلی</option></select></td><td><input type="number" step="1" data-ff="${t[0]}|mt" value="${f.mt||0}"></td></tr>`}).join('')}</tbody></table><button class="sx-btn sm" data-frs>بازگردانی ضرایب</button>
  <p class="sx-note">سوخت سهمیه‌ای ۳۰۰ تومان/لیتر است. با کمبود سهمیه، سوخت آزاد گران‌تر تهیه می‌شود (گزارش‌های بازار ۲٬۵۰۰ تا ۷٬۰۰۰ تومان). این هزینه در جدول رسمی دیده نمی‌شود و نرخ بازار را بالا می‌برد.</p></details></div><div class="fw-o"></div></div>`;
 const fresh=async()=>{const V=dtCur(),st=dtStop(),O=dtObs();const lw=O.map(x=>x.date).sort().pop();let w='';if(svOn()){try{const r=await svApi('/api/domestic/watch?status=new');w=`<span class="dt-ch ${r.items.length?'warn':''}">پایش ابلاغ‌ها: ${r.last?'آخرین بررسی '+tmDt(r.last):'هنوز اجرا نشده'}${r.items.length?' · '+fa(r.items.length)+' مورد تازه':''}</span>`}catch(e){}}
  const el=$('.dt-fresh',B);if(el)el.innerHTML=`<span class="dt-ch ok">شاخص رسمی: ${nf(V.tkm)} ریال/تن-km از ${jdt(V.from)}${V.ap?' (تقریبی)':''}</span><span class="dt-ch ${st.ver?'':'warn'}">حق توقف: ${tmn(st.sgl)} / ${tmn(st.dbl)} در ۴۸ ساعت${st.ver?'':' · تأییدنشده'}</span><span class="dt-ch ${O.length?'':'warn'}">دادهٔ بازار: ${O.length?fa(O.length)+' کرایهٔ واقعی · آخرین '+jdt(lw):'بارنامه‌ای ثبت نشده'}</span>${w}`};
 const out=()=>{const R=dtCalc(S,T),o=R.off;const ex=$('.fw-o',B);const fromN=dmN(S.from),toN=dmN(S.to);const O=dtObs();const mk=dtMarket(S.from,S.to,O);const mkPer=mk?o.floor*mk.m:null;const sc=dtScore(mk,o.V);const vd=dtVerdict(+S.offer,R,mkPer,S);
  const mx=Math.max(o.floor,R.per,mkPer||0,+S.offer||0);
  const mat=DMC.filter(c=>c[0]!==S.from).map(c=>{const r=dtCalc({...S,to:c[0],km:null},T);const m2=dtMarket(S.from,c[0],O);return [c,r,m2&&m2.scope==='lane'?r.off.floor*m2.m:null]}).sort((a,c)=>a[1].km-c[1].km);
  const lanes={};O.forEach(x=>{const k=x.from+'→'+x.to;(lanes[k]=lanes[k]||[]).push(x)});
  const LT=Object.entries(lanes).map(([k,a])=>{const {keep}=dtClean(a);const m=mkMed(keep.map(x=>x.m));const r=dtCalc({...S,from:a[0].from,to:a[0].to,km:null,stop:0,offer:0},T);return {k,a,keep,m,from:a[0].from,to:a[0].to,fl:r.off.floor,full:r.per,last:a.map(x=>x.date).sort().pop()}}).sort((x,y)=>y.a.length-x.a.length).slice(0,12);
  ex.innerHTML=`<div class="ex-kpis">${kpi('فاصله',R.km,{suf:' km',sub:esc(fromN)+' ← '+esc(toN)})}${kpi('کف قانونی (خالص راننده)',o.floor/1e7,{d:1,suf:' م.ت',sub:'هر دستگاه · '+fa(nf(o.ch,1))+' تن'})}${kpi('برآورد کامل رسمی',R.per/1e7,{d:1,suf:' م.ت',sub:'هر دستگاه · '+fa(R.n)+' دستگاه'})}${kpi('نرخ بازار',mkPer?mkPer/1e7:0,{d:1,suf:mkPer?' م.ت':'',sub:mk?(mk.scope==='lane'?'میانهٔ '+fa(mk.n)+' کرایهٔ این مسیر':'ضریب کل بازار ('+fa(mk.n)+' کرایه)'):'دادهٔ واقعی ثبت نشده'})}${kpi('امتیاز اعتبار',sc.s,{suf:'/۱۰۰',cls:sc.s>=70?'ok':sc.s>=45?'':'bad'})}</div>
  <div class="ct-g2"><div class="sx-card"><header><b>کف قانونی، بازار و پیشنهاد</b><small>هر دستگاه · ${esc(R.t[1])}</small></header>
   <table class="sx-tbl dt-cmp"><tbody><tr><td>کف قانونی (خالص راننده)</td><td>${tmn(o.floor)}</td><td>${dtBar(o.floor,mx,'fl')}</td></tr><tr><td>برآورد کامل (کف + ضرایب + کمیسیون + جانبی)</td><td>${tmn(R.per)}</td><td>${dtBar(R.per,mx,'of')}</td></tr><tr><td>نرخ بازار ${mk?'<small class="sx-muted">(×'+fa(nf(mk.m,2))+' کف)</small>':''}</td><td>${mkPer?tmn(mkPer):'—'}</td><td>${mkPer?dtBar(mkPer,mx,'mk'):''}</td></tr>${+S.offer>0?`<tr><td>نرخ پیشنهادی</td><td>${tmn(+S.offer)}</td><td>${dtBar(+S.offer,mx,'pr')}</td></tr>`:''}</tbody></table>
   ${vd?`<div class="dt-vd">${vd.F.map(f=>`<div class="fw-al ${f[0]==='ok'?'ok':f[0]==='bad'?'bad':''}">${f[1]}</div>`).join('')}<small class="sx-muted">اختلاف با برآورد رسمی: ${(vd.dOff>0?'+':'')+fa(nf(vd.dOff*100,1))}٪${vd.dMk!=null?' · با بازار: '+(vd.dMk>0?'+':'')+fa(nf(vd.dMk*100,1))+'٪':''}</small></div>`:'<p class="sx-muted">برای سنجش نرخی که دریافت کرده‌اید، «نرخ پیشنهادی دریافتی» را وارد کنید.</p>'}
   <div class="dt-sc">${sc.P.map(p=>`<span><small>${p[0]}</small>${dtBar(p[1],p[2])}<em>${fa(p[1])}/${fa(p[2])}</em></span>`).join('')}</div>
   ${mk?`<p class="sx-note">بازار از ${fa(mk.n)} کرایهٔ واقعی${mk.out?' (پس از حذف '+fa(mk.out)+' دادهٔ پرت)':''}. هر کرایه با شاخص رسمی همان تاریخ نرمال شده است${mk.pre?'؛ '+fa(mk.pre)+' مورد پیش از آخرین ابلاغ ثبت شده و با شاخص روز تعدیل شده است':''}.</p>`:''}
   ${mk&&mk.m<.95?`<div class="fw-al bad">میانهٔ کرایه‌های واقعی ${fa(nf((1-mk.m)*100,0))}٪ زیر کف قانونی است. شاید کرایهٔ خالص، قدیمی یا ناقص ثبت شده باشد؛ بارنامه‌ها را بررسی کنید.</div>`:''}
   ${o.W.map(w=>`<div class="fw-al">${w}</div>`).join('')}</div>
  <div class="sx-card"><header><b>ریز کرایه (هر دستگاه)</b><small>شاخص ${nf(o.V.tkm)} ریال · ضریب مسافت ${fa(nf(o.K,1))}</small></header><table class="sx-tbl"><tbody>
   <tr><td>کف قانونی: ${fa(nf(o.K,1))} × ${nf(o.V.tkm)} ریال × ${fa(nf(o.ch,1))} تن${(+o.F.c||1)!==1?' × '+fa(nf(o.F.c,2)):''}</td><td>${tmn(o.floor)}</td></tr>${o.adj?`<tr><td>ضرایب مسیر و کالا (${fa(nf(o.adj,1))}٪)</td><td>${tmn(o.net-o.floor)}</td></tr>`:''}
   <tr><td>کمیسیون شرکت حمل (${fa(nf(+S.com||0,1))}٪)</td><td>${tmn(o.com)}</td></tr>${o.levy?`<tr><td>عوارض بارنامه (${fa(nf(+S.levy,1))}٪)</td><td>${tmn(o.levy)}</td></tr>`:''}<tr><td>بیمهٔ بار</td><td>${tmn(o.insr)}</td></tr><tr><td>بارگیری، تخلیه، عوارض آزادراه، باسکول</td><td>${tmn(o.extra)}</td></tr>${o.stop?`<tr><td>حق توقف ${fa(+S.stop)} روز (${o.F.st==='sgl'?'کامیون تک':'جفت/تریلی'})</td><td>${tmn(o.stop)}</td></tr>`:''}
   <tr class="on"><td><b>جمع هر دستگاه</b></td><td><b>${tmn(R.per)}</b></td></tr><tr><td>جمع ${fa(R.n)} دستگاه</td><td><b>${tmn(R.tot)}</b> <small class="sx-muted">≈ ${usd0(R.tot/fwFx().free)}</small></td></tr><tr><td>هر تن · هر تن-کیلومتر</td><td>${tmn(R.pt)} · ${tmn(R.ptk)}</td></tr></tbody></table>
   <p class="sx-note">سوخت سفر حدود ${fa(nf(o.fuelL,0))} لیتر است و با سهمیهٔ ${fa(nf(+S.qs,0))}٪ حدود ${tmn(o.fuel)} هزینه دارد. اگر تمام سوخت آزاد تهیه شود، ${tmn(o.fuelFree)} می‌شود (${fa(nf(o.fuelFree/o.floor*100,1))}٪ کف کرایه).</p>
   ${R.rail!=null?`<div class="fw-al ${R.rail<R.tot?'ok':''}"><b>گزینهٔ ریلی:</b> ${tmn(R.rail)} (${R.rail<R.tot?fa(nf((1-R.rail/R.tot)*100,0))+'٪ ارزان‌تر':'گران‌تر'}) — بدون حمل تکمیلی از ایستگاه</div>`:''}
   <div class="fw-bt"><button class="sx-btn sm" data-job>ثبت در سود و زیان پرونده</button><button class="sx-btn sm" data-csv>خروجی CSV مقصدها</button></div></div></div>
  <div class="ct-g2"><div class="sx-card"><header><b>از ${esc(fromN)} به سایر شهرها</b><small>${esc(R.t[1])} · ${fa(nf(R.tons,1))} تن</small></header><div class="sx-tw dm-mx"><table class="sx-tbl"><thead><tr><th>مقصد</th><th>km</th><th>کف قانونی</th><th>برآورد کامل</th><th>بازار مسیر</th><th>هر تن</th></tr></thead><tbody>${mat.map(([c,r,m2])=>`<tr data-to="${c[0]}" class="${c[0]===S.to?'on':''}"><td>${esc(c[1])}${c[4]?' <small>🚆</small>':''}</td><td>${fa(r.km)}</td><td>${tmn(r.off.floor)}</td><td>${tmn(r.per)}</td><td>${m2?tmn(m2):'—'}</td><td>${tmn(r.pt)}</td></tr>`).join('')}</tbody></table></div></div>
  <div class="sx-card"><header><b>بازار مسیرهای دارای کرایهٔ واقعی</b><small>کرایهٔ واقعی ÷ کف قانونی همان تاریخ</small></header>${LT.length?`<div class="sx-tw"><table class="sx-tbl"><thead><tr><th>مسیر</th><th>تعداد</th><th>ضریب بازار</th><th>بازار امروز</th><th>برآورد کامل رسمی</th><th>آخرین</th></tr></thead><tbody>${LT.map(l=>{const now=l.fl*l.m;const d=now/l.full-1;return `<tr data-ln="${l.from}|${l.to}"><td>${esc(dmN(l.from))} → ${esc(dmN(l.to))}</td><td>${fa(l.keep.length)}${l.a.length>l.keep.length?' <small class="sx-muted">(−'+fa(l.a.length-l.keep.length)+' پرت)</small>':''}</td><td>×${fa(nf(l.m,2))}</td><td>${tmn(now)}</td><td>${tmn(l.full)} <small class="${Math.abs(d)>.2?'bad':'sx-muted'}">${(d>0?'+':'')+fa(nf(d*100,0))}٪</small></td><td>${jdt(l.last)}</td></tr>`}).join('')}</tbody></table></div>`:'<p class="sx-muted">هنوز کرایهٔ واقعی داخلی ثبت نشده است. بارنامه‌ها را در «بارنامهٔ داخلی» ثبت کنید یا فایلشان را از «ورود بارنامه‌ها» وارد کنید تا نرخ بازار هر مسیر کنار نرخ رسمی نمایش داده شود.</p>'}</div></div>
  ${fwNote('کف قانونی همان «کرایهٔ خالص راننده» در نرخ‌نامهٔ رسمی تن-کیلومتر سازمان راهداری است (شاخص × ضریب مسافت × تناژ). کمیسیون، عوارض، بیمه، بارگیری، توقف و ریسک مسیر جزو آن نیستند و جداگانه اضافه می‌شوند. ضریب‌های مسافت از جدول ۱۴۰۵ استخراج شده‌اند، با جدول ۱۴۰۴ هم یکسان‌اند و بین ردیف‌های ۵۰ کیلومتری به‌صورت خطی میان‌یابی می‌شوند.')}`;
  $$('[data-to]',ex).forEach(x=>x.onclick=()=>{S.to=x.dataset.to;S.km=null;sv();re()});$$('[data-ln]',ex).forEach(x=>x.onclick=()=>{const [f,t2]=x.dataset.ln.split('|');S.from=f;S.to=t2;S.km=null;sv();re()});
  $('[data-job]',ex).onclick=()=>fwJobAdd({n:`حمل داخلی ${fromN} ← ${toN} (${fa(R.n)}× ${R.t[1]}) · شاخص ${nf(o.V.tkm)}`,v:'باربری',cur:'IRR',be:Math.round(R.tot),se:Math.round((mkPer?Math.max(mkPer,R.per):R.per)*R.n*1.08)});
  $('[data-csv]',ex).onclick=()=>{const L=[['مقصد','km','کف قانونی (ریال)','برآورد کامل (ریال)','بازار مسیر (ریال)','هر تن (ریال)','شاخص','تاریخ شاخص'],...mat.map(([c,r,m2])=>[c[1],r.km,Math.round(r.off.floor),Math.round(r.per),m2?Math.round(m2):'',Math.round(r.pt),o.V.tkm,o.V.from])];dl('domestic-'+S.from+'.csv','\ufeff'+L.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n'),'text/csv')}};
 fwBind($('.fw-form',B),S,k=>{if(k==='from'||k==='to')S.km=null;sv();if(['from','to'].includes(k)){re();return}out()});
 $$('[data-ff]',B).forEach(x=>x.onchange=()=>{const [ty,f]=x.dataset.ff.split('|');const o=LSG('ifa-dom-f',{})||{};o[ty]=Object.assign({},o[ty]||{},{[f]:f==='st'?x.value:+x.value||0});LSS('ifa-dom-f',o);out()});$('[data-frs]',B).onclick=()=>{localStorage.removeItem('ifa-dom-f');re()};
 out();fresh()}
function dtTar(B,S,sv,re){const V=dtVers(),cur=dtCur(),st=dtStop();const own=dtStore();const kmL=[75,100,200,300,500,750,1000,1250,1500,2000];
 B.innerHTML=`<div class="ct-g2"><div class="sx-card"><header><b>تاریخچهٔ شاخص رسمی تن-کیلومتر</b><small>ریال به ازای هر تن-کیلومتر · کرایهٔ خالص راننده</small></header>
  <table class="sx-tbl"><thead><tr><th>از تاریخ</th><th>شاخص (ریال)</th><th>تغییر</th><th>منبع</th></tr></thead><tbody>${V.slice().reverse().map((v,i,a)=>{const p=a[i+1];return `<tr class="${v===cur?'on':''}"><td>${jdt(v.from)}${v.ap?' <small class="sx-muted">(تقریبی)</small>':''}</td><td><b>${nf(v.tkm)}</b></td><td>${p?'+'+fa(nf((v.tkm/p.tkm-1)*100,1))+'٪':'—'}</td><td><small>${v.url?`<a href="${esc(v.url)}" target="_blank" rel="noopener">${esc(v.src||'')}</a>`:esc(v.src||'')}${v.by?' · ثبت: '+esc(v.by):''}</small></td></tr>`}).join('')}</tbody></table>
  <p class="sx-note">ابلاغ میانی ۱۴۰۳ (۸٬۹۰۰ ریال) به‌دلیل نامعلوم بودن تاریخ دقیق اجرا وارد نشده است. اگر تاریخ را دارید، از فرم زیر ثبتش کنید.</p>
  <div class="fw-g dt-add">${fwI('تاریخ اجرا','f',fwToday(),{t:'date'})}${fwI('شاخص جدید (ریال)','v','')}${fwI('منبع (بخشنامه/خبر)','s','',{t:'text'})}${fwI('پیوند منبع','u','',{t:'text'})}</div><div class="fw-bt"><button class="sx-btn sm pri" data-addv>ثبت ابلاغ جدید</button>${(own.v||[]).length?'<button class="sx-btn sm" data-rmv>حذف ابلاغ‌های ثبت‌شدهٔ دستی</button>':''}</div></div>
 <div class="sx-card"><header><b>نرخ هر تن با شاخص فعلی</b><small>${nf(cur.tkm)} ریال · از ${jdt(cur.from)}</small></header><table class="sx-tbl"><thead><tr><th>مسافت (km)</th><th>ضریب مسافت</th><th>هر تن (تومان)</th><th>کشندهٔ ۲۴ تن</th></tr></thead><tbody>${kmL.map(k=>`<tr><td>${fa(k)}</td><td>${fa(nf(dtK(k),1))}</td><td>${nf(Math.round(dtK(k)*cur.tkm/10))}</td><td>${tmn(dtK(k)*cur.tkm*24)}</td></tr>`).join('')}</tbody></table>
  <header style="margin-top:12px"><b>حق توقف (هر ۴۸ ساعت)</b><small>${esc(st.src||'')}</small></header><div class="fw-g">${fwI('کامیون تک (ریال)','sgl',st.sgl)}${fwI('جفت، تریلی و کمرشکن (ریال)','dbl',st.dbl)}${fwI('از تاریخ','sf',st.from,{t:'date'})}${fwI('منبع','ss',st.ver?st.src:'',{t:'text'})}</div><div class="fw-bt"><button class="sx-btn sm" data-stp>ثبت و تأیید حق توقف</button></div>
  <p class="sx-note">پله‌ها: ۴۸ ساعت اول نرخ پایه است. هر دورهٔ ۴۸ ساعتهٔ بعدی تا روز دهم +۳۰٪، تا یک ماه +۴۰٪ و بیش از یک ماه +۷۰٪ حساب می‌شود. این برداشت از گزارش مرداد ۱۴۰۵ است؛ با متن بخشنامه تطبیق دهید.</p></div></div>
 <div class="sx-card dt-w"><header><b>پایش ابلاغ‌ها و خبرهای تعرفه</b><small>سرور خبرگزاری‌ها را هر چند ساعت بررسی می‌کند و خبرهای تن-کیلومتر، حق توقف، تعرفهٔ ریلی و بندری، عوارض و سوخت را با عدد استخراج‌شده نشان می‌دهد. چیزی بدون تأیید شما اعمال نمی‌شود.</small></header><div class="dt-wl"><div class="sx-empty sm">در حال بارگذاری…</div></div></div>`;
 const save=o=>{LSS('ifa-dtar',o);if(svOn())try{svSync(true)}catch(e){}};
 $('[data-addv]',B).onclick=()=>{const g=k=>$('[data-k="'+k+'"]',$('.dt-add',B)).value.trim();const f=g('f'),v=+enD(g('v')).replace(/[^\d.]/g,'');if(!/^\d{4}-\d\d-\d\d$/.test(f)||!(v>1000)){toast('تاریخ و شاخص (ریال) را درست وارد کنید');return}const o=dtStore();o.v=(Array.isArray(o.v)?o.v:[]).filter(x=>x.from!==f);o.v.push({id:'m'+Date.now().toString(36),from:f,tkm:v,src:g('s')||'ثبت دستی',url:g('u')||'',by:(SV.st.user&&SV.st.user.name)||'',ts:Date.now()});save(o);emit('domestic.tariff',{ref:'شاخص '+nf(v),title:'ثبت ابلاغ جدید شاخص تن-کیلومتر',kind:'tkm',value:nf(v)+' ریال',effective:f});toast('ابلاغ جدید ثبت شد');re()};
 const rm=$('[data-rmv]',B);if(rm)rm.onclick=()=>{if(!confirm('ابلاغ‌های ثبت‌شدهٔ دستی و تأییدشده حذف شوند؟'))return;const o=dtStore();o.v=[];save(o);re()};
 $('[data-stp]',B).onclick=()=>{const g=k=>$('[data-k="'+k+'"]',B).value.trim();const o=dtStore();o.stop={sgl:+enD(g('sgl'))||0,dbl:+enD(g('dbl'))||0,from:g('sf'),src:g('ss')||'تأیید کاربر',ver:1};save(o);toast('حق توقف ثبت شد');re()};
 const W=$('.dt-wl',B);if(!svOn()){W.innerHTML='<p class="sx-muted">پایش خودکار روی سرور تیمی اجرا می‌شود («سیستم ← همگام‌سازی تیمی»). بدون سرور، ابلاغ‌های جدید را از فرم بالا ثبت کنید.</p>';return}
 const load=async()=>{let r;try{r=await svApi('/api/domestic/watch')}catch(e){W.innerHTML='<div class="sx-empty">خطا: '+esc(e.message)+'</div>';return}
  W.innerHTML=`<div class="fw-bt"><button class="sx-btn sm pri" data-poll>بررسی اکنون</button><small class="sx-muted">${r.on?(r.last?'آخرین بررسی '+tmDt(r.last):'هنوز اجرا نشده')+' · '+fa(r.feeds)+' منبع خبری'+(r.auto?' · خودکار هر '+fa(r.everyH)+' ساعت':' · زمان‌بندی خاموش'):'پایش روی سرور غیرفعال است (IFA_LIVE_OFF)'}${Object.keys(r.errors||{}).length?' · خطا در '+fa(Object.keys(r.errors).length)+' منبع':''}</small></div>
  ${r.items.length?`<div class="sx-tw"><table class="sx-tbl"><thead><tr><th>نوع</th><th>خبر</th><th>عدد استخراج‌شده</th><th>تاریخ اجرا</th><th>وضعیت</th><th></th></tr></thead><tbody>${r.items.map(i=>{const v=i.vals||{};const am=(v.amounts||[]).slice(0,4);const nw=i.status==='new';return `<tr class="${nw?'on':''}"><td>${esc(DTKIND[i.kind]||i.kind)}</td><td><a href="${esc(i.url)}" target="_blank" rel="noopener">${esc(i.title)}</a><br><small class="sx-muted">${esc((i.snippet||'').slice(0,220))}</small></td><td>${v.tkm?'<b>'+nf(v.tkm)+'</b> ریال/تن-km':am.length?am.map(a=>tmn(a)).join('<br>'):'—'}${v.pct?'<br><small>'+fa(v.pct)+'٪</small>':''}</td><td>${v.eff?jdt(v.eff):'—'}</td><td>${{new:'تازه',ok:'اعمال‌شده',rej:'ردشده',seen:'دیده‌شده'}[i.status]||i.status}</td><td>${nw?(i.kind==='tkm'&&v.tkm?`<button class="sx-btn sm pri" data-ap="${i.id}" data-v="${v.tkm}" data-f="${v.eff||''}">اعمال شاخص</button>`:i.kind==='stop'&&am.length>=2?`<button class="sx-btn sm pri" data-as="${i.id}" data-a="${Math.min(...am)}" data-b="${Math.max(...am)}" data-f="${v.eff||''}">اعمال حق توقف</button>`:'')+`<button class="sx-btn sm" data-sn="${i.id}">دیدم</button><button class="sx-btn sm" data-rj="${i.id}">رد</button>`:''}</td></tr>`}).join('')}</tbody></table></div>`:'<p class="sx-muted">خبری از تغییر تعرفه پیدا نشده است.</p>'}`;
  $('[data-poll]',W).onclick=async e=>{e.target.disabled=true;try{const x=await svApi('/api/domestic/watch/poll',{method:'POST'});toast(fa(x.new||0)+' خبر تازه · '+fa(x.checked||0)+' منبع بررسی شد')}catch(er){toast('خطا: '+er.message)}load()};
  const act=async(id,body)=>{try{const x=await svApi('/api/domestic/watch/'+id,{method:'POST',body});if(x.applied){try{await svSync(true)}catch(e){}emit('domestic.tariff',{ref:'شاخص '+(x.applied.tkm?nf(x.applied.tkm):''),title:'اعمال ابلاغ از پایش خبرها',kind:x.applied.tkm?'tkm':'stop',value:x.applied.tkm?nf(x.applied.tkm)+' ریال':'',effective:x.applied.from||''});toast('اعمال شد؛ همهٔ محاسبه‌ها با مقدار جدید انجام می‌شود')}re()}catch(e){toast('خطا: '+e.message)}};
  $$('[data-ap]',W).forEach(x=>x.onclick=()=>{const f=prompt('تاریخ اجرا (YYYY-MM-DD):',x.dataset.f||fwToday());if(!f)return;const v=prompt('شاخص (ریال/تن-کیلومتر):',x.dataset.v);if(!v)return;act(x.dataset.ap,{status:'ok',tkm:+enD(v),from:f})});
  $$('[data-as]',W).forEach(x=>x.onclick=()=>{const a=prompt('حق توقف کامیون تک (ریال/۴۸ ساعت):',x.dataset.a);if(!a)return;const b2=prompt('حق توقف جفت/تریلی (ریال/۴۸ ساعت):',x.dataset.b);if(!b2)return;act(x.dataset.as,{status:'ok',stop:{sgl:+enD(a),dbl:+enD(b2),from:x.dataset.f}})});
  $$('[data-sn]',W).forEach(x=>x.onclick=()=>act(x.dataset.sn,{status:'seen'}));$$('[data-rj]',W).forEach(x=>x.onclick=()=>act(x.dataset.rj,{status:'rej'}))};load()}
/* waybill / invoice import (CSV, TSV, Excel) */
const DTCOL={date:/تاریخ|date/i,from:/مبدا|مبدأ|origin|from|بارگیری/i,to:/مقصد|destination|\bto\b|تخلیه/i,kg:/وزن|تناژ|weight|\bkg\b|tons?\b|تن\b/i,freight:/کرایه|مبلغ|freight|amount|fare|هزینه/i,ty:/ناوگان|بارگیر|نوع|vehicle|truck|type/i,co:/شرکت|باربری|company|carrier/i,no:/شماره|بارنامه|\bno\b|number|waybill/i};
function dtJ2G(s){const m=enD(String(s||'')).match(/(\d{4})[\/\-.](\d{1,2})[\/\-.](\d{1,2})/);if(!m)return '';let [y,mo,d]=[+m[1],+m[2],+m[3]];if(y>1700)return y+'-'+String(mo).padStart(2,'0')+'-'+String(d).padStart(2,'0');
 y+=1595;let days=-355668+365*y+Math.floor(y/33)*8+Math.floor(((y%33)+3)/4)+d+(mo<7?(mo-1)*31:(mo-7)*30+186);let gy=400*Math.floor(days/146097);days%=146097;if(days>36524){gy+=100*Math.floor(--days/36524);days%=36524;if(days>=365)days++}gy+=4*Math.floor(days/1461);days%=1461;if(days>365){gy+=Math.floor((days-1)/365);days=(days-1)%365}let gd=days+1;const sal=[0,31,(gy%4===0&&gy%100!==0)||gy%400===0?29:28,31,30,31,30,31,31,30,31,30,31];let gm;for(gm=0;gm<13&&gd>sal[gm];gm++)gd-=sal[gm];return gy+'-'+String(gm).padStart(2,'0')+'-'+String(gd).padStart(2,'0')}
function dtCity(s){const k=nkey(String(s||''));if(!k)return null;const c=DMC.find(x=>nkey(x[1])===k||nkey(x[0])===k)||DMC.find(x=>k.includes(nkey(x[1]))||nkey(x[1]).includes(k));return c?c[0]:null}
function dtTy(s){const k=String(s||'');if(/یخچال|reef/i.test(k))return 'rf';if(/کانتینر|container/i.test(k))return 'ctn';if(/ده.?چرخ|جفت|10/i.test(k))return 'ten';if(/تک|single/i.test(k))return 'sgl';if(/وانت|نیسان|van/i.test(k))return 'van';return 'trl'}
function dtRows(rows){rows=rows.filter(r=>r&&r.some(c=>String(c??'').trim()!==''));if(rows.length<2)return {map:{},H:[],R:[]};const H=rows[0].map(h=>String(h??'').trim());const map={};for(const [k,re] of Object.entries(DTCOL)){const i=H.findIndex((h,j)=>re.test(h)&&!Object.values(map).includes(j));if(i>=0)map[k]=i}return {map,H,R:rows.slice(1)}}
function dtParse(P,map){const ton=P.H[map.kg]&&/تن|ton/i.test(P.H[map.kg])&&!/کیلو|kg/i.test(P.H[map.kg]),tmnH=P.H[map.freight]&&/تومان/.test(P.H[map.freight]);
 return P.R.map((r,i)=>{const g=k=>map[k]!=null?r[map[k]]:'';const num=v=>+enD(String(v??'')).replace(/[^\d.]/g,'')||0;let kg=num(g('kg'));if(ton||(kg>0&&kg<80))kg*=1000;let fr=num(g('freight'));if(tmnH)fr*=10;
  const x={i,from:dtCity(g('from')),to:dtCity(g('to')),fromT:String(g('from')||''),toT:String(g('to')||''),kg,freight:fr,date:dtJ2G(g('date'))||(typeof g('date')==='number'&&g('date')>20000?new Date(Date.UTC(1899,11,30)+g('date')*864e5).toISOString().slice(0,10):''),ty:dtTy(g('ty')),co:String(g('co')||''),no:String(g('no')||'')};
  x.ok=!!(x.from&&x.to&&x.from!==x.to&&x.freight>0);if(x.ok){const R=dtCalc({from:x.from,to:x.to,ty:x.ty,tons:(x.kg||24000)/1000,date:x.date,km:null},dmTypes());x.fl=R.off.floor*R.n;x.m=x.freight/x.fl}return x})}
function dtImp(B,re){let P=null,map={},X=[];
 B.innerHTML=`<div class="sx-card"><header><b>ورود بارنامه‌ها و فاکتورهای حمل داخلی</b><small>فایل CSV یا Excel شرکت حمل، یا متن جدول کپی‌شده. ستون‌ها خودکار تشخیص داده می‌شوند و قابل تغییرند. تاریخ شمسی و میلادی، وزن به تن یا کیلوگرم، و مبلغ به ریال یا تومان (با «تومان» در عنوان ستون) پذیرفته می‌شود.</small></header>
  <div class="fw-bt"><label class="sx-btn sm pri">انتخاب فایل CSV / Excel<input type="file" accept=".csv,.tsv,.txt,.xlsx" hidden class="dt-f"></label><button class="sx-btn sm" data-tpl>دریافت قالب CSV</button></div>
  <textarea class="sx-in dt-tx" rows="5" placeholder="یا جدول را این‌جا بچسبانید (سطر اول عنوان ستون‌ها): تاریخ، مبدأ، مقصد، وزن (کیلوگرم)، کرایه (ریال)، نوع ناوگان، شرکت حمل، شماره بارنامه"></textarea><div class="fw-bt"><button class="sx-btn sm" data-ps>تحلیل متن</button></div><div class="dt-pv"></div></div>`;
 const show=()=>{const E=$('.dt-pv',B);if(!P||!P.R.length){E.innerHTML='<p class="sx-muted">ردیفی پیدا نشد.</p>';return}X=dtParse(P,map);const ok=X.filter(x=>x.ok);
  E.innerHTML=`<div class="dt-map">${Object.keys(DTCOL).map(k=>`<label class="sx-f"><span>${{date:'تاریخ',from:'مبدأ',to:'مقصد',kg:'وزن',freight:'کرایه',ty:'ناوگان',co:'شرکت حمل',no:'شمارهٔ بارنامه'}[k]}</span><select data-m="${k}"><option value="">—</option>${P.H.map((h,i)=>`<option value="${i}" ${map[k]===i?'selected':''}>${esc(h||'ستون '+(i+1))}</option>`).join('')}</select></label>`).join('')}</div>
  <p>${fa(ok.length)} ردیف معتبر از ${fa(X.length)}${X.length-ok.length?' · '+fa(X.length-ok.length)+' ردیف بدون مبدأ/مقصد شناخته‌شده یا کرایه':''}</p>
  <div class="sx-tw"><table class="sx-tbl"><thead><tr><th>#</th><th>تاریخ</th><th>مبدأ</th><th>مقصد</th><th>وزن (kg)</th><th>کرایه</th><th>کف قانونی</th><th>نسبت</th></tr></thead><tbody>${X.slice(0,40).map(x=>`<tr class="${x.ok?'':'bad'}"><td>${fa(x.i+1)}</td><td>${x.date?jdt(x.date):'—'}</td><td>${x.from?esc(dmN(x.from)):'<s>'+esc(x.fromT)+'</s>'}</td><td>${x.to?esc(dmN(x.to)):'<s>'+esc(x.toT)+'</s>'}</td><td>${nf(x.kg)}</td><td>${tmn(x.freight)}</td><td>${x.fl?tmn(x.fl):'—'}</td><td class="${x.m&&x.m<1?'bad':''}">${x.m?'×'+fa(nf(x.m,2))+(x.m<1?' زیر کف':''):'—'}</td></tr>`).join('')}</tbody></table></div>
  <div class="fw-bt"><button class="sx-btn sm pri" data-add ${ok.length?'':'disabled'}>افزودن ${fa(ok.length)} بارنامه به دفتر بارنامه‌ها</button></div>`;
  $$('[data-m]',E).forEach(s=>s.onchange=()=>{if(s.value==='')delete map[s.dataset.m];else map[s.dataset.m]=+s.value;show()});
  $('[data-add]',E).onclick=()=>{const L=LSG('ifa-wb',[]);const sig=w=>[w.off,w.date,w.from,w.to,Math.round(+w.freight)].join('|');const have=new Set(L.map(sig));let n=0;
   for(const x of X.filter(x=>x.ok)){const w=Object.assign(wbNew(L),{off:x.no,date:x.date||fwToday(),from:x.from,to:x.to,kg:x.kg||24000,freight:Math.round(x.freight),ty:x.ty,co:x.co,st:'delivered',src:'import',log:[{t:Date.now(),m:'ورود از فایل'}]});if(have.has(sig(w)))continue;have.add(sig(w));L.unshift(w);n++}
   LSS('ifa-wb',L);toast(fa(n)+' بارنامه افزوده شد'+(X.filter(x=>x.ok).length-n?' · '+fa(X.filter(x=>x.ok).length-n)+' تکراری':''));emit('rates.imported',{n,src:'domestic-waybills'});DTV='calc';re()}};
 const take=rows=>{P=dtRows(rows);map={...P.map};show()};
 $('.dt-f',B).onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(/\.xlsx$/i.test(f.name))take(await readXlsx(await f.arrayBuffer()));else take(readCsv(await f.text()))}catch(er){toast('خطا در خواندن فایل: '+er.message)}};
 $('[data-ps]',B).onclick=()=>{const t=$('.dt-tx',B).value;if(t.trim())take(readCsv(t))};
 $('[data-tpl]',B).onclick=()=>dl('waybills-template.csv','\ufeffتاریخ,مبدأ,مقصد,وزن (کیلوگرم),کرایه (ریال),نوع ناوگان,شرکت حمل,شماره بارنامه\n1405/07/10,بندرعباس,تهران,24000,520000000,تریلی کانتینربر,نمونه ترابر,12345678\n','text/csv')}
const dtApi={tariff:()=>({current:dtCur(),versions:dtVers(),stop:dtStop(),fleet:dtFleet(),K:[75,100,500,1000,2000].map(k=>[k,+dtK(k).toFixed(2)])}),
 calc:(from='BND',to='THR',ty='trl',tons=24,o={})=>{const R=dtCalc(Object.assign({},LSG('ifa-dom',{}),{from,to,ty,tons,km:null},o),dmTypes());const mk=dtMarket(from,to);const r=Math.round;return {from:dmN(from),to:dmN(to),km:R.km,trucks:R.n,index:R.off.V.tkm,indexFrom:R.off.V.from,distanceFactor:+R.off.K.toFixed(2),floorPerTruckIRR:r(R.off.floor),fullPerTruckIRR:r(R.per),totalIRR:r(R.tot),marketPerTruckIRR:mk?r(R.off.floor*mk.m):null,marketN:mk?mk.n:0,marketScope:mk?mk.scope:null,score:dtScore(mk,R.off.V).s,warnings:R.off.W}},
 market:(from,to)=>{const m=dtMarket(from,to);return m?{scope:m.scope,n:m.n,outliers:m.out,factor:+m.m.toFixed(3),last:m.last}:null},
 check:(from,to,offerIRR,o={})=>{const S=Object.assign({},LSG('ifa-dom',{}),{from,to,km:null},o);const R=dtCalc(S,dmTypes());const mk=dtMarket(from,to);const v=dtVerdict(+offerIRR,R,mk?R.off.floor*mk.m:null,S);return v?{driverNetIRR:Math.round(v.net),floorIRR:Math.round(R.off.floor),flags:v.F.map(f=>({level:f[0],text:f[1]})),vsOfficial:+v.dOff.toFixed(3),vsMarket:v.dMk==null?null:+v.dMk.toFixed(3)}:null},
 watch:()=>svApi('/api/domestic/watch')};
(function(){const st=document.createElement('style');st.textContent=`.dt .dt-sub{margin-bottom:12px}.dt-fresh{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:10px}.dt-ch{font-size:11.5px;padding:4px 10px;border-radius:999px;border:1px solid var(--line2);background:var(--panel2)}.dt-ch.ok{border-color:color-mix(in srgb,var(--good) 45%,transparent)}.dt-ch.warn{border-color:color-mix(in srgb,#e0a23a 60%,transparent);background:color-mix(in srgb,#e0a23a 10%,transparent)}
.dt-bar{display:inline-block;width:140px;height:8px;border-radius:6px;background:var(--line2);vertical-align:middle;overflow:hidden}.dt-bar>i{display:block;height:100%;background:var(--acc,#5b8def);border-radius:6px}.dt-bar.fl>i{background:#8a94a6}.dt-bar.mk>i{background:#3fb37f}.dt-bar.pr>i{background:#e0a23a}
.dt-cmp td:nth-child(2){white-space:nowrap;font-weight:600}.dt-vd{display:grid;gap:6px;margin:10px 0}.dt-sc{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px;margin:10px 0}.dt-sc span{display:grid;gap:3px;font-size:11px}.dt-sc .dt-bar{width:100%}.dt-sc em{font-style:normal;color:var(--mut)}
.dt-map{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:8px;margin:10px 0}.dt-tx{width:100%;margin-top:10px;font-family:inherit}.dt-w .sx-tbl td{vertical-align:top}.dt-w .sx-tbl a{color:inherit}.dt-add{margin-top:10px}.dt-pv tr.bad td{opacity:.6}`;document.head.appendChild(st)})();
