/* ===== v15.3: China logistics ecosystem — 6,981 entities / 12 layers (China_Logistics_Ecosystem_Consolidated_FA_2026-09.xlsx) ===== */
const EKO_B64='__EKO_B64__';
const EKO_LINK=__EKO_LINK__;
const EKO_SNAP=__EKO_SNAP__;
const EKO_L={FF:['فورواردر و NVOCC','فورواردری بار (لایه B)','#5e9fe8'],RT:['حمل جاده‌ای/TIR','حمل جاده‌ای/کامیونی (لایه C)','#e0a84e'],WH:['انبار و CFS','انبارداری/CFS (لایه E)','#9aa4ad'],OC:['کشتیرانی','حمل دریایی (لایه C)','#4fb3c9'],PT:['بنادر و پایانه‌ها','بنادر و پایانه‌ها (لایه D)','#6d8fe0'],PL:['پلتفرم و رصد','پلتفرم‌ها/رصد/ETA (لایه H)','#c58be0'],CB:['کارگزار گمرکی','کارگزاری گمرکی (لایه F)','#d9c25a'],AC:['بار هوایی','بار هوایی (لایه C)','#e07fa2'],RR:['حمل ریلی','حمل ریلی (لایه C)','#a98be0'],IN:['بیمه و تأمین مالی','بیمه و تأمین‌مالی تجاری (لایه G)','#72bc8f'],EX:['اکسپرس و پارسل','آخرین‌مایل/اکسپرس/پارسل (لایه I)','#e39a6b'],RG:['رگولاتور و دولت','استانداردها/رگولاتورها/دولت (لایه J)','#b0b0a8']};
const EKO_V={V:['راستی‌آزمایی‌شده','ok'],P:['تا حدی راستی‌آزمایی‌شده','warn'],U:['نامطمئن','bad']};
const EKO_E={S:['شواهد قوی','ok'],M:['شواهد متوسط','warn'],W:['شواهد ضعیف','bad'],U:['شواهد نامشخص','']};
const EKO_I={H:['ادعای قوی در منبع (سقف Moderate)','bad'],M:['ارتباط متوسط','warn'],I:['استنباطی/غیرمستقیم','warn'],W:['ارتباط ضعیف/کم','u'],N:['ارتباطی یافت نشد',''],U:['نامشخص','']};
const EKO_M={s:'دریایی',a:'هوایی',r:'ریلی',d:'جاده‌ای',m:'چندوجهی'};
const EKO_ST={'已备案':'ثبت‌شده در فهرست NVOCC وزارت حمل‌ونقل (已备案)','未申请备案':'درخواست ثبت نداده (未申请备案)','已申请未备案':'درخواست ثبت داده، هنوز ثبت نشده (已申请未备案)'};
const EKO_NODE={CN_KHG:'خورگوس',CN_KSG:'کاشغر',CN_URC:'ارومچی',CN_XIY:'شی‌آن',CN_LHW:'لانژو',CN_YIW:'ییوو',CN_NGB:'نینگبو',CN_TAO:'چینگدائو',CN_TSN:'تیانجین',CN_SZX:'شنژن',CN_CAN:'گوانگژو',CN_SHA:'شانگهای',CN_PVG:'فرودگاه پودونگ',CN_CGO:'فرودگاه گوانگژو'};
const EK={id:0,L:1,n:2,cn:3,ty:4,ro:5,v0:6,ev:7,ir:8,ie:9,xr:10,rs:11,src:12,no:13,de:14,V:15,ba:16,co:17,cd:18,ci:19,et:20,it:21,hq:22,pv:23,st:24,md:25,ow:26,ls:27,fd:28,sc:29,sv:30,sb:31,tel:32,mail:33,pm:34,rf:35,nd:36};
const EKO={tab:'dir',q:'',full:false,L:[],V:'',E:'',I:'',pv:'',md:'',nd:'',corr:false,pick:false,ct:false,sort:'rel',page:0,sel:null,scope:'pick',busy:false,prog:0};
let EKD=null,EKP=null;
const ekoS=()=>LSG('ifa-eko',{pick:[],note:{},scr:null}),ekoW=v=>LSS('ifa-eko',v);
async function ekoLoad(){if(EKD)return EKD;if(EKP)return EKP;EKP=(async()=>{const bin=Uint8Array.from(atob(EKO_B64),c=>c.charCodeAt(0));const t=await new Response(new Blob([bin]).stream().pipeThrough(new DecompressionStream('gzip'))).text();
 const J=JSON.parse(t);const by=new Map();J.d.forEach((r,i)=>{by.set(r[0],r);r.k=nkey([r[0],r[2],r[3],r[22],r[5],r[4],r[34],r[24],J.pv[r[23]]||''].join(' '));r.w=(r[17]?50:0)+({H:40,M:30,I:20,W:10}[r[21]]||0)+({V:20,P:10}[r[15]]||0)+({S:15,M:8,W:2}[r[20]]||0)});
 J.by=by;J.latin=r=>/[A-Za-z]{3}/.test(r[2]);EKD=J;return J})();return EKP}
const ekoTbl=(c,R)=>`<div class="sx-tw"><table class="sx-tbl"><thead><tr>${c.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${R.map(r=>`<tr>${c.map((_,i)=>`<td>${esc(r[i]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const ekoNm=r=>r[2]||r[3]||r[0];
const ekoLat=r=>/[A-Za-z]{3}/.test(r[2]);
function ekoTag(r){return [r[22],(EKD&&EKD.pv[r[23]])||'',r[23],r[36]?EKO_NODE[r[36]]:'',[...(r[25]||'')].map(c=>EKO_M[c]).join(' '),r[5],/Xinjiang|新疆|TIR/i.test(r[13]+r[5])?'Xinjiang Khorgos Alashankou Urumqi Kashgar':'',r[17]?'corridor iran':''].join(' ')}
function ekoPickObj(r){return {id:r[0],n:ekoNm(r),cn:r[3],L:r[1],ro:r[5],ty:r[4],hq:r[22],tel:r[32],mail:r[33],md:r[25],V:r[15],ev:r[20],ir:r[21],co:r[17],pm:r[34],lic:(/NVOCC/i.test(r[4]+r[5])?'NVOCC ':'')+(/TIR/i.test(r[5]+r[13])?'TIR ':'')+(/AEO/i.test(r[13]+r[14])?'AEO ':'')+(/FIATA/i.test(r[13])?'FIATA ':'')+(/ISO/i.test(r[13])?'ISO':''),tag:ekoTag(r)}}
function ekoKp(){const e=document.querySelector('.eko-kp b');if(e)e.textContent=fa(ekoPicks().length)}
function ekoPicks(){return ekoS().pick||[]}
function ekoIsPick(id){return ekoPicks().some(p=>p.id===id)}
function ekoToggle(r){const S=ekoS();S.pick=S.pick||[];const i=S.pick.findIndex(p=>p.id===r[0]);if(i>=0)S.pick.splice(i,1);else S.pick.push(ekoPickObj(r));ekoW(S);ekoKp();emit('china.pick',{id:r[0],name:ekoNm(r),picked:i<0});return i<0}
function ekoParties(){return ekoPicks().map(p=>({id:'e'+p.id,n:p.n,en:p.n,mail:p.mail||'',g:'اکوسیستم چین',x:(EKO_L[p.L]||[p.L])[0]+' · '+(p.hq||''),tag:p.tag||''}))}
function ekoRaw(pid){const id=String(pid).replace(/^e/,'');const p=ekoPicks().find(x=>x.id===id)||{};const r=EKD&&EKD.by.get(id);
 return {en:p.n,cn:p.cn,type:(EKO_L[p.L]||[p.L])[0]+' · '+(p.ty||''),svc:p.ro,hq:p.hq,tel:p.tel||'',mail:p.mail||'',web:r&&r[12][0]||'',lic:p.lic||'',mode:[...(p.md||'')].map(c=>EKO_M[c]).join('، '),fleet:'',id:p.id,ver:(EKO_V[p.V]||[''])[0],ev:(EKO_E[p.ev]||[''])[0]}}
function ekoGo(id,tab){EKO.tab=tab||'dir';if(id){EKO.sel=id}open('eko')}
function ekoCard(f){const i=DS.cncos.indexOf(f);const L=EKO_LINK[i];return L?`<div class="eko-lk">${L.map(id=>`<button class="eko-id" data-eko="${id}" title="باز کردن در اکوسیستم لجستیک چین">${id}</button>`).join('')}</div>`:''}
function ekoBind(root){$$('[data-eko]',root).forEach(x=>x.onclick=e=>{e.stopPropagation();ekoGo(x.dataset.eko)})}
document.addEventListener('click',e=>{const x=e.target.closest&&e.target.closest('[data-ekoq]');if(!x)return;Object.assign(EKO,{q:x.dataset.ekoq,full:false,L:[],V:'',E:'',I:'',pv:'',md:'',nd:'',corr:false,pick:false,ct:false,sn:false,page:0,sel:null});ekoGo(null,'dir')});
const ekoB=(cls,t,ti)=>`<span class="tm-s ${cls}"${ti?` title="${esc(ti)}"`:''}>${t}</span>`;
const ekoLB=L=>`<span class="eko-lb" style="--c:${(EKO_L[L]||[])[2]||'#999'}">${L}</span>`;
function ekoBadges(r){return ekoB(EKO_V[r[15]][1],EKO_V[r[15]][0],'وضعیت بازطبقه‌بندی‌شده: '+r[15])+ekoB(EKO_E[r[20]][1],EKO_E[r[20]][0],'Evidence_Strength: '+r[7])+(r[17]?ekoB('warn','کریدور ایران','Corridor_Flag · آخرین بازبینی '+r[18]):'')+(r[21]!=='U'&&r[21]!=='N'?ekoB(EKO_I[r[21]][1],'ایران: '+EKO_I[r[21]][0],'Iran_Relevance: '+r[8]):'')+ekoHitB((EKO.H||{})[r[0]])}
function ekoHitMap(){const u=(ekoS().scr||{}).hits||{};const M={};Object.entries(EKO_SNAP.h).forEach(([k,v])=>M[k]={...v,src:'s'});Object.entries(u).forEach(([k,h])=>{if(h&&h[0]&&!M[k])M[k]={...h[0],l:'u',src:'u'}});return M}
function ekoHitB(x){return x?ekoB(x.l==='s'?'bad':'warn',x.l==='s'?'⚠ تطبیق قوی نام در فهرست تحریم':x.l==='p'?'تطبیق احتمالی تحریمی':'تطبیق تحریمی (اجرای شما)',(LISTN[x.list]||x.list)+': '+x.name+' · '+(x.programs||'')):''}
function ekoFilter(J){EKO.H=ekoHitMap();const q=nkey(EKO.q),ql=EKO.q.toLowerCase();const P=new Set(ekoPicks().map(p=>p.id));
 return J.d.filter(r=>(!EKO.L.length||EKO.L.includes(r[1]))&&(!EKO.V||r[15]===EKO.V)&&(!EKO.E||r[20]===EKO.E)&&(!EKO.I||(EKO.I==='any'?!'UN'.includes(r[21]):r[21]===EKO.I))&&(!EKO.pv||r[23]===EKO.pv)&&(!EKO.md||(r[25]||'').includes(EKO.md))&&(!EKO.nd||r[36]===EKO.nd)&&(!EKO.corr||r[17])&&(!EKO.pick||P.has(r[0]))&&(!EKO.ct||r[32]||r[33])&&(!EKO.sn||EKO.H[r[0]])
  &&(!q||r.k.includes(q)||(EKO.full&&(r[14].includes(EKO.q)||r[13].toLowerCase().includes(ql)||r[9].toLowerCase().includes(ql)))))}
function ekoSort(L){const f={rel:(a,b)=>b.w-a.w||a[0].localeCompare(b[0]),id:(a,b)=>a[0].localeCompare(b[0]),n:(a,b)=>ekoNm(a).localeCompare(ekoNm(b)),hq:(a,b)=>(a[22]||'~').localeCompare(b[22]||'~')}[EKO.sort]||(()=>0);return L.sort(f)}
function rEko(b){if(!document.getElementById('eko-css')){const st=document.createElement('style');st.id='eko-css';st.textContent=EKO_CSS;document.head.appendChild(st)}
 b.innerHTML='<div class="sx-empty"><span class="sx-spin"></span><p>باز کردن پایگاه اکوسیستم لجستیک چین (۶٬۹۸۱ نهاد، ۱۲ لایه)…</p></div>';
 ekoLoad().then(J=>{if(b.isConnected&&view==='eko')ekoMain(b,J)}).catch(e=>{b.innerHTML='<div class="sx-empty">خطا در بارگذاری داده: '+esc(e.message)+'</div>'})}
function ekoMain(b,J){const S=ekoS();const D=J.d;const cnt=k=>D.filter(k).length;
 const subs=[['dir','فهرست جامع شرکت‌ها و نهادها'],['cor','کریدور چین–ایران و ادعاهای مستند'],['scr','غربالگری تحریمی شرکا'],['pick','فهرست منتخب من'],['qa','کیفیت داده و روش‌شناسی']];
 b.innerHTML=`<div class="eko"><div class="ex-kpis">${kpi('نهاد در ۱۲ لایه',D.length,{sub:fa(cnt(r=>r[1]==='FF'))+' فورواردر/NVOCC'})}${kpi('راستی‌آزمایی‌شده',cnt(r=>r[15]==='V'),{sub:fa(cnt(r=>r[15]==='P'))+' تا حدی · '+fa(cnt(r=>r[15]==='U'))+' نامطمئن'})}${kpi('مجموعهٔ کریدور ایران',cnt(r=>r[17]),{sub:'آخرین بازبینی '+esc(J.gen)})}${kpi('ارتباط ثبت‌شده با ایران',cnt(r=>!'UN'.includes(r[21])),{sub:'غیر از نامشخص/هیچ'})}${kpi('حامل TIR و مجوزدار',cnt(r=>r[34]),{sub:fa(cnt(r=>r[32]))+' با تلفن در منبع'})}${kpi('منتخب من',(S.pick||[]).length,{sub:'در شرکا، استعلام و تحریم',cls:'eko-kp'})}</div>
 ${subNav(subs,EKO.tab)}<div class="eko-b"></div></div>`;countUp(b);
 $$('.x-sub button',b).forEach(x=>x.onclick=()=>{EKO.tab=x.dataset.v;ekoMain(b,J)});const B=$('.eko-b',b);
 ({dir:ekoDir,cor:ekoCor,scr:ekoScr,pick:ekoPick,qa:ekoQa})[EKO.tab](B,J,b)}
function ekoDir(B,J,root){const all=ekoFilter(J);const L=ekoSort(all.slice());const PG=50;const pages=Math.max(1,Math.ceil(L.length/PG));EKO.page=Math.min(EKO.page,pages-1);const rows=L.slice(EKO.page*PG,EKO.page*PG+PG);
 if(EKO.sel&&!J.by.get(EKO.sel))EKO.sel=null;if(!EKO.sel&&rows[0])EKO.sel=rows[0][0];const sel=J.by.get(EKO.sel);
 const lc={};J.d.forEach(r=>lc[r[1]]=(lc[r[1]]||0)+1);const pvs=Object.entries(J.d.reduce((a,r)=>{if(r[23])a[r[23]]=(a[r[23]]||0)+1;return a},{})).sort((a,b2)=>b2[1]-a[1]);
 const opt=(v,cur,n)=>`<option value="${v}"${cur===v?' selected':''}>${n}</option>`;const P=new Set(ekoPicks().map(p=>p.id));
 B.innerHTML=`<div class="sx-card eko-fb"><div class="eko-lc">${Object.keys(EKO_L).map(k=>`<button class="sx-chip ${EKO.L.includes(k)?'on':''}" data-l="${k}" style="--c:${EKO_L[k][2]}"><i></i>${EKO_L[k][0]} <small>${fa(lc[k]||0)}</small></button>`).join('')}</div>
  <div class="eko-fr"><label class="in-gs eko-q">${svgI(IC.search)}<input placeholder="نام لاتین یا چینی، شناسه، شهر، نقش، شمارهٔ مجوز…" value="${esc(EKO.q)}"></label>
  <label class="eko-ck"><input type="checkbox" data-f="full"${EKO.full?' checked':''}> جستجو در متن کامل</label>
  <select data-s="V">${opt('',EKO.V,'همهٔ وضعیت‌های راستی‌آزمایی')}${Object.entries(EKO_V).map(([k,v])=>opt(k,EKO.V,v[0])).join('')}</select>
  <select data-s="E">${opt('',EKO.E,'همهٔ سطوح شواهد')}${Object.entries(EKO_E).map(([k,v])=>opt(k,EKO.E,v[0])).join('')}</select>
  <select data-s="I">${opt('',EKO.I,'ارتباط با ایران: همه')}${opt('any',EKO.I,'هر ارتباط ثبت‌شده')}${Object.entries(EKO_I).map(([k,v])=>opt(k,EKO.I,v[0])).join('')}</select>
  <select data-s="pv">${opt('',EKO.pv,'همهٔ استان‌ها/کشورها')}${pvs.map(([k,n])=>opt(k,EKO.pv,(J.pv[k]||k)+' ('+fa(n)+')')).join('')}</select>
  <select data-s="md">${opt('',EKO.md,'همهٔ شیوه‌های حمل')}${Object.entries(EKO_M).map(([k,v])=>opt(k,EKO.md,v)).join('')}</select>
  <select data-s="nd">${opt('',EKO.nd,'همهٔ هاب‌های نقشه')}${Object.entries(EKO_NODE).map(([k,v])=>opt(k,EKO.nd,v)).join('')}</select>
  <label class="eko-ck"><input type="checkbox" data-f="corr"${EKO.corr?' checked':''}> فقط کریدور ایران</label><label class="eko-ck"><input type="checkbox" data-f="ct"${EKO.ct?' checked':''}> دارای تماس</label><label class="eko-ck"><input type="checkbox" data-f="sn"${EKO.sn?' checked':''}> تطبیق تحریمی</label><label class="eko-ck"><input type="checkbox" data-f="pick"${EKO.pick?' checked':''}> منتخب من</label>
  <select data-s="sort">${opt('rel',EKO.sort,'مرتب: اولویت کریدور و اعتبار')}${opt('id',EKO.sort,'مرتب: شناسه')}${opt('n',EKO.sort,'مرتب: نام')}${opt('hq',EKO.sort,'مرتب: مقر')}</select>
  <span class="sx-sp"></span><button class="sx-btn sm" data-x="reset">پاک کردن فیلترها</button><button class="sx-btn sm" data-x="csv">CSV</button><button class="sx-btn sm" data-x="xlsx">Excel</button><button class="sx-btn sm" data-x="pickall" title="افزودن ۵۰ ردیف این صفحه به منتخب">+ منتخب (صفحه)</button></div></div>
 <div class="eko-g"><div class="sx-card eko-l"><header><b>${fa(all.length)} نهاد</b><small>${EKO.L.length?EKO.L.map(k=>EKO_L[k][0]).join('، '):'همهٔ لایه‌ها'} · صفحهٔ ${fa(EKO.page+1)} از ${fa(pages)}</small><span class="sx-sp"></span><button class="sx-btn sm" data-pg="-1"${EKO.page?'':' disabled'}>قبلی</button><button class="sx-btn sm" data-pg="1"${EKO.page<pages-1?'':' disabled'}>بعدی</button></header>
  <div class="eko-rows">${rows.map(r=>`<div class="eko-r ${r[0]===EKO.sel?'on':''}" data-id="${r[0]}">${ekoLB(r[1])}<div class="t"><b dir="auto">${esc(ekoNm(r))}</b>${r[3]&&r[3]!==r[2]?`<small dir="auto" class="cn">${esc(r[3])}</small>`:''}<small>${esc(r[0])} · ${esc(String(r[5]).slice(0,70))}${r[22]?' · '+esc(String(r[22]).slice(0,40)):''}</small><div class="tg">${ekoBadges(r)}</div></div><button class="sx-btn sm eko-pk ${P.has(r[0])?'on':''}" data-pk="${r[0]}">${P.has(r[0])?'✓ منتخب':'+ منتخب'}</button></div>`).join('')||'<div class="sx-empty">نهادی با این فیلترها یافت نشد.</div>'}</div></div>
  <div class="eko-d">${sel?ekoDetail(sel,J):'<div class="sx-card"><div class="sx-empty">یک نهاد را انتخاب کنید.</div></div>'}</div></div>`;
 const re=()=>ekoDir(B,J,root);const q=$('.eko-q input',B);
 q.oninput=()=>{EKO.q=q.value;EKO.page=0;clearTimeout(EKO.tq);EKO.tq=setTimeout(()=>{EKO.sel=null;re();const n=$('.eko-q input',B);n.focus();n.setSelectionRange(n.value.length,n.value.length)},280)};
 $$('[data-l]',B).forEach(x=>x.onclick=()=>{const k=x.dataset.l;const i=EKO.L.indexOf(k);if(i>=0)EKO.L.splice(i,1);else EKO.L.push(k);EKO.page=0;EKO.sel=null;re()});
 $$('select[data-s]',B).forEach(x=>x.onchange=()=>{EKO[x.dataset.s]=x.value;EKO.page=0;EKO.sel=null;re()});
 $$('input[data-f]',B).forEach(x=>x.onchange=()=>{EKO[x.dataset.f]=x.checked;EKO.page=0;EKO.sel=null;re()});
 $$('[data-pg]',B).forEach(x=>x.onclick=()=>{EKO.page+=+x.dataset.pg;EKO.sel=null;re();B.scrollIntoView&&$('.eko-l',B).scrollIntoView({block:'nearest'})});
 $$('.eko-r',B).forEach(x=>x.onclick=e=>{if(e.target.closest('button'))return;EKO.sel=x.dataset.id;$$('.eko-r',B).forEach(y=>y.classList.toggle('on',y===x));$('.eko-d',B).innerHTML=ekoDetail(J.by.get(EKO.sel),J);ekoDBind(B,J,re)});
 $$('[data-pk]',B).forEach(x=>x.onclick=()=>{const on=ekoToggle(J.by.get(x.dataset.pk));toast(on?'به منتخب اضافه شد — در شرکا، استعلام قیمت و غربالگری تحریم در دسترس است':'از منتخب حذف شد');re()});
 $('[data-x="reset"]',B).onclick=()=>{Object.assign(EKO,{q:'',full:false,L:[],V:'',E:'',I:'',pv:'',md:'',nd:'',corr:false,pick:false,ct:false,sn:false,page:0,sel:null});re()};
 $('[data-x="csv"]',B).onclick=()=>{const [c,R]=ekoTable(L,J);dlFile('china-logistics-ecosystem.csv',toCSV(c,R))};
 $('[data-x="xlsx"]',B).onclick=()=>{const [c,R]=ekoTable(L,J);const bl=xlsxBlob([['China Ecosystem',[c,...R]]]);const a=document.createElement('a');a.href=URL.createObjectURL(bl);a.download='china-logistics-ecosystem.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800)};
 $('[data-x="pickall"]',B).onclick=()=>{const S=ekoS();S.pick=S.pick||[];let n=0;rows.forEach(r=>{if(!S.pick.some(p=>p.id===r[0])){S.pick.push(ekoPickObj(r));n++}});ekoW(S);ekoKp();toast(fa(n)+' نهاد به منتخب اضافه شد');re()};
 ekoDBind(B,J,re)}
function ekoTable(L,J){const c=['Entity_ID','Layer','لایه','Canonical_Name','Chinese_Name','Entity_Type','Primary_Role','مقر','استان/کشور','وضعیت کنونی','شیوهٔ حمل','مالکیت','سال تأسیس','تلفن (منبع)','ایمیل (منبع)','شمارهٔ مجوز','Verification (Reclassified)','Evidence_Strength','Iran_Relevance','Iran_Evidence','Corridor_Flag','Corridor_Last_Verified','Cross-layer','Source_URLs','Notes','Persian_Description'];
 return [c,L.map(r=>[r[0],r[1],(EKO_L[r[1]]||[''])[1],r[2],r[3],r[4],r[5],r[22],J.pv[r[23]]||'',r[24],[...(r[25]||'')].map(x=>EKO_M[x]).join('، '),r[26],r[28],r[32],r[33],r[34],r[15]==='V'?'Verified':r[15]==='P'?'Partially Verified':'Uncertain',r[7],r[8],r[9],r[17]?'Corridor':'',r[18],r[35].join(' '),r[12].join(' ; '),r[13],r[14]])]}
function ekoDetail(r,J){const P=ekoIsPick(r[0]);const U=(ekoS().note||{})[r[0]]||{};const dd=(n,v,ltr)=>v?`<dt>${n}</dt><dd${ltr?' dir="auto"':''}>${esc(v)}</dd>`:'';const ci=r[19]>=0?J.cn[r[19]]:'';
 const host=u=>{try{return new URL(u).hostname.replace(/^www\./,'')}catch(e){return u.slice(0,30)}};const lic=/NVOCC/i.test(r[4]);
 return `<div class="sx-card eko-dc"><header>${ekoLB(r[1])}<b dir="auto">${esc(ekoNm(r))}</b><small dir="ltr">${esc(r[0])}</small><span class="sx-sp"></span><button class="sx-btn sm ${P?'on':''}" data-dk="pick">${P?'✓ در منتخب':'+ افزودن به منتخب'}</button></header>
 ${r[3]&&r[3]!==r[2]?`<div class="eko-cn" dir="auto">${esc(r[3])}</div>`:''}<div class="tg">${ekoBadges(r)}</div>
 <dl class="eko-dl">${dd('لایه',(EKO_L[r[1]]||['',''])[1])}${dd('نوع نهاد',r[4],1)}${dd('نقش اصلی',r[5],1)}${dd('مقر',r[22],1)}${dd('استان/کشور',J.pv[r[23]]||'')}${dd('وضعیت کنونی',EKO_ST[r[24]]||r[24])}${dd('شیوه‌های حمل',[...(r[25]||'')].map(c=>EKO_M[c]).join('، '))}${dd('مالکیت',r[26])}${dd('وضعیت بورسی',r[27])}${dd('سال تأسیس',r[28])}${dd('مقیاس',r[29])}${dd('حوزهٔ خدمات',r[30])}${dd('نقش‌های فرعی',r[31])}${dd('شمارهٔ مجوز TIR',r[34],1)}${dd('تفکیک موجودیت',r[11],1)}${dd('طبقه‌بندی اولیه',r[6],1)}</dl>
 ${r[32]||r[33]?`<div class="cr-ct">${r[32]?`<a dir="ltr" href="tel:${esc(r[32].replace(/[^\d+]/g,''))}">${esc(r[32])}</a>`:''}${r[33]?`<a dir="ltr" href="mailto:${esc(r[33])}">${esc(r[33])}</a>`:''}<small class="sx-muted">تماس ثبت‌شده در منبع — پیش از استفاده تأیید کنید</small></div>`:`<p class="sx-note">تماس مستقیم در منبع ثبت نشده؛ از نشانی‌های منبع زیر${lic?' (سامانهٔ ثبت NVOCC)':''} استفاده کنید.</p>`}
${(EKO.H||{})[r[0]]?(x=>`<div class="eko-ir sn"><b>${ekoHitB(x)}</b><span>${esc(LISTN[x.list]||x.list)}: <em dir="ltr">${esc(x.name)}</em> · ${esc(x.programs||'')} · امتیاز ${nf(x.score*100)}٪${x.q!=null?' · شباهت نام '+nf(x.q*100)+'٪':''}</span><p class="eko-tn">${x.src==='s'?'تصویر غربالگری خودکار نام لاتین با فهرست‌های داخلی اطلس (تاریخ فهرست‌ها '+esc(EKO_SNAP.date)+')':'نتیجهٔ آخرین غربالگری شما'} — تطبیق نام به معنی یکسان بودن شخص حقوقی نیست؛ با شناسه، نشانی و منبع رسمی تطبیق دهید.</p></div>`)((EKO.H||{})[r[0]]):''}
 <div class="eko-ir ${r[17]?'on':''}"><b>ارتباط با کریدور ایران</b><span>رتبهٔ ثبت‌شده در منبع (Iran_Relevance): <em dir="ltr">${esc(r[8]||'—')}</em> · قوت شواهد (Evidence_Strength، ستون جدا): <em dir="ltr">${esc(r[7]||'—')}</em></span>${r[9]&&!/^unknown$/i.test(r[9])?`<p dir="auto">${esc(r[9])}</p>`:''}${ci?`<p class="eko-tn">${esc(ci)}<br><small>آخرین بازبینی کریدور: ${esc(r[18]||'—')}</small></p>`:''}</div>
 <details class="eko-x" open><summary>توضیح فارسی (منبع)</summary><p>${esc(r[14])}</p></details>
 ${r[13]?`<details class="eko-x"><summary>یادداشت‌های منبع (Notes)</summary><p dir="ltr">${esc(r[13])}</p></details>`:''}
 <details class="eko-x"><summary>مبنای بازطبقه‌بندی راستی‌آزمایی</summary><p>${esc(r[16])}</p></details>
 ${r[35].length?`<div class="eko-rf"><b>ارجاع میان‌لایه‌ای</b>${r[35].map(id=>{const t=J.by.get(id);return t?`<button class="eko-id" data-go="${id}" title="${esc(ekoNm(t))}">${ekoLB(t[1])}${esc(id)} · ${esc(ekoNm(t).slice(0,34))}</button>`:''}).join('')}${r[10]?`<small dir="ltr">${esc(r[10])}</small>`:''}</div>`:''}
 <div class="eko-src"><b>منابع (${fa(r[12].length)})</b>${r[12].map(u=>`<a href="${esc(u)}" target="_blank" rel="noopener" dir="ltr" title="${esc(u)}">${esc(host(u))}</a>`).join('')}</div>
 <div class="eko-act"><button class="sx-btn sm" data-dk="scr">${svgI(IC.shield)}غربالگری تحریمی</button>${r[1]==='RT'||r[1]==='RR'?`<button class="sx-btn sm" data-dk="flt">افزودن به بانک حمل‌کنندگان</button>`:''}${r[36]?`<button class="sx-btn sm" data-dk="route" data-n="${r[36]}">۳ مسیر برتر ${esc(EKO_NODE[r[36]])} ← تهران</button>`:''}<button class="sx-btn sm" data-dk="copy">کپی خلاصه</button></div><div class="eko-out"></div>
 <label class="sx-f"><span>یادداشت و برچسب من (همگام با سرور تیمی)</span><textarea class="eko-nt" rows="2" placeholder="مثلاً: تماس گرفته شد، نرخ ارومچی–سرخس دریافت شد…">${esc(U.t||'')}</textarea></label>
 <p class="sx-note">همهٔ ارقام و ادعاها عیناً از فایل منبع است (بدون جعل). وضعیت تحریم، مرز، گمرک، نرخ و سرویس فعال <b>حساس به زمان</b> است و باید روزِ استفاده راستی‌آزمایی شود.</p></div>`}
function ekoDBind(B,J,re){const d=$('.eko-d',B);if(!d)return;const r=J.by.get(EKO.sel);if(!r)return;const out=$('.eko-out',d);
 $$('[data-go]',d).forEach(x=>x.onclick=()=>{EKO.sel=x.dataset.go;re()});
 const pk=$('[data-dk="pick"]',d);if(pk)pk.onclick=()=>{const on=ekoToggle(r);toast(on?'به منتخب اضافه شد':'از منتخب حذف شد');re()};
 $('[data-dk="scr"]',d).onclick=async()=>{if(!ekoLat(r)){out.innerHTML='<p class="sx-note warn">نام لاتین در منبع ثبت نشده؛ فهرست‌های تحریم با نام لاتین تطبیق می‌شوند. نام چینی را دستی در فهرست‌ها بررسی کنید.</p>';return}out.innerHTML='<div class="sx-empty sm"><span class="sx-spin"></span> بررسی در OFAC/UN/EU/UK…</div>';try{await sxLoad();const h=screen(ekoNm(r));ekoScrSave({[r[0]]:h});out.innerHTML=h.length?h.slice(0,4).map(x=>sxRow(x,ekoNm(r))).join(''):'<p class="sx-note">✓ تطبیقی بالاتر از آستانه در فهرست‌های تحریم یافت نشد (به معنی تأیید حقوقی نیست).</p>';emit('screening.done',{query:ekoNm(r),hits:h.length})}catch(e){out.innerHTML='<p class="sx-note warn">خطا: '+esc(e.message)+'</p>'}};
 const fl=$('[data-dk="flt"]',d);if(fl)fl.onclick=()=>{const A=LSG('ifa-flt',[]);if(A.some(x=>x.ekoId===r[0]))return toast('این حمل‌کننده قبلاً افزوده شده');A.unshift({id:rgId(),ekoId:r[0],type:'co',name:ekoNm(r),co:r[3]||'',tel:r[32]||'',nid:r[34]||r[0],plate:'',truck:'تریلی چادری',hub:r[22]||'',lanes:r[1]==='RT'?'چین ← آسیای مرکزی (TIR)':'ریلی چین–آسیای مرکزی–ایران',rate:3,card:'',ins:'',lic:'',tech:'',blk:false,note:'از اکوسیستم لجستیک چین '+r[0]+' · '+(EKO_V[r[15]]||[''])[0]+' · منبع: '+(r[12][0]||'')});LSS('ifa-flt',A);toast('به بانک حمل‌کنندگان افزوده شد')};
 const rt=$('[data-dk="route"]',d);if(rt)rt.onclick=async()=>{out.innerHTML='<div class="sx-empty sm"><span class="sx-spin"></span> محاسبه…</div>';try{const R=await IFA.optimize({from:rt.dataset.n,to:'IR_THR'});out.innerHTML=`<ol class="cn-or">${R.slice(0,3).map(x=>`<li><b>${esc(x.name)}</b><span>$${nf(x.costP50)}</span><span>${fa(x.daysP50)} روز</span><span>ریسک ${fa(x.risk)}</span><small>${esc(x.route.nodes.map(nname).join(' ← '))}</small></li>`).join('')}</ol>`}catch(e){out.innerHTML='<p class="sx-note warn">ابتدا موتور نقشه باید بارگذاری شود: '+esc(e.message)+'</p>'}};
 $('[data-dk="copy"]',d).onclick=()=>{const t=[ekoNm(r)+(r[3]&&r[3]!==r[2]?' / '+r[3]:''),r[0]+' · '+(EKO_L[r[1]]||[''])[1],'نقش: '+r[5],'مقر: '+(r[22]||'—'),'راستی‌آزمایی: '+(EKO_V[r[15]]||[''])[0]+' · شواهد: '+r[7],'ایران: '+r[8]+(r[17]?' · کریدور (بازبینی '+r[18]+')':''),r[32]?'تلفن: '+r[32]:'','منابع: '+r[12].join(' ')].filter(Boolean).join('\n');(navigator.clipboard?navigator.clipboard.writeText(t):Promise.reject()).then(()=>toast('خلاصه کپی شد')).catch(()=>toast('کپی ممکن نشد'))};
 const nt=$('.eko-nt',d);nt.onchange=()=>{const S=ekoS();S.note=S.note||{};S.note[r[0]]={t:nt.value,u:Date.now()};if(!nt.value)delete S.note[r[0]];ekoW(S);toast('یادداشت ذخیره شد')};
 $$('.sn-dc button',d).length&&bindDec(d,()=>{})}
function ekoScrSave(M){const S=ekoS();const sc=S.scr||{t:0,hits:{},n:0};Object.entries(M).forEach(([id,h])=>{if(h&&h.length)sc.hits[id]=h.slice(0,3).map(x=>({name:x.name,list:x.list,score:x.score,programs:x.programs||'',type:x.type}));else delete sc.hits[id]});sc.t=Date.now();S.scr=sc;ekoW(S)}
function ekoCor(B,J){const C=J.d.filter(r=>r[17]);const by={};C.forEach(r=>(by[r[1]]=by[r[1]]||[]).push(r));const hub={};J.d.forEach(r=>{if(r[36])hub[r[36]]=(hub[r[36]]||0)+1});const IR=J.d.filter(r=>r[23]==='IR');
 const gw=[['خورگوس / آلتین‌کل',/khorgos|horgos|霍尔果斯/i],['آلاشانکو / دوستیق',/alashankou|阿拉山口/i],['کاشغر / ارکشتام / تورگارت',/kashgar|kashi|喀什|irkeshtam|torugart/i],['ارومچی',/urumqi|乌鲁木齐/i],['شی‌آن (خط ریلی آپرین)',/xi'an|xian|西安/i],['ییوو',/yiwu|义乌/i]].map(([n,re])=>[n,J.d.filter(r=>re.test(r[2]+' '+r[3]+' '+r[22]+' '+r[13]))]);
 const conf={high:['بالا','ok'],medium:['متوسط','warn'],low:['پایین','bad']};
 B.innerHTML=`<div class="sx-card eko-warn"><b>⚠ حساس به زمان — نیازمند راستی‌آزمایی روز</b><p>${J.rules.map(([k,v])=>`<span><em>${esc(k)}:</em> ${esc(v)}</span>`).join('')}</p></div>
 <div class="sx-card"><header><b>یافته‌های پژوهش کریدور — ۷ ادعای مستند</b><small>با سطح اطمینان، برچسب معرفتی و منبع تاریخ‌دار</small></header><div class="eko-cl">${J.claims.map((c,i)=>`<div class="eko-c" style="--d:${i*30}ms"><header><code dir="ltr">${esc(c.id)}</code>${ekoB((conf[c.conf]||['',''])[1],'اطمینان: '+((conf[c.conf]||[c.conf])[0]))}</header><b dir="ltr">${esc(c.topic)}</b><p>${esc(c.fa)}</p><small class="sx-muted">${esc(c.label)}</small><ul>${c.src.map(s=>`<li>${s.u?`<a href="${esc(s.u)}" target="_blank" rel="noopener" dir="ltr">${esc(s.t)}</a>`:esc(s.t)}${s.d?` <small dir="ltr">${esc(s.d)}</small>`:''}</li>`).join('')}</ul>${/IN-0104|Kunlun/.test(c.topic)?`<button class="sx-btn sm" data-go="IN-0104">نمایش Bank of Kunlun (IN-0104)</button>`:''}</div>`).join('')}</div></div>
 <div class="ct-g2"><div class="sx-card"><header><b>دروازه‌های زمینی و هاب‌های کریدور</b><small>نهادهای مرتبط با هر گذرگاه (از نام، مقر و یادداشت منبع)</small></header><div class="eko-gw">${gw.map(([n,L])=>`<button data-gw="${esc(n)}"><b>${esc(n)}</b><span>${fa(L.length)} نهاد</span><small>${fa(L.filter(r=>r[17]).length)} در کریدور · ${fa(L.filter(r=>r[1]==='RT').length)} جاده‌ای · ${fa(L.filter(r=>r[1]==='FF').length)} فورواردر</small></button>`).join('')}</div>
  <h5 class="eko-h5">هاب‌های نقشهٔ اطلس</h5><div class="eko-gw sm">${Object.entries(hub).sort((a,b2)=>b2[1]-a[1]).map(([k,n])=>`<button data-nd="${k}"><b>${esc(EKO_NODE[k]||k)}</b><span>${fa(n)}</span></button>`).join('')}</div></div>
  <div class="sx-card"><header><b>مجموعهٔ کریدور به تفکیک لایه</b><small>${fa(C.length)} ردیف · Corridor_Flag = Corridor</small></header><table class="sx-tbl"><thead><tr><th>لایه</th><th>تعداد</th><th>ادعای قوی*</th><th>متوسط</th><th>استنباطی</th><th>ضعیف</th><th></th></tr></thead><tbody>${Object.entries(by).sort((a,b2)=>b2[1].length-a[1].length).map(([k,L])=>`<tr><td>${ekoLB(k)} ${EKO_L[k][0]}</td><td><b>${fa(L.length)}</b></td>${['H','M','I','W'].map(t=>`<td>${fa(L.filter(r=>r[21]===t).length)}</td>`).join('')}<td><button class="sx-btn sm" data-cl="${k}">نمایش</button></td></tr>`).join('')}</tbody></table>
  <p class="sx-note">* ${esc('ردیف‌هایی که در ستون Iran_Relevance عبارت «Strong Evidence/Confirmed» دارند؛ طبق قاعدهٔ منبع بالاتر از سقف Moderate ارتقا نیافته‌اند و برای بازبینی انسانی علامت خورده‌اند.')}</p>
  <h5 class="eko-h5">نهادهای مستقر در ایران (${fa(IR.length)})</h5><div class="eko-mini">${IR.slice(0,60).map(r=>`<button class="eko-id" data-go="${r[0]}">${ekoLB(r[1])}${esc(ekoNm(r).slice(0,40))}</button>`).join('')}</div></div></div>
 <div class="sx-card"><header><b>تعریف شمارش‌های کریدور</b><small>حفظ همهٔ ارقام با تعریف — طبق برگهٔ B5</small></header>${ekoTbl(['رقم','برچسب','تعریف','بازمحاسبه','برچسب معرفتی'],J.counts,20)}</div>`;
 $$('[data-go]',B).forEach(x=>x.onclick=()=>{EKO.tab='dir';EKO.sel=x.dataset.go;EKO.q='';rEko(B.closest('.sx-body')||B)});
 const toDir=pt=>{Object.assign(EKO,{q:'',full:false,L:[],V:'',E:'',I:'',pv:'',md:'',nd:'',corr:false,pick:false,ct:false,sn:false,page:0,sel:null},pt,{tab:'dir'});rEko(B.closest('.sx-body')||B)};
 $$('[data-cl]',B).forEach(x=>x.onclick=()=>toDir({L:[x.dataset.cl],corr:true}));$$('[data-nd]',B).forEach(x=>x.onclick=()=>toDir({nd:x.dataset.nd}));
 $$('[data-gw]',B).forEach(x=>x.onclick=()=>{const g=gw.find(z=>z[0]===x.dataset.gw);toDir({q:{'خورگوس / آلتین‌کل':'khorgos','آلاشانکو / دوستیق':'alashankou','کاشغر / ارکشتام / تورگارت':'kashgar','ارومچی':'urumqi','شی‌آن (خط ریلی آپرین)':"xi'an",'ییوو':'yiwu'}[g[0]],full:true})})}
function ekoScope(J){const P=new Set(ekoPicks().map(p=>p.id));return {pick:J.d.filter(r=>P.has(r[0])),corr:J.d.filter(r=>r[17]),filt:ekoFilter(J),all:J.d}[EKO.scope]||[]}
function ekoScr(B,J){const S=ekoS();const sc=S.scr||{t:0,hits:{}};const L=ekoScope(J);const lat=L.filter(ekoLat);const H=Object.entries(sc.hits||{}).map(([id,h])=>({r:J.by.get(id),h})).filter(x=>x.r).sort((a,b2)=>b2.h[0].score-a.h[0].score);const SN=Object.entries(EKO_SNAP.h).map(([id,x])=>({r:J.by.get(id),x})).filter(z=>z.r).sort((a,b2)=>(a.x.l===b2.x.l?b2.x.q-a.x.q:a.x.l==='s'?-1:1));
 B.innerHTML=`<div class="sx-card"><header><b>غربالگری تحریمی دسته‌ای نهادهای چینی</b><small>تطبیق نام لاتین با OFAC SDN/Non-SDN، سازمان ملل، اتحادیهٔ اروپا و بریتانیا (همان موتور «غربالگری تحریم»)</small></header>
 <div class="eko-fr"><div class="sx-seg eko-sc">${[['pick','منتخب من'],['corr','مجموعهٔ کریدور'],['filt','نتیجهٔ فیلتر فعلی'],['all','همهٔ نهادها']].map(([k,n])=>`<button data-v="${k}" class="${EKO.scope===k?'on':''}">${n}</button>`).join('')}</div><span>${fa(L.length)} نهاد · ${fa(lat.length)} با نام لاتین قابل غربالگری</span><span class="sx-sp"></span><button class="sx-btn pri" data-run${EKO.busy||!lat.length?' disabled':''}>${EKO.busy?'در حال غربالگری… '+fa(EKO.prog)+'٪':'اجرای غربالگری'}</button>${H.length?'<button class="sx-btn sm" data-csv>CSV نتایج</button><button class="sx-btn sm" data-clr>پاک کردن نتایج</button>':''}</div>
 <p class="sx-note">${fa(L.length-lat.length)} نهاد این دامنه فقط نام چینی دارند و به‌طور خودکار قابل تطبیق نیستند؛ برای آن‌ها نام چینی را در منابع رسمی (مثلاً OpenSanctions) بررسی کنید. نتیجهٔ غربالگری ابزار کمکی است، نه نظر حقوقی. آخرین اجرا: ${sc.t?fdT(sc.t):'—'}</p></div>
 <div class="sx-card"><header><b>تصویر اولیهٔ غربالگری همهٔ ${fa(J.d.filter(ekoLat).length)} نام لاتین</b><small>فهرست‌های داخلی اطلس به تاریخ ${esc(EKO_SNAP.date)} · ${fa(SN.filter(z=>z.x.l==='s').length)} تطبیق قوی نام · ${fa(SN.filter(z=>z.x.l==='p').length)} تطبیق احتمالی</small></header>${SN.map(({r,x})=>`<div class="eko-sh"><button class="eko-id" data-go="${r[0]}">${ekoLB(r[1])}${esc(r[0])}</button><div><b dir="auto">${esc(ekoNm(r))}</b><small>${esc(String(r[5]).slice(0,60))}</small></div><div class="eko-hl"><span>${ekoHitB(x)} <i class="sn-l l-${x.list}">${esc(LISTN[x.list]||x.list)}</i> <b dir="ltr">${esc(x.name)}</b> <em>شباهت ${nf(x.q*100)}٪</em> <small dir="ltr">${esc(x.programs)}</small></span></div></div>`).join('')}<p class="sx-note">«تطبیق قوی نام» یعنی نام لاتین تقریباً یکسان با یک ردیف فهرست تحریم است؛ «احتمالی» شباهت جزئی است و اغلب مثبت کاذب. هیچ‌کدام حکم حقوقی نیست؛ با فهرست به‌روز روز معامله دوباره اجرا کنید.</p></div>
 <div class="sx-card"><header><b>نتیجهٔ اجراهای شما</b><small>${fa(H.length)} نهاد با تطبیق بالاتر از آستانه</small></header>${H.length?H.map(({r,h})=>`<div class="eko-sh"><button class="eko-id" data-go="${r[0]}">${ekoLB(r[1])}${esc(r[0])}</button><div><b dir="auto">${esc(ekoNm(r))}</b><small>${esc(String(r[5]).slice(0,60))}</small></div><div class="eko-hl">${h.map(x=>`<span><i class="sn-l l-${x.list}">${esc(LISTN[x.list]||x.list)}</i> <b dir="ltr">${esc(x.name)}</b> <em>${nf(x.score*100)}٪</em> <small dir="ltr">${esc(x.programs)}</small></span>`).join('')}</div></div>`).join(''):'<div class="sx-empty sm">هنوز تطبیقی ثبت نشده — دامنه را انتخاب و غربالگری را اجرا کنید.</div>'}
 <div class="sx-note">نکتهٔ مستند منبع: Bank of Kunlun (IN-0104) از ۲۰۱۲ مشمول یافتهٔ CISADA و در فهرست CAPTA اداره OFAC است (ممنوعیت حساب کارگزار/عبوری، نه درج در SDN) — بنابراین ممکن است در غربالگری SDN ظاهر نشود. <button class="sx-btn sm" data-go="IN-0104">نمایش</button></div></div>`;
 $$('.eko-sc button',B).forEach(x=>x.onclick=()=>{EKO.scope=x.dataset.v;ekoScr(B,J)});$$('[data-go]',B).forEach(x=>x.onclick=()=>{EKO.tab='dir';EKO.sel=x.dataset.go;rEko(B.closest('.sx-body')||B)});
 const cl=$('[data-clr]',B);if(cl)cl.onclick=()=>{const S2=ekoS();S2.scr=null;ekoW(S2);ekoScr(B,J)};
 const cs=$('[data-csv]',B);if(cs)cs.onclick=()=>dlFile('china-ecosystem-screening.csv',toCSV(['Entity_ID','Name','Layer','Match','List','Score','Programs'],H.flatMap(({r,h})=>h.map(x=>[r[0],ekoNm(r),r[1],x.name,LISTN[x.list]||x.list,Math.round(x.score*100),x.programs]))));
 $('[data-run]',B).onclick=async()=>{if(EKO.busy)return;EKO.busy=true;EKO.prog=0;ekoScr(B,J);try{const th=(typeof SNC!=='undefined'&&SNC.th?SNC.th/100:.86);const CH=250;const res={};for(let i=0;i<lat.length;i+=CH){const part=lat.slice(i,i+CH);const out=await screenBatch(part.map(ekoNm),{th});part.forEach((r,j)=>res[r[0]]=out[j]||[]);EKO.prog=Math.round(Math.min(100,(i+CH)/lat.length*100));const bt=$('[data-run]',B);if(bt)bt.textContent='در حال غربالگری… '+fa(EKO.prog)+'٪'}
  ekoScrSave(res);const n=Object.values(res).filter(h=>h.length).length;emit('china.screened',{scope:EKO.scope,screened:lat.length,hits:n});toast(fa(lat.length)+' نام غربال شد · '+fa(n)+' تطبیق')}catch(e){toast('خطا در غربالگری: '+e.message)}EKO.busy=false;if(B.isConnected)ekoScr(B,J)}}
function ekoPick(B,J){const P=ekoPicks();const sc=(ekoS().scr||{}).hits||{};const N=ekoS().note||{};
 B.innerHTML=`<div class="sx-card"><header><b>فهرست منتخب شرکای چینی</b><small>${fa(P.length)} نهاد · خودکار در «شرکا و فورواردرها»، «استعلام قیمت» و «غربالگری تحریم» حاضر می‌شوند</small><span class="sx-sp"></span>${P.length?`<button class="sx-btn sm" data-o="crm">${svgI(IC.crm)}کارت امتیاز شرکا</button><button class="sx-btn sm" data-o="rfq">${svgI(IC.rfq)}استعلام قیمت</button><button class="sx-btn sm" data-o="sanc">${svgI(IC.shield)}غربالگری تحریم</button><button class="sx-btn sm" data-csv>CSV</button><button class="sx-btn sm" data-clr>پاک کردن همه</button>`:''}</header>
 ${P.length?`<table class="sx-tbl"><thead><tr><th>شناسه</th><th>نام</th><th>لایه</th><th>مقر</th><th>اعتبار</th><th>کریدور</th><th>تحریم</th><th>تماس</th><th>یادداشت من</th><th></th></tr></thead><tbody>${P.map(p=>`<tr><td><button class="eko-id" data-go="${p.id}">${esc(p.id)}</button></td><td dir="auto"><b>${esc(p.n)}</b>${p.cn&&p.cn!==p.n?`<br><small>${esc(p.cn)}</small>`:''}</td><td>${ekoLB(p.L)} ${esc((EKO_L[p.L]||[''])[0])}</td><td dir="auto">${esc(p.hq||'—')}</td><td>${ekoB((EKO_V[p.V]||['',''])[1],(EKO_V[p.V]||['—'])[0])}</td><td>${p.co?'✓':'—'}</td><td>${sc[p.id]?ekoB('bad','⚠ '+esc(sc[p.id][0].name)):'—'}</td><td dir="ltr">${esc(p.tel||p.mail||'—')}</td><td>${esc(((N[p.id]||{}).t||'').slice(0,60))}</td><td><button class="sx-btn sm" data-rm="${p.id}">حذف</button></td></tr>`).join('')}</tbody></table>`:'<div class="sx-empty">هنوز نهادی منتخب نشده است. از «فهرست جامع» با دکمهٔ «+ منتخب» اضافه کنید.</div>'}</div>`;
 $$('[data-go]',B).forEach(x=>x.onclick=()=>{EKO.tab='dir';EKO.sel=x.dataset.go;rEko(B.closest('.sx-body')||B)});
 $$('[data-rm]',B).forEach(x=>x.onclick=()=>{ekoToggle(J.by.get(x.dataset.rm)||[x.dataset.rm]);ekoPick(B,J)});
 $$('[data-o]',B).forEach(x=>x.onclick=()=>{if(x.dataset.o==='crm')CRM.g='اکوسیستم چین';if(x.dataset.o==='sanc')SNC.tab='b';open(x.dataset.o)});
 const cl=$('[data-clr]',B);if(cl)cl.onclick=()=>{if(!confirm('همهٔ منتخب‌ها حذف شوند؟'))return;const S=ekoS();S.pick=[];ekoW(S);ekoPick(B,J)};
 const cs=$('[data-csv]',B);if(cs)cs.onclick=()=>{const [c,R]=ekoTable(P.map(p=>J.by.get(p.id)).filter(Boolean),J);dlFile('china-ecosystem-shortlist.csv',toCSV(c,R))}}
function ekoQa(B,J){const D=J.d;const Ls=Object.keys(EKO_L);const M=J.meta;
 const mat=Ls.map(k=>{const L=D.filter(r=>r[1]===k);return [`${EKO_L[k][0]} (${k})`,L.length,...['V','P','U'].map(v=>L.filter(r=>r[15]===v).length),...['S','M','W','U'].map(v=>L.filter(r=>r[20]===v).length),L.filter(r=>r[17]).length,L.filter(r=>r[22]).length,L.filter(r=>r[3]).length]});
 const sheet=(n,lim)=>{const R=(M[n]||[]).filter(r=>r.some(x=>String(x).trim()));if(!R.length)return '';const w=Math.max(...R.map(r=>r.length));return `<details class="sx-card eko-sh2"><summary><b>${esc(n)}</b><small>${fa(R.length)} ردیف</small></summary><div class="sx-tw"><table class="sx-t"><tbody>${R.slice(0,lim||400).map(r=>`<tr>${Array.from({length:w},(_,i)=>`<td dir="auto">${/^https?:\/\//.test(r[i]||'')?`<a href="${esc(r[i])}" target="_blank" rel="noopener">${esc(String(r[i]).slice(0,40))}</a>`:esc(r[i]||'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div></details>`};
 B.innerHTML=`<div class="sx-card"><header><b>ماتریس لایه × اعتبار</b><small>بازمحاسبه از ۶٬۹۸۱ ردیف · وضعیت بازطبقه‌بندی‌شده و قوت شواهد دو محور جدا هستند</small></header>${ekoTbl(['لایه','کل','راستی‌آزمایی‌شده','تا حدی','نامطمئن','شواهد قوی','متوسط','ضعیف','نامشخص','کریدور','دارای مقر','دارای نام چینی'],mat.map(r=>r.map(x=>typeof x==='number'?nf(x):x)),20)}
 <p class="sx-note">منبع: ${esc(J.file)} · تولید ${esc(J.gen)} · ${nf(D.reduce((a,r)=>a+r[12].length,0))} نشانی منبع. فیلدهای «مقر، وضعیت، مالکیت، شیوهٔ حمل و…» از متن توضیح فارسی هر ردیف استخراج شده‌اند؛ «استان/کشور» و «هاب نقشه» از مقر/نام استنتاج شده‌اند (استنتاج تحلیلی).</p></div>
 ${Object.keys(M).map(n=>sheet(n)).join('')}`}
const EKO_CSS=`.eko .ex-kpis{margin-bottom:10px}.eko-b{display:flex;flex-direction:column;gap:12px;margin-top:10px}
.eko-fb{display:flex;flex-direction:column;gap:8px}.eko-lc{display:flex;flex-wrap:wrap;gap:5px}.eko-lc .sx-chip i{width:7px;height:7px;border-radius:50%;background:var(--c)}.eko-lc .sx-chip.on{color:var(--text);border-color:var(--c);background:color-mix(in srgb,var(--c) 16%,transparent)}.eko-lc small{color:var(--faint)}
.eko-fr .sx-btn{flex:0 0 auto;width:auto;margin-top:0}.eko-fr{display:flex;flex-wrap:wrap;gap:6px;align-items:center;font-size:11px}.eko-fr select{height:28px;border:1px solid var(--line2);border-radius:8px;background:var(--panel-solid);color:var(--text);font:inherit;font-size:11px;padding:0 6px;max-width:200px}.eko-q{flex:1 1 260px;min-width:200px}.eko-q input{width:100%}.eko-ck{display:inline-flex;gap:4px;align-items:center;color:var(--muted);white-space:nowrap}
.eko-g{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(0,1fr);gap:12px;align-items:start}@media (max-width:1180px){.eko-g{grid-template-columns:1fr}}
.eko-rows{display:flex;flex-direction:column;gap:2px;max-height:68vh;overflow:auto}.eko-r{display:grid;grid-template-columns:30px minmax(0,1fr) auto;gap:9px;align-items:center;padding:7px 8px;border-radius:9px;cursor:pointer;font-size:11px}.eko-r:hover{background:var(--hover)}.eko-r.on{background:var(--accent-soft)}
.eko-r .t b{display:block;font-size:11.5px;font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.eko-r .t small{display:block;color:var(--faint);font-size:10px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.eko-r .t small.cn{color:var(--muted)}.tg{display:flex;flex-wrap:wrap;gap:3px;margin-top:4px}.tg .tm-s{font-size:9.5px;padding:0 6px}.tm-s.u{color:var(--muted)}
.eko-lb{display:inline-grid;place-items:center;min-width:26px;height:18px;border-radius:5px;font:600 9.5px Inter,Vazirmatn;color:var(--c);background:color-mix(in srgb,var(--c) 15%,transparent);border:1px solid color-mix(in srgb,var(--c) 40%,transparent);margin-inline-end:4px}
.eko-pk.on,.eko-dc header .sx-btn.on{color:var(--good);border-color:color-mix(in srgb,var(--good) 50%,transparent)}
.eko-d{position:sticky;top:0}.eko-dc>header b{font-size:13px}.eko-cn{font-size:13px;color:var(--muted);margin:-4px 0 6px}.eko-dl{display:grid;grid-template-columns:110px minmax(0,1fr);gap:4px 10px;font-size:11px;margin:10px 0}.eko-dl dt{color:var(--faint)}.eko-dl dd{margin:0;line-height:1.7}
.eko-ir{border:1px solid var(--line);border-radius:9px;padding:8px 10px;margin:8px 0;font-size:11px;line-height:1.8}.eko-ir.on{border-color:color-mix(in srgb,var(--fwarn) 45%,transparent);background:color-mix(in srgb,var(--fwarn) 6%,transparent)}.eko-ir>b{display:block;font-size:11.5px}.eko-ir span{color:var(--muted)}.eko-ir em{font-style:normal;color:var(--text)}.eko-ir p{margin:4px 0 0}.eko-tn{color:var(--muted);font-size:10.5px}
.eko-x{margin:6px 0;font-size:11px;line-height:1.9}.eko-x summary{cursor:pointer;color:var(--muted);font-size:11px}.eko-x p{margin:4px 0;white-space:pre-wrap;word-break:break-word}
.eko-rf,.eko-src{display:flex;flex-wrap:wrap;gap:4px 8px;align-items:center;margin:8px 0;font-size:10.5px}.eko-rf>b,.eko-src>b{font-size:11px;width:100%}.eko-src a{color:var(--accent);text-decoration:none;border:1px solid var(--line2);border-radius:6px;padding:1px 6px}
.eko-id{border:1px solid var(--line2);background:none;color:var(--text);border-radius:6px;font:inherit;font-size:10.5px;padding:2px 7px;cursor:pointer;display:inline-flex;align-items:center}.eko-id:hover{border-color:var(--accent)}.eko-lk{display:flex;flex-wrap:wrap;gap:4px;margin:4px 0}
.eko-act{display:flex;flex-wrap:wrap;gap:6px;margin:10px 0 6px}.eko-out:empty{display:none}.eko-out{margin-bottom:8px}
.eko-warn{border-color:color-mix(in srgb,var(--fwarn) 45%,transparent)}.eko-warn p{display:flex;flex-direction:column;gap:3px;font-size:11px;line-height:1.8;margin:6px 0 0;color:var(--muted)}.eko-warn em{font-style:normal;color:var(--text)}
.eko-cl{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:10px}.eko-c{border:1px solid var(--line);border-radius:10px;padding:10px;font-size:11px;line-height:1.85;animation:sxRise .45s both;animation-delay:var(--d)}.eko-c header{display:flex;justify-content:space-between;align-items:center}.eko-c b{display:block;margin:4px 0}.eko-c p{margin:4px 0;color:var(--muted)}.eko-c ul{margin:6px 0;padding-inline-start:16px;font-size:10.5px}.eko-c a{color:var(--accent)}
.eko-gw{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:6px}.eko-gw button{display:flex;flex-direction:column;align-items:flex-start;gap:2px;border:1px solid var(--line2);border-radius:9px;background:none;color:var(--text);font:inherit;padding:8px;cursor:pointer;text-align:start}.eko-gw button:hover{border-color:var(--accent)}.eko-gw b{font-size:11.5px}.eko-gw span{font:600 15px Inter,Vazirmatn}.eko-gw small{color:var(--faint);font-size:10px}.eko-gw.sm span{font-size:12px}
.eko-h5{margin:12px 0 6px;font-size:11.5px;font-weight:600}.eko-mini{display:flex;flex-wrap:wrap;gap:4px;max-height:220px;overflow:auto}
.eko-sh{display:grid;grid-template-columns:auto minmax(0,.6fr) minmax(0,1.4fr);gap:10px;align-items:start;padding:8px 0;border-bottom:1px solid var(--line);font-size:11px}.eko-sh>div>small{display:block;color:var(--faint)}.eko-hl small{color:var(--faint);margin-inline-start:6px}.eko-ir.sn{border-color:color-mix(in srgb,var(--fbad) 50%,transparent);background:color-mix(in srgb,var(--fbad) 7%,transparent)}.eko-hl{display:flex;flex-direction:column;gap:3px}.eko-hl em{font-style:normal;color:var(--fbad)}
.eko-sh2 summary{cursor:pointer;display:flex;gap:8px;align-items:center}.eko-sh2 summary small{color:var(--faint)}.eko-sh2 .sx-tw{margin-top:8px;max-height:420px;overflow:auto}.eko-sh2 td{font-size:10.5px;vertical-align:top;line-height:1.7;max-width:520px}`;
