
/* ===== v15.6: live O→D freight cost — every leg priced from up-to-date public data (+ your own quotes) ===== */
const LQS=Object.assign({on:false,sea:1,road:1,dom:1,rail:1,vRef:600,dRef:1.0,lpk:.33,from:'',to:'',sel:0,top:5,cal:''},LSG('ifa-lq',{}));const lqSv=()=>{const {sel,...o}=LQS;LSS('ifa-lq',o)};
let LQD=null,LQF=0,LQOFF=0,LQTR=null,LQRES=null;
const LQASIA=new Set(['CN','KR','SG','MY','LK']),LQEU=new Set(['DE','NL','BE','IT','GR','TR','ES','FR','PL']),LQGULF=new Set(['IR','AE','OM','IQ','QA','KW','SA']),LQSUB=new Set(['IN','PK']);
const LQGRP={ag:'آسیای شرقی ← خلیج فارس',eg:'اروپا ← خلیج فارس',ig:'شبه‌قاره ← خلیج فارس',ga:'خلیج فارس ← آسیا',ge:'خلیج فارس ← اروپا',x:'سایر'};
const lqGrp=(A,B)=>{const a=A.country,b=B.country;if(LQGULF.has(b)&&!LQGULF.has(a))return LQASIA.has(a)?'ag':LQEU.has(a)?'eg':LQSUB.has(a)?'ig':'x';if(LQGULF.has(a)&&!LQGULF.has(b))return LQASIA.has(b)?'ga':LQEU.has(b)?'ge':'x';return 'x'};
const LQTRI={ag:['ccfi|PERSIAN_GULF_RED_SEA'],eg:['fbx|FBX12','fbx|FBX14'],ge:['fbx|FBX12','fbx|FBX14']};
const lqEqK=e=>{const c=mkEqC(e);return c==='20'?'20DV':c==='40RF'?'40RF':c==='20RF'?'20RF':'40HC'};
const lqNm=n=>{const e=n.nameEn||'',p=(e.match(/\(([^)]+)\)/)||[])[1]||'';return [...new Set([e.replace(/\(.*?\)/g,'').trim(),p,e.split(/[\s(]/)[0],p.split(/\s/)[0],n.nameFa||''].filter(x=>x&&x.length>2))]};
const lqPks=n=>[...new Set(lqNm(n).map(mkPk).filter(Boolean))];
const lqRates=()=>(window.__IFA_ARGS&&window.__IFA_ARGS[2])||(ctx()||{}).rates||null;
const lqM1=(R,eq,km)=>{const f=R.sea.fcl[eq]||R.sea.fcl['40HC'];return (f.base+f.perKm*km)*(1+R.sea.bafPct/100)};
const lqAge=d=>d?fwDiff(String(d).slice(0,10),fwToday()):null;
/* ---------- data snapshot (cached; rebuilt when any source changes) ---------- */
function lqData(){const now=Date.now();if(LQD&&now-LQD.chk<4000)return LQD;
 const c=mkC();const M=mkM();const RB=rbAll();const fxL=LSG('ifa-irr-live',null);const fx=(fxL&&fxL.USD>1e4?fxL.USD:0)||fwFx().free||1050000;
 const key=[c&&c.t,c&&c.got,fx,(M.manual||[]).length,(M.base||[]).length,RB.length,RB[0]&&RB[0].id,JSON.stringify(LQS),!!(window.__IFA_E&&window.__IFA_E.G),(localStorage.getItem('ifa-wb')||'').length,(localStorage.getItem('ifa-dom-t')||'').length,localStorage.getItem('ifa-dom')||''].join('|');
 if(LQD&&LQD.k===key){LQD.chk=now;return LQD}
 const H=mkHist();const R=lqRates();const G=window.__IFA_E&&window.__IFA_E.G;
 const vl=mkLast(H,'bunker|FUJ_VLSFO')||mkLast(H,'bunker|SIN_VLSFO');
 const dsl={};Object.keys(H).filter(k=>k.startsWith('diesel|')).forEach(k=>{const p=mkLast(H,k);if(p)dsl[k.slice(7)]=p});
 const D={k:key,chk:now,H,R,fx,fxT:fxL&&fxL.t||null,fxSrc:fxL?(fxL.src||'tgju'):'تنظیمات مالی',vl,vlr:vl?vl[1]/LQS.vRef:1,dsl,mem:new Map(),cal:{},trend:{},own:0};
 /* trend ratio of the lane-group index since calibration date (or since history start) */
 for(const [g,ks] of Object.entries(LQTRI)){const rs=[];let d0=null,d1=null;for(const k of ks){const a=H[k];if(!a||a.length<1)continue;const b=LQS.cal?mkAt(H,k,LQS.cal)||a[0]:a[0];const L=a[a.length-1];if(b&&b[1]>0){rs.push(L[1]/b[1]);d0=b[0];d1=L[0]}}
  if(rs.length)D.trend[g]={r:Math.min(3,Math.max(.33,mkMed(rs))),k:ks.filter(k=>H[k]),d0,d1}}
 /* own quotes (rate bank + calibration bases) → lane lookup + group calibration factor (actual ÷ model) */
 const lanes=new Set();const own=[];RB.filter(r=>(r.mode||'sea')==='sea'&&r.amt>0).forEach(r=>{lanes.add(mkLane(r));own.push({...r,mode:'sea'})});(M.base||[]).forEach(b=>{if(b.amt>0){lanes.add(mkLane({mode:'sea',...b}));own.push({mode:'sea',...b,kind:'base'})}});D.lanes=lanes;D.own=own.length;
 if(G&&R&&own.length){const ek=new Map();G.edges.filter(e=>e.mode==='sea').forEach(e=>{const A=G.nodeById[e.from],B=G.nodeById[e.to];lqPks(A).forEach(a=>lqPks(B).forEach(b=>{ek.set(a+'|'+b,[e,A,B]);if(!ek.has(b+'|'+a))ek.set(b+'|'+a,[e,B,A])}))});
  const per={};for(const r of own){const x=ek.get(mkPk(r.pol)+'|'+mkPk(r.pod));if(!x)continue;const [e,A,B]=x;const g=lqGrp(A,B);const a=mkAdj(r,H);const u=a?a.usd:pU(r.amt,r.cur);const m=lqM1(R,lqEqK(r.eq),e.distanceKm);if(u>0&&m>0)(per[g]=per[g]||[]).push({f:u/m,d:mkRefD(r),lane:(A.nameFa||A.id)+' ← '+(B.nameFa||B.id)})}
  for(const [g,a] of Object.entries(per)){const f=mkMed(a.map(x=>x.f));D.cal[g]={f:Math.min(4,Math.max(.25,f)),n:a.length,d:a.map(x=>x.d).sort().pop(),lanes:[...new Set(a.map(x=>x.lane))].slice(0,4)}}}
 const W=LSG('ifa-wb',[]).filter(w=>w.st!=='cancel'&&+w.freight>0&&w.from&&w.to&&(!w.date||lqAge(w.date)<=180));const pk=[];let pd='';
 W.forEach(w=>{const km=dmKm(w.from,w.to);const tr=Math.max(1,Math.ceil((+w.kg||20000)/26000));if(km>50){pk.push(+w.freight/tr/km*(typeof dtAdjF==='function'?dtAdjF(w.date):1));if((w.date||'')>pd)pd=w.date||''}});
 RB.filter(r=>r.mode==='dom'&&r.cur==='IRR'&&r.amt>0&&(!r.from||lqAge(r.from)<=180)).forEach(r=>{const f=DMC.find(c=>nkey(r.pol).includes(nkey(c[1]))||nkey(r.pol)===nkey(c[0])),g=DMC.find(c=>nkey(r.pod).includes(nkey(c[1]))||nkey(r.pod)===nkey(c[0]));const km=f&&g?dmKm(f[0],g[0]):0;if(km>50){pk.push(+r.amt/km*(typeof dtAdjF==='function'?dtAdjF(r.from):1));if((r.from||'')>pd)pd=r.from||''}});
 D.domK=pk.length?{v:mkMed(pk),n:pk.length,d:pd||null}:null;D.domT=!!LSG('ifa-dom-t',null);D.domR=LSG('ifa-dom',{}).rr!=null;
 LQD=D;return D}
/* own lane rate for a specific edge (exact lane or CN proxy), via the v15.4 estimator: index-adjusted to today */
function lqOwn(D,A,B,eq){const key=A.id+'|'+B.id+'|'+eq;if(D.mem.has(key))return D.mem.get(key);let best=null;
 const ec=mkEqC(eq);outer:for(const pa of lqNm(A))for(const pb of lqNm(B)){const ln=['sea',mkPk(pa),mkPk(pb),ec].join('|');
  if(!D.lanes.has(ln))continue;let E=null;try{E=mkEstimate({pol:pa,pod:pb,eq},D.H)}catch(e){}if(E&&E.base&&E.usd>0){best={usd:E.usd,kind:E.base.kind,date:E.adj?E.adj.d1:mkRefD(E.base),from:mkRefD(E.base),idx:E.adj?E.adj.k:null,vendor:E.base.vendor||'',age:E.age};break outer}}
 D.mem.set(key,best);return best}
const LQSRC={own:['نرخ واقعی شما (تعدیل با شاخص)','hi'],proxy:['نرخ واقعی مسیر مشابه','mid'],cal:['مدل کالیبره با نرخ‌های واقعی شما','mid'],trend:['مدل × روند شاخص بازار','lo'],fuel:['مدل + سوخت روز','lo'],domown:['کرایهٔ واقعی شما ÷ دلار آزاد روز','hi'],dom:['تعرفهٔ داخلی شما ÷ دلار آزاد روز','mid'],dto:['شاخص رسمی تن-کیلومتر راهداری + هزینه‌های جانبی ÷ دلار آزاد','mid'],diesel:['مدل + گازوئیل روز کشور','mid'],model:['مدل (بدون منبع عمومی)','model']};
/* ---------- per-leg live pricing ---------- */
function lqLeg(e,t,r,n,o,X){const G=window.__IFA_E&&window.__IFA_E.G;if(!G)return null;const ld=window.__IFA_LD;window.__IFA_LD=null;const fid=ld===e.to?e.to:e.from;const A=G.nodeById[fid],B=G.nodeById[fid===e.from?e.to:e.from];if(!A||!B)return null;const D=lqData();const m=e.mode,km=e.distanceKm;const allin=X.freight+X.fuel;let y=null;
 if(m==='sea'&&LQS.sea){const eq=t.full?(n.sea.fcl[t.eqKey]?t.eqKey:t.teu/t.units>=2?'40HC':'20DV'):'40HC';const M1=lqM1(n,eq,km);const g=lqGrp(A,B);
  const own=lqOwn(D,A,B,eq);
  if(own){const rho=own.usd/M1;const P=allin*rho;const fu=P*n.sea.bafPct/(100+n.sea.bafPct);y={freight:P-fu,fuel:fu,src:own.kind==='proxy'?'proxy':'own',date:own.date,note:(own.vendor?own.vendor+' · ':'')+'پایه '+own.from+(own.idx?' · '+mkName(own.idx):''),rho}}
  else if(D.cal[g]){const c=D.cal[g];const P=allin*c.f;const fu=P*n.sea.bafPct/(100+n.sea.bafPct);y={freight:P-fu,fuel:fu,src:'cal',date:c.d,note:'ضریب '+nf(c.f,2)+' از '+fa(c.n)+' نرخ واقعی ('+LQGRP[g]+')',rho:c.f}}
  else{const tr=D.trend[g];const fr=X.freight*(tr?tr.r:1),fu=X.fuel*D.vlr;y={freight:fr,fuel:fu,src:tr?'trend':D.vl?'fuel':'model',date:tr?tr.d1:D.vl?D.vl[0]:null,note:(tr?tr.k.map(mkName).join('، ')+' ×'+nf(tr.r,2)+' از '+tr.d0:'')+(D.vl?(tr?' · ':'')+'VLSFO '+nf(D.vl[1])+'$/t':'')}}}
 else if(m==='short'&&LQS.sea&&D.vl){y={freight:X.freight,fuel:X.fuel*D.vlr,src:'fuel',date:D.vl[0],note:'VLSFO '+nf(D.vl[1])+'$/t (مرجع '+nf(LQS.vRef)+')'}}
 else if(m==='road'&&LQS.road){const trucks=t.full?t.units:Math.max(.15,Math.min(1,(t.roadKg||t.tonnes*1000)/24000));
  if(A.country==='IR'&&B.country==='IR'&&LQS.dom&&(D.domK||D.domT||dtOn())){const T=dmTypes();const ty=t.full?(r.reefer?'rf':'ctn'):'trl';const tt=T.find(x=>x[0]===ty)||T[0];const S=Object.assign({ret:0,load:15e6,toll:3e6,com:8,fp:30000},LSG('ifa-dom',{}));
   const ctn=T.find(x=>x[0]==='ctn')||tt;const own=D.domK?D.domK.v*(tt[3]/(ctn[3]||tt[3])):0;const dto=!own&&dtOn();const DR=dto?dtCalc(Object.assign({},S,{km,ty,tons:t.full?Math.max(1,(+t.tonnes||20*t.units)/Math.max(1,t.units)):24,stop:0,val:0,offer:0},o?{load:0,toll:0,wgh:0}:{}),T):null;const per=own?km*own:dto?DR.per:(km*tt[3]*(1+(S.ret||0)/100)+(o?0:(+S.load||0)+(+S.toll||0)))*(1+(+S.com||0)/100);const fuI=dto?DR.fuel:km*tt[4]/100*(+S.fp||0);const P=per*trucks/D.fx,fu=Math.min(P*.6,fuI*trucks/D.fx);
   y={freight:P-fu,fuel:fu,src:own?'domown':dto?'dto':'dom',date:D.fxT?new Date(D.fxT).toISOString().slice(0,10):null,irr:per*trucks,note:(own?'میانهٔ '+fa(D.domK.n)+' کرایهٔ واقعی تعدیل‌شده با شاخص ('+nf(own)+' ﷼/km)':dto?'شاخص رسمی '+nf(DR.off.V.tkm)+' ﷼/تن-km از '+DR.off.V.from+' · '+tt[1]+' · کف '+nf(DR.off.floor)+' ﷼':tt[1]+' · '+nf(tt[3])+' ﷼/km')+' · دلار '+nf(D.fx)+' ﷼',base:o?0:(dto?DR.off.extra:((+S.load||0)+(+S.toll||0)))*trucks/D.fx}}
  else{const a=D.dsl[A.country],b=D.dsl[B.country];const ps=[a,b].filter(Boolean);if(ps.length){const p=ps.reduce((s,x)=>s+x[1],0)/ps.length;const dlt=trucks*km*LQS.lpk*(p-LQS.dRef);y={freight:X.freight,fuel:Math.max(0,X.fuel+dlt),src:'diesel',date:ps.map(x=>x[0]).sort()[0],note:'گازوئیل '+[...new Set([A.country,B.country])].join('/')+' '+nf(p,2)+'$/L (مرجع '+nf(LQS.dRef,2)+')'}}}}
 else if(m==='rail'&&LQS.rail&&A.country==='IR'&&B.country==='IR'&&LQS.dom&&D.domR){const S=Object.assign({rr:4500,rh:2500000},LSG('ifa-dom',{}));const tons=t.full?Math.max(t.tonnes,t.units*10):Math.max(1,t.tonnes);
  const irr=km*tons*(+S.rr||0)+(o?0:tons*(+S.rh||0)*2);if(irr>0){const P=irr/D.fx;y={freight:P*.9,fuel:P*.1,src:'dom',irr,date:D.fxT?new Date(D.fxT).toISOString().slice(0,10):null,note:'تعرفهٔ ریلی '+nf(+S.rr)+' ﷼/تن‌کیلومتر · دلار '+nf(D.fx)+' ﷼',base:o?0:tons*(+S.rh||0)*2/D.fx}}}
 if(!y)y={freight:X.freight,fuel:X.fuel,src:'model',date:null,note:m==='air'?'شاخص عمومی هوایی رایگان در دسترس نیست':A.country==='IR'&&B.country==='IR'&&(m==='road'||m==='rail')?'برای کرایهٔ داخلی روز، بارنامه/نرخ واقعی یا تعرفهٔ به‌روز را در «حمل داخلی» ثبت کنید':m==='rail'?'تعرفهٔ ریلی بین‌المللی عمومی نیست':''};
 const out={...X,freight:y.freight,fuel:y.fuel,base:y.base!=null?y.base:X.base};
 if(LQTR)LQTR.push({edge:e.id,from:A.id,to:B.id,mode:m,km,model:allin,live:y.freight+y.fuel,src:y.src,date:y.date,note:y.note,irr:y.irr||null,extra:X.peak+X.special});return out}
window.__IFA_LF=(e,t,r,n,o,X)=>{if(LQOFF||!(LQS.on||LQF))return X;try{return lqLeg(e,t,r,n,o,X)||X}catch(err){return X}};
/* map / optimizer recompute when live mode or data changes */
function lqApply(){try{EMC.key=''}catch(e){}LQD=null;const R=window.__IFA_RATES;if(R&&R[0]&&R[1])R[1]({...R[0],__live:Date.now()})}
let LQT=0;const lqBump=()=>{LQD=null;if(!LQS.on)return;clearTimeout(LQT);LQT=setTimeout(lqApply,1500)};
['market.updated','fx.market','fx.updated','rates.imported'].forEach(ev=>(BUS[ev]=BUS[ev]||[]).push(lqBump));
/* ---------- quote: optimizer under live pricing + model re-cost of the same paths ---------- */
function lqCost(legs,live){const keep=LQTR;LQTR=live?[]:null;if(live)LQF++;else LQOFF++;try{const x=yr(legs);return {x,tr:LQTR}}finally{if(live)LQF--;else LQOFF--;LQTR=keep}}
function lqQuote(from,to,top=LQS.top){const C=ctx();if(!C)throw new Error('موتور نقشه آماده نیست');const G=C.G;if(!G.nodeById[from]||!G.nodeById[to])throw new Error('مبدأ/مقصد نامعتبر');if(from===to)throw new Error('مبدأ و مقصد یکی است');
 if(LQD)LQD.chk=0;const sv={o:OPT.o,d:OPT.d,res:OPT.res,sig:OPT.sig,sel:OPT.sel};let R;LQF++;try{EMC.key='';OPT.o=from;OPT.d=to;OPT.res=null;R=runOpt(C)}finally{LQF--;EMC.key='';Object.assign(OPT,sv)}
 const D=lqData();const out=R.cands.slice(0,top).map(c=>{const legs=c.x.legs.map(l=>({edge:l.edge,from:l.from,to:l.to}));const L=lqCost(legs,true),M=lqCost(legs,false);if(!L.x||!M.x)return null;
  const T=L.tr.map((s,i)=>({...s,days:(c.x.legs[i]&&c.x.legs[i].runHours||0)/24}));const tot=T.reduce((s,x)=>s+x.live,0)||1;const w={hi:1,mid:.7,lo:.4,model:.15};const conf=T.reduce((s,x)=>s+x.live*(w[(LQSRC[x.src]||LQSRC.model)[1]]||.15),0)/tot;
  return {name:c.name,rank:c.rank,modes:c.modeSeq,nodes:c.x.nodeSeq,days:c.p50D,p90:c.p90D,risk:c.risk,live:L.x.total,model:M.x.total,cost:L.x.cost,mcost:M.x.cost,legs:T,conf,tags:c.tags||[]}}).filter(Boolean);
 out.sort((a,b)=>a.live-b.live);return {from,to,at:Date.now(),cargo:C.cargo,routes:out,data:lqFresh(D)}}
function lqFresh(D=lqData()){const H=D.H;const L=k=>mkLast(H,k);const S=mkC();const pg=L('ccfi|PERSIAN_GULF_RED_SEA');const pgA=H['ccfi|PERSIAN_GULF_RED_SEA']||[];const pg4=pgA.length>1?pgA[Math.max(0,pgA.length-5)]:null;
 const dk=Object.keys(D.dsl);const dd=dk.map(k=>D.dsl[k][0]).sort();const fb=L('fbx|FBX')||L('fbx|FBX11'),wc=L('wci|COMP');
 return [
  {k:'fx',n:'دلار بازار آزاد',v:nf(D.fx)+' ﷼',d:D.fxT?new Date(D.fxT).toISOString().slice(0,10):null,s:D.fxSrc,use:'کرایهٔ جاده‌ای و ریلی داخل ایران'},
  {k:'pg',n:'CCFI خلیج فارس/دریای سرخ',v:pg?nf(pg[1],1):null,d:pg&&pg[0],s:'SSE',chg:pg&&pg4&&pg4!==pg?(pg[1]/pg4[1]-1)*100:null,wk:pg&&pg4?Math.max(1,Math.round(fwDiff(pg4[0],pg[0])/7)):0,use:'روند دریایی آسیا ← خلیج فارس'},
  {k:'bk',n:'سوخت کشتی VLSFO',v:D.vl?nf(D.vl[1])+' $/t':null,d:D.vl&&D.vl[0],s:'Ship & Bunker',use:'جزء سوخت دریایی و کوتاه‌برد'},
  {k:'ds',n:'گازوئیل '+fa(dk.length)+' کشور',v:D.dsl.IR?'ایران '+nf(D.dsl.IR[1],3)+' · ترکیه '+(D.dsl.TR?nf(D.dsl.TR[1],2):'—')+' $/L':dk.length?fa(dk.length)+' کشور':null,d:dd[0]||null,s:'GlobalPetrolPrices',use:'جزء سوخت جاده‌ای بین‌المللی'},
  {k:'fbx',n:'FBX / WCI (آسیا–اروپا)',v:fb||wc?[fb?'FBX '+nf(fb[1]):'',wc?'WCI '+nf(wc[1]):''].filter(Boolean).join(' · ')+' $/FEU':null,d:(fb||wc||[])[0]||null,s:'Freightos · Drewry',use:'روند اروپا ← خلیج فارس (FBX12/14)'},
  {k:'own',n:'نرخ‌های واقعی شما',v:D.own?fa(D.own)+' نرخ دریایی':null,d:null,s:'بانک نرخ + کالیبراسیون',use:'دقیق‌ترین منبع؛ با CCFI تا امروز تعدیل می‌شود'}].map(x=>({...x,age:lqAge(x.d),srv:!!(S&&S.t)}))}
/* ---------- view ---------- */
const lqAgeC=a=>a==null?'':a<=8?'ok':a<=35?'warn':'bad';
const lqBadge=s=>{const [n,c]=LQSRC[s]||LQSRC.model;return `<span class="lq-b ${c}">${n}</span>`};
const lqConf=v=>`<span class="mk-cr ${v>=.65?'':v>=.4?'warn':'bad'}" title="سهم هزینه که از دادهٔ روز/نرخ واقعی آمده (وزن‌دار)"><i><s style="width:${Math.round(v*100)}%"></s></i><b>${fa(Math.round(v*100))}</b></span>`;
const LQCL=[['freight','کرایهٔ حمل'],['fuel','سوخت'],['peak','فصل اوج'],['special','ریسک جنگ/ویژه'],['thc','THC'],['handling','تخلیه و بارگیری'],['transfer','جابه‌جایی بین‌وجهی'],['border','مرز و ترانزیت'],['customs','گمرک'],['docs','اسناد'],['insurance','بیمه'],['origin','مبدأ'],['lastMile','تحویل نهایی']];
function rLq(b,C){if(!C){b.innerHTML='<div class="sx-empty">موتور نقشه هنوز آماده نیست.</div>';return}const G=C.G;
 if(!LQS.from||!G.nodeById[LQS.from])LQS.from=C.R?C.R.nodeSeq[0]:'CN_SHA';if(!LQS.to||!G.nodeById[LQS.to])LQS.to=C.R?C.R.nodeSeq[C.R.nodeSeq.length-1]:'IR_THR';
 const ns=[...G.nodes].sort((a,c)=>(a.country==='IR')-(c.country==='IR')||a.country.localeCompare(c.country)||a.nameFa.localeCompare(c.nameFa,'fa'));
 const opts=v=>{let cur='',h='';ns.forEach(n=>{if(n.country!==cur){if(cur)h+='</optgroup>';cur=n.country;h+=`<optgroup label="${esc(n.country)}">`}h+=`<option value="${n.id}"${n.id===v?' selected':''}>${esc(n.nameFa)}${n.nameEn?' — '+esc(n.nameEn):''}</option>`});return h+'</optgroup>'};
 const cg=C.cargo||{};const cs=[cg.shipmentType==='FCL'||!cg.shipmentType?(cg.containerType||'40HC'):cg.shipmentType,cg.units?fa(cg.units)+' واحد':'',cg.weightKg?nf(cg.weightKg)+' kg':'',cg.value?'$'+nf(cg.value):''].filter(Boolean).join(' · ');
 b.innerHTML=`<div class="fw mk lq"><div class="sx-card lq-h"><div class="lq-od"><label class="sx-f"><span>مبدأ</span><select class="lq-f">${opts(LQS.from)}</select></label><button class="sx-btn sm lq-sw" title="جابه‌جایی مبدأ و مقصد">⇄</button><label class="sx-f"><span>مقصد</span><select class="lq-t">${opts(LQS.to)}</select></label><button class="sx-btn pri lq-go">محاسبهٔ هزینه با دادهٔ روز</button></div>
  <div class="lq-sub"><span class="sx-muted">محموله (از پنل اصلی): ${esc(cs||'پیش‌فرض')}</span><label class="lq-ck"><input type="checkbox" class="lq-on"${LQS.on?' checked':''}> اعمال دادهٔ روز در همهٔ محاسبات اپ (نقشه، بهینه‌ساز، هزینهٔ تمام‌شده)</label><button class="sx-btn sm lq-rf"${svUrl()?'':' disabled title="نیاز به سرور تیمی"'}>به‌روزرسانی داده‌ها از منابع</button><button class="sx-btn sm lq-cfg">تنظیمات</button></div>
  <div class="lq-cfgb" hidden><label class="sx-f"><span>VLSFO مرجع مدل ($/t)</span><input type="number" data-k="vRef" value="${LQS.vRef}"></label><label class="sx-f"><span>گازوئیل مرجع مدل ($/L)</span><input type="number" step=".05" data-k="dRef" value="${LQS.dRef}"></label><label class="sx-f"><span>مصرف کامیون (L/km)</span><input type="number" step=".01" data-k="lpk" value="${LQS.lpk}"></label><label class="sx-f"><span>تاریخ کالیبراسیون مدل</span><input type="date" data-k="cal" value="${LQS.cal||''}"></label>
   ${[['sea','دریایی (شاخص/نرخ واقعی/بانکر)'],['road','جاده‌ای (گازوئیل روز)'],['dom','داخل ایران (تعرفهٔ ریالی ÷ دلار آزاد)'],['rail','ریلی داخلی']].map(([k,n])=>`<label class="lq-ck"><input type="checkbox" data-b="${k}"${LQS[k]?' checked':''}> ${n}</label>`).join('')}<p class="sx-note">حمل جاده‌ای داخل ایران با شاخص رسمی تن-کیلومتر سازمان راهداری و هزینه‌های جانبی «حمل داخلی» حساب می‌شود. اگر کرایهٔ واقعی ثبت کرده باشید، همان کرایه پس از تعدیل با شاخص رسمی به کار می‌رود.</p></div></div>
  <div class="lq-fr"></div><div class="lq-out"><div class="sx-empty sm">مبدأ و مقصد را انتخاب کنید و «محاسبه» را بزنید.</div></div></div>`;
 const fr=$('.lq-fr',b);const drawF=()=>{const F=lqFresh();fr.innerHTML=`<div class="lq-fg">${F.map(x=>`<div class="lq-fc ${x.v?lqAgeC(x.age):'none'}"><b>${x.n}</b><span>${x.v?esc(x.v):'ناموجود'}${x.chg!=null?` <small class="${x.chg>0?'up':'dn'}">${x.chg>0?'▲':'▼'}${nf(Math.abs(x.chg),1)}٪ ${fa(x.wk||1)} هفته</small>`:''}</span><small>${x.d?esc(x.s)+' · '+(x.age!=null?(x.age<=0?'امروز':fa(x.age)+' روز پیش'):x.d):esc(x.s)}</small><em>${x.use}</em></div>`).join('')}</div>${!svUrl()?'<p class="sx-note">برای دریافت خودکار شاخص‌ها، سوخت و دلار، اپ را از سرور تیمی اجرا کنید؛ بدون آن، فقط نرخ‌های ثبت‌شده و دلار تنظیمات مالی استفاده می‌شود.</p>':''}`};drawF();
 const out=$('.lq-out',b);
 const draw=()=>{const Q=LQRES;if(!Q||Q.from!==LQS.from||Q.to!==LQS.to){return}if(!Q.routes.length){out.innerHTML='<div class="sx-empty">مسیری بین این دو نقطه یافت نشد.</div>';return}const sel=Q.routes[Math.min(LQS.sel,Q.routes.length-1)];const best=Q.routes[0];
  const dv=(a,m)=>{const p=(a/m-1)*100;return `<small class="${p>0?'up':'dn'}">${p>0?'+':''}${nf(p,1)}٪</small>`};
  out.innerHTML=`<div class="lq-hero sx-card"><div><small>ارزان‌ترین مسیر با دادهٔ روز</small><b>${usd0(best.live)}</b><span>${esc(best.name)} · ${fa(nf(best.days,1))} روز</span></div><div><small>همان مسیر با مدل ثابت</small><b class="m">${usd0(best.model)}</b>${dv(best.live,best.model)}</div><div><small>به ریال (دلار آزاد)</small><b class="m">${mirr(best.live*lqData().fx)}</b></div><div><small>اطمینان داده</small>${lqConf(best.conf)}</div></div>
  <div class="sx-card"><div class="sx-tw"><table class="sx-tbl mk-t lq-rt"><thead><tr><th>#</th><th>مسیر</th><th>روش</th><th>زمان (روز)</th><th>هزینه با دادهٔ روز</th><th>مدل ثابت</th><th>اختلاف</th><th>اطمینان</th></tr></thead><tbody>${Q.routes.map((r,i)=>`<tr data-i="${i}" class="${r===sel?'on':''}"><td>${fa(i+1)}</td><td><b>${esc(r.name)}</b>${r.tags.length?' <small class="sx-muted">'+r.tags.map(esc).join('، ')+'</small>':''}</td><td>${r.modes.map(m=>`<span class="lq-m" style="--c:${MODE[m].c}">${MODE[m].n}</span>`).join('')}</td><td>${fa(nf(r.days,1))}<small class="sx-muted"> (P90 ${fa(nf(r.p90,1))})</small></td><td class="n">${usd0(r.live)}</td><td class="n sx-muted">${usd0(r.model)}</td><td>${dv(r.live,r.model)}</td><td>${lqConf(r.conf)}</td></tr>`).join('')}</tbody></table></div></div>
  <div class="mk-g lq-d"><div class="sx-card"><h4>بخش‌های مسیر: ${esc(sel.name)}</h4><div class="sx-tw"><table class="sx-tbl lq-lg"><thead><tr><th>بخش</th><th>روش</th><th>km</th><th>مدل</th><th>دادهٔ روز</th><th>منبع</th></tr></thead><tbody>${sel.legs.map(l=>`<tr><td>${esc(nname(l.from))} ← ${esc(nname(l.to))}</td><td><span class="lq-m" style="--c:${MODE[l.mode].c}">${MODE[l.mode].n}</span></td><td>${nf(l.km)}</td><td class="n sx-muted">${usd0(l.model)}</td><td class="n">${usd0(l.live)}${l.irr?`<div class="sx-muted lq-irr">${mirr(l.irr)}</div>`:''}</td><td>${lqBadge(l.src)}${l.date?` <small class="lq-a ${lqAgeC(lqAge(l.date))}">${esc(l.date)}</small>`:''}<div class="lq-nt">${esc(l.note||'')}</div>${l.mode==='sea'?`<button class="sx-btn xs lq-cb" data-f="${l.from}" data-t="${l.to}">ثبت نرخ واقعی این بخش</button>`:''}</td></tr>`).join('')}</tbody></table></div></div>
   <div class="sx-card"><h4>ریز هزینه (دادهٔ روز در برابر مدل)</h4><table class="sx-tbl lq-cl"><tbody>${LQCL.filter(([k])=>(sel.cost[k]||0)+(sel.mcost[k]||0)>.5).map(([k,n])=>`<tr><td>${n}</td><td class="n">${usd0(sel.cost[k])}</td><td class="n sx-muted">${usd0(sel.mcost[k])}</td></tr>`).join('')}<tr class="t"><td><b>جمع</b></td><td class="n"><b>${usd0(sel.live)}</b></td><td class="n sx-muted">${usd0(sel.model)}</td></tr></tbody></table>
   <div class="lq-act"><button class="sx-btn sm lq-op">باز کردن در بهینه‌ساز</button><button class="sx-btn sm lq-xl">خروجی CSV</button><button class="sx-btn sm lq-rfx"${svOn()?'':' disabled title="نیاز به ورود به سرور تیمی"'}>مرجع آنلاین (Freightos)</button></div><div class="lq-refb"></div><p class="sx-note">جزئیات ریسک جنگ، THC، گمرک، مرز و بیمه از فرض‌های مدل است؛ «دادهٔ روز» فقط کرایه و سوخت هر بخش را جایگزین می‌کند.</p></div></div>`;
  $$('.lq-rt tr[data-i]',out).forEach(tr=>tr.onclick=()=>{LQS.sel=+tr.dataset.i;draw()});
  $$('.lq-cb',out).forEach(x=>x.onclick=()=>{const A=G.nodeById[x.dataset.f],B=G.nodeById[x.dataset.t];const eq=lqEqK(cg.containerType||'40HC');const v=prompt(`نرخ واقعی کرایهٔ دریایی ${A.nameFa} ← ${B.nameFa} برای هر ${eq} (دلار، all-in):`);const a=+fa2(v||'').replace(/[^\d.]/g,'');if(!(a>0))return;
   const M=mkM();M.base=(M.base||[]).filter(z=>mkLane({mode:'sea',...z})!==mkLane({mode:'sea',pol:A.nameEn,pod:B.nameEn,eq}));M.base.push({pol:A.nameEn,pod:B.nameEn,eq,amt:a,cur:'USD',from:fwToday(),incl:'all-in',vendor:'کالیبراسیون'});mkMS(M);LQD=null;toast('نرخ ثبت شد؛ از این پس با CCFI تعدیل می‌شود');run();if(LQS.on)lqApply()});
  {const rx=$('.lq-rfx',out);if(rx)rx.onclick=()=>lqRef($('.lq-refb',out),G)}$('.lq-op',out).onclick=()=>{OPT.o=LQS.from;OPT.d=LQS.to;OPT.res=null;OPT.sig='';open('opt')};
  $('.lq-xl',out).onclick=()=>{const rows=[['route','leg_from','leg_to','mode','km','model_usd','live_usd','source','date','note']];Q.routes.forEach(r=>r.legs.forEach(l=>rows.push([r.name,nname(l.from),nname(l.to),l.mode,Math.round(l.km),Math.round(l.model),Math.round(l.live),(LQSRC[l.src]||LQSRC.model)[0],l.date||'',l.note||''])));
   const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='ifa-live-quote.csv';a.click()}};
 const run=()=>{out.innerHTML='<div class="sx-empty sm">در حال محاسبه…</div>';setTimeout(()=>{try{LQRES=lqQuote(LQS.from,LQS.to);LQS.sel=0;emit('live.quote',{from:LQS.from,to:LQS.to,usd:LQRES.routes[0]&&Math.round(LQRES.routes[0].live)});draw()}catch(e){out.innerHTML='<div class="sx-empty">خطا: '+esc(e.message)+'</div>'}},20)};
 $('.lq-f',b).onchange=e=>{LQS.from=e.target.value;lqSv();run()};$('.lq-t',b).onchange=e=>{LQS.to=e.target.value;lqSv();run()};
 $('.lq-sw',b).onclick=()=>{[LQS.from,LQS.to]=[LQS.to,LQS.from];lqSv();rLq(b,C);run()};$('.lq-go',b).onclick=run;
 $('.lq-on',b).onchange=e=>{LQS.on=e.target.checked;lqSv();lqApply();toast(LQS.on?'دادهٔ روز در همهٔ محاسبات اعمال شد':'بازگشت به مدل ثابت')};
 $('.lq-cfg',b).onclick=()=>{const x=$('.lq-cfgb',b);x.hidden=!x.hidden};
 $$('.lq-cfgb [data-k]',b).forEach(i=>i.onchange=()=>{LQS[i.dataset.k]=i.type==='date'?i.value:Math.max(.0001,+i.value||0);lqSv();LQD=null;if(LQS.on)lqApply();drawF();run()});
 $$('.lq-cfgb [data-b]',b).forEach(i=>i.onchange=()=>{LQS[i.dataset.b]=i.checked?1:0;lqSv();LQD=null;if(LQS.on)lqApply();run()});
 $('.lq-rf',b).onclick=async e=>{e.target.disabled=true;e.target.textContent='در حال دریافت…';try{await Promise.all([mkPull(true),window.__IFA_LIVE&&window.__IFA_LIVE.fx&&window.__IFA_LIVE.fx()].filter(Boolean))}catch(err){}LQD=null;e.target.disabled=false;e.target.textContent='به‌روزرسانی داده‌ها از منابع';drawF();run()};
 if(LQRES&&LQRES.from===LQS.from&&LQRES.to===LQS.to)draw();else run()}
(function(){const st=document.createElement('style');st.textContent=`.lq .lq-od{display:flex;gap:10px;align-items:flex-end;flex-wrap:wrap}.lq .lq-od .sx-f{margin:0;flex:1;min-width:220px}.lq .lq-od select{width:100%}.lq .lq-sw{height:34px}.lq .lq-go{height:36px}
.lq .lq-sub{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-top:10px;font-size:12.5px}.lq .lq-ck{display:inline-flex;gap:6px;align-items:center;font-size:12.5px;cursor:pointer}.lq .lq-cfgb{display:flex;flex-wrap:wrap;gap:10px;margin-top:10px;align-items:flex-end}.lq .lq-cfgb .sx-f{margin:0;width:170px}.lq .lq-cfgb .sx-note{flex-basis:100%;margin:0}.lq .lq-cfgb[hidden]{display:none}
.lq-fg{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:8px;margin:12px 0}.lq-fc{border:1px solid var(--line);border-radius:10px;padding:8px 10px;display:flex;flex-direction:column;gap:2px;border-inline-start:3px solid var(--line2)}.lq-fc b{font-size:12px}.lq-fc span{font:600 13px Inter,Vazirmatn}.lq-fc small{color:var(--faint);font-size:11px}.lq-fc em{font-style:normal;color:var(--muted);font-size:11px}
.lq-fc.ok{border-inline-start-color:var(--good)}.lq-fc.warn{border-inline-start-color:var(--fwarn)}.lq-fc.bad,.lq-fc.none{border-inline-start-color:var(--fbad)}.lq-fc.none span{color:var(--faint)}.lq small.up{color:var(--fbad)}.lq small.dn{color:var(--good)}
.lq-hero{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:14px;align-items:center;margin-bottom:12px}.lq-hero>div{display:flex;flex-direction:column;gap:3px}.lq-hero small{color:var(--muted)}.lq-hero b{font:700 24px Inter,Vazirmatn;color:var(--accent)}.lq-hero b.m{font-size:17px;color:var(--text)}.lq-hero span{font-size:12px;color:var(--muted)}
.lq-m{display:inline-block;font-size:11px;padding:1px 7px;border-radius:999px;margin:1px;border:1px solid var(--c);color:var(--c)}.lq-b{display:inline-block;font-size:11px;padding:1px 7px;border-radius:6px;background:var(--panel2);border:1px solid var(--line2)}.lq-b.hi{border-color:var(--good);color:var(--good)}.lq-b.mid{border-color:var(--accent);color:var(--accent)}.lq-b.lo{border-color:var(--fwarn);color:var(--fwarn)}.lq-b.model{color:var(--faint)}
.lq-a{font-size:10.5px}.lq-a.ok{color:var(--good)}.lq-a.warn{color:var(--fwarn)}.lq-a.bad{color:var(--fbad)}.lq-nt{font-size:10.5px;color:var(--faint);margin-top:2px;max-width:320px}.lq-irr{font-size:10.5px}.lq .lq-lg td,.lq .lq-cl td{padding:5px 8px;vertical-align:top}.lq .lq-cl tr.t td{border-top:1px solid var(--line2)}.lq .lq-cb{margin-top:4px}.lq-act{display:flex;gap:8px;margin-top:10px}.lq .lq-d{grid-template-columns:repeat(auto-fit,minmax(380px,1fr))}`;document.head.appendChild(st)})();
