
/* ===== v15.4: market indices · unified rate bank with provenance · credibility · benchmarking · auto-ingest · Iran-lane estimates ===== */
const MKSER={manual:'شاخص دستی',ccfi:'CCFI',scfi:'SCFI',wci:'Drewry WCI',fbx:'Freightos FBX',bunker:'سوخت کشتی'};
const MKL={'ccfi|COMPOSITE_INDEX':'CCFI ترکیبی','ccfi|PERSIAN_GULF_RED_SEA':'CCFI خلیج فارس/دریای سرخ','ccfi|EUROPE':'CCFI اروپا','ccfi|MEDITERRANEAN':'CCFI مدیترانه','ccfi|SOUTHEAST':'CCFI جنوب شرق آسیا','ccfi|W_C_AMERICA':'CCFI ساحل غربی آمریکا','ccfi|E_C_AMERICA':'CCFI ساحل شرقی آمریکا','ccfi|WEST_EAST_AFRICA':'CCFI آفریقای غربی/شرقی','ccfi|SOUTH_AFRICA':'CCFI آفریقای جنوبی',
 'scfi|COMPREHENSIVE_INDEX':'SCFI ترکیبی','wci|COMP':'WCI ترکیبی','wci|ROTTERDAM':'WCI شانگهای←روتردام','wci|GENOA':'WCI شانگهای←جنوا','wci|NEW_YORK':'WCI شانگهای←نیویورک','wci|LOS_ANGELES':'WCI شانگهای←لس‌آنجلس',
 'fbx|FBX':'FBX جهانی','fbx|FBX11':'FBX11 چین←شمال اروپا','fbx|FBX13':'FBX13 چین←مدیترانه','fbx|FBX01':'FBX01 چین←ساحل غربی آمریکا','fbx|FBX03':'FBX03 چین←ساحل شرقی آمریکا',
 'manual|ERAI':'ERAI ریلی چین–اروپا (دستی)','bunker|FUJ_VLSFO':'فجیره VLSFO','bunker|FUJ_MGO':'فجیره MGO','bunker|FUJ_IFO380':'فجیره IFO380','bunker|SIN_VLSFO':'سنگاپور VLSFO','bunker|SIN_MGO':'سنگاپور MGO','bunker|SIN_IFO380':'سنگاپور IFO380'};
const MKUNIT={manual:'',ccfi:'نقطه',scfi:'نقطه',wci:'$/FEU',fbx:'$/FEU',bunker:'$/تن'};
const MKS=Object.assign({tab:'idx',sel:'ccfi|PERSIAN_GULF_RED_SEA',lane:'',q:'',ing:'',ingR:null,feeder:350,fuel:0.3,fcK:'ccfi|PERSIAN_GULF_RED_SEA',fcH:12,dw:7,rt:5,dct:'40'},LSG('ifa-mkt-ui',{}));const mkSv=()=>{const {ingR,...o}=MKS;LSS('ifa-mkt-ui',o)};
const mkC=()=>LSG('ifa-mkt-cache',null);
const mkM=()=>Object.assign({manual:[],base:[],seen:0},LSG('ifa-mkt',{}));const mkMS=m=>LSS('ifa-mkt',m);
const fa2=s=>String(s==null?'':s).replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d)).replace(/[٬،]/g,',').replace(/٫/g,'.');
/* history = server-accumulated + manual entries (manual wins on the same day) */
function mkHist(){const C=mkC()||{hist:{}};const H={};Object.entries(C.hist||{}).forEach(([k,a])=>H[k]=a.map(x=>[x[0],+x[1]]));
 mkM().manual.forEach(m=>{const k=m.s+'|'+m.l;const a=H[k]=H[k]||[];const i=a.findIndex(x=>x[0]===m.d);if(i>=0)a[i]=[m.d,+m.v];else a.push([m.d,+m.v])});Object.values(H).forEach(a=>a.sort((x,y)=>x[0]<y[0]?-1:1));return H}
const mkLast=(H,k)=>{const a=H[k];return a&&a.length?a[a.length-1]:null};
function mkAt(H,k,d){const a=H[k];if(!a||!a.length||!d)return null;let best=null;for(const p of a){if(p[0]<=d)best=p;else break}if(best&&fwDiff(best[0],d)<=21)return best;const f=a.find(p=>p[0]>d);return f&&fwDiff(d,f[0])<=10?f:null}
const mkName=k=>MKL[k]||((MKSER[k.split('|')[0]]||k.split('|')[0])+' '+k.split('|')[1].replace(/_/g,' '));
/* lane → index mapping (sea freight; primary first) */
const MKRX={cn:/china|shanghai|ningbo|qingdao|shenzhen|yantian|shekou|guangzhou|nansha|tianjin|xingang|xiamen|dalian|lianyungang|fuzhou|hong ?kong|چین|شانگهای|نینگبو|چینگدائو|شنژن|گوانگژو|تیانجین|شیامن|دالیان|هنگ‌?کنگ/i,
 asia:/busan|korea|japan|tokyo|yokohama|singapore|port klang|kaohsiung|ho chi minh|haiphong|laem chabang|کره|ژاپن|سنگاپور|بوسان/i,
 ir:/bandar ?abbas|shahid ?rajaee|rajaee|bnd\b|bushehr|chabahar|imam khomeini|bik\b|khorramshahr|asaluyeh|iran|بندرعباس|بندر عباس|شهید رجایی|رجایی|بوشهر|چابهار|امام خمینی|خرمشهر|عسلویه|ایران/i,
 gulf:/jebel ?ali|dubai|sharjah|khalifa|abu dhabi|dammam|hamad|doha|sohar|kuwait|umm qasr|basra|jeddah|aqaba|جبل ?علی|دبی|شارجه|ابوظبی|دمام|دوحه|صحار|کویت|ام‌?القصر|بصره|جده/i,
 neu:/rotterdam|hamburg|antwerp|felixstowe|bremerhaven|le havre|gdansk|روتردام|هامبورگ|آنتورپ/i,
 med:/genoa|genova|piraeus|valencia|barcelona|mersin|istanbul|ambarli|izmit|gemlik|novorossiysk|constanta|koper|trieste|la spezia|جنوا|پیرئوس|مرسین|استانبول|نووروسیسک/i,
 usw:/los angeles|long beach|oakland|seattle|tacoma|vancouver|لس/i,use:/new york|savannah|norfolk|charleston|houston|نیویورک/i};
function mkMap(r){if(r&&r.mode==='rail'){const H=mkHist();return (MKRX.cn.test(String(r.pol||''))||MKRX.cn.test(String(r.pod||'')))&&H['manual|ERAI']?['manual|ERAI']:[]}if(!r||!['sea','multi'].includes(r.mode||'sea'))return [];const o=String(r.pol||''),d=String(r.pod||'');const fromCn=MKRX.cn.test(o)||MKRX.asia.test(o);if(!fromCn)return MKRX.cn.test(d)?[]:['fbx|FBX'];
 if(MKRX.ir.test(d)||MKRX.gulf.test(d))return ['ccfi|PERSIAN_GULF_RED_SEA','scfi|COMPREHENSIVE_INDEX','ccfi|COMPOSITE_INDEX'];if(MKRX.neu.test(d))return ['fbx|FBX11','wci|ROTTERDAM','ccfi|EUROPE'];if(MKRX.med.test(d))return ['fbx|FBX13','wci|GENOA','ccfi|MEDITERRANEAN'];
 if(MKRX.usw.test(d))return ['fbx|FBX01','wci|LOS_ANGELES','ccfi|W_C_AMERICA'];if(MKRX.use.test(d))return ['fbx|FBX03','wci|NEW_YORK','ccfi|E_C_AMERICA'];return ['ccfi|COMPOSITE_INDEX','scfi|COMPREHENSIVE_INDEX']}
const mkRefD=r=>r.from||(r.t?new Date(r.t).toISOString().slice(0,10):null)||fwToday();
/* index-adjusted value of an actual rate as of `to` (default: latest index) */
function mkAdj(r,H=mkHist(),to){const u=pU(r.amt,r.cur);for(const k of mkMap(r)){const a=mkAt(H,k,mkRefD(r));const b=to?mkAt(H,k,to):mkLast(H,k);if(a&&b&&a[1]>0){const ratio=b[1]/a[1];return {usd:u*ratio,ratio,k,d0:a[0],v0:a[1],d1:b[0],v1:b[1],base:u}}}return null}
/* unified lane key: mode | origin | destination | equipment class */
const mkEqC=e=>{e=String(e||'').toUpperCase().replace(/\s/g,'');if(/^40|FEU|HC|HQ/.test(e))return /RF|RH/.test(e)?'40RF':'40';if(/^20|TEU/.test(e))return /RF/.test(e)?'20RF':'20';return e||'?'};
const mkPk=s=>nkey(String(s||'').replace(/\(.*?\)|port|بندر|,.*$/gi,'')).slice(0,18);
const mkLane=r=>[r.mode||'sea',mkPk(r.pol),mkPk(r.pod),mkEqC(r.eq)].join('|');
const MKSRC={rfq:['استعلام آنلاین',85],email:['ایمیل/متن',70],excel:['فایل Excel',70],csv:['فایل CSV',70],manual:['ثبت دستی',65],seed:['مرجع کریدور',40],index:['برآورد شاخص',35]};
const mkSrcOf=r=>r.src||(/مرجع کریدور/.test(r.note||'')?'seed':'manual');
const mkMed=a=>{if(!a.length)return null;const s=[...a].sort((x,y)=>x-y),m=s.length>>1;return s.length%2?s[m]:(s[m-1]+s[m])/2};
/* credibility (0-100) + verdict for every rate in one pass */
function mkScore(R=rbAll(),H=mkHist()){const t=fwToday();const L={};const V=R.map(r=>{const a=mkAdj(r,H);const u=pU(r.amt,r.cur);const now=a?a.usd:u;const o={r,u,now,adj:a,lane:mkLane(r)};(L[o.lane]=L[o.lane]||[]).push(o);return o});
 V.forEach(o=>{const r=o.r;const peers=L[o.lane].filter(x=>x!==o&&rbStat(x.r,t)!=='exp');const ref=mkMed(peers.map(x=>x.now));o.ref=ref;o.n=peers.length;
  const age=Math.max(0,fwDiff(mkRefD(r),t));const fr=age<=7?100:age<=30?80:age<=60?55:age<=90?35:15;const exp=rbStat(r,t)==='exp';
  const st=(MKSRC[mkSrcOf(r)]||MKSRC.manual)[1]*(r.conf!=null?(.6+.4*r.conf):1);const near=peers.filter(x=>Math.abs(x.now/o.now-1)<=.15).length;const cor=!peers.length?50:near>=2?100:near===1?75:30;
  o.dv=ref?(o.now/ref-1):null;const ds=o.dv==null?60:Math.abs(o.dv)<=.1?100:Math.abs(o.dv)<=.2?75:Math.abs(o.dv)<=.35?45:15;
  o.score=Math.round((st*.3+fr*.3+cor*.2+ds*.2)*(exp?.6:1));o.cl=o.score>=75?'ok':o.score>=50?'warn':'bad';
  o.verdict=o.dv==null?'':o.dv>.15?'exp':o.dv<-.2?'cheap':'fair'});return V}
const MKV={exp:['گران‌تر از بازار','bad'],cheap:['ارزان مشکوک','warn'],fair:['منصفانه','ok'],'':['بدون مرجع','']};
const mkVb=v=>`<span class="tm-s ${MKV[v||''][1]}">${MKV[v||''][0]}</span>`;
const mkCb=o=>`<span class="mk-cr ${o.cl}" title="منبع، تازگی، تأیید متقابل و فاصله از میانهٔ بازار"><i><s style="width:${o.score}%"></s></i><b>${fa(o.score)}</b></span>`;
/* RFQ quote verdict: other quotes on the route (index-adjusted to today) + system model */
function mkQuote(q,Q,model){const H=mkHist();const k='ccfi|COMPOSITE_INDEX';const last=mkLast(H,k);const adj=x=>{const d=new Date(x.t||Date.now()).toISOString().slice(0,10);const a=mkAt(H,k,d);return a&&last?x.c*last[1]/a[1]:x.c};
 const refs=Q.filter(x=>x!==q).map(adj);if(model>0)refs.push(model);const ref=mkMed(refs);if(!ref)return {v:'',dv:null};const dv=q.c/ref-1;return {v:dv>.15?'exp':dv<-.2?'cheap':'fair',dv,ref,n:refs.length}}
/* ---------- auto-ingest: e-mail / free text / CSV / Excel ---------- */
const MKCUR=[[/US\$|USD|\$|دلار/i,'USD'],[/EUR|€|یورو/i,'EUR'],[/AED|درهم/i,'AED'],[/CNY|RMB|¥|یوان/i,'CNY'],[/TRY|₺|لیر/i,'TRY'],[/RUB|₽|روبل/i,'RUB'],[/IRR|ریال/i,'IRR']];
const mkCur=s=>{for(const [re,c] of MKCUR)if(re.test(s))return c;return ''};
const MKEQ=/\b(20|40|45)\s*['’`]?\s*(GP|DV|DC|HC|HQ|RF|RH|OT|FR|ST|STD)?\b|\b(FEU|TEU)\b/gi;
const mkEqN=(n,t)=>{if(!n)return t==='FEU'?'40DV':'TEU';t=(t||'').toUpperCase();return n==='20'?(t==='RF'?'20RF':'20DV'):n==='45'?'40HC':t==='HC'||t==='HQ'?'40HC':t==='RF'||t==='RH'?'40RF':'40DV'};
const MKMON={jan:1,feb:2,mar:3,apr:4,may:5,jun:6,jul:7,aug:8,sep:9,oct:10,nov:11,dec:12};
function mkDate(s){s=fa2(s).trim();let m;if(typeof s==='number'||/^\d{5}$/.test(s)){const n=+s;if(n>30000&&n<70000)return new Date(Date.UTC(1899,11,30)+n*864e5).toISOString().slice(0,10)}
 if((m=s.match(/(20\d\d)[-/.](\d{1,2})[-/.](\d{1,2})/)))return mkIso(+m[1],+m[2],+m[3]);if((m=s.match(/(1[34]\d\d)[-/.](\d{1,2})[-/.](\d{1,2})/))){try{return mkJal(+m[1],+m[2],+m[3])}catch(e){}}
 if((m=s.match(/(\d{1,2})[-/.](\d{1,2})[-/.](20\d\d)/)))return mkIso(+m[3],+m[2],+m[1]);
 if((m=s.match(/(\d{1,2})(?:st|nd|rd|th)?[\s-]*([A-Za-z]{3})[a-z]*[\s,-]*(20\d\d)?/))&&MKMON[m[2].toLowerCase()]){const y=+m[3]||new Date().getFullYear();return mkIso(y,MKMON[m[2].toLowerCase()],+m[1])}
 if((m=s.match(/([A-Za-z]{3})[a-z]*\.?\s+(\d{1,2})(?:st|nd|rd|th)?,?\s*(20\d\d)?/))&&MKMON[m[1].toLowerCase()]){const y=+m[3]||new Date().getFullYear();return mkIso(y,MKMON[m[1].toLowerCase()],+m[2])}return ''}
const mkIso=(y,m,d)=>{const x=new Date(Date.UTC(y,m-1,d));return isNaN(x)||m>12||d>31?'':x.toISOString().slice(0,10)};
function mkJal(jy,jm,jd){jy+=1595;let days=-355668+365*jy+Math.floor(jy/33)*8+Math.floor((jy%33+3)/4)+jd+(jm<7?(jm-1)*31:(jm-7)*30+186);let gy=400*Math.floor(days/146097);days%=146097;if(days>36524){gy+=100*Math.floor(--days/36524);days%=36524;if(days>=365)days++}gy+=4*Math.floor(days/1461);days%=1461;if(days>365){gy+=Math.floor((days-1)/365);days=(days-1)%365}
 const sal=[0,31,(gy%4===0&&gy%100!==0)||gy%400===0?29:28,31,30,31,30,31,31,30,31,30,31];let gm=1;for(;gm<13&&days>=sal[gm];gm++)days-=sal[gm];return mkIso(gy,gm,days+1)}
const MKPORT=/(shanghai|ningbo|qingdao|shenzhen|yantian|shekou|guangzhou|nansha|tianjin|xingang|xiamen|dalian|hong ?kong|busan|singapore|bandar ?abbas|shahid ?rajaee|bushehr|chabahar|imam khomeini|jebel ?ali|dubai|sharjah|mersin|istanbul|rotterdam|hamburg|genoa|novorossiysk|umm qasr|karachi|nhava sheva|mundra|شانگهای|نینگبو|چینگدائو|شنژن|گوانگژو|تیانجین|بندرعباس|بندر عباس|شهید رجایی|بوشهر|چابهار|امام خمینی|جبل ?علی|دبی|مرسین|استانبول)/i;
function mkIncl(s){s=String(s);const inc=[];if(/all[\s-]?in/i.test(s))inc.push('all-in');if(/BAF|bunker/i.test(s))inc.push(/BAF[^.\n]{0,20}(incl|included|شامل)/i.test(s)?'BAF شامل':'BAF جدا');if(/THC/i.test(s))inc.push(/THC[^.\n]{0,20}(incl|included|شامل)/i.test(s)?'THC شامل':'THC جدا');if(/subject to|excl/i.test(s))inc.push('هزینه‌های جانبی جدا');return inc.join('، ')}
function mkMode(s){return /rail|train|wagon|ریلی|قطار|واگن/i.test(s)?'rail':/truck|road|FTL|LTL|کامیون|جاده/i.test(s)?'road':/air|AWB|kg\b|هوایی/i.test(s)?'air':'sea'}
/* header-based tables (CSV/Excel/TSV) */
const MKH={pol:/^(pol|origin|from|load|loading|port of loading|مبدأ|مبدا|بارگیری)/i,pod:/^(pod|dest|destination|to|discharge|port of discharge|مقصد|تخلیه)/i,eq:/^(eq|equip|equipment|container|cntr|type|size|تجهیز|کانتینر|نوع)/i,amt:/^(amt|amount|rate|price|o\/f|ocean ?freight|freight|all ?in|مبلغ|نرخ|قیمت|کرایه)/i,cur:/^(cur|currency|ارز)/i,
 to:/^(valid|validity|valid to|valid till|expiry|exp|to date|اعتبار|معتبر تا)/i,from:/^(valid from|from date|effective|شروع)/i,vendor:/^(vendor|carrier|line|agent|forwarder|supplier|company|شرکت|خط|حمل|تأمین)/i,tt:/^(tt|transit|t\/t|ترانزیت)/i,mode:/^(mode|شیوه)/i,note:/^(note|remark|توضیح)/i};
function mkTable(rows,src){if(!rows||rows.length<2)return null;let hi=-1,map=null;for(let i=0;i<Math.min(rows.length,8);i++){const M={},eqc=[];rows[i].forEach((c,j)=>{const s=fa2(c).trim();if(!s)return;const em=s.match(/^(20|40|45)\s*['’]?\s*(GP|DV|DC|HC|HQ|RF|ST)?$/i);if(em){eqc.push([j,mkEqN(em[1],em[2])]);return}for(const [k,re] of Object.entries(MKH))if(M[k]==null&&re.test(s)){M[k]=j;break}});
  if((M.pol!=null||M.pod!=null)&&(M.amt!=null||eqc.length)){hi=i;map={M,eqc};break}}if(!map)return null;const {M,eqc}=map;const out=[];const g=(r,k)=>M[k]!=null?fa2(r[M[k]]).trim():'';
 rows.slice(hi+1).forEach(r=>{if(!r||!r.some(x=>String(x).trim()))return;const pol=g(r,'pol'),pod=g(r,'pod');if(!pol&&!pod)return;const cur=mkCur(g(r,'cur'))||mkCur(g(r,'amt'))||'USD';const to=mkDate(r[M.to]!=null?r[M.to]:'');const from=mkDate(r[M.from]!=null?r[M.from]:'')||fwToday();
  const base={mode:RMODE[g(r,'mode')]?g(r,'mode'):mkMode(g(r,'eq')+' '+g(r,'note')),vendor:g(r,'vendor'),pol,pod,cur,from,to,tt:fwN(g(r,'tt'))||null,note:g(r,'note'),incl:mkIncl(g(r,'note')+' '+g(r,'amt')),src};
  const push=(eq,amt)=>{const a=+String(amt).replace(/[^\d.]/g,'');if(a>0)out.push({...base,eq,amt:a,conf:(pol&&pod?.5:.2)+(to?.25:0)+(base.vendor?.25:0)})};
  if(eqc.length)eqc.forEach(([j,eq])=>push(eq,fa2(r[j])));else push(M.eq!=null?(()=>{const s=g(r,'eq').toUpperCase();const m=s.match(/(20|40|45)\s*['’]?\s*(GP|DV|DC|HC|HQ|RF)?/);return m?mkEqN(m[1],m[2]):REQ.includes(s)?s:s||'40DV'})():'40DV',g(r,'amt'))});return out}

/* pair money amounts with the nearest container size on one line */
function mkAmts(L0){const L=L0.replace(/\d{4}[-/.]\d{1,2}[-/.]\d{1,2}|\d{1,2}[-/.]\d{1,2}[-/.]\d{4}/g,x=>' '.repeat(x.length));const E=[],A=[];let m;const er=/\b(20|40|45)\s*['’`]?\s*(GP|DV|DC|HC|HQ|RF|RH|OT|FR|ST|STD|NOR)?(?!\d)(?![.,]\d)(?!\s*(?:days?|روز|%|kg|ton|t\b))|\b(FEU|TEU)\b/gi;
 while((m=er.exec(L)))E.push({s:m.index,e:m.index+m[0].length,eq:m[3]?(m[3].toUpperCase()==='FEU'?'40DV':'TEU'):mkEqN(m[1],m[2])});
 const ar=/(US\$|USD|\$|EUR|€|AED|CNY|RMB|¥)?\s?(\d{1,3}(?:,\d{3})+|\d{2,6})(\.\d+)?\s?(USD|EUR|AED|CNY|RMB|\$|دلار)?/gi;const lc=mkCur(L);
 while((m=ar.exec(L))){const s0=m.index+(m[0].length-m[0].trimStart().length),e0=m.index+m[0].trimEnd().length;if(E.some(x=>s0<x.e&&e0>x.s))continue;const n=+m[2].replace(/,/g,'');const cur=mkCur((m[1]||'')+(m[4]||''));
  const after=L.slice(e0,e0+16);if(/^\s*(?:days?|روز|%|kg|cbm|ton)/i.test(after))continue;if(!cur&&!lc)continue;if(!cur&&n>=1990&&n<=2100)continue;if(n<50||n>200000)continue;A.push({s:s0,e:e0,n,cur:cur||lc||'USD',after})}
 const used=new Set();return A.map(a=>{let eq=null;const pv0=E.filter(x=>x.e<=a.s&&a.s-x.e<=14&&!used.has(x)&&/^[\s:=@\-–]*(?:US\$|USD|\$|EUR|€|AED|CNY|RMB)?[\s:=]*$/i.test(L.slice(x.e,a.s))).pop();const nx=pv0?null:E.find(x=>x.s>=a.e&&x.s-a.e<=10&&/^\s*(?:\/|per|for|each|\bx\b)/i.test(L.slice(a.e,x.s)));if(pv0)eq=pv0;else if(nx)eq=nx;else{const pv=E.filter(x=>x.e<=a.s&&a.s-x.e<=40&&!used.has(x)).pop();if(pv)eq=pv}if(eq)used.add(eq);return {eq:eq?eq.eq:'40DV',amt:a.n,cur:a.cur,sure:!!eq}})}
/* free text / e-mail */
function mkText(t,src='email'){t=fa2(t).replace(/\r/g,'');const out=[];const G={to:'',vendor:'',from:''};
 const vm=t.match(/valid(?:ity)?\s*(?:till|until|thru|through|to|up to|:)?\s*([^\n;]{4,24})|(?:اعتبار|معتبر)\s*(?:تا|:)\s*([^\n;]{4,24})/i);if(vm)G.to=mkDate(vm[1]||vm[2]);
 const cm=t.match(/(?:carrier|line|vessel operator|شرکت کشتیرانی|خط)\s*[:：]\s*([^\n,;]{2,40})|\bvia\s+(MSC|Maersk|CMA[\s-]?CGM|COSCO|OOCL|Evergreen|ONE|HMM|Hapag[\s-]?Lloyd|ZIM|Yang ?Ming|PIL|Emirates Shipping|IRISL|Wan Hai|KMTC|SITC)\b/i);if(cm)G.vendor=(cm[1]||cm[2]).trim();
 const fm=t.match(/^(?:from|sender|از)\s*:\s*(.+)$/im);const sender=fm?fm[1].replace(/<.*?>/,'').trim().slice(0,40):'';let route=null;
 const lines=t.split(/\n|(?<=\.)\s+(?=[A-Z])/);for(const ln of lines){const L=ln.trim();if(!L)continue;
  const rm=L.match(new RegExp(MKPORT.source+'(?:\\s*(?:port|,?\\s*china|,?\\s*uae|,?\\s*iran))?\\s*(?:-+|–|—|to|→|->|>|/|تا|به)\\s*'+MKPORT.source,'i'));if(rm)route={pol:rm[1].replace(/\b\w/g,c=>c.toUpperCase()),pod:rm[2].replace(/\b\w/g,c=>c.toUpperCase())};
  if(!route)continue;const lineTo=(()=>{const m=L.match(/valid[^\d\n]{0,12}([^\n;]{4,24})|اعتبار[^\d\n]{0,8}([^\n;]{4,24})/i);return m?mkDate(m[1]||m[2]):''})();
  const amts=mkAmts(L);
  amts.forEach(a=>out.push({mode:mkMode(L),vendor:G.vendor||sender,pol:route.pol,pod:route.pod,eq:a.eq,amt:a.amt,cur:a.cur,from:fwToday(),to:lineTo||G.to,tt:(()=>{const x=L.match(/(?:t\/t|transit|ترانزیت)\D{0,10}(\d{1,3})/i);return x?+x[1]:null})(),note:L.slice(0,120),incl:mkIncl(L),src,conf:.45+(lineTo||G.to?.25:0)+(G.vendor||sender?.15:0)+(a.sure?.15:0)}))}
 const seen=new Set();return out.filter(r=>{const k=[r.pol,r.pod,r.eq,r.amt].join('|');if(seen.has(k))return false;seen.add(k);return true})}
function mkParse(input,src){if(Array.isArray(input))return mkTable(input,src||'excel')||[];const t=String(input||'');const first=t.split(/\r?\n/).find(x=>x.trim())||'';
 if(/[,;\t]/.test(first)&&first.split(/[,;\t]/).length>=3){try{const T=mkTable(readCsv(t),src||'csv');if(T&&T.length)return T}catch(e){}}return mkText(t,src||'email')}
/* ---------- server pull + jump alerts ---------- */
let MKBUSY=null;async function mkPull(force){const u=svUrl();if(!u)return null;if(MKBUSY)return MKBUSY;MKBUSY=(async()=>{try{const j=force&&svOn()?await svApi('/api/live/indices/refresh',{method:'POST'}):await fetch(u+'/api/live/indices?days=400',{cache:'no-cache'}).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json()});
  if(!j||!j.series)throw new Error('پاسخ نامعتبر');LSS('ifa-mkt-cache',{...j,got:Date.now()});const M=mkM();const fresh=(j.alerts||[]).filter(a=>a.t>(M.seen||0));if(fresh.length){M.seen=Math.max(...fresh.map(a=>a.t));mkMS(M);
   fresh.slice(0,3).forEach(a=>{toast(`⚠ جهش شاخص ${MKSER[a.s]||a.s} — ${a.n}: ${a.chg>0?'+':''}${nf(a.chg,1)}٪`);emit('rate.jump',{index:a.s,line:a.k,name:a.n,value:a.v,change:a.chg})})}
  emit('market.updated',{series:Object.keys(j.series).length,t:j.t});mkWatchRun();return j}catch(e){MKS.err=e.message;return null}finally{MKBUSY=null}})();return MKBUSY}
setTimeout(()=>{if(svUrl()){const c=mkC();if(!c||Date.now()-(c.got||0)>3*3600e3)mkPull(false)}},9000);setInterval(()=>{if(svUrl())mkPull(false)},3*3600e3);
/* ---------- charts ---------- */
function mkSpark(a,w=120,h=30){if(!a||a.length<2)return `<svg class="mk-sp" width="${w}" height="${h}"></svg>`;const v=a.map(x=>x[1]),lo=Math.min(...v),hi=Math.max(...v),r=hi-lo||1;const P=v.map((y,i)=>[(i/(v.length-1))*(w-4)+2,h-3-(y-lo)/r*(h-6)]);const up=v[v.length-1]>=v[0];
 return `<svg class="mk-sp ${up?'up':'dn'}" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><path d="M${P.map(p=>p.map(n=>n.toFixed(1)).join(',')).join('L')}"/><circle cx="${P[P.length-1][0].toFixed(1)}" cy="${P[P.length-1][1].toFixed(1)}" r="2.2"/></svg>`}
function mkChart(a,unit){if(!a||a.length<2)return '<div class="sx-muted mk-ce">برای نمودار دست‌کم دو نقطهٔ تاریخی لازم است — سرور تاریخچه را هر هفته انباشته می‌کند؛ مقادیر گذشته را می‌توانید دستی هم وارد کنید.</div>';
 const W=760,Hh=220,pl=54,pr=12,pt=12,pb=26;const v=a.map(x=>x[1]),lo=Math.min(...v)*.97,hi=Math.max(...v)*1.03,r=hi-lo||1;const t0=Date.parse(a[0][0]),t1=Date.parse(a[a.length-1][0]),tr=t1-t0||1;
 const X=d=>pl+(Date.parse(d)-t0)/tr*(W-pl-pr),Y=y=>pt+(1-(y-lo)/r)*(Hh-pt-pb);const P=a.map(p=>[X(p[0]),Y(p[1])]);const ticks=[0,.25,.5,.75,1].map(f=>lo+f*r);
 return `<svg class="mk-ch" viewBox="0 0 ${W} ${Hh}" preserveAspectRatio="none">${ticks.map(y=>`<line x1="${pl}" x2="${W-pr}" y1="${Y(y)}" y2="${Y(y)}"/><text x="${pl-6}" y="${Y(y)+3}" text-anchor="end">${nf(y)}</text>`).join('')}
  <path class="a" d="M${P[0][0]},${Hh-pb}L${P.map(p=>p.join(',')).join('L')}L${P[P.length-1][0]},${Hh-pb}Z"/><path class="l" d="M${P.map(p=>p.map(n=>n.toFixed(1)).join(',')).join('L')}"/>
  ${a.length<=60?P.map((p,i)=>`<circle cx="${p[0].toFixed(1)}" cy="${p[1].toFixed(1)}" r="2.4"><title>${jdt(a[i][0])}: ${nf(a[i][1],1)} ${unit||''}</title></circle>`).join(''):''}
  <text x="${pl}" y="${Hh-8}">${jdt(a[0][0])}</text><text x="${W-pr}" y="${Hh-8}" text-anchor="end">${jdt(a[a.length-1][0])}</text></svg>`}
/* ---------- view ---------- */
function rMkt(b,C){const subs=[['idx','شاخص‌های بازار'],['fcst','پیش‌بینی'],['bm','محک و اعتبار نرخ‌ها'],['est','برآورد مسیرهای ایران'],['sur','سربارها و دموراژ'],['land','جاده‌ای و ریلی'],['watch','هشدارها و قراردادها'],['ing','ورود خودکار نرخ'],['src','منابع و روش']];
 b.innerHTML=`<div class="fw mk">${subNav(subs,MKS.tab,'mk-sub')}<div class="mk-b"></div></div>`;$$('.mk-sub button',b).forEach(x=>x.onclick=()=>{MKS.tab=x.dataset.v;mkSv();rMkt(b,C)});
 const B=$('.mk-b',b);(({idx:mkIdx,fcst:mkFc,bm:mkBm,est:mkEst,sur:mkSur,land:mkLand,watch:mkWatch,ing:mkIng,src:mkSrc})[MKS.tab]||mkIdx)(B,C,()=>rMkt(b,C));mkWatchRun()}
function mkIdx(B,C,re){const S=mkC();const H=mkHist();const on=!!svUrl();const ser=S&&S.series||{};const jp=S&&S.jumpPct||5;
 const lines=[];Object.entries(ser).forEach(([s,o])=>(o.lines||[]).forEach(l=>lines.push({key:s+'|'+l.k,s,...l})));mkM().manual.forEach(m=>{const k=m.s+'|'+m.l;if(!lines.some(x=>x.key===k)){const a=H[k];const L=a[a.length-1],P=a.length>1?a[a.length-2]:null;lines.push({key:k,s:m.s,k:m.l,n:mkName(k),v:L[1],prev:P?P[1]:null,chg:P?Math.round((L[1]/P[1]-1)*1e4)/100:null,man:1})}});
 const pick=k=>lines.find(x=>x.key===k);const pg=pick('ccfi|PERSIAN_GULF_RED_SEA'),fbx=pick('fbx|FBX'),wci=pick('wci|COMP'),fuj=pick('bunker|FUJ_VLSFO');const jumps=lines.filter(l=>l.chg!=null&&Math.abs(l.wk!=null?l.wk:l.chg)>=jp);
 const ck=(l,d)=>l?`${l.chg!=null?(l.chg>0?'▲ ':'▼ ')+nf(Math.abs(l.chg),1)+'٪ نسبت به قبل':''}`:'';
 const sel=MKS.sel&&H[MKS.sel]?MKS.sel:(lines[0]||{}).key;
 B.innerHTML=`${!on?`<div class="sx-card mk-off">${svgI(IC.warn||IC.info||'')}<div><b>بدون اتصال به سرور تیمی</b><p>دریافت خودکار CCFI، SCFI، WCI، FBX و قیمت سوخت از سرور انجام می‌شود (مرورگر به‌دلیل CORS نمی‌تواند مستقیم بخواند). از «تنظیمات ← سرور تیمی» وصل شوید یا مقادیر را دستی وارد کنید.</p></div></div>`:''}
 <div class="ex-kpis">${kpi('CCFI خلیج فارس/دریای سرخ',pg?pg.v:0,{d:1,sub:pg?ck(pg):'—',cls:pg&&Math.abs(pg.chg||0)>=jp?'warn':''})}${kpi('FBX جهانی ($/FEU)',fbx?fbx.v:0,{pre:'$',sub:fbx?ck(fbx):'—'})}${kpi('Drewry WCI ($/FEU)',wci?wci.v:0,{pre:'$',sub:wci?jdt((ser.wci||{}).date):'—'})}${kpi('VLSFO فجیره ($/تن)',fuj?fuj.v:0,{d:1,pre:'$',sub:fuj?ck(fuj):'—'})}${kpi('هشدار جهش (≥'+fa(jp)+'٪)',jumps.length,{cls:jumps.length?'bad':''})}</div>
 <div class="om-tb"><b>${S&&S.t?'آخرین دریافت: '+fdT(S.t):'هنوز داده‌ای دریافت نشده'}</b>${MKS.err?` <small class="bad">· ${esc(MKS.err)}</small>`:''}<span class="sx-sp"></span>${on?`<button class="sx-btn sm" data-pull>دریافت از سرور</button>${svOn()?'<button class="sx-btn sm" data-force title="فقط مدیر/پشتیبان">بروزرسانی فوری منابع</button>':''}`:''}<button class="sx-btn sm" data-xl>خروجی Excel</button></div>
 ${jumps.length?`<div class="sx-card mk-al"><header><b>هشدارهای جهش قیمت</b><small>تغییر هفتگی ≥ ${fa(jp)}٪ — روی نرخ‌های در جریان مذاکره اثر دارد</small></header>${jumps.map(l=>`<span class="mk-j ${(l.wk!=null?l.wk:l.chg)>0?'up':'dn'}">${esc(mkName(l.key))}: ${(l.wk!=null?l.wk:l.chg)>0?'+':''}${nf(l.wk!=null?l.wk:l.chg,1)}٪</span>`).join(' ')}</div>`:''}
 <div class="mk-g">${Object.keys(MKSER).filter(s=>s!=='manual'||lines.some(l=>l.s==='manual')).map(s=>{const o=ser[s]||{};const L=lines.filter(l=>l.s===s);const er=S&&S.errors&&S.errors[s];return `<div class="sx-card mk-c"><header><b>${esc(o.name||MKSER[s])}</b><small>${esc(o.src||'')} · ${o.date?jdt(o.date):'—'} · ${esc(o.freq||'')}</small></header>
  ${er?`<p class="sx-muted bad">خطای آخرین دریافت: ${esc(er.err)}</p>`:''}${L.length?`<table class="sx-tbl mk-t"><tbody>${L.map(l=>{const a=H[l.key]||[];const ch=l.wk!=null?l.wk:l.chg;return `<tr class="${l.key===sel?'on':''}" data-sel="${esc(l.key)}"><td>${esc(l.n)}${l.man?' <small class="sx-muted">(دستی)</small>':''}</td><td class="n">${(MKUNIT[s]||'').includes('$')?'$':''}${nf(l.v,s==='ccfi'||s==='scfi'?1:0)}</td><td class="n ${ch==null?'':ch>0?'up':'dn'}">${ch==null?'—':(ch>0?'+':'')+nf(ch,1)+'٪'}${ch!=null&&Math.abs(ch)>=jp?' ⚡':''}</td><td>${mkSpark(a.slice(-26))}</td></tr>`}).join('')}</tbody></table>`:'<p class="sx-muted">داده‌ای نیست</p>'}</div>`}).join('')}</div>
 <div class="sx-card"><header><b>روند: ${esc(sel?mkName(sel):'—')}</b><small>${sel&&H[sel]?fa(H[sel].length)+' نقطه · '+(MKUNIT[sel.split('|')[0]]||''):''}</small></header>${mkChart(sel?H[sel]:null,sel?MKUNIT[sel.split('|')[0]]:'')}</div>
 <div class="sx-card fw-form mk-man"><header><b>ثبت دستی مقدار شاخص</b><small>برای کار آفلاین، تکمیل تاریخچهٔ گذشته یا شاخص‌های لایسنسی (Xeneta، SCFI مسیرها، ERAI)</small></header><div class="fw-g">
  <label class="sx-f fw-f"><span>شاخص و خط</span><select data-mk="k">${Object.keys(MKL).map(k=>`<option value="${k}" ${k===sel?'selected':''}>${esc(MKL[k])}</option>`).join('')}<option value="custom">سفارشی…</option></select></label>
  <label class="sx-f fw-f"><span>تاریخ</span><input data-mk="d" type="date" value="${fwToday()}"></label><label class="sx-f fw-f"><span>مقدار</span><input data-mk="v" type="number" step="any"></label><label class="sx-f fw-f"><span>نام خط سفارشی (اختیاری)</span><input data-mk="c" placeholder="مثلاً ERAI یا XSI_CN_IR"></label></div>
  <div class="fw-bt"><button class="sx-btn sm pri" data-man>ثبت</button>${mkM().manual.length?`<small class="sx-muted">${fa(mkM().manual.length)} مقدار دستی</small><button class="sx-btn sm" data-manx>حذف مقادیر دستی</button>`:''}</div></div>`;
 $$('[data-sel]',B).forEach(x=>x.onclick=()=>{MKS.sel=x.dataset.sel;mkSv();re()});const pl=$('[data-pull]',B);if(pl)pl.onclick=async()=>{pl.disabled=true;pl.textContent='در حال دریافت…';MKS.err='';await mkPull(false);re()};
 const fo=$('[data-force]',B);if(fo)fo.onclick=async()=>{fo.disabled=true;fo.textContent='در حال خواندن منابع…';MKS.err='';await mkPull(true);re()};
 $('[data-xl]',B).onclick=()=>{const rows=[['series','line','name','date','value']];Object.entries(H).forEach(([k,a])=>a.forEach(p=>rows.push([k.split('|')[0],k.split('|')[1],mkName(k),p[0],p[1]])));dlFile('market-indices.xlsx',xlsxBlob([['indices',rows]]));emit('export.xlsx',{file:'market-indices.xlsx'})};
 $('[data-man]',B).onclick=async()=>{let k=$('[data-mk="k"]',B).value;const c=$('[data-mk="c"]',B).value.trim();if(k==='custom'||c)k=(k==='custom'?'manual':k.split('|')[0])+'|'+(c||'X').toUpperCase().replace(/[^A-Z0-9]+/g,'_');const d=$('[data-mk="d"]',B).value,v=+$('[data-mk="v"]',B).value;if(!(v>0)||!d)return toast('تاریخ و مقدار لازم است');
  const M=mkM();const [s,l]=k.split('|');M.manual=M.manual.filter(m=>!(m.s===s&&m.l===l&&m.d===d));M.manual.push({s,l,d,v,by:(SV.st.user&&SV.st.user.username)||'',t:Date.now()});mkMS(M);if(svOn()&&MKSER[s])svApi('/api/live/indices/manual',{method:'POST',body:{series:s,line:l,date:d,value:v}}).catch(()=>{});MKS.sel=k;mkSv();toast('ثبت شد');emit('market.updated',{manual:k});re()};
 const mx=$('[data-manx]',B);if(mx)mx.onclick=()=>{if(!confirm('همهٔ مقادیر دستی حذف شوند؟'))return;const M=mkM();M.manual=[];mkMS(M);re()}}
function mkBm(B,C,re){const R=rbAll();const V=mkScore(R);const lanes={};V.forEach(o=>{(lanes[o.lane]=lanes[o.lane]||{k:o.lane,n:0,r:o.r}).n++});const LL=Object.values(lanes).sort((a,b)=>b.n-a.n);
 const q=nkey(MKS.q||'');let L=V.filter(o=>(!MKS.lane||o.lane===MKS.lane)&&(!q||nkey([o.r.vendor,o.r.pol,o.r.pod,o.r.eq].join(' ')).includes(q)));L.sort((a,b)=>a.lane.localeCompare(b.lane)||a.now-b.now);
 const ln=MKS.lane&&lanes[MKS.lane];const LV2=ln?V.filter(o=>o.lane===MKS.lane&&rbStat(o.r)!=='exp'):[];const med=mkMed(LV2.map(o=>o.now));const idx=ln?mkMap(ln.r):[];
 const avg=V.length?Math.round(V.reduce((s,o)=>s+o.score,0)/V.length):0;const cnt=v=>V.filter(o=>o.verdict===v).length;
 B.innerHTML=`<div class="ex-kpis">${kpi('نرخ در بانک',V.length,{sub:fa(LL.length)+' مسیر/تجهیز'})}${kpi('میانگین اعتبار',avg,{suf:'/۱۰۰',cls:avg<50?'bad':avg<75?'warn':''})}${kpi('گران‌تر از بازار',cnt('exp'),{cls:cnt('exp')?'bad':''})}${kpi('ارزان مشکوک',cnt('cheap'),{cls:cnt('cheap')?'warn':''})}${kpi('تعدیل‌پذیر با شاخص',V.filter(o=>o.adj).length)}</div>
 ${!V.length?`<div class="sx-empty">بانک نرخ خالی است. از «ورود خودکار نرخ» یا «بانک نرخ» نرخ اضافه کنید.</div>`:''}
 <div class="om-tb"><select class="mk-ln"><option value="">همهٔ مسیرها</option>${LL.map(l=>`<option value="${esc(l.k)}" ${l.k===MKS.lane?'selected':''}>${esc(RMODE[l.r.mode]||'')} · ${esc(l.r.pol)} → ${esc(l.r.pod)} · ${esc(mkEqC(l.r.eq))} (${fa(l.n)})</option>`).join('')}</select><input class="fw-q mk-q" placeholder="جستجو…" value="${esc(MKS.q||'')}"><span class="sx-sp"></span><button class="sx-btn sm" data-open-rate>بانک نرخ</button><button class="sx-btn sm" data-xl>خروجی Excel</button></div>
 ${ln?`<div class="sx-card mk-lane"><header><b>${esc(ln.r.pol)} → ${esc(ln.r.pod)} · ${esc(mkEqC(ln.r.eq))}</b><small>میانهٔ نرخ‌های معتبر پس از تعدیل با شاخص تا امروز</small></header><div class="ex-kpis">${kpi('میانهٔ بازار',med||0,{pre:'$'})}${kpi('کمینه',LV2.length?Math.min(...LV2.map(o=>o.now)):0,{pre:'$'})}${kpi('بیشینه',LV2.length?Math.max(...LV2.map(o=>o.now)):0,{pre:'$'})}${kpi('شاخص مرجع',0,{sub:idx.length?esc(mkName(idx[0])):'بدون شاخص (غیردریایی)'})}</div>
  <div class="mk-chk"><label class="sx-f"><span>محک یک قیمت پیشنهادی</span><input class="mk-ca" type="number" placeholder="مبلغ"></label><select class="mk-cc">${PCUR.map(c=>`<option>${c}</option>`).join('')}</select><button class="sx-btn sm" data-chk>محک بزن</button><b class="mk-cr2"></b></div></div>`:''}
 ${V.length?`<div class="sx-card"><div class="sx-tw"><table class="sx-tbl mk-bt"><thead><tr><th>مسیر</th><th>تأمین‌کننده</th><th>تجهیز</th><th>نرخ ثبت‌شده</th><th>تاریخ پایه</th><th>تعدیل‌شده تا امروز</th><th>میانهٔ هم‌مسیرها</th><th>انحراف</th><th>حکم</th><th>اعتبار</th><th>منبع</th><th>شمول</th></tr></thead><tbody>${L.slice(0,400).map(o=>{const r=o.r;return `<tr class="${rbStat(r)==='exp'?'exp':''}"><td>${esc(r.pol)} → ${esc(r.pod)}<br><small class="sx-muted">${RMODE[r.mode]||''}</small></td><td>${esc(r.vendor||'—')}</td><td>${esc(r.eq)}</td><td>${nf(r.amt)} ${esc(r.cur)}</td><td>${jdt(mkRefD(r))}</td><td>${o.adj?`${usd0(o.adj.usd)} <small class="sx-muted" title="${esc(mkName(o.adj.k))}">×${nf(o.adj.ratio,3)}</small>`:'<small class="sx-muted">—</small>'}</td><td>${o.ref?usd0(o.ref)+` <small class="sx-muted">(${fa(o.n)})</small>`:'—'}</td><td class="${o.dv==null?'':Math.abs(o.dv)>.15?'bad':''}">${o.dv==null?'—':(o.dv>0?'+':'')+nf(o.dv*100,1)+'٪'}</td><td>${mkVb(o.verdict)}</td><td>${mkCb(o)}</td><td><small>${esc((MKSRC[mkSrcOf(r)]||MKSRC.manual)[0])}</small></td><td><small>${esc(r.incl||'—')}</small></td></tr>`}).join('')}</tbody></table></div></div>`:''}
 ${fwNote('اعتبار = منبع (۳۰٪: استعلام آنلاین > ایمیل/فایل > ثبت دستی > مرجع کریدور) + تازگی (۳۰٪) + تأیید متقابل با نرخ‌های هم‌مسیر در بازهٔ ±۱۵٪ (۲۰٪) + فاصله از میانهٔ بازار (۲۰٪)؛ نرخ منقضی ×۰٫۶. حکم: بیش از ۱۵٪ بالاتر از میانه «گران‌تر از بازار»، بیش از ۲۰٪ پایین‌تر «ارزان مشکوک» (احتمال هزینهٔ پنهان، شمول ناقص یا فضای غیرقطعی). نرخ‌های دریایی با نسبت شاخص مرجع (CCFI خلیج فارس، FBX، WCI) از تاریخ پایه تا امروز تعدیل می‌شوند.')}`;
 $('.mk-ln',B).onchange=e=>{MKS.lane=e.target.value;mkSv();re()};const qi=$('.mk-q',B);qi.oninput=()=>{MKS.q=qi.value;mkSv();clearTimeout(mkBm.t);mkBm.t=setTimeout(()=>{re();const i=$('.mk-q');if(i){i.focus();i.setSelectionRange(99,99)}},300)};
 $('[data-open-rate]',B).onclick=()=>open('rate');
 $('[data-xl]',B).onclick=()=>{dlFile('rate-benchmark.xlsx',xlsxBlob([['benchmark',[['mode','vendor','pol','pod','eq','amount','cur','base_date','usd','adj_usd_today','index','lane_median','deviation','verdict','credibility','source','inclusions'],...V.map(o=>[o.r.mode,o.r.vendor,o.r.pol,o.r.pod,o.r.eq,o.r.amt,o.r.cur,mkRefD(o.r),Math.round(o.u),o.adj?Math.round(o.adj.usd):'',o.adj?o.adj.k:'',o.ref?Math.round(o.ref):'',o.dv==null?'':+o.dv.toFixed(3),MKV[o.verdict||''][0],o.score,mkSrcOf(o.r),o.r.incl||''])]]]))};
 const ch=$('[data-chk]',B);if(ch)ch.onclick=()=>{const u=pU(+$('.mk-ca',B).value,$('.mk-cc',B).value);if(!u||!med)return;const dv=u/med-1;const v=dv>.15?'exp':dv<-.2?'cheap':'fair';$('.mk-cr2',B).innerHTML=`${usd0(u)} · ${(dv>0?'+':'')+nf(dv*100,1)}٪ نسبت به میانه ${mkVb(v)}`}}
/* Iran lanes estimated from index: last actual rate on the lane (or a base you enter) × index ratio (+ feeder, + BAF drift) */
const MKIR=[['Shanghai','Bandar Abbas','40HC'],['Ningbo','Bandar Abbas','40HC'],['Qingdao','Bandar Abbas','40HC'],['Shenzhen','Bandar Abbas','40HC'],['Shanghai','Bandar Abbas','20DV'],['Tianjin','Bandar Abbas','40HC'],['Shanghai','Jebel Ali','40HC'],['Shanghai','Bushehr','40HC'],['Shanghai','Chabahar','40HC']];
function mkEstimate(o,H=mkHist()){const R=rbAll();const lane=mkLane({mode:'sea',...o});const SC=new Map(mkScore(R,H).map(x=>[x.r,x]));const byD=(a,b)=>mkRefD(b).localeCompare(mkRefD(a));const good=r=>{const x=SC.get(r);return !x||!['cheap','exp'].includes(x.verdict)};
 const same=R.filter(r=>mkLane(r)===lane&&r.amt>0).sort(byD);const [,,pk,eqc]=lane.split('|');const prox=R.filter(r=>(r.mode||'sea')==='sea'&&r.amt>0&&mkLane(r)!==lane&&mkPk(r.pod)===pk&&mkEqC(r.eq)===eqc&&MKRX.cn.test(r.pol)&&MKRX.cn.test(o.pol)).sort(byD);
 let act=same.find(good)||same[0];let proxy=false;if(!act&&prox.length){act=prox.find(good)||prox[0];proxy=true}const M=mkM();const bs=M.base.find(x=>mkLane({mode:'sea',...x})===lane);
 const base=act&&(!bs||mkRefD(act)>=bs.from)?{...act,kind:proxy?'proxy':'bank'}:bs?{mode:'sea',...bs,kind:'base'}:null;if(!base)return {lane,o,base:null};const a=mkAdj({mode:'sea',...base},H);const fu=mkAdj({mode:'sea',pol:base.pol,pod:base.pod,amt:1,cur:'USD',from:mkRefD(base)},H);
 const b0=mkAt(H,'bunker|FUJ_VLSFO',mkRefD(base)),b1=mkLast(H,'bunker|FUJ_VLSFO');const teu=/^20/.test(mkEqC(o.eq))?1:2;const baf=b0&&b1?(b1[1]-b0[1])*MKS.fuel*teu:0;
 const viaGulf=MKRX.gulf.test(o.pod)&&o.dest!=='gulf';const fd=viaGulf?+MKS.feeder||0:0;const est=a?a.usd:pU(base.amt,base.cur);return {lane,o,base,adj:a,baf:Math.round(baf),feeder:fd,usd:Math.round(est+baf*(a&&/BAF شامل|all-in/.test(base.incl||'')?1:0)+fd),bunker:b0&&b1?[b0,b1]:null,age:fwDiff(mkRefD(base),fwToday())}}
function mkEst(B,C,re){const H=mkHist();const E=MKIR.map(([pol,pod,eq])=>mkEstimate({pol,pod,eq},H));const pg=mkLast(H,'ccfi|PERSIAN_GULF_RED_SEA');
 B.innerHTML=`<div class="sx-card mk-off"><div><b>برآورد، نه نرخ قطعی</b><p>نرخ مسیرهای ایران در شاخص‌های جهانی منتشر نمی‌شود. برآورد = آخرین نرخ واقعی همان مسیر (از بانک نرخ یا نرخ پایه‌ای که وارد می‌کنید) × نسبت شاخص مرجع (CCFI خلیج فارس/دریای سرخ ${pg?'= '+nf(pg[1],1)+' در '+jdt(pg[0]):''}) از تاریخ نرخ پایه تا امروز، به‌اضافهٔ فیدر جبل‌علی→بندرعباس در صورت ترانشیپ و تغییر سوخت (BAF) اگر نرخ پایه شامل BAF بوده. برای عقد قرارداد استعلام روز بگیرید.</p></div></div>
 <div class="sx-card fw-form"><header><b>فرض‌ها</b></header><div class="fw-g"><label class="sx-f fw-f"><span>هزینهٔ فیدر جبل‌علی → بندرعباس ($/کانتینر)</span><input data-a="feeder" type="number" value="${MKS.feeder}"></label><label class="sx-f fw-f"><span>ضریب BAF: تن سوخت به‌ازای هر TEU</span><input data-a="fuel" type="number" step=".05" value="${MKS.fuel}"></label></div></div>
 <div class="sx-card"><div class="sx-tw"><table class="sx-tbl mk-et"><thead><tr><th>مسیر</th><th>تجهیز</th><th>نرخ پایه</th><th>تاریخ پایه</th><th>شاخص مرجع (آن روز → امروز)</th><th>نسبت</th><th>تغییر سوخت</th><th>برآورد امروز</th><th>نرخ پایهٔ جدید</th></tr></thead><tbody>${E.map((e,i)=>`<tr><td>${esc(e.o.pol)} → ${esc(e.o.pod)}${e.feeder?'<br><small class="sx-muted">+ فیدر به بندرعباس</small>':''}</td><td>${esc(e.o.eq)}</td>
  <td>${e.base?`${nf(e.base.amt)} ${esc(e.base.cur)} <small class="sx-muted">${e.base.kind==='bank'?'بانک نرخ':e.base.kind==='proxy'?'مسیر مشابه: '+esc(e.base.pol):'پایهٔ دستی'}${e.base.vendor?' · '+esc(e.base.vendor):''}</small>`:'<small class="sx-muted">نرخ واقعی ثبت نشده</small>'}</td><td>${e.base?jdt(mkRefD(e.base))+` <small class="sx-muted">(${fa(e.age)} روز)</small>`:'—'}</td>
  <td>${e.adj?`<small>${esc(mkName(e.adj.k))}</small><br>${nf(e.adj.v0,1)} → ${nf(e.adj.v1,1)}`:e.base?'<small class="sx-muted">شاخصِ تاریخ پایه موجود نیست</small>':'—'}</td><td class="${e.adj?e.adj.ratio>1.05?'bad':e.adj.ratio<.95?'ok':'':''}">${e.adj?'×'+nf(e.adj.ratio,3):'—'}</td><td>${e.bunker?`${e.baf>=0?'+':''}${usd0(e.baf)}<br><small class="sx-muted">${nf(e.bunker[0][1])}→${nf(e.bunker[1][1])} $/t</small>`:'—'}</td>
  <td>${e.base?`<b>${usd0(e.usd)}</b>${e.feeder?`<br><small class="sx-muted">با فیدر ${usd0(e.feeder)}</small>`:''}${!e.adj?'<br><small class="sx-muted">بدون تعدیل</small>':''}`:'—'}</td>
  <td class="mk-bi"><input type="number" placeholder="مبلغ $" data-bi="${i}"><input type="date" value="${fwToday()}" data-bd="${i}"><button class="sx-btn sm" data-bs="${i}">ثبت</button></td></tr>`).join('')}</tbody></table></div></div>
 ${fwNote('نرخ پایه از جدیدترین نرخ همان مسیر و تجهیز در «بانک نرخ» برداشته می‌شود؛ اگر نرخی ندارید، آخرین نرخ واقعیِ پرداخت‌شده یا استعلام‌شده را با تاریخش در ستون آخر وارد کنید. شاخص مرجع باید در تاریخ پایه هم مقدار داشته باشد (تاریخچه از روز راه‌اندازی سرور انباشته می‌شود؛ مقادیر گذشته را می‌توان در «شاخص‌های بازار» دستی ثبت کرد).')}`;
 $$('[data-a]',B).forEach(x=>x.onchange=()=>{MKS[x.dataset.a]=+x.value||0;mkSv();re()});
 $$('[data-bs]',B).forEach(x=>x.onclick=()=>{const i=+x.dataset.bs;const v=+$(`[data-bi="${i}"]`,B).value,d=$(`[data-bd="${i}"]`,B).value;if(!(v>0)||!d)return toast('مبلغ و تاریخ لازم است');const [pol,pod,eq]=MKIR[i];const M=mkM();const ln=mkLane({mode:'sea',pol,pod,eq});M.base=M.base.filter(b=>mkLane({mode:'sea',...b})!==ln);M.base.push({pol,pod,eq,amt:v,cur:'USD',from:d,t:Date.now()});mkMS(M);toast('نرخ پایه ثبت شد');re()})}
function mkIng(B,C,re){const P=MKS.ingR;const R=rbAll();
 B.innerHTML=`<div class="sx-card fw-form"><header><b>ورود نرخ از ایمیل، متن، CSV یا Excel</b><small>متن ایمیل یا پیام واتس‌اپ/تلگرام نماینده را بچسبانید یا فایل جدول نرخ را انتخاب کنید؛ پیش‌نمایش را بازبینی و سپس به بانک نرخ اضافه کنید</small></header>
  <textarea class="mk-tx" rows="8" placeholder="مثال:\nFrom: Ali @ Sea Star Logistics\nShanghai - Bandar Abbas 20GP USD 1,150 / 40HQ USD 1,900 all in, valid till 31 Oct\nNingbo to Jebel Ali: $1,350/40HC, T/T 18 days, BAF included\nCarrier: COSCO">${esc(MKS.ing||'')}</textarea>
  <div class="fw-bt"><button class="sx-btn sm pri" data-parse>تحلیل متن</button><label class="sx-btn sm mk-file">انتخاب فایل CSV / Excel<input type="file" accept=".csv,.tsv,.txt,.xlsx" hidden></label><button class="sx-btn sm" data-clr>پاک کردن</button></div></div>
 ${P?`<div class="sx-card"><header><b>پیش‌نمایش: ${fa(P.length)} نرخ شناسایی شد</b><small>ستون‌ها را پیش از افزودن اصلاح کنید؛ ردیف‌های تکراری با بانک نرخ علامت خورده‌اند</small></header>${P.length?`<div class="sx-tw"><table class="sx-tbl mk-pv"><thead><tr><th><input type="checkbox" data-all checked></th><th>شیوه</th><th>تأمین‌کننده</th><th>مبدأ</th><th>مقصد</th><th>تجهیز</th><th>مبلغ</th><th>ارز</th><th>اعتبار تا</th><th>شمول</th><th>اطمینان</th></tr></thead><tbody>${P.map((r,i)=>{const dup=R.some(x=>mkLane(x)===mkLane(r)&&+x.amt===+r.amt&&x.cur===r.cur);return `<tr class="${dup?'exp':''}"><td><input type="checkbox" data-ck="${i}" ${dup?'':'checked'}></td><td><select data-f="mode" data-i="${i}">${Object.entries(RMODE).map(([k,n])=>`<option value="${k}" ${k===r.mode?'selected':''}>${n}</option>`).join('')}</select></td>${['vendor','pol','pod','eq','amt','cur','to','incl'].map(f=>`<td><input data-f="${f}" data-i="${i}" value="${esc(r[f]??'')}" ${f==='amt'?'type="number" step="any"':f==='to'?'type="date"':''}></td>`).join('')}<td><span class="tm-s ${r.conf>=.8?'ok':r.conf>=.6?'warn':'bad'}">${fa(Math.round(r.conf*100))}٪</span>${dup?' <small class="sx-muted">تکراری</small>':''}</td></tr>`}).join('')}</tbody></table></div><div class="fw-bt"><button class="sx-btn sm pri" data-addp>افزودن ردیف‌های انتخاب‌شده به بانک نرخ</button></div>`:'<p class="sx-muted">الگوی «مبدأ - مقصد … تجهیز … مبلغ» پیدا نشد. هر خط باید نام بندر مبدأ و مقصد و مبلغ داشته باشد (مثل نمونه)، یا فایل دارای سرستون‌های POL/POD/Rate باشد.</p>'}</div>`:''}
 ${fwNote('تشخیص خودکار: بنادر رایج چین، خلیج فارس، ایران و اروپا (فارسی و انگلیسی)؛ تجهیز 20/40/40HC/RF و FEU/TEU؛ ارز USD/EUR/AED/CNY؛ اعتبار «valid till …» یا «اعتبار تا …» (میلادی و شمسی)؛ شمول all-in/BAF/THC؛ جدول‌هایی که هر سایز کانتینر یک ستون دارد. منبع هر نرخ (ایمیل/CSV/Excel) و ضریب اطمینان تحلیل در بانک نرخ ذخیره و در امتیاز اعتبار لحاظ می‌شود.')}`;
 const tx=$('.mk-tx',B);tx.oninput=()=>{MKS.ing=tx.value;mkSv()};
 $('[data-parse]',B).onclick=()=>{MKS.ing=tx.value;MKS.ingR=mkParse(tx.value);mkSv();re()};$('[data-clr]',B).onclick=()=>{MKS.ing='';MKS.ingR=null;mkSv();re()};
 $('.mk-file input',B).onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(/\.xlsx$/i.test(f.name)){const rows=await readXlsx(await f.arrayBuffer());MKS.ingR=mkParse(rows,'excel')}else{const t=await f.text();MKS.ingR=mkParse(t,'csv');if(!MKS.ingR.length)MKS.ingR=mkText(t,'email')}MKS.ingR.forEach(r=>r.note=(r.note?r.note+' · ':'')+f.name);re()}catch(err){toast('خواندن فایل ناموفق: '+err.message)}};
 if(P){$$('[data-f]',B).forEach(x=>x.onchange=()=>{const r=P[+x.dataset.i];r[x.dataset.f]=x.dataset.f==='amt'?+x.value:x.value});const al=$('[data-all]',B);if(al)al.onchange=()=>$$('[data-ck]',B).forEach(c=>c.checked=al.checked);
  const ad=$('[data-addp]',B);if(ad)ad.onclick=()=>{const sel=$$('[data-ck]',B).filter(c=>c.checked).map(c=>P[+c.dataset.ck]).filter(r=>r.amt>0&&r.pol&&r.pod);if(!sel.length)return toast('ردیفی انتخاب نشده');const A=rbAll();sel.forEach(r=>A.unshift({id:'R'+Math.random().toString(36).slice(2,9),mode:r.mode,vendor:r.vendor||'',pol:r.pol,pod:r.pod,eq:r.eq,amt:+r.amt,cur:r.cur||'USD',from:r.from||fwToday(),to:r.to||'',tt:r.tt||null,note:r.note||'',src:r.src,incl:r.incl||'',conf:+(r.conf||.5).toFixed(2)}));LSS('ifa-rates',A);
   emit('rates.imported',{n:sel.length,src:sel[0].src});toast(fa(sel.length)+' نرخ به بانک نرخ افزوده شد');MKS.ingR=null;MKS.ing='';mkSv();MKS.tab='bm';mkSv();re()}}}
function mkSrc(B){const S=mkC();const src=(S&&S.sources)||{};const st=S&&S.series||{};
 const rows=[['ccfi','CCFI (شانگهای)','۱۲ مسیر + ترکیبی، شامل خلیج فارس/دریای سرخ — شاخص (نقطه)','هفتگی','عمومی'],['scfi','SCFI (شانگهای)','فقط شاخص ترکیبی؛ نرخ دلاری مسیرها لایسنسی است','هفتگی','ترکیبی عمومی'],['wci','Drewry WCI','ترکیبی + ۴ مسیر شانگهای ($/FEU) از متن عمومی هفتگی','هفتگی','عمومی (نمایشی)'],['fbx','Freightos FBX','جهانی + ۱۲ مسیر ($/FEU) از تیکر عمومی','روزانه','عمومی (نمایشی)'],['bunker','Ship & Bunker','VLSFO / MGO / IFO380 فجیره و سنگاپور ($/تن) با تاریخچهٔ ۲ هفته','روزانه','عمومی']];
 B.innerHTML=`<div class="sx-card"><header><b>منابع شاخص و وضعیت اتصال</b><small>${svUrl()?'از طریق سرور تیمی':'سرور متصل نیست'}</small></header><div class="sx-tw"><table class="sx-tbl"><thead><tr><th>منبع</th><th>پوشش</th><th>تناوب</th><th>مجوز</th><th>آخرین داده</th><th>وضعیت</th></tr></thead><tbody>${rows.map(([k,n,c,f,l])=>{const e=S&&S.errors&&S.errors[k];const o=st[k];return `<tr><td>${src[k]&&src[k].url?`<a href="${esc(src[k].url)}" target="_blank" rel="noopener">${n}</a>`:n}</td><td><small>${c}</small></td><td>${f}</td><td><small>${l}</small></td><td>${o&&o.date?jdt(o.date):'—'}</td><td>${e?`<span class="tm-s bad" title="${esc(e.err)}">خطا</span>`:o?'<span class="tm-s ok">فعال</span>':'<span class="tm-s">—</span>'}</td></tr>`}).join('')}
  <tr><td>Xeneta / Baltic / TAC / ERAI</td><td><small>نرخ قراردادی و اسپات دقیق، شاخص ریلی چین–اروپا</small></td><td>—</td><td><small>اشتراک پولی یا بدون API عمومی</small></td><td>—</td><td><span class="tm-s">ثبت دستی</span></td></tr></tbody></table></div></div>
 <div class="sx-card"><header><b>ساختار یکپارچهٔ هر نرخ (Provenance)</b></header><p class="sx-muted">مسیر (شیوه، مبدأ، مقصد) · تجهیز و واحد · مبلغ و ارز · بازهٔ اعتبار · شمول هزینه‌ها (all-in / BAF / THC) · منبع (استعلام آنلاین، ایمیل، فایل، دستی، مرجع) · تاریخ و ضریب اطمینان ورود — همه در «بانک نرخ» ذخیره و با سرور تیمی همگام می‌شوند.</p></div>
 ${fwNote('سرور هر ۶ ساعت (WCI و FBX حداکثر روزی یک‌بار) منابع را می‌خواند و تاریخچه را در پایگاه داده انباشته می‌کند، چون منابع عمومی تاریخچهٔ رایگان نمی‌دهند. تغییر هفتگی ≥ ۵٪ رویداد rate.jump می‌سازد که از «قوانین اعلان» به تلگرام/بله/ایمیل قابل ارسال است. WCI و FBX از صفحات عمومی خوانده می‌شوند؛ برای استفادهٔ تجاری یا بازنشر، شرایط استفادهٔ ناشر را رعایت کنید.')}`}
(function(){const st=document.createElement('style');st.textContent=`.mk .mk-g{display:grid;grid-template-columns:repeat(auto-fill,minmax(330px,1fr));gap:12px;margin:12px 0}
.mk .mk-t td{padding:5px 8px}.mk .mk-t tr{cursor:pointer}.mk .mk-t tr.on td{background:color-mix(in srgb,var(--accent) 12%,transparent)}.mk .mk-t td.n{font:600 12.5px Inter,Vazirmatn;white-space:nowrap;direction:ltr;text-align:left}.mk td.up{color:var(--fbad)}.mk td.dn{color:var(--good)}
.mk-sp path{fill:none;stroke:var(--muted);stroke-width:1.6}.mk-sp.up path{stroke:var(--fbad)}.mk-sp.dn path{stroke:var(--good)}.mk-sp circle{fill:currentColor;color:var(--text)}
.mk-ch{width:100%;height:220px;display:block;direction:ltr}.mk-ch line{stroke:var(--line);stroke-width:1}.mk-ch text{fill:var(--faint);font:10px Inter,Vazirmatn}.mk-ch .l{fill:none;stroke:var(--accent);stroke-width:2}.mk-ch .a{fill:var(--accent);opacity:.08}.mk-ch circle{fill:var(--accent)}.mk-ce{padding:24px;text-align:center}
.mk-off{display:flex;gap:12px;align-items:flex-start;border-color:var(--fwarn)!important;margin-bottom:12px}.mk-off svg{width:22px;height:22px;flex:none;stroke:var(--fwarn);fill:none}.mk-off p{margin:4px 0 0;color:var(--muted);font-size:12.5px;line-height:1.8}
.mk-al{margin:10px 0}.mk-al .sx-chip{margin:3px}.mk-cr{display:inline-flex;align-items:center;gap:6px;min-width:84px}.mk-cr i{display:block;height:6px;border-radius:3px;background:var(--line);width:56px;overflow:hidden;flex:none}.mk-cr i s{display:block;height:100%;background:var(--good);text-decoration:none}.mk-cr.warn i s{background:var(--fwarn)}.mk-cr.bad i s{background:var(--fbad)}
.mk-j{display:inline-block;margin:3px;padding:3px 10px;border-radius:999px;font-size:12px;border:1px solid var(--line2)}.mk-j.up{color:var(--fbad);border-color:color-mix(in srgb,var(--fbad) 45%,transparent)}.mk-j.dn{color:var(--good);border-color:color-mix(in srgb,var(--good) 45%,transparent)}.mk-cr b{font:600 11.5px Inter,Vazirmatn}
.mk .sx-btn.pri{width:auto;margin-top:0}.mk .mk-chk{display:flex;gap:8px;align-items:flex-end;flex-wrap:wrap;margin-top:10px}.mk .mk-chk .sx-f{margin:0}.mk select.mk-ln{max-width:420px}.mk .mk-q{max-width:220px}
.mk-pv input,.mk-pv select{width:100%;min-width:70px;background:var(--panel2);border:1px solid var(--line);border-radius:6px;color:var(--text);padding:3px 5px;font:inherit;font-size:12px}.mk-pv input[type=checkbox]{width:auto;min-width:0}
.mk-tx{width:100%;box-sizing:border-box;background:var(--panel2);border:1px solid var(--line);border-radius:10px;color:var(--text);padding:10px;font:12.5px/1.8 Inter,Vazirmatn;direction:ltr;text-align:left}
.mk-bi{white-space:nowrap}.mk-bi input{width:86px;background:var(--panel2);border:1px solid var(--line);border-radius:6px;color:var(--text);padding:3px 5px;font-size:12px;margin-inline-end:4px}.mk-bi input[type=date]{width:120px}
.mk-file{cursor:pointer}.rb-t .mk-cr{min-width:64px}.rb-src{font-size:10.5px;color:var(--faint)}`;document.head.appendChild(st)})();

/* ===== v15.5: phase 2 — surcharge engine, D&D comparison, domestic & rail benchmark, index forecast, thresholds & contract watch ===== */
const MKSUR0={wrs:'normal',wrsT:{normal:0,elevated:50,high:150,critical:400},eis:0,pss:[0,0,0,0,0,0,0,0,0,0,0,0],bafRef:null,thcO:0,thcD:0,bl:0,dof:0,apply:false};
const mkSurC=()=>{const M=mkM();const S=Object.assign(JSON.parse(JSON.stringify(MKSUR0)),M.sur||{});S.wrsT=Object.assign({},MKSUR0.wrsT,(M.sur||{}).wrsT||{});if(!Array.isArray(S.pss)||S.pss.length!==12)S.pss=MKSUR0.pss.slice();return S};
const mkSurS=S=>{const M=mkM();M.sur=S;mkMS(M)};
const MKWRS={normal:'عادی',elevated:'افزایش‌یافته',high:'بالا',critical:'بحرانی (تنگهٔ هرمز/درگیری)'};
const mkTeu=eq=>/^20|TEU/.test(mkEqC(eq))?1:2;
/* all-in build-up for one sea lane: ocean (index-adjusted) + surcharges that are not already included */
function mkSurCalc(o,H=mkHist()){const S=mkSurC();const E=mkEstimate(o,H);const teu=mkTeu(o.eq);const m=(o.month||new Date().getMonth()+1)-1;const inc=String(E.base&&E.base.incl||'');const allIn=/all-in/.test(inc),bafIn=allIn||/BAF شامل/.test(inc),thcIn=allIn||/THC شامل/.test(inc);
 const fu=mkLast(H,'bunker|FUJ_VLSFO');const L=[];const ocean=E.base?(E.adj?E.adj.usd:pU(E.base.amt,E.base.cur)):null;
 L.push({k:'ocean',n:'کرایهٔ دریایی (تعدیل‌شده با شاخص)',v:ocean,b:E.base?(E.adj?mkName(E.adj.k)+' ×'+nf(E.adj.ratio,3):'بدون تعدیل'):'نرخ پایه ثبت نشده'});
 if(bafIn)L.push({k:'baf',n:'تغییر BAF از تاریخ پایه',v:E.baf,b:'شامل در نرخ پایه؛ فقط تغییر سوخت'});
 else{const ref=S.bafRef||0;const v=fu?(ref?(fu[1]-ref):fu[1])*MKS.fuel*teu:null;L.push({k:'baf',n:ref?'BAF (فرمول: تفاوت با قیمت مرجع)':'BAF (کامل از قیمت سوخت)',v:v==null?null:Math.round(v),b:fu?`VLSFO فجیره ${nf(fu[1])} $/t${ref?' − مرجع '+nf(ref):''} × ${nf(MKS.fuel,2)} t/TEU × ${fa(teu)} TEU`:'قیمت سوخت در دسترس نیست'})}
 L.push({k:'pss',n:'سورشارژ فصل اوج (PSS)',v:(+S.pss[m]||0)*teu,b:'جدول ماهانه · '+fa(m+1)+' · $/TEU'});
 L.push({k:'wrs',n:'ریسک جنگ / تنگهٔ هرمز (WRS)',v:MKRX.ir.test(o.pod)||MKRX.gulf.test(o.pod)?(+S.wrsT[S.wrs]||0)*teu:0,b:'سطح: '+MKWRS[S.wrs]});
 L.push({k:'eis',n:'کمبود تجهیزات (EIS)',v:(+S.eis||0)*teu,b:'$/TEU'});
 if(!thcIn){L.push({k:'thcO',n:'THC مبدأ',v:+S.thcO||0,b:'$/کانتینر'});L.push({k:'thcD',n:'THC مقصد',v:+S.thcD||0,b:'$/کانتینر'})}
 L.push({k:'docs',n:'صدور بارنامه و ترخیصیه (BL/DO)',v:(+S.bl||0)+(+S.dof||0),b:'$/بارنامه'});if(E.feeder)L.push({k:'feeder',n:'فیدر جبل‌علی → بندرعباس',v:E.feeder,b:'فرض «برآورد مسیرهای ایران»'});
 const tot=ocean==null?null:L.reduce((a,x)=>a+(+x.v||0),0);return {E,L,total:tot==null?null:Math.round(tot),teu,inc}}
/* optional: push market surcharges into «هزینهٔ کامل زنجیره» (sea routes only; avoids double-counting the model's own fuel/peak lines) */
const _mkLanded=landed;landed=function(C,src,P){const R=_mkLanded(C,src,P);try{const S=mkSurC();if(!S.apply||!R.r||!(R.r.legs||[]).some(l=>l.mode==='sea'))return R;const H=mkHist();const eq=(R.r.d&&R.r.d.eqKey)||'40';const teu=mkTeu(eq);const u=R.units||1;
  const fu=mkLast(H,'bunker|FUJ_VLSFO');const baf=S.bafRef&&fu?(fu[1]-S.bafRef)*MKS.fuel*teu:0;const v=Math.max(0,((+S.wrsT[S.wrs]||0)+(+S.eis||0))*teu+baf)*u;if(!(v>0))return R;
  const fr=R.L.find(x=>x.k==='freight');const x={k:'mktsur',n:'سربارهای بازار (ریسک جنگ، کمبود تجهیزات، تعدیل BAF)',st:3,cat:'transport',v,who:fr?fr.who:'b'};const i=R.L.findIndex(y=>y.k==='peak');R.L.splice(i>=0?i+1:R.L.length,0,x);
  R.total+=v;if(x.who==='s')R.seller+=v;else R.buyer+=v;R.logistic+=v}catch(e){}return R};
function mkSur(B,C,re){const S=mkSurC();const H=mkHist();const sv=()=>{mkSurS(S);re()};const fu=mkLast(H,'bunker|FUJ_VLSFO');
 const lanes=MKIR.map(([pol,pod,eq])=>({pol,pod,eq}));const li=Math.min(lanes.length-1,+MKS.sl||0);const X=mkSurCalc({...lanes[li],month:+MKS.sm||new Date().getMonth()+1},H);
 const MN=['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'];const GM=['ژانویه','فوریه','مارس','آوریل','مه','ژوئن','ژوئیه','اوت','سپتامبر','اکتبر','نوامبر','دسامبر'];
 const L=ddLines(),P=ddPorts();const t=fwToday();const dw=Math.max(1,+MKS.dw||7),rt=Math.max(0,+MKS.rt||5);const pt=P.find(p=>p.id===MKS.dp)||P[0];
 const DD=L.map(l=>{try{const r=ddCalc({line:l.id,port:pt.id,ct:MKS.dct||'40',n:1,rf:false,dis:t,out:fwAdd(t,dw-1),ret:fwAdd(t,dw-1+rt),dep:0},L,P);return {l,free:l.comb?l.dem.free:l.dem.free+'/'+l.det.free,line:r.dem+r.det,st:r.stU||0,tot:r.dem+r.det+(r.stU||0)}}catch(e){return null}}).filter(Boolean).sort((a,b)=>a.tot-b.tot);
 B.innerHTML=`<div class="ct-g2 mk-2"><div class="sx-card fw-form"><header><b>موتور سربارها</b><small>${S.apply?'<span class="tm-s ok">در هزینهٔ کامل زنجیره اعمال می‌شود</span>':'فعلاً فقط محاسبه — اعمال در هزینهٔ کامل زنجیره خاموش است'}</small></header><div class="fw-g">
  <label class="sx-f fw-f"><span>سطح ریسک جنگ / هرمز</span><select data-s="wrs">${Object.entries(MKWRS).map(([k,n])=>`<option value="${k}" ${k===S.wrs?'selected':''}>${n} · $${S.wrsT[k]}/TEU</option>`).join('')}</select></label>
  ${Object.keys(MKWRS).map(k=>`<label class="sx-f fw-f"><span>WRS ${MKWRS[k]} ($/TEU)</span><input type="number" data-w="${k}" value="${S.wrsT[k]}"></label>`).join('')}
  <label class="sx-f fw-f"><span>EIS کمبود تجهیزات ($/TEU)</span><input type="number" data-s="eis" value="${S.eis}"></label>
  <label class="sx-f fw-f"><span>قیمت مرجع سوخت BAF ($/t، اختیاری)</span><input type="number" data-s="bafRef" value="${S.bafRef||''}" placeholder="${fu?'فعلی '+Math.round(fu[1]):''}"></label>
  <label class="sx-f fw-f"><span>مصرف سوخت (t/TEU)</span><input type="number" step=".05" data-m="fuel" value="${MKS.fuel}"></label>
  <label class="sx-f fw-f"><span>THC مبدأ ($/کانتینر)</span><input type="number" data-s="thcO" value="${S.thcO}"></label><label class="sx-f fw-f"><span>THC مقصد ($/کانتینر)</span><input type="number" data-s="thcD" value="${S.thcD}"></label>
  <label class="sx-f fw-f"><span>هزینهٔ بارنامه BL ($)</span><input type="number" data-s="bl" value="${S.bl}"></label><label class="sx-f fw-f"><span>ترخیصیه DO ($)</span><input type="number" data-s="dof" value="${S.dof}"></label></div>
  <h5>PSS فصل اوج ($/TEU به‌تفکیک ماه میلادی)</h5><div class="mk-pss">${GM.map((g,i)=>`<label><span>${g}</span><input type="number" data-p="${i}" value="${S.pss[i]||0}"></label>`).join('')}</div>
  <div class="fw-bt"><label class="mk-ap"><input type="checkbox" data-apply ${S.apply?'checked':''}> اعمال WRS، EIS و تعدیل BAF در «هزینهٔ کامل زنجیره» برای مسیرهای دریایی</label></div></div>
 <div class="sx-card"><header><b>قیمت تمام‌شدهٔ حمل دریایی (all-in)</b><small>نرخ پایه + سربارهایی که در نرخ پایه نیستند</small></header>
  <div class="om-tb"><select class="mk-sl">${lanes.map((l,i)=>`<option value="${i}" ${i===li?'selected':''}>${esc(l.pol)} → ${esc(l.pod)} · ${l.eq}</option>`).join('')}</select><select class="mk-sm">${GM.map((g,i)=>`<option value="${i+1}" ${i+1===(+MKS.sm||new Date().getMonth()+1)?'selected':''}>${g}</option>`).join('')}</select></div>
  ${X.E.base?`<table class="sx-tbl"><tbody>${X.L.map(x=>`<tr><td>${esc(x.n)}<br><small class="sx-muted">${esc(x.b)}</small></td><td class="n">${x.v==null?'—':usd0(x.v)}</td></tr>`).join('')}<tr class="mk-tot"><td><b>جمع all-in برآوردی</b>${X.inc?`<br><small class="sx-muted">شمول نرخ پایه: ${esc(X.inc)}</small>`:''}</td><td class="n"><b>${X.total==null?'—':usd0(X.total)}</b></td></tr></tbody></table>
   <div class="fw-bt"><button class="sx-btn sm" data-job>→ افزودن به پروندهٔ جاری</button></div>`:'<p class="sx-muted">برای این مسیر نرخ پایه‌ای نیست؛ در «برآورد مسیرهای ایران» نرخ پایه وارد کنید یا نرخ واقعی به بانک نرخ اضافه کنید.</p>'}</div></div>
 <div class="sx-card"><header><b>مقایسهٔ دموراژ، دیتنشن و انبارداری خطوط</b><small>با تعرفه‌های «عملیات ← دموراژ و انبارداری» · برای انتخاب خط بر اساس هزینهٔ کل، نه فقط کرایه</small></header>
  <div class="om-tb"><label class="sx-f"><span>روز ماندن پر در بندر</span><input type="number" class="mk-dw" value="${dw}"></label><label class="sx-f"><span>روز تا تحویل خالی</span><input type="number" class="mk-rt" value="${rt}"></label><label class="sx-f"><span>بندر</span><select class="mk-dp">${P.map(p=>`<option value="${p.id}" ${p.id===pt.id?'selected':''}>${esc(p.n)}</option>`).join('')}</select></label><label class="sx-f"><span>کانتینر</span><select class="mk-dct"><option value="20" ${MKS.dct==='20'?'selected':''}>۲۰ فوت</option><option value="40" ${MKS.dct!=='20'?'selected':''}>۴۰ فوت</option></select></label><span class="sx-sp"></span><button class="sx-btn sm" data-dd>ویرایش تعرفه‌ها</button></div>
  <table class="sx-tbl"><thead><tr><th>خط / پروفایل</th><th>روز آزاد</th><th>دموراژ + دیتنشن</th><th>انبارداری بندر</th><th>جمع برای هر کانتینر</th></tr></thead><tbody>${DD.map((d,i)=>`<tr class="${i===0?'best':''}"><td>${esc(d.l.n)}${i===0?' <b class="ok">✓ کمترین</b>':''}</td><td>${esc(String(d.free))}</td><td>${usd0(d.line)}</td><td>${usd0(d.st)}</td><td><b>${usd0(d.tot)}</b></td></tr>`).join('')}</tbody></table></div>
 ${fwNote('مقادیر سربارها پیش‌فرض صفر یا نمونه‌اند؛ آن‌ها را از اعلامیه‌های خطوط (Surcharge Notice) و نرخ‌نامهٔ نماینده‌ها به‌روز کنید. BAF وقتی نرخ پایه «شامل BAF / all-in» باشد فقط به‌اندازهٔ تغییر قیمت سوخت از تاریخ پایه تعدیل می‌شود؛ وگرنه از قیمت روز VLSFO فجیره × مصرف هر TEU محاسبه می‌شود. با فعال‌کردن «اعمال»، فقط WRS، EIS و تفاوت BAF با قیمت مرجع به‌عنوان یک ردیف جدا به هزینهٔ کامل زنجیره اضافه می‌شود تا سورشارژ فصلی و سوخت خود مدل دوبار شمرده نشود.')}`;
 $$('[data-s]',B).forEach(x=>x.onchange=()=>{const k=x.dataset.s;S[k]=k==='wrs'?x.value:(x.value===''?null:+x.value);sv()});$$('[data-w]',B).forEach(x=>x.onchange=()=>{S.wrsT[x.dataset.w]=+x.value||0;sv()});
 $$('[data-p]',B).forEach(x=>x.onchange=()=>{S.pss[+x.dataset.p]=+x.value||0;sv()});$('[data-m]',B).onchange=e=>{MKS.fuel=+e.target.value||0;mkSv();re()};
 $('[data-apply]',B).onchange=e=>{S.apply=e.target.checked;mkSurS(S);toast(S.apply?'سربارهای بازار در هزینهٔ کامل زنجیره اعمال شد':'اعمال سربارها خاموش شد');emit('market.updated',{surcharges:S.apply});re()};
 $('.mk-sl',B).onchange=e=>{MKS.sl=+e.target.value;mkSv();re()};$('.mk-sm',B).onchange=e=>{MKS.sm=+e.target.value;mkSv();re()};
 [['mk-dw','dw'],['mk-rt','rt'],['mk-dp','dp'],['mk-dct','dct']].forEach(([c,k])=>$('.'+c,B).onchange=e=>{MKS[k]=k==='dp'||k==='dct'?e.target.value:+e.target.value;mkSv();re()});$('[data-dd]',B).onclick=()=>open('dd');
 const jb=$('[data-job]',B);if(jb)jb.onclick=()=>{X.L.filter(x=>x.v>0).forEach(x=>fwJobAdd({n:`${x.n} · ${lanes[li].pol} → ${lanes[li].pod} (${lanes[li].eq})`,v:'برآورد بازار',cur:'USD',be:Math.round(x.v),se:Math.round(x.v*1.1)}))}}
/* domestic trucking & rail: actual vs model, ERAI-adjusted rail, transit fee calculator */
const MKTR=[['KZ','قزاقستان'],['UZ','ازبکستان'],['TM','ترکمنستان'],['KG','قرقیزستان'],['AZ','آذربایجان'],['RU','روسیه'],['TR','ترکیه'],['GE','گرجستان']];
function mkLand(B,C,re){const W=LSG('ifa-wb',[]).filter(w=>w.st!=='cancel'&&+w.freight>0&&w.from&&w.to);const T=dmTypes();const tk=w=>T.some(t=>t[0]===w.ty)?w.ty:'trl';
 const G={};W.forEach(w=>{let m=null;try{m=IFA.truckCost(w.from,w.to,tk(w),Math.max(1,(+w.kg||20000)/1000))}catch(e){}const k=w.from+'→'+w.to;(G[k]=G[k]||{k,from:w.from,to:w.to,a:[],m:m&&m.perTruckIRR,km:m&&m.km,last:''}).a.push(+w.freight);if((w.date||'')>G[k].last)G[k].last=w.date||''});
 rbAll().filter(r=>r.mode==='dom'&&r.cur==='IRR'&&r.amt>0).forEach(r=>{const f=DMC.find(c=>nkey(r.pol).includes(nkey(c[1]))||nkey(r.pol)===nkey(c[0])),t2=DMC.find(c=>nkey(r.pod).includes(nkey(c[1]))||nkey(r.pod)===nkey(c[0]));if(!f||!t2)return;const k=f[0]+'→'+t2[0];let m=null;try{m=IFA.truckCost(f[0],t2[0],'trl',24)}catch(e){}(G[k]=G[k]||{k,from:f[0],to:t2[0],a:[],m:m&&m.perTruckIRR,km:m&&m.km,last:''}).a.push(+r.amt);if((r.from||'')>G[k].last)G[k].last=r.from||''});
 const DL=Object.values(G).map(g=>{const md=mkMed(g.a);const dv=g.m?md/g.m-1:null;return {...g,md,dv,v:dv==null?'':dv>.15?'exp':dv<-.2?'cheap':'fair'}}).sort((a,b)=>b.a.length-a.a.length);
 const H=mkHist();const er=mkLast(H,'manual|ERAI');const RL=mkScore().filter(o=>o.r.mode==='rail');const M=mkM();const TF=Object.assign({},M.transit||{});const sel=new Set(MKS.tsel||[]);const tsum=[...sel].reduce((a,k)=>a+(+TF[k]||0),0);
 B.innerHTML=`<div class="sx-card"><header><b>حمل جاده‌ای داخلی: نرخ واقعی در برابر مدل</b><small>نرخ واقعی از «بارنامهٔ داخلی» و نرخ‌های داخلی بانک نرخ (ریال) · مدل از «حمل داخلی» (فاصله، نوع ناوگان، قیمت گازوئیل)</small></header>
  ${DL.length?`<table class="sx-tbl"><thead><tr><th>مسیر</th><th>فاصله</th><th>تعداد نرخ واقعی</th><th>میانهٔ واقعی (ریال/کامیون)</th><th>مدل</th><th>انحراف</th><th>حکم</th><th>آخرین</th></tr></thead><tbody>${DL.map(d=>`<tr><td>${esc(dmN(d.from))} → ${esc(dmN(d.to))}</td><td>${d.km?fa(Math.round(d.km))+' km':'—'}</td><td>${fa(d.a.length)}</td><td>${nf(d.md)}</td><td>${d.m?nf(d.m):'—'}</td><td class="${d.dv!=null&&Math.abs(d.dv)>.15?'bad':''}">${d.dv==null?'—':(d.dv>0?'+':'')+nf(d.dv*100,1)+'٪'}</td><td>${mkVb(d.v)}</td><td>${d.last?jdt(d.last):'—'}</td></tr>`).join('')}</tbody></table>`:'<p class="sx-muted">هنوز بارنامهٔ داخلیِ دارای کرایه یا نرخ داخلی ریالی ثبت نشده است. با ثبت بارنامه‌ها، نرخ واقعی هر مسیر با مدل مقایسه می‌شود.</p>'}
  <div class="fw-bt"><button class="sx-btn sm" data-o="dom">پارامترهای مدل (قیمت سوخت، نرخ ناوگان)</button><button class="sx-btn sm" data-o="wb">بارنامهٔ داخلی</button></div></div>
 <div class="ct-g2 mk-2"><div class="sx-card"><header><b>ریلی: نرخ‌های واقعی و تعدیل با ERAI</b><small>${er?'ERAI '+nf(er[1])+' در '+jdt(er[0]):'ERAI ثبت نشده — از «شاخص‌های بازار ← ثبت دستی» مقدار هفتگی را وارد کنید'}</small></header>
  ${RL.length?`<table class="sx-tbl"><thead><tr><th>مسیر</th><th>تأمین‌کننده</th><th>نرخ</th><th>تعدیل‌شده</th><th>حکم</th><th>اعتبار</th></tr></thead><tbody>${RL.map(o=>`<tr><td>${esc(o.r.pol)} → ${esc(o.r.pod)}</td><td>${esc(o.r.vendor||'—')}</td><td>${nf(o.r.amt)} ${esc(o.r.cur)}</td><td>${o.adj?usd0(o.adj.usd)+' <small class="sx-muted">×'+nf(o.adj.ratio,3)+'</small>':'—'}</td><td>${mkVb(o.verdict)}</td><td>${mkCb(o)}</td></tr>`).join('')}</tbody></table>`:'<p class="sx-muted">نرخ ریلی در بانک نرخ نیست. پاسخ‌های استعلام ریلی را از «ورود خودکار نرخ» وارد کنید.</p>'}</div>
 <div class="sx-card fw-form"><header><b>ماشین‌حساب عوارض و تعرفهٔ ترانزیت</b><small>تعرفهٔ ترانزیت هر کشور برای هر کانتینر ۴۰ فوت را از نرخ‌نامهٔ اپراتور ریلی وارد کنید</small></header>
  <div class="mk-tf">${MKTR.map(([k,n])=>`<label><input type="checkbox" data-ts="${k}" ${sel.has(k)?'checked':''}><span>${n}</span><input type="number" data-tf="${k}" value="${TF[k]??''}" placeholder="$/FEU"></label>`).join('')}</div>
  <div class="mk-chk"><label class="sx-f"><span>نرخ پایهٔ ریلی ($/FEU)</span><input type="number" class="mk-rb" value="${MKS.rb||''}"></label><b>${MKS.rb?`جمع: ${usd0((+MKS.rb||0)+tsum)} <small class="sx-muted">(ترانزیت ${usd0(tsum)})</small>`:`جمع ترانزیت انتخاب‌شده: ${usd0(tsum)}`}</b></div></div></div>
 ${fwNote('ERAI (شاخص کرایهٔ ریلی کانتینر چین–اروپا) صفحهٔ پویا و محافظت‌شده دارد و به‌صورت خودکار خوانده نمی‌شود؛ با ثبت دستی هفتگی، نرخ‌های ریلی مبدأ چین با نسبت ERAI تعدیل می‌شوند. نرخ ریلی چین–ایران شاخص عمومی ندارد و فقط از پاسخ‌های واقعی استعلام می‌آید. تعرفهٔ ترانزیت را با «شمول» نرخ ریلی تطبیق دهید تا دوبار شمرده نشود.')}`;
 $$('[data-o]',B).forEach(x=>x.onclick=()=>open(x.dataset.o));
 $$('[data-tf]',B).forEach(x=>x.onchange=()=>{const M2=mkM();M2.transit=Object.assign({},M2.transit||{},{[x.dataset.tf]:x.value===''?null:+x.value});mkMS(M2);re()});
 $$('[data-ts]',B).forEach(x=>x.onchange=()=>{const s2=new Set(MKS.tsel||[]);x.checked?s2.add(x.dataset.ts):s2.delete(x.dataset.ts);MKS.tsel=[...s2];mkSv();re()});$('.mk-rb',B).onchange=e=>{MKS.rb=+e.target.value||0;mkSv();re()}}
/* ---------- short-term index forecast (4–12 weeks) ---------- */
const MKVOL={ccfi:.04,scfi:.06,wci:.06,fbx:.07,bunker:.035,manual:.05};
const MKCNY=['2026-02-17','2027-02-06','2028-01-26','2029-02-13','2030-02-03'];
function mkSeas(d,s){if(s==='bunker')return 1;const t=Date.parse(d);let f=1;for(const c of MKCNY){const w=(t-Date.parse(c))/(7*864e5);if(w>=-5&&w<-1)f*=1.05;else if(w>=1&&w<5)f*=.95}const m=new Date(t).getUTCMonth()+1;if(m>=7&&m<=9)f*=1.03;if(m===10&&new Date(t).getUTCDate()<=14)f*=.98;return f}
function mkWeekly(a){const W=new Map();(a||[]).forEach(([d,v])=>{const t=Date.parse(d);const wk=Math.floor((t/864e5+3)/7);W.set(wk,[d,v])});return [...W.values()].sort((x,y)=>x[0]<y[0]?-1:1)}
function mkForecast(k,h=12,H=mkHist()){const s=k.split('|')[0];const a=mkWeekly(H[k]);if(!a.length)return null;const y=a.map(p=>Math.log(p[1]));let lv=y[0],tr=0;const al=.5,be=.3,ph=.85;
 for(let i=1;i<y.length;i++){const pl=lv;lv=al*y[i]+(1-al)*(lv+ph*tr);tr=be*(lv-pl)+(1-be)*ph*tr}if(y.length<3)tr=0;
 const ch=[];for(let i=1;i<a.length;i++)ch.push(y[i]-y[i-1]);const sdv=ch.length>=5?Math.sqrt(ch.reduce((q,x)=>q+x*x,0)/ch.length):null;const sig=Math.max(sdv||0,(MKVOL[s]||.05)*(sdv?.5:1));
 const last=a[a.length-1];const t0=Date.parse(last[0]);const s0=mkSeas(last[0],s);const F=[];let acc=0;
 for(let i=1;i<=h;i++){acc+=Math.pow(ph,i);const d=new Date(t0+i*7*864e5).toISOString().slice(0,10);const mu=Math.exp(lv+acc*tr)*mkSeas(d,s)/s0;const bw=1.2816*sig*Math.sqrt(i);F.push({d,v:mu,lo:mu*Math.exp(-bw),hi:mu*Math.exp(bw)})}
 return {k,hist:a,last,F,sig,emp:!!sdv,n:a.length,trend:tr}}
function mkFcChart(R,unit){const W=760,Hh=240,pl=58,pr=12,pt=12,pb=26;const A=[...R.hist.map(p=>({d:p[0],v:p[1]})),...R.F];const vs=A.flatMap(p=>[p.v,p.lo||p.v,p.hi||p.v]);const lo=Math.min(...vs)*.97,hi=Math.max(...vs)*1.03,r=hi-lo||1;
 const t0=Date.parse(A[0].d),t1=Date.parse(A[A.length-1].d),tr=t1-t0||1;const X=d=>pl+(Date.parse(d)-t0)/tr*(W-pl-pr),Y=v=>pt+(1-(v-lo)/r)*(Hh-pt-pb);const last=R.hist[R.hist.length-1];
 const band=[...R.F.map(p=>`${X(p.d).toFixed(1)},${Y(p.hi).toFixed(1)}`),...R.F.slice().reverse().map(p=>`${X(p.d).toFixed(1)},${Y(p.lo).toFixed(1)}`)];band.unshift(`${X(last[0]).toFixed(1)},${Y(last[1]).toFixed(1)}`);
 return `<svg class="mk-ch" viewBox="0 0 ${W} ${Hh}" preserveAspectRatio="none">${[0,.25,.5,.75,1].map(f=>lo+f*r).map(y=>`<line x1="${pl}" x2="${W-pr}" y1="${Y(y)}" y2="${Y(y)}"/><text x="${pl-6}" y="${Y(y)+3}" text-anchor="end">${nf(y)}</text>`).join('')}
  <polygon class="b" points="${band.join(' ')}"/><path class="l" d="M${R.hist.map(p=>X(p[0]).toFixed(1)+','+Y(p[1]).toFixed(1)).join('L')}"/><path class="f" d="M${X(last[0]).toFixed(1)},${Y(last[1]).toFixed(1)}L${R.F.map(p=>X(p.d).toFixed(1)+','+Y(p.v).toFixed(1)).join('L')}"/>
  ${R.hist.map(p=>`<circle cx="${X(p[0]).toFixed(1)}" cy="${Y(p[1]).toFixed(1)}" r="2.4"><title>${jdt(p[0])}: ${nf(p[1],1)} ${unit||''}</title></circle>`).join('')}
  <line class="now" x1="${X(last[0])}" x2="${X(last[0])}" y1="${pt}" y2="${Hh-pb}"/><text x="${pl}" y="${Hh-8}">${jdt(A[0].d)}</text><text x="${W-pr}" y="${Hh-8}" text-anchor="end">${jdt(A[A.length-1].d)}</text></svg>`}
function mkFc(B,C,re){const H=mkHist();const keys=Object.keys(H).filter(k=>H[k].length).sort((a,b)=>(MKL[a]?0:1)-(MKL[b]?0:1)||a.localeCompare(b));if(!keys.length){B.innerHTML='<div class="sx-empty">هنوز تاریخچهٔ شاخصی وجود ندارد. به سرور وصل شوید یا مقادیر را دستی ثبت کنید.</div>';return}
 const k=keys.includes(MKS.fcK)?MKS.fcK:keys[0];const h=[4,8,12].includes(+MKS.fcH)?+MKS.fcH:12;const R=mkForecast(k,h,H);const s=k.split('|')[0];const u=MKUNIT[s]||'';const at=w=>R.F[Math.min(R.F.length,w)-1];
 const ch=w=>{const p=at(w);return p?(p.v/R.last[1]-1)*100:0};const sum=[4,8,12].filter(w=>w<=h).map(w=>{const p=at(w);return kpi(fa(w)+' هفته بعد',p.v,{d:s==='ccfi'||s==='scfi'?1:0,pre:u.includes('$')?'$':'',sub:`${ch(w)>=0?'▲':'▼'} ${nf(Math.abs(ch(w)),1)}٪ · بازه ${nf(p.lo)} تا ${nf(p.hi)}`})}).join('');
 const dir=ch(Math.min(4,h));const LE=s==='ccfi'||s==='scfi'?MKIR.map(([pol,pod,eq])=>mkEstimate({pol,pod,eq},H)).filter(e=>e.base&&e.adj&&e.adj.k===k):[];
 B.innerHTML=`<div class="om-tb"><select class="mk-fk">${keys.map(x=>`<option value="${esc(x)}" ${x===k?'selected':''}>${esc(mkName(x))} (${fa(H[x].length)})</option>`).join('')}</select><div class="sx-seg">${[4,8,12].map(w=>`<button data-h="${w}" class="${w===h?'on':''}">${fa(w)} هفته</button>`).join('')}</div><span class="sx-sp"></span><small class="sx-muted">آخرین: ${nf(R.last[1],1)} ${esc(u)} · ${jdt(R.last[0])}</small></div>
 <div class="ex-kpis">${sum}${kpi('نوسان هفتگی',R.sig*100,{d:1,suf:'٪',sub:R.emp?'از تاریخچه ('+fa(R.n)+' هفته)':'فرض پیش‌فرض — تاریخچه کم است'})}</div>
 <div class="sx-card"><header><b>${esc(mkName(k))}: تاریخچه و پیش‌بینی ${fa(h)} هفته</b><small>خط‌چین = پیش‌بینی · ناحیهٔ رنگی = بازهٔ ۸۰٪</small></header>${mkFcChart(R,u)}</div>
 <div class="sx-card mk-off"><div><b>${Math.abs(dir)<1.5?'بازار تقریباً پایدار':dir>0?'انتظار افزایش نرخ':'انتظار کاهش نرخ'} در ۴ هفتهٔ آینده (${dir>=0?'+':''}${nf(dir,1)}٪)</b><p>${dir>1.5?'اگر زمان حمل قابل جابه‌جایی نیست، رزرو یا تمدید نرخ فعلی زودتر انجام شود؛ مدت اعتبار پیشنهادها را کوتاه‌تر بپذیرید.':dir<-1.5?'در صورت امکان، تعهد بلندمدت را به تعویق بیندازید یا نرخ شناور مرتبط با شاخص بخواهید.':'برای قراردادهای بلندتر از ۴ هفته، بند تعدیل با شاخص (CCFI خلیج فارس) پیشنهاد می‌شود.'} ${R.emp?'':'تاریخچهٔ کافی هنوز جمع نشده و پیش‌بینی عمدتاً بر فرض‌های فصلی و نوسان پیش‌فرض است.'}</p></div></div>
 ${LE.length?`<div class="sx-card"><header><b>اثر پیش‌بینی بر مسیرهای ایران</b><small>برآورد امروز × نسبت پیش‌بینی شاخص</small></header><table class="sx-tbl"><thead><tr><th>مسیر</th><th>برآورد امروز</th>${[4,8,12].filter(w=>w<=h).map(w=>`<th>${fa(w)} هفته بعد</th>`).join('')}</tr></thead><tbody>${LE.map(e=>`<tr><td>${esc(e.o.pol)} → ${esc(e.o.pod)} · ${e.o.eq}</td><td>${usd0(e.usd)}</td>${[4,8,12].filter(w=>w<=h).map(w=>{const p=at(w);const f=p.v/R.last[1];return `<td>${usd0(e.usd*f)} <small class="sx-muted" dir="ltr">(${usd0(e.usd*p.lo/R.last[1])} – ${usd0(e.usd*p.hi/R.last[1])})</small></td>`}).join('')}</tr>`).join('')}</tbody></table></div>`:''}
 ${fwNote('روش: هموارسازی نمایی با روند میرا (Holt damped) روی لگاریتم مقادیر هفتگی، به‌اضافهٔ ضرایب فصلی فرضی (پیش از سال نو چینی +۵٪، پس از آن −۵٪، تیر تا شهریور +۳٪، نیمهٔ اول اکتبر −۲٪). بازه از نوسان تاریخی هفتگی؛ اگر کمتر از ۶ هفته تاریخچه باشد، نوسان پیش‌فرض هر شاخص به کار می‌رود. پیش‌بینی ابزار تصمیم است، نه تضمین؛ شوک‌هایی مثل بسته‌شدن تنگه یا تحریم جدید در مدل نیستند.')}`;
 $('.mk-fk',B).onchange=e=>{MKS.fcK=e.target.value;mkSv();re()};$$('[data-h]',B).forEach(x=>x.onclick=()=>{MKS.fcH=+x.dataset.h;mkSv();re()})}
/* ---------- thresholds (index & lane), expiring rates, contract vs market ---------- */
function mkWatchVal(w,H=mkHist()){if(w.type==='index'){const l=mkLast(H,w.key);return l?{v:l[1],d:l[0]}:null}const e=mkEstimate({pol:w.pol,pod:w.pod,eq:w.eq},H);return e.base?{v:e.usd,d:fwToday()}:null}
const mkHit=(w,x)=>x&&(w.op==='>'?x.v>=w.val:x.v<=w.val);
function mkWatchRun(){try{const M=mkM();const W=M.watch||[];if(!W.length)return;const H=mkHist();const t=fwToday();let ch=false;W.forEach(w=>{const x=mkWatchVal(w,H);if(mkHit(w,x)&&w.fired!==t){w.fired=t;ch=true;const n=w.type==='index'?mkName(w.key):`${w.pol} → ${w.pod} (${w.eq})`;toast(`🔔 آستانه: ${n} ${w.op==='>'?'بالای':'زیر'} ${nf(w.val)} (اکنون ${nf(x.v)})`);emit('rate.threshold',{name:n,op:w.op,threshold:w.val,value:Math.round(x.v),type:w.type})}});if(ch)mkMS(M)}catch(e){}}
function mkWatch(B,C,re){const M=mkM();const W=M.watch||[];const H=mkHist();const keys=Object.keys(MKL).concat(Object.keys(H).filter(k=>!MKL[k]));const R=rbAll();const t=fwToday();
 const exp=R.filter(r=>r.to&&fwDiff(t,r.to)>=0&&fwDiff(t,r.to)<=14).sort((a,b)=>a.to.localeCompare(b.to));const V=mkScore(R,H);
 const ctr=V.filter(o=>o.r.to&&fwDiff(t,o.r.to)>=0&&(o.ref||(o.adj&&o.adj.d0!==o.adj.d1))).map(o=>{const mk=o.ref||o.adj.usd;const dv=o.u/mk-1;return {o,mk,dv,act:dv>.1?'مذاکرهٔ مجدد یا استعلام جدید — نرخ قرارداد بالاتر از بازار است':dv<-.1?'تمدید زودهنگام — نرخ قرارداد زیر بازار است':'نگه‌داشتن نرخ؛ نزدیک به بازار'}}).sort((a,b)=>Math.abs(b.dv)-Math.abs(a.dv));
 B.innerHTML=`<div class="sx-card fw-form"><header><b>آستانه‌های هشدار</b><small>هشدار وقتی شاخص یا نرخ برآوردی مسیر از حد تعیین‌شده عبور کند · روی سرور، آستانه‌های شاخص هم بررسی و به کانال‌های اعلان ارسال می‌شوند (رویداد rate.threshold)</small></header>
  <div class="fw-g"><label class="sx-f fw-f"><span>نوع</span><select class="mk-wt"><option value="index">شاخص</option><option value="lane" ${MKS.wt==='lane'?'selected':''}>مسیر ایران (برآورد)</option></select></label>
  ${MKS.wt==='lane'?`<label class="sx-f fw-f w2"><span>مسیر</span><select class="mk-wl">${MKIR.map(([a,b2,e],i)=>`<option value="${i}">${a} → ${b2} · ${e}</option>`).join('')}</select></label>`:`<label class="sx-f fw-f w2"><span>شاخص</span><select class="mk-wk">${keys.map(k=>`<option value="${esc(k)}">${esc(mkName(k))}</option>`).join('')}</select></label>`}
  <label class="sx-f fw-f"><span>شرط</span><select class="mk-wo"><option value=">">بالاتر یا برابر</option><option value="<">پایین‌تر یا برابر</option></select></label><label class="sx-f fw-f"><span>مقدار</span><input type="number" class="mk-wv"></label></div><div class="fw-bt"><button class="sx-btn sm pri" data-wadd>افزودن آستانه</button></div>
  ${W.length?`<table class="sx-tbl"><thead><tr><th>موضوع</th><th>شرط</th><th>مقدار فعلی</th><th>وضعیت</th><th></th></tr></thead><tbody>${W.map(w=>{const x=mkWatchVal(w,H);const hit=mkHit(w,x);return `<tr><td>${esc(w.type==='index'?mkName(w.key):w.pol+' → '+w.pod+' · '+w.eq)}</td><td>${w.op==='>'?'بالای':'زیر'} ${nf(w.val)}</td><td>${x?nf(x.v):'—'}</td><td>${x?`<span class="tm-s ${hit?'bad':'ok'}">${hit?'عبور کرد':'در محدوده'}</span>`:'<span class="tm-s">بدون داده</span>'}${w.fired?` <small class="sx-muted">آخرین هشدار ${jdt(w.fired)}</small>`:''}</td><td><button class="sx-btn xs" data-wdel="${w.id}">${svgI(IC.trash)}</button></td></tr>`}).join('')}</tbody></table>`:''}</div>
 <div class="ct-g2 mk-2"><div class="sx-card"><header><b>نرخ‌های رو به انقضا (۱۴ روز)</b><small>سرور هم هشدار rate.expiring را ۷ روز مانده ارسال می‌کند</small></header>${exp.length?`<table class="sx-tbl"><tbody>${exp.map(r=>`<tr><td>${esc(r.vendor||'—')}<br><small class="sx-muted">${esc(r.pol)} → ${esc(r.pod)} · ${esc(r.eq)}</small></td><td>${nf(r.amt)} ${esc(r.cur)}</td><td><span class="tm-s ${fwDiff(t,r.to)<=7?'warn':''}">${fa(fwDiff(t,r.to))} روز</span></td></tr>`).join('')}</tbody></table>`:'<p class="sx-muted">نرخی در ۱۴ روز آینده منقضی نمی‌شود.</p>'}</div>
 <div class="sx-card"><header><b>نرخ قراردادی در برابر بازار</b><small>پیشنهاد اقدام برای هر نرخ معتبر</small></header>${ctr.length?`<table class="sx-tbl"><thead><tr><th>نرخ</th><th>قرارداد</th><th>بازار</th><th>تفاوت</th><th>اقدام</th></tr></thead><tbody>${ctr.slice(0,30).map(c=>`<tr><td>${esc(c.o.r.vendor||'—')}<br><small class="sx-muted">${esc(c.o.r.pol)} → ${esc(c.o.r.pod)} · ${esc(c.o.r.eq)} · تا ${jdt(c.o.r.to)}</small></td><td>${usd0(c.o.u)}</td><td>${usd0(c.mk)}</td><td class="${c.dv>.1?'bad':''}">${(c.dv>0?'+':'')+nf(c.dv*100,1)}٪</td><td><small>${c.act}</small></td></tr>`).join('')}</tbody></table>`:'<p class="sx-muted">برای مقایسه، دست‌کم دو نرخ هم‌مسیر یا تاریخچهٔ شاخص لازم است.</p>'}</div></div>`;
 $('.mk-wt',B).onchange=e=>{MKS.wt=e.target.value;mkSv();re()};
 $('[data-wadd]',B).onclick=()=>{const v=+$('.mk-wv',B).value;if(!v)return toast('مقدار آستانه لازم است');const M2=mkM();const w={id:'W'+Date.now().toString(36),type:MKS.wt==='lane'?'lane':'index',op:$('.mk-wo',B).value,val:v,t:Date.now()};
  if(w.type==='lane'){const [pol,pod,eq]=MKIR[+$('.mk-wl',B).value];Object.assign(w,{pol,pod,eq})}else w.key=$('.mk-wk',B).value;M2.watch=[...(M2.watch||[]),w];mkMS(M2);toast('آستانه افزوده شد');mkWatchRun();re()};
 $$('[data-wdel]',B).forEach(x=>x.onclick=()=>{const M2=mkM();M2.watch=(M2.watch||[]).filter(w=>w.id!==x.dataset.wdel);mkMS(M2);re()})}
(function(){const st=document.createElement('style');st.textContent=`.mk-2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:12px 0}@media(max-width:1100px){.mk-2{grid-template-columns:1fr}}
.mk .mk-pss{display:grid;grid-template-columns:repeat(6,1fr);gap:6px;margin:6px 0 10px}.mk .mk-pss label{display:flex;flex-direction:column;font-size:11px;color:var(--faint);gap:3px}.mk .mk-pss input,.mk .mk-tf input[type=number]{width:100%;box-sizing:border-box;background:var(--panel2);border:1px solid var(--line);border-radius:6px;color:var(--text);padding:4px 6px;font:12px Inter,Vazirmatn}
.mk .mk-ap{display:flex;gap:8px;align-items:center;font-size:12.5px}.mk td.n{direction:ltr;text-align:left;white-space:nowrap}.mk tr.mk-tot td{border-top:2px solid var(--line2)}
.mk .mk-tf{display:grid;grid-template-columns:1fr 1fr;gap:6px 14px;margin:6px 0 10px}.mk .mk-tf label{display:grid;grid-template-columns:auto 1fr 96px;gap:8px;align-items:center;font-size:12.5px}
.mk-ch .b{fill:var(--accent);opacity:.13}.mk-ch .f{fill:none;stroke:var(--accent);stroke-width:2;stroke-dasharray:5 4}.mk-ch .now{stroke:var(--faint);stroke-dasharray:2 3}
.mk .om-tb .sx-f{margin:0}.mk .om-tb input[type=number]{width:80px}`;document.head.appendChild(st)})();
