
/* ===== v15.7: phase 3 — partner rate panel · weekly market report · rate e-mail inbox · external quote references ===== */
MKSRC.partner=['پنل نرخ شرکا',75];MKSRC.inbox=['صندوق ایمیل نرخ',70];
const P3S={prt:null,rep:null,ib:null,err:''};
const p3Need=B=>{if(svOn())return false;B.innerHTML=`<div class="sx-card mk-off"><div><b>نیاز به سرور تیمی</b><p>این بخش روی سرور تیمی اجرا می‌شود (پیوند عمومی شرکا، زمان‌بند هفتگی، صندوق ایمیل). از «سیستم ← همگام‌سازی» وارد سرور شوید.</p></div></div>`;return true};
const p3Lanes=t=>String(t||'').split(/\n|;/).map(l=>l.trim()).filter(Boolean).map(l=>{const m=l.match(/^(?:(sea|lcl|rail|road|air|dom)\s*[:|]\s*)?(.+?)\s*(?:-|–|→|>|to|به)\s*(.+?)(?:\s+(20\w*|40\w*|LCL|FTL|kg))?$/i);return m?{mode:(m[1]||'sea').toLowerCase(),pol:m[2].trim(),pod:m[3].trim(),eq:(m[4]||'').toUpperCase()}:null}).filter(Boolean);
async function mkPrt(B,C,re){if(p3Need(B))return;B.innerHTML='<div class="sx-empty sm">در حال بارگذاری…</div>';let P=[],R=[];try{[P,R]=await Promise.all([svApi('/api/partners'),svApi('/api/partners/rates?status=new&days=120')])}catch(e){B.innerHTML='<div class="sx-empty">خطا: '+esc(e.message)+'</div>';return}
 const sug=MKIR.slice(0,5).map(([a,b,c])=>a+' - '+b+' '+c).join('\n');const H=mkHist();
 const vb=r=>{if((r.mode||'sea')!=='sea'||!(r.usd>0))return '';try{const x=IFA.market.check(r.usd,'USD',{pol:r.pol,pod:r.pod,eq:r.eq});return x.verdict?mkVb(x.verdict==='expensive'?'exp':x.verdict==='fair'?'fair':'cheap')+` <small class="sx-muted">${x.deviation>0?'+':''}${nf(x.deviation*100,1)}٪</small>`:'<small class="sx-muted">بدون مرجع</small>'}catch(e){return ''}};
 B.innerHTML=`<div class="sx-card mk-off"><div><b>پنل نرخ هفتگی شرکا</b><p>برای هر فورواردر/خط منتخب (از جمله منتخب‌های اکوسیستم چین) یک پیوند اختصاصی بسازید. هر شنبه ساعت ${fa(9)} یادآوری ایمیلی می‌رود؛ نرخ‌ها پس از تأیید شما با منبع «پنل شرکا» وارد بانک نرخ مشترک می‌شوند و در محک، کالیبراسیون «هزینهٔ حمل با دادهٔ روز» و گزارش هفتگی به کار می‌روند.</p></div></div>
 <div class="mk-g"><div class="sx-card fw-form"><header><b>دعوت شریک جدید</b></header><label class="sx-f"><span>نام شرکت</span><input class="p3-n" placeholder="Sea Star Logistics"></label><label class="sx-f"><span>ایمیل نرخ</span><input class="p3-e" type="email" placeholder="rates@example.com" dir="ltr"></label>
  <label class="sx-f"><span>مسیرها (هر خط: مبدأ - مقصد تجهیز؛ اختیاری: rail: / road: / air:)</span><textarea class="mk-tx p3-l" rows="5">${esc(sug)}</textarea></label><div class="fw-bt"><button class="sx-btn sm pri p3-add">ساخت پیوند و ارسال دعوت</button></div><div class="p3-msg"></div></div>
 <div class="sx-card"><header><b>شرکا (${fa(P.length)})</b></header>${P.length?`<div class="sx-tw"><table class="sx-tbl"><thead><tr><th>شریک</th><th>مسیرها</th><th>ثبت‌ها</th><th>آخرین پاسخ</th><th></th></tr></thead><tbody>${P.map(p=>`<tr class="${p.revoked?'exp':''}"><td><b>${esc(p.name)}</b><div class="sx-muted" dir="ltr">${esc(p.email||'—')}</div></td><td>${fa(p.lanes.length)}</td><td>${fa(p.n)}${p.pending?` <small class="sx-muted">(${fa(p.pending)} در انتظار)</small>`:''}</td><td>${p.last_resp?fdate(p.last_resp):'—'}</td><td class="p3-act"><button class="sx-btn xs" data-cp="${esc(p.url)}">کپی پیوند</button>${p.email&&!p.revoked?`<button class="sx-btn xs" data-rm="${p.token}">یادآوری</button>`:''}<button class="sx-btn xs" data-rv="${p.token}" data-v="${p.revoked?0:1}">${p.revoked?'فعال‌سازی':'لغو'}</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="sx-muted">هنوز شریکی دعوت نشده است.</p>'}</div></div>
 <div class="sx-card"><header><b>نرخ‌های در انتظار تأیید (${fa(R.length)})</b><small>حکم محک: مقایسه با میانهٔ نرخ‌های تعدیل‌شدهٔ هم‌مسیر در بانک نرخ</small></header>${R.length?`<div class="sx-tw"><table class="sx-tbl"><thead><tr><th><input type="checkbox" data-all checked></th><th>شریک</th><th>شیوه</th><th>مسیر</th><th>نرخ</th><th>معادل $</th><th>شمول</th><th>T/T</th><th>اعتبار تا</th><th>محک بازار</th><th>توضیح</th></tr></thead><tbody>${R.map(r=>`<tr><td><input type="checkbox" data-ck="${r.id}" checked></td><td>${esc(r.partner)}</td><td>${esc(RMODE[r.mode]||r.mode)}</td><td dir="ltr">${esc(r.pol)} → ${esc(r.pod)} ${esc(r.eq||'')}</td><td>${nf(r.amt)} ${esc(r.cur)}</td><td>${r.usd?usd0(r.usd):'—'}</td><td>${esc(r.incl||'')}</td><td>${r.days?fa(r.days):'—'}</td><td>${esc(r.valid||'—')}</td><td>${vb(r)}</td><td><small>${esc(r.note||'')}</small></td></tr>`).join('')}</tbody></table></div><div class="fw-bt"><button class="sx-btn sm pri" data-ok>تأیید و افزودن به بانک نرخ</button><button class="sx-btn sm" data-rej>رد انتخاب‌شده‌ها</button></div>`:'<p class="sx-muted">نرخ جدیدی در انتظار نیست.</p>'}</div>`;
 const msg=$('.p3-msg',B);
 $('.p3-add',B).onclick=async()=>{const name=$('.p3-n',B).value.trim(),email=$('.p3-e',B).value.trim(),lanes=p3Lanes($('.p3-l',B).value);if(!name){msg.textContent='نام شرکت لازم است';return}
  try{const r=await svApi('/api/partners',{method:'POST',body:{name,email,lanes}});try{await navigator.clipboard.writeText(r.url)}catch(e){}toast(r.emailed?'دعوت ایمیل شد و پیوند کپی شد':'پیوند ساخته و کپی شد');re()}catch(e){msg.textContent='خطا: '+e.message}};
 $$('[data-cp]',B).forEach(x=>x.onclick=async()=>{try{await navigator.clipboard.writeText(x.dataset.cp);toast('پیوند کپی شد')}catch(e){prompt('پیوند پنل نرخ:',x.dataset.cp)}});
 $$('[data-rm]',B).forEach(x=>x.onclick=async()=>{try{await svApi('/api/partners/'+x.dataset.rm+'/remind',{method:'POST'});toast('یادآوری در صف ارسال قرار گرفت')}catch(e){toast('خطا: '+e.message)}});
 $$('[data-rv]',B).forEach(x=>x.onclick=async()=>{try{await svApi('/api/partners/'+x.dataset.rv,{method:'PATCH',body:{revoked:+x.dataset.v}});re()}catch(e){toast('خطا: '+e.message)}});
 const all=$('[data-all]',B);if(all)all.onchange=()=>$$('[data-ck]',B).forEach(c=>c.checked=all.checked);
 const act=async st=>{const ids=$$('[data-ck]',B).filter(c=>c.checked).map(c=>+c.dataset.ck);if(!ids.length)return;try{const r=await svApi('/api/partners/rates',{method:'POST',body:{ids,status:st}});if(st==='ok'){try{await svSync(true)}catch(e){}toast(fa(r.added)+' نرخ به بانک نرخ افزوده شد');emit('rates.imported',{n:r.added,src:'partner'})}re()}catch(e){toast('خطا: '+e.message)}};
 const ok=$('[data-ok]',B);if(ok){ok.onclick=()=>act('ok');$('[data-rej]',B).onclick=()=>act('rej')}}
async function mkRep(B,C,re){if(p3Need(B))return;B.innerHTML='<div class="sx-empty sm">در حال ساخت گزارش…</div>';let R;try{R=await svApi('/api/reports/market')}catch(e){B.innerHTML='<div class="sx-empty">خطا: '+esc(e.message)+'</div>';return}
 const ar=v=>v==null?'—':`<span class="${v>0?'up':'dn'}">${v>0?'▲':'▼'} ${nf(Math.abs(v),1)}٪</span>`;
 B.innerHTML=`<div class="sx-card mk-off"><div><b>گزارش هفتگی خودکار بازار نرخ</b><p>هر شنبه ساعت ${fa(8)} به وقت تهران برای همهٔ قوانین اعلان با رویداد <code>market.weekly</code> (ایمیل، تلگرام، بله، وب‌هوک) ارسال می‌شود. برای مدیران و مشتریان در «اعلان‌ها» قانون بسازید؛ متن پیش‌فرض قالب {{text}} است.</p></div></div>
 <div class="mk-g"><div class="sx-card"><header><b>هفتهٔ ${fa(R.week)}</b><small>${fdate(R.generated)}</small></header><div class="sx-tw"><table class="sx-tbl mk-t"><thead><tr><th>شاخص</th><th>مقدار</th><th>هفتگی</th><th>ماهانه</th></tr></thead><tbody>${R.rows.map(r=>`<tr><td>${esc(r.name)}<div class="sx-muted"><small>${esc(r.date)} · ${esc(r.unit)}</small></div></td><td class="n">${nf(r.value,r.series==='diesel'?3:1)}</td><td class="${r.w>0?'up':'dn'}">${ar(r.w)}</td><td>${ar(r.m)}</td></tr>`).join('')||'<tr><td colspan="4" class="sx-muted">هنوز شاخصی دریافت نشده</td></tr>'}</tbody></table></div></div>
  <div class="sx-card"><header><b>متن ارسالی</b></header><pre class="p3-pre">${esc(R.text)}</pre><div class="fw-bt"><button class="sx-btn sm pri" data-send>ارسال اکنون</button><button class="sx-btn sm" data-html>نسخهٔ قابل چاپ</button><button class="sx-btn sm" data-rule>ساخت قانون ایمیل گزارش</button></div></div></div>
 ${R.lanes.length?`<div class="sx-card"><header><b>نرخ‌های پنل شرکا در ۷ روز اخیر</b></header><table class="sx-tbl"><thead><tr><th>مسیر</th><th>میانه</th><th>بازه</th><th>تعداد</th></tr></thead><tbody>${R.lanes.map(l=>`<tr><td dir="ltr">${esc(l.pol)} → ${esc(l.pod)} ${esc(l.eq||'')}</td><td>${usd0(l.median)}</td><td>${usd0(l.min)} – ${usd0(l.max)}</td><td>${fa(l.n)} نرخ / ${fa(l.partners)} شریک</td></tr>`).join('')}</tbody></table></div>`:''}`;
 $('[data-send]',B).onclick=async()=>{try{const r=await svApi('/api/reports/market/send',{method:'POST'});toast(r.queued?fa(r.queued)+' پیام در صف ارسال':'قانونی برای market.weekly تعریف نشده')}catch(e){toast('خطا: '+e.message)}};
 $('[data-html]',B).onclick=()=>window.open(svUrl()+'/api/reports/market?format=html&t='+encodeURIComponent(SV.st.token),'_blank');
 $('[data-rule]',B).onclick=async()=>{const to=prompt('ایمیل گیرندهٔ گزارش هفتگی:');if(!to||!/@/.test(to))return;try{await svApi('/api/notify/rules',{method:'POST',body:{event:'market.weekly',channel:'email',target:to.trim(),template:'{{text}}'}});toast('قانون ساخته شد؛ گزارش هر شنبه ارسال می‌شود')}catch(e){toast('خطا: '+e.message)}}}
/* rate e-mail inbox panel on top of the auto-ingest tab */
async function mkInbox(B,re){if(!svOn())return;const box=document.createElement('div');box.className='sx-card p3-ib';box.innerHTML='<header><b>صندوق ایمیل نرخ</b><small>در حال بارگذاری…</small></header>';B.prepend(box);
 let L=[],cfg={};try{[L,cfg]=await Promise.all([svApi('/api/rates/inbox'),svApi('/api/live/status').then(s=>s.config||{}).catch(()=>({}))])}catch(e){box.innerHTML='<header><b>صندوق ایمیل نرخ</b><small>'+esc(e.message)+'</small></header>';return}
 box.innerHTML=`<header><b>صندوق ایمیل نرخ ${L.length?'('+fa(L.length)+' جدید)':''}</b><small>${cfg.imap?'سرور هر ۳۰ دقیقه ایمیل‌های خوانده‌نشده را دریافت می‌کند؛ «تحلیل» متن و پیوست CSV/Excel را به پیش‌نمایش پایین می‌برد':'IMAP تنظیم نشده — متغیرهای IFA_IMAP_HOST / IFA_IMAP_USER / IFA_IMAP_PASS را روی سرور بگذارید'}</small></header>
 ${L.length?`<table class="sx-tbl"><tbody>${L.map(m=>`<tr><td><b>${esc(m.subject||'(بدون موضوع)')}</b><div class="sx-muted"><small dir="ltr">${esc(m.sender)}</small> · ${fdate(m.ts)}${m.atts.length?' · 📎 '+m.atts.map(a=>esc(a.name)).join('، '):''}</div></td><td class="p3-act"><button class="sx-btn xs pri" data-an="${m.id}">تحلیل</button><button class="sx-btn xs" data-sk="${m.id}">نادیده</button></td></tr>`).join('')}</tbody></table>`:'<p class="sx-muted">ایمیل نرخ جدیدی نیست.</p>'}
 ${cfg.imap?'<div class="fw-bt"><button class="sx-btn sm" data-poll>بررسی صندوق اکنون</button></div>':''}`;
 const pl=$('[data-poll]',box);if(pl)pl.onclick=async()=>{pl.disabled=true;try{const r=await svApi('/api/rates/inbox/poll',{method:'POST'});toast(fa(r.new)+' ایمیل جدید')}catch(e){toast('خطا: '+e.message)}re()};
 $$('[data-sk]',box).forEach(x=>x.onclick=async()=>{await svApi('/api/rates/inbox/'+x.dataset.sk,{method:'POST',body:{status:'skip'}}).catch(()=>{});re()});
 $$('[data-an]',box).forEach(x=>x.onclick=async()=>{try{const m=await svApi('/api/rates/inbox/'+x.dataset.an);let P=mkParse(m.text||'','email');if(!P.length)P=mkText(m.text||'','email');
  for(const a of m.atts||[]){try{if(a.b64&&/\.xlsx$/i.test(a.name)){const bin=atob(a.b64),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);P=P.concat(mkParse(await readXlsx(u.buffer),'excel').map(r=>({...r,note:(r.note?r.note+' · ':'')+a.name})))}else if(a.text!=null)P=P.concat(mkParse(a.text,'csv').map(r=>({...r,note:(r.note?r.note+' · ':'')+a.name})))}catch(e){}}
  const vend=(m.sender||'').replace(/<.*>/,'').replace(/"/g,'').trim();P.forEach(r=>{r.src='inbox';if(!r.vendor&&vend)r.vendor=vend;r.note=(r.note?r.note+' · ':'')+'ایمیل: '+(m.subject||'').slice(0,60)});
  MKS.ing=m.text||'';MKS.ingR=P;mkSv();await svApi('/api/rates/inbox/'+m.id,{method:'POST',body:{status:'done'}}).catch(()=>{});toast(fa(P.length)+' نرخ شناسایی شد — پیش‌نمایش را بازبینی کنید');re()}catch(e){toast('خطا: '+e.message)}})}
function mkIngX(B,C,re){mkIng(B,C,re);mkInbox(B,re)}
/* external quote reference (Freightos public estimator / configured paid API) for the live O→D view */
async function lqRef(box,G){const A=G.nodeById[LQS.from],Z=G.nodeById[LQS.to];if(!A||!Z)return;const cg=(ctx()||{}).cargo||{};const nm=n=>(lqNm(n)[0]||n.nameEn||n.id);
 const qs=new URLSearchParams({o:nm(A),oc:A.country,d:nm(Z),dc:Z.country,eq:cg.containerType||'40HC',kg:String(cg.weightKg||''),cbm:String(cg.cbm||''),mode:cg.shipmentType==='LCL'?'LCL':cg.shipmentType==='AIR'?'air':'FCL'});
 box.innerHTML='<small class="sx-muted">در حال استعلام مرجع آنلاین…</small>';try{const r=await svApi('/api/live/quote-ref?'+qs);const P=r.providers||[];if(!P.length){box.innerHTML='<small class="sx-muted">هیچ اتصال مرجعی فعال نیست (Freightos در سرور غیرفعال است و API سفارشی تنظیم نشده).</small>';return}
  box.innerHTML=P.map(p=>p.ok?`<div class="lq-ref"><b>${esc(p.name)}</b>${p.quotes.length?p.quotes.map(x=>`<span>${esc(x.mode)}: ${usd0(x.min)}${x.max&&x.max!==x.min?' – '+usd0(x.max):''}${x.days?` · ${fa(x.days[0])}–${fa(x.days[1])} روز`:''}</span>`).join(''):'<span class="sx-muted">برای این مسیر برآوردی ندارد</span>'}${p.proxy?`<small class="sx-muted">${esc(p.proxy)}</small>`:''}${p.note?`<small class="sx-muted">${esc(p.note)}${p.cached?' · از حافظهٔ ۲۴ ساعته':''}</small>`:''}${p.link?`<small>منبع: <a href="${esc(p.link)}" target="_blank" rel="noopener">${esc(p.attribution)}</a></small>`:''}</div>`:`<div class="lq-ref"><b>${esc(p.id)}</b><small class="sx-muted">${esc(p.err)}</small></div>`).join('')}catch(e){box.innerHTML='<small class="sx-muted">خطا: '+esc(e.message)+'</small>'}}
(function(){const st=document.createElement('style');st.textContent=`.p3-act{white-space:nowrap}.p3-act .sx-btn{margin-inline-start:4px}.p3-pre{white-space:pre-wrap;font:12.5px/1.9 Vazirmatn,Inter;background:var(--panel2);border:1px solid var(--line);border-radius:10px;padding:10px;max-height:340px;overflow:auto}.p3-ib{margin-bottom:12px}.mk .up{color:var(--fbad)}.mk .dn{color:var(--good)}
.lq-ref{display:flex;flex-direction:column;gap:2px;border:1px dashed var(--line2);border-radius:10px;padding:8px 10px;margin-top:8px}.lq-ref span{font:600 13px Inter,Vazirmatn}.lq-ref small{font-size:11px}`;document.head.appendChild(st)})();
