# v15.9.2: rebrand → «سامانه لجستیک آسانا» (Asana Logistics) with the uploaded logo
P='/data/atlas/ifa/public/index.html'
h=open(P,encoding='utf8').read()
def rep(a,b,n=1):
    global h
    assert h.count(a)==n,(a[:80],h.count(a)); h=h.replace(a,b)
FA='سامانه لجستیک آسانا';EN='Asana Logistics'
u=lambda s:''.join(c if ord(c)<128 else '\\u%04X'%ord(c) for c in s)
OLD=r'\u0627\u0637\u0644\u0633 \u0628\u0627\u0631\u0628\u0631\u06CC \u0627\u06CC\u0631\u0627\u0646'
B64=open('/data/atlas/brand/mark.b64').read().strip()
LOGO='data:image/svg+xml;base64,'+B64
rep('<meta name="application-name" content="اطلس باربری ایران" />','<meta name="application-name" content="%s" />\n    <meta name="apple-mobile-web-app-title" content="آسانا" />'%FA)
rep('<title>اطلس باربری ایران · Iran Freight Atlas</title>','<title>%s · %s</title>'%(FA,EN))
rep('document.title="%s \\xB7 Iran Freight Atlas"'%OLD,'document.title="%s \\xB7 %s"'%(u(FA),EN))
# intro splash: logo + name
rep('children:(0,q.jsxs)("div",{children:[(0,q.jsx)(Gt.h2,{initial:{letterSpacing:"0.2em",opacity:0},animate:{letterSpacing:"0em",opacity:1},transition:{duration:1.6,ease:[.2,.9,.2,1]},children:"%s"}),(0,q.jsx)(Gt.p,{initial:{opacity:0},animate:{opacity:1},transition:{delay:.6},children:"Iran Freight Atlas"})'%OLD,
    'children:(0,q.jsxs)("div",{children:[(0,q.jsx)(Gt.img,{className:"intro-logo",src:"%s",alt:"",initial:{opacity:0,scale:.86},animate:{opacity:1,scale:1},transition:{duration:.9,ease:[.2,.9,.2,1]}}),(0,q.jsx)(Gt.h2,{initial:{letterSpacing:"0.2em",opacity:0},animate:{letterSpacing:"0em",opacity:1},transition:{duration:1.6,ease:[.2,.9,.2,1]},children:"%s"}),(0,q.jsx)(Gt.p,{initial:{opacity:0},animate:{opacity:1},transition:{delay:.6},children:"%s"})'%(LOGO,u(FA),EN))
# header brand
rep('(0,q.jsx)("h1",{children:"%s"}),(0,q.jsx)("small",{children:"Iran Freight Atlas"})'%OLD,'(0,q.jsx)("h1",{children:"%s"}),(0,q.jsx)("small",{children:"%s"})'%(u(FA),EN))
rep('className:"print-sheet",dir:"rtl",children:[(0,q.jsx)("h1",{children:"%s"})'%OLD,'className:"print-sheet",dir:"rtl",children:[(0,q.jsxs)("h1",{className:"ps-brand",children:[(0,q.jsx)("img",{src:"%s",alt:""}),"%s"]})'%(LOGO,u(FA)))
# brand mark component → uploaded logo
i=h.find('function iD(){');j=h.find('a(iD,"BrandMark")',i);assert i>0 and j>i
h=h[:i]+'function iD(){return(0,xe.jsx)("img",{className:"brand-mark",src:"%s",alt:"%s",draggable:!1})}'%(LOGO,u(FA))+h[j:]
rep('<small class="mut">اطلس باربری ایران · گزارش زنجیرهٔ تأمین','<small class="mut"><img src="%s" alt="" style="width:18px;height:18px;vertical-align:-4px;margin-left:6px">%s · گزارش زنجیرهٔ تأمین'%(LOGO,FA))
rep('Draft generated by Iran Freight Atlas — verify before issue','Draft generated by %s — verify before issue'%EN)
rep("PRODID:-//IFA//Freight Atlas//FA","PRODID:-//Asana//Logistics//FA")
css=""".brand-mark{width:30px!important;height:30px!important;flex:none;opacity:1!important;border-radius:8px;box-shadow:0 1px 0 rgba(255,255,255,.06),0 2px 8px rgba(0,0,0,.35)}
.brand small{letter-spacing:.12em}
.intro-logo{display:block;width:96px;height:96px;margin:0 auto 18px;border-radius:24px;box-shadow:0 10px 40px rgba(10,31,122,.45)}
.ps-brand{display:flex;align-items:center;gap:10px}.ps-brand img{width:34px;height:34px}
.sx-brandlogo{width:22px;height:22px;border-radius:6px;vertical-align:middle}"""
assert '</head>' in h;h=h.replace('</head>','<style id="asana-brand">%s</style>\n</head>'%css,1)
rep("const IFA={version:'15.9.1',","const IFA={version:'15.9.2',brand:'%s',brandEn:'%s',"%(FA,EN))
open(P,'w',encoding='utf8').write(h);print('brand ok')
